### ISSUE TITLE
Updated 1 minute ago IItemRenderer missing.

### ISSUE THREAD

**Issue by DrZed** [TheCBProject/CodeChickenLib#10]
You ALMOST got it right this last update
Le crash report.
http://puu.sh/rFvjx.txt
CodeChicken Lib 1.10.2-2.4.1.97-universal
Here is my tree
http://puu.sh/rFvz0.txt

**Comment by covers1624** [comment]
Update draconic evolution, brandon just pushed it.

**Comment by DrZed** [comment]
Oh cool

**Comment by DrZed** [comment]
Nope still crashing
the second puush contains my mods folder.
I don't know what else depends on Chicken Lib.

**Comment by dirtyfargo** [comment]
After updating Draconic Evolution and BrandonsCore, and all of the chicken bones mods, I am now getting [this client crash](https://gist.github.com/dirtyfargo/9dce29088fad0d912928027f78297291) with a mod called 'Modularity', it could be related to the same issue here. _Edit Removed 'Modularity' and tested, get same crash as OP as well_

**Comment by Gepett0** [comment]
After updating to:
CodeChickenCore-1.10.2-2.3.1.81-universal
CodeChickenLib-1.10.2-2.4.1.97-universal
BrandonsCore-1.10.2-2.1.0.48-universal
Draconic-Evolution-1.10.2-2.0.0d.107-universal

I get the same crash as OP, server starting fine though. Only client affected so far.
Will xpost to DE.

**Comment by covers1624** [comment]
Fuck.. Any repo for modularity?

**Comment by dirtyfargo** [comment]
https://github.com/AstroDevelopment/Modularity

**Comment by DrZed** [comment]
I don't use modularity (check my second puush)

**Comment by covers1624** [comment]
check commit message

**Comment by DrZed** [comment]
Yay ASM code.
