### ISSUE TITLE
Crash in renderer

### ISSUE THREAD

**Issue by nrllewellyn** [TheCBProject/CodeChickenLib#100]
Crash report: https://pastebin.com/f7tktFWp

This is most likely related to this issue: https://github.com/CoFH/Feedback/issues/410

I have tried the latest version of CodeChickenLib on ChickenBones' web site (3.1.2.311) with no luck. Any help would be appreciated (event a try/catch/log just to get things working again).

**Comment by covers1624** [comment]
https://github.com/CoFH/Feedback/issues/410#issuecomment-324019105 There is literely nothing i can do, this is a crash that absolutely cannot happen, strip down your mod set to the minimal mods required, update ALL your drivers and report back on the CoFH issue. This issue absolutely cannot happen in any standard instance, a java NIO buffer NOT creating with the correct size just cannot happen at all ever.
Duplicate: https://github.com/TheCBProject/CodeChickenLib/issues/89
