### ISSUE TITLE
[1.12.1] Crash in rendering

### ISSUE THREAD

**Issue by gchpaco** [TheCBProject/CodeChickenLib#102]
I've had this problem with roots books going from one page to the next.

Crash report: Opened a roots book and paged through it: [crash-2017-09-17_20.25.35-client.txt](https://github.com/TheCBProject/CodeChickenLib/files/1309533/crash-2017-09-17_20.25.35-client.txt)

**Comment by covers1624** [comment]
Not me, Roots its trying to render a null ItemStack.
