### ISSUE TITLE
Crash when clicking on rftools shape card which has been used before in CCL

### ISSUE THREAD

**Issue by digi-tal-it** [TheCBProject/CodeChickenLib#103]
MC 1.12.1 server and client
Forge 14.22.1.2485 on client and server
rftools 1.12-6.13
CCL 3.1.2.297

Here is what I did:

Placed the builder, used a void shape card and set the desired dimensions. Inserted the shape card and hit the preview button. I saw, that the dimensions are not correct, so i take out the shape card to correct the dimensions. On right clicking the shape card, my client crashes.
I can log onto my server again after restarting the client but the problem persists. I right click the shape card and it crashes again.

I reported it to McJty who kindly looked into the chrashlog. He said, the crash occured in CodeChickenLib, so I am reporting it here.

     #####https://github.com/McJty/RFTools/issues/1373

Here ist the crashlog : https://pastebin.com/xVUHbYXS

**Comment by covers1624** [comment]
```
    at net.minecraftforge.client.model.obj.OBJModel$OBJBakedModel.buildQuads(OBJModel.java:1345)
    at net.minecraftforge.client.model.obj.OBJModel$OBJBakedModel.func_188616_a(OBJModel.java:1314)
    at jds.bibliocraft.models.ModelClipboard.func_188616_a(ModelClipboard.java:332)
```
Bibilio craft not me.
