### ISSUE TITLE
[1.12.1] Unable to class load the plugin

### ISSUE THREAD

**Issue by UnPure** [TheCBProject/CodeChickenLib#105]
While starting a server/client, CodeChickenLib is producing an error in the logs.

    [10:42:27] [main/ERROR] [FML]: Coremod codechicken.lib.asm.CCLCorePlugin: Unable to class load the plugin java.lang.ClassNotFoundException: codechicken.lib.asm.CCLCorePlugin

**CodeChickenLib:** 3.1.2.297
**Forge:** 14.22.0.2475

**Comment by p455w0rd** [comment]
I just tested this via Twitch app...loads fine for me

**Comment by p455w0rd** [comment]
well..there is one difference..your forge version for 1.12.1 is outdated..try updating to latest (14.22.1.2485)

**Comment by covers1624** [comment]
It's safe to ignore, seems I forgot to remove the flag from the jar manifest.

**Comment by p455w0rd** [comment]
so..issue closed?

**Comment by covers1624** [comment]
When i fix it, leaving it open as a reminder to myself.
