### ISSUE TITLE
Crash during startup

### ISSUE THREAD

**Issue by HendrikJ79** [TheCBProject/CodeChickenLib#11]
[crash-2016-10-11_21.05.53-client.txt](https://github.com/TheCBProject/CodeChickenLib/files/522787/crash-2016-10-11_21.05.53-client.txt)
[crash-2016-10-11_21.07.22-client.txt](https://github.com/TheCBProject/CodeChickenLib/files/522790/crash-2016-10-11_21.07.22-client.txt)
[crash-2016-10-11_21.09.06-client.txt](https://github.com/TheCBProject/CodeChickenLib/files/522788/crash-2016-10-11_21.09.06-client.txt)
[crash-2016-10-11_21.11.33-client.txt](https://github.com/TheCBProject/CodeChickenLib/files/522792/crash-2016-10-11_21.11.33-client.txt)
[crash-2016-10-11_21.16.31-client.txt](https://github.com/TheCBProject/CodeChickenLib/files/522789/crash-2016-10-11_21.16.31-client.txt)
[crash-2016-10-11_21.18.49-client.txt](https://github.com/TheCBProject/CodeChickenLib/files/522791/crash-2016-10-11_21.18.49-client.txt)
[crash-2016-10-11_21.22.01-client.txt](https://github.com/TheCBProject/CodeChickenLib/files/522793/crash-2016-10-11_21.22.01-client.txt)
[crash-2016-10-11_21.25.07-client.txt](https://github.com/TheCBProject/CodeChickenLib/files/522794/crash-2016-10-11_21.25.07-client.txt)

**Comment by elifoster** [comment]
Perhaps those crash reports could be put somewhere that does not require people to actually download any files, like Pastee or Pastebin.

**Comment by robaimes** [comment]
This is fixed in latest CCL. See #9 and #10

**Comment by HendrikJ79** [comment]
What is the latest CCL?
The latest I can find in Curse is: 1.101.2-2..4.1.101-universal

**Comment by HendrikJ79** [comment]
Still a Crash with the latest version (1.10.2-2.4.1.101-universal): [Latest Crash Log](https://gist.github.com/HendrikJ79/0e7f5c3efad7fc0d0f4b95b745f4a406)

**Comment by DrZed** [comment]
Did you not read the commit message?
 @covers1624    actually fix #10, Requires update of all mods.

**Comment by HendrikJ79** [comment]
All the mods are updated

**Edit:** Removed Translocators, looks loading fine at this moment, still loading

**Comment by robaimes** [comment]
@HendrikJ79 Update Draconic Evolution and Brandon's Core
