### ISSUE TITLE
MC 1.11.2 Crash when chunks with TE Blocks are loaded

### ISSUE THREAD

**Issue by Secretname2009** [TheCBProject/CodeChickenLib#114]
When i try to return home after some exploring, going near my home that has Thermal Expansion blocks(Specifically a Hardened Energy Cell and a Hardened Enervation Dynamo) or even tp home will crash the game with this error, entering the world again works fine but once the chunk unloads it can happen again.
Im just asking for what is the cause of this as the only mod that is mentioned in the crashlog is CodeChickenLib, that and OpenEye does mention it aswell: http://openeye.openmods.info/crashes/12b689567e85704ca06012184a6defc9

CodeChickenLib Version: 3.0.0.298
Forge Version: 13.20.1.2530
[crash-2017-11-19_09.47.50-client.txt](https://github.com/TheCBProject/CodeChickenLib/files/1485402/crash-2017-11-19_09.47.50-client.txt)

**Comment by covers1624** [comment]
No, this is an issue with Harvest Craft that i pr'd a fix for ages ago, their tiles improperly load NBT on the client causing TE's tiles to not load at all hence the crash. Update Harvest craft or move to 1.12, Im unsure if pam ported the fix back to 1.11 or not.

**Comment by Secretname2009** [comment]
Okay, i should probably look at the closed issue before i post, i just did and found my issue, but thanks for responding so quickly.

**Comment by covers1624** [comment]
No worries, Discord bot ftw :D
