### ISSUE TITLE
[1.10.2] Conflict with Matter Overdrive

### ISSUE THREAD

**Issue by Brycey92** [TheCBProject/CodeChickenLib#116]
When loading just Wireless Redstone CBE and its dependencies, and Matter Overdrive and its dependencies, CodeChickenLib's TextureUtils.textureLoad is called a second time, which causes [this crash report](https://gist.github.com/Brycey92/de0cd89afe0a2268fdbd05f90c97d044).

Equivalent issue to https://github.com/simeonradivoev/MatterOverdrive/issues/635.

All mods used were the latest versions as of 12/3/2017 7:50pm EST.

The PRs referenced below fix this issue in both 1.10.2 and 1.11.2, if it even happens in 1.11.2.

**Comment by covers1624** [comment]
Merged, see #117 for my comments on the issue.
