### ISSUE TITLE
Crash NullPointerException Rendering screen with MC 1-12-2 CCL 1.12-3.1.4.316-universal Forge 2555 and Futurepack-1.12.2-26.3.7

### ISSUE THREAD

**Issue by trogarus** [TheCBProject/CodeChickenLib#122]
Not sure if this is you or them, but here is the crash log mentioning both mods. Cross posting this on futurepack tracker as well. Will edit with post to that here once I post there.

Crash Log
[crash-2017-12-09_15.13.11-client.txt](https://github.com/TheCBProject/CodeChickenLib/files/1545073/crash-2017-12-09_15.13.11-client.txt)

Client Log
[latest.log](https://github.com/TheCBProject/CodeChickenLib/files/1545074/latest.log)

**Comment by covers1624** [comment]
Futurepack seems to be attempting to render a null ItemStack, Ill leave this open for now, but its a Futurepack issue.

**Comment by trogarus** [comment]
Cross posted it to them here, so thanks for letting it open for now =)

https://github.com/mcenderdragon/Futurepack-API/issues/325

**Comment by trogarus** [comment]
Null item was a code derp with a comma on Futurepack's part. Issue is solved as of Futurepack-1.12.2-26.3.24

**Comment by covers1624** [comment]
Glad it was resolved.
