### ISSUE TITLE
Not loading 

### ISSUE THREAD

**Issue by Blacbirdjr** [TheCBProject/CodeChickenLib#13]
This keeps happening every time I launch. It all started after I updated my pack on curse. The pack is Creatively UnCreative.

http://pastebin.com/DaXPgqKL

**Comment by covers1624** [comment]
Make sure all your CodeChicken mods are up to date.

**Comment by Blacbirdjr** [comment]
I had to disable CodeChicken Core

**Comment by covers1624** [comment]
Define disable

**Comment by Blacbirdjr** [comment]
I had to remove the mods from the pack. Unless there was another mod conflicting with it, I didn't see it. All of the Mods were the latest versions.

**Comment by covers1624** [comment]
make sure your brandons core is updated to the latest, if so, ill have to reopen this

**Comment by Blacbirdjr** [comment]
I updated to the latest but I will add them again on a separate profile to see if it is still doing the same thing.

**Comment by redo6565** [comment]
im getting same error all mods are up to date

**Comment by covers1624** [comment]
This should not be an issue by this point, send me your crash log,

**Comment by covers1624** [comment]
Closing due to this is soo old and probably invalid.
