### ISSUE TITLE
CodeChickenLib makes minecraft no launching.

### ISSUE THREAD

**Issue by Zolithen** [TheCBProject/CodeChickenLib#136]
Playing minecraft, i can't launch it because it throws me this error:

https://pastebin.com/DY6eKgU2

I think that is a problem with ASM and NEI because the crash report shows that there is problems with it.

**Comment by covers1624** [comment]
Update your mods those versions are ancient dev builds.

**Comment by covers1624** [comment]
No actually i was wrong, you have 1.10 versions of NEI and CCL installed on 1.12..
