### ISSUE TITLE
CCBlockStateLoader keeps dangling ModelLoader reference

### ISSUE THREAD

**Issue by asiekierka** [TheCBProject/CodeChickenLib#137]
This prevents FoamFix, especially an upcoming release, from doing major RAM usage optimizations.

Do you need that dangling ModelLoader reference? Forge disposes of it after model baking is complete, as IModels can still be dynamically loaded through the ModelLoaderRegistry.

**Comment by covers1624** [comment]
Nope its not needed after baking, `VanillaLoader` and `VariantLoader` also store a reference in case you weren't aware :D

**Comment by asiekierka** [comment]
@covers1624 ...oh.

...okay, that's fair, nevermind. Couldn't spot it at first. I relied on that reference once, so I'm surprised I didn't remember. Sorry.

**Comment by covers1624** [comment]
Ill clean it up my end, but i'm fairly sure its safe to nuke the instances inside `VariantLoader` and `VanillaLoader`, unless anything lazy loads models that is.

**Comment by asiekierka** [comment]
@covers1624 Some mods do lazy-load models, probably. FoamFix's optimization will make everything lazy-load models, as 90% of them aren't used.

I'm not going to nuke the instances, I'm just going to, um, FoamFix them a bit more. Yeah. I forgot I had the dangling ref.

**Comment by asiekierka** [comment]
In other words, this is no longer an issue.

**Comment by covers1624** [comment]
Im still going to cleanup my fields there, 1.13 it will be wayy more sane..
