### ISSUE TITLE
no idea how to fix this need help

### ISSUE THREAD

**Issue by rapgodbrad** [TheCBProject/CodeChickenLib#138]
The game crashed whilst there was a severe problem during mod loading that has caused the game to fail
Error: net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from CodeChicken Lib (codechickenlib)

**Comment by covers1624** [comment]
Please provide your log file.

**Comment by rapgodbrad** [comment]
how I do that. not that into computers

**Comment by covers1624** [comment]
As this is just going to turn in to general tech support, Please join the discord chat, as this isnt the place for InstantMessaging type conversations. https://discord.gg/9nr3qyC
