### ISSUE TITLE
Crash using Forge/MC 1.12.2 

### ISSUE THREAD

**Issue by risingfish** [TheCBProject/CodeChickenLib#140]
Not sure if this is my game or not, but I thought I would report if it's not. The OS is Ubuntu 16.04.

[crash-2018-02-23_21.10.22-server.txt](https://github.com/TheCBProject/CodeChickenLib/files/1754041/crash-2018-02-23_21.10.22-server.txt)

**Comment by covers1624** [comment]
`CodeChickenLib-1.12.2-3.1.5.331-deobf.jar` You have the deobfuscated version installed, that is for mod developers, You want the `universal` jar.
