### ISSUE TITLE
Crashing rendering process

### ISSUE THREAD

**Issue by ghost** [TheCBProject/CodeChickenLib#141]
All information provided in this file
https://gist.github.com/ternsip/fe12d3f1289336dc4985aee411231825
Crashes when i open NEI
[LNK](https://github.com/TheCBProject/EnderStorage/issues/77)
Same thing on CodeChicken Lib 1.12.2-3.1.6.339-universal

**Comment by covers1624** [comment]
You didn't need to open a second issue for this, it's likely on ES's side anyway.

**Comment by ghost** [comment]
ok, thanks
