### ISSUE TITLE
ProjectRed 1.12.2-4.8.6.55 crash, caused by this module.

### ISSUE THREAD

**Issue by Dushess** [TheCBProject/CodeChickenLib#144]
java.lang.NoSuchMethodError: codechicken.multipart.MultiPartRegistry$.registerParts(Lcodechicken/multipart/api/IPartFactory;
-----
All PR modules with E flag reffered to this error.
Latest avail Forge
https://pastebin.com/XBJX1xrn

With other mods errored modules has been scrambled

> | UE    | projectred-transportation | 1.0            | ProjectRed-1.12.2-4.8.6.55-all.jar            | None                                     |
> 	| UE    | projectred-exploration    | 1.0            | ProjectRed-1.12.2-4.8.6.55-all.jar            | None                                     |
> 	| UE    | projectred-transmission   | 1.0            | ProjectRed-1.12.2-4.8.6.55-all.jar            | None                                     |
> 	| UE    | projectred-expansion      | 1.0            | ProjectRed-1.12.2-4.8.6.55-all.jar            | None                                     |
> 	| UE    | projectred-illumination   | 1.0            | ProjectRed-1.12.2-4.8.6.55-all.jar            | None                                     |
> 	| UC    | projectred-fabrication    | 1.0            | ProjectRed-1.12.2-4.8.6.55-all.jar            | None                                     |
> 	| UE    | projectred-integration    | 1.0            | ProjectRed-1.12.2-4.8.6.55-all.jar            | None

**Comment by covers1624** [comment]
1.12 project red is not released, it is not ready either, this particular crash is a result of you attempting to throw the latest of everything in. I have changes locally for PR that I have not pushed yet.

**Comment by Dushess** [comment]
Just one guy on minecraftforum told he used it correctly. Or he have something other, or he just lies.

**Comment by covers1624** [comment]
`this particular crash is a result of you attempting to throw the latest of everything in. I have changes locally for PR that I have not pushed yet.`
