### ISSUE TITLE
Please Help, minecraft forge keeps on crashing due to this mod

### ISSUE THREAD

**Issue by eddiebytes** [TheCBProject/CodeChickenLib#146]
[crash-2018-04-13_20.52.51-client.txt](https://github.com/TheCBProject/CodeChickenLib/files/1910245/crash-2018-04-13_20.52.51-client.txt)
I have no idea what the problem is but i think it may be due to this mod, I have linked the crash report

**Comment by IchigoGames** [comment]
same crash https://pastebin.com/pYsbVFJb
Minecraft 1.12.2
Forge 2611
CodeChickenLib-1.12.2-3.1.6.339

**Comment by ZombieKilla111** [comment]
I had the same issue. Updating to the latest forge (2669) seemed to work for me

**Comment by covers1624** [comment]
Whops, completely missed this issue.. Yeah there is nothing I can do to fix this, try updating forge.
