### ISSUE TITLE
CodeChickenCore/CodeChickenLib rendering interfering with Botania Floating Pure Daisy

### ISSUE THREAD

**Issue by quantumSuperposition** [TheCBProject/CodeChickenLib#147]
CodeChickenLib/CodeChickenCore seem to interfere with the rendering of the floating pure daisy from Botania. I report this issue to the Botania Github as well and it seems to be a problem with CodeChickenLib.  The URL to the Botania Github bug report is as follows: https://github.com/Vazkii/Botania/issues/2592.

Link to crash log: https://gist.github.com/quantumSuperposition/5aacd7222336da7842b95e2bb51331d5
Steps to reproduce:

1. Place floating Pure Daisy.
2. Place vanilla logs (not sure if this matters) around pure daisy.
3. Crash and unable to recover world except by using MCEdit to delete the Floating Pure Daisy.

The Minecraft window stopped responding and crashed. I was unable to go back into the world; every time the world would crash. All other floating flowers work. The floating Pure Daisy will crash when a log is placed next to it and is reproducible.

**Comment by covers1624** [comment]
This is not CCL. CCL has wrappers over the BlockRenderDispatcher, but they do nothing unless the block specifies that it should. At any rate, 1.10 is unsuported, update to 1.12.
