### ISSUE TITLE
CodeChickenLib crashes on pre-initialization

### ISSUE THREAD

**Issue by Cyancraft** [TheCBProject/CodeChickenLib#148]
This happens on Forge 14.23.3.2691 and the current latest version (14.23.3.2701).

This actually only happens on my buddy's computer, but not on mine.

He's running my modpack (The Adanicx Pack), using the latest everything in the pack. 

Attached his crash report paste bin.

https://pastebin.com/387GSwrP

**Comment by covers1624** [comment]
Reinstall java. Others have had this, and reinstalling it has been known to fix it.

**Comment by Cyancraft** [comment]
We've used Java 32bit and 64 bit. We've updated to Java's latest version. I'm using JRE 1.8.0_151, he was using revision 147, updated to 151 to match mine, and then updated to 171. All versions had no change. We even rebooted to see if it would apply any additional Java things during a reboot, and no dice.

**Comment by Cyancraft** [comment]
I understand the issue, and that it isn't exactly the mod crashing, as it is definitely a Java issue. CCBlockStateLoader trying to get information from Java, and Java being stubborn and not providing.

**Comment by covers1624** [comment]
Do you have Java 9 installed at all? (even though its not launching with it). Can you try uninstalling every java you have installed, and install the latest 1.8 java.

**Comment by covers1624** [comment]
This crash should not happen, forge does the same call later in the load cycle and that magically works.

**Comment by Cyancraft** [comment]
The only Java version installed is 1.8.0_171.

**Comment by Kydog100** [comment]
try to delete your codechicken lib config that worked for me

**Comment by covers1624** [comment]
@Kydog100 they are not the same issues. As for the actual issue here, please make sure you are not running the game out of a OneDrive or a GoogleDrive folder, they do weird things to the FileSystem that java doesn't like.

**Comment by HeroOfFire45** [comment]
I recommend deleting your config in the .minecraft/config folder. It's likely the mod is referencing a config for an older version (for example, the 1.7.10 version) and is crashing due to missing values.

**Comment by covers1624** [comment]
This issue is not related to config files... Only comment if you have the EXACT same crash.

I'm going to close this, its turned in to tech support, swing by the discord if you experience this issue. https://discord.gg/9nr3qyC
