### ISSUE TITLE
java.lang.NullPointerException: Unexpected error

### ISSUE THREAD

**Issue by Xiaminou** [TheCBProject/CodeChickenLib#150]
Minecraft's client crashes when I join my dedicated server.

Crash Report: [crash-2018-05-29_17.38.15-client.txt](https://github.com/TheCBProject/CodeChickenLib/files/2049035/crash-2018-05-29_17.38.15-client.txt)

Mods updated today: [list-latest.txt](https://github.com/TheCBProject/CodeChickenLib/files/2049060/list-latest.txt)

Minecraft: 1.12.2
Forge: 2705
Mods: [list-alphabetical.txt](https://github.com/TheCBProject/CodeChickenLib/files/2049063/list-alphabetical.txt)

**Comment by Xiaminou** [comment]
I forgot to mention I also updated forge from 26XX to 2705.

**Comment by covers1624** [comment]
Nothing i can do about this, someone is trying to render an invalid model, ccl is in the stack, yes, but i only sniff things, i don't modify the state unless the item wants me to.
