### ISSUE TITLE
Crash at loading

### ISSUE THREAD

**Issue by AndreiTS** [TheCBProject/CodeChickenLib#152]
https://paste.dimdev.org/eyekobomal.mccrash

**Comment by miguel456** [comment]
Try updating your graphics drivers and use a newer version of the mod.
If none works tell me and I'll analyse the report in detail and give you a detailed response
I can't help you more because I'm about to leave today, sorry

**Comment by covers1624** [comment]
Going to need your full launch log for this one. The only thing that can cause this is an outdated version of LWJGL.

**Comment by BaccarWozat** [comment]
I got the same crash: https://pastebin.com/99s8Ub4W . Drivers were said by the OS to be the latest.
I then tested it with LWJGL 2.9.4-nightly-20150209 and it loaded perfectly.

**Comment by covers1624** [comment]
I'm going to put this down to outdated LWJGL, minecraft ships 2.9.4, any launcher not using that is doing it wrong.

**Comment by AndreiTS** [comment]
This happened because i'm using a multimc cracked version. But I found a solution for that. (yes, I know that I should buy minecraft)
