### ISSUE TITLE
Crashes on pre-initialization (Linux)

### ISSUE THREAD

**Issue by PagnuM** [TheCBProject/CodeChickenLib#157]
Hi.
When I try to run CodeChickenLib the game crashes, it only crashes with this mod. I've tried with other mods and this doesn't happen, I don't know if it's because I'm on Linux.

Here is the log: https://pastebin.com/GjLHs83b

**Comment by Kydog100** [comment]
delete your code chicken lib config

**Comment by covers1624** [comment]
Multimc is launching your game with outdated lwjgl
