### ISSUE TITLE
crash upon start 

### ISSUE THREAD

**Issue by Jz003** [TheCBProject/CodeChickenLib#158]
The game crashes upon star idk why. here is the crash report.
[crash-2018-06-25_19.42.54-client.txt](https://github.com/TheCBProject/CodeChickenLib/files/2135385/crash-2018-06-25_19.42.54-client.txt)

**Comment by covers1624** [comment]
delete CCL's config and let it make you a new one. Find it in `config/codechickenlib.cfg`
