### ISSUE TITLE
CodeChickenLib crashes at initializing mods

### ISSUE THREAD

**Issue by Pelayori003** [TheCBProject/CodeChickenLib#160]
Whenever I try to run the game it crashes every time the same. I tried some versions of forge and some versions of CCL: Here's the crash report: https://pastebin.com/xu2PEsvx (1.12.2 Version)

**Comment by covers1624** [comment]
You likely have an outdated version of ccl still in your mods folder as a zip not a jar, please make sure this is not the case.

**Comment by Pelayori003** [comment]
No it isn't that

**Comment by covers1624** [comment]
Your jar is corrupt or there is a ccl version hanging arround in a sub folder of mods.

**Comment by Pelayori003** [comment]
I tried searching it by me or with windows search box and nothing, only the file in /mods.
However it worked with the first version of CCL for 1.12.2

**Comment by covers1624** [comment]
Please re-download CCL, the jar is likely corrupt. Or another mod is being dumb and repacking CCL classes.
