### ISSUE TITLE
Crash 

### ISSUE THREAD

**Issue by ghost** [TheCBProject/CodeChickenLib#162]
The game crashes when I tried to load it.

Cause:  "The game crashed whilst there was a severe problem during mod loading that has caused the game to fail
The game crashed whilst there was a severe problem during mod loading that has caused the game to fail
Error: net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from CodeChicken Lib (codechickenlib)"

**Comment by covers1624** [comment]
Cool, please provide your crash report, i cannot help without it.

**Comment by esv110842** [comment]
I have the same problem,game crashes while loading.
The crash report file is here.
[crash-2018-07-11_22.49.30-client.txt](https://github.com/TheCBProject/CodeChickenLib/files/2185026/crash-2018-07-11_22.49.30-client.txt)

**Comment by covers1624** [comment]
@esv110842 Delete CCL's config file an extremely old config from 1.10 is hanging around. Closing this issue as the OP has not replied with his crash report.
