### ISSUE TITLE
Tesselation Crash

### ISSUE THREAD

**Issue by funfight22** [TheCBProject/CodeChickenLib#164]
https://pastebin.com/yyk4zkYc

I originally posted this to the AW2 github but he was unable to recreate the issue.  Posting here in case the problem is with this mod or that you may have insight.  The crash happens on load, is SMP.

**Comment by covers1624** [comment]
Interesting, It looks like an error on AW2's end to me as I've never had issues in TE.. Can you link to the AW2 issue please?

**Comment by funfight22** [comment]
https://github.com/P3pp3rF1y/AncientWarfare2/issues/722

**Comment by angelnc1989** [comment]
I posted a similar crash on the Blockcraftery issue tracker and they sent me here:
https://github.com/EpicSquid/Blockcraftery/issues/1#issuecomment-405010691

**Comment by covers1624** [comment]
@angelnc1989 Please don't hijack issues, i have replied over there. As for the initial report here, this is nothing in CCL, it would have to be on AW2's end, CCL just passes the what ever the bakery gives as a blockstate through to the key generator.
