### ISSUE TITLE
Vanilla Fix and codechicken-lib are not compatible, causing the client to crash

### ISSUE THREAD

**Issue by MoeShimaKaze** [TheCBProject/CodeChickenLib#165]
codechicken-lib Version:1.12.2-3.2.0.345-universal
VanillaFix Version:VanillaFix-1.0.10-107
Forge Version:1.12.2-14.23.4.2705
Mod list:https://pastebin.com/Zsf5A1wL
Crash-report:https://paste.dimdev.org/avojimogen.mccrash

**Comment by covers1624** [comment]
Absolutely nothing to do with me, I just happen to be the one causing the class to load then their transformer is failing an injection.
