### ISSUE TITLE
java.lang.NoSuchFieldError: OpenGL45

### ISSUE THREAD

**Issue by EverNife** [TheCBProject/CodeChickenLib#166]
I am getting this crash, just by trying to start Code Chicken Lib

https://hastebin.com/upiposabel.rb

(Tested with booth forge 14.23.4.2705 and 14.23.4.2732)

**Comment by covers1624** [comment]
This is a duplicate, your launcher is launching minecraft with an outdated lwjgl version.

**Comment by EverNife** [comment]
Hmm, ty for the help.

Updating the launcher solved the problem.
