### ISSUE TITLE
Issue with codechicken.lib.render.item.CCRenderItem.func_184393_a

### ISSUE THREAD

**Issue by Shovinus** [TheCBProject/CodeChickenLib#170]
Issue with codechicken.lib.render.item.CCRenderItem.func_184393_a
https://pastebin.com/hDZpjC7x
https://pastebin.com/DUmcZiQ2
https://pastebin.com/3ir6tRQv

**Comment by covers1624** [comment]
Oh look, the first 2 crash reports have been modified, the last one indicates CTM, They had some incompatabilites with a newer version of forge. Please for the love of god, update ALL your mods before posting any issues.

**Comment by Shovinus** [comment]
Sorry was late, take it you found the fix

**Comment by covers1624** [comment]
There was nothing to fix, the problem is you need to update CTM.

**Comment by Shovinus** [comment]
The previous 2 were not modified by me, basically I was running revelation, and those 2 error showed, so I updated chicken to latest and retried, then got 3rd error, I just noticed it still had that function in its path so made a dumb assumption it had fixed but not quite. I updated CTM now and yes seems fine
