### ISSUE TITLE
Suggestion: Change OpenGL version detection to use reflection

### ISSUE THREAD

**Issue by Janrupf** [TheCBProject/CodeChickenLib#173]
Looking at the issues #172 and #166. This can easily be resolved by changing the detection here https://github.com/TheCBProject/CodeChickenLib/blob/4d48a21d5c057839eefd78092d872237a3aeb68b/src/main/java/codechicken/lib/render/OpenGLUtils.java#L27-L32 to use reflection and catching exceptions. This might even happen on the Vanilla launcher and its not a that big pain to simply fix this. You can't expect everyone to use the latest version of LWJGL because some new version are bugged on some OS.

**Comment by peterix** [comment]
A bit of context:
* This is coming from people using outdated versions of MultiMC (it did default to 2.9.1 for all versions)
* In the current version, the user can choose any of the Mojang-provided LWJGL versions of LWJGL. That means you can get LWJGL 2.9.1 in Minecraft 1.12.2, or LWJGL 2.9.4 in old beta versions. It is up to the user. The default is whatever was in the upstream Mojang version json though.
* This works well in Vanilla, and up to now, worked flawlessly with pretty much every other mod.

Feel free to close this. The users should not be running ancient cracked versions of MultiMC.

**Comment by covers1624** [comment]
That has been my stance up until now, don't be using ancient versions of things, mojang ships 2.9.4 so things should use that. But mitigation has been added: https://github.com/TheCBProject/CodeChickenLib/commit/68c1667024d36d3373110ac137a79b435084053e

**Comment by jikuja** [comment]
Partially true:

```json
        {
            "name": "org.lwjgl.lwjgl:lwjgl:2.9.2-nightly-20140822",
            "rules": [
                {
                    "action": "allow",
                    "os": {
                        "name": "osx"
                    }
                }
            ],...
        }```

Looks like this nightly is few days later than the commit which is required for `caps.OpenGL45`
