### ISSUE TITLE
[1.12.2] Crash with, I think, shader.

### ISSUE THREAD

**Issue by TheSnowyChickens** [TheCBProject/CodeChickenLib#174]
https://paste.dimdev.org/yupazosite.mccrash

Mods, OS, Forge and more is in the crash log.

![crash chl](https://user-images.githubusercontent.com/29357962/43744838-39f46c0a-99dc-11e8-8714-dabbb44965c1.PNG)

**Comment by covers1624** [comment]
No this is not me.
