### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by SrUca** [TheCBProject/CodeChickenLib#184]
"The game crashed whilst there was a severe problem during mod loading that has caused the game to fail
The game crashed whilst there was a severe problem during mod loading that has caused the game to fail
Error: net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from CodeChicken Lib (codechickenlib)"

If someone can help me pls do it i need it

**Comment by Archengius** [comment]
Give full game log when requesting support please. There is nothing that can be understood from fail message you provided.

**Comment by covers1624** [comment]
Im just gonna start insta closing these.
