### ISSUE TITLE
Add EnumBlockRenderType values on the server

### ISSUE THREAD

**Issue by codewarrior0** [TheCBProject/CodeChickenLib#185]
Regarding the issue reported here: https://github.com/raoulvdberge/refinedstorage/issues/1972

Short version: Refined Storage uses the return value of `IBlockState#getRenderType` to decide whether a block should be craftable as a RS cover. CCL (as used by GregTech CE) adds new values to the `EnumBlockRenderType` enum, but only on the client side. The authors of both mods seem to be doing nothing wrong, which makes me think CCL should be adding the new enum values on both sides.

`CodeChickenLib-1.12.2-3.2.1.351-universal.jar`
`Forge Mod Loader version 14.23.4.2757 for Minecraft 1.12.2`

**Comment by covers1624** [comment]
Sadly this isn't a simple change, when the system was originally written it was a client side method iirc, I can make some changes CCL side but it's up to the mods using it to actually return something useful on the server.

**Comment by covers1624** [comment]
This system will be rewritten in 1.13, RS shouldn't care that it returns null, it should only check against the `MODEL` render type.
