### ISSUE TITLE
ModelWrapper with Lightmap

### ISSUE THREAD

**Issue by nikita488** [TheCBProject/CodeChickenLib#19]
So, i mean if i want to make a model that has brightness, then i want to add "brightness": 220 tag in .json file (instead of using IBakedModel and etc). You can see here what i want: https://github.com/AppliedEnergistics/Applied-Energistics-2/blob/master/src/main/java/appeng/client/render/model/UVLModelLoader.java

**Comment by covers1624** [comment]
So, can you explain what you want more clearly, as in, added to the CCL blockstate format by default, or a wrapper inside CCL for it. etc..

**Comment by nikita488** [comment]
For example, I want to make a multilayered block, so first layer that has brightness and color and second layer that don't have color and brightness. With Vanilla Model Json Format i can create model that has layers and i can paint one layer (For example see models/block/grass.json), but what if i want to add brightness? I can't do this with Vanilla .json files, so i need IBakedModel for that, but it's not that simple. I want something like that: https://gist.github.com/nikita488/99ff741a87abe809cb7206e88b068fdd So i can create multilayered model with color and brightness just with .json file. I found that AE2 implement something like what i want and there is a .json model file for Controller and custom tag for brightness https://github.com/AppliedEnergistics/Applied-Energistics-2/blob/master/src/main/resources/assets/appliedenergistics2/models/block/controller/controller_block_online.json#L20

**Comment by covers1624** [comment]
Now that you mention it, im working on a new multi layered system that can be loaded from the blockstate file, so ill add this to that.

**Comment by nikita488** [comment]
Awesome!

**Comment by covers1624** [comment]
https://github.com/TheCBProject/Feedback/issues/2
