### ISSUE TITLE
Crash with Microblocks

### ISSUE THREAD

**Issue by TimGoll** [TheCBProject/CodeChickenLib#192]
Minecraft 1.12.2, newest version of your library
https://gist.github.com/TimGoll/04f13633ea274625c50efb8c43a2ddc2

It seems to crash when I have a forge microblock in my hand and move the camera around.

Yes, I use optifine and shaders, could be caused by this too

**Comment by TimGoll** [comment]
Update: It seems like it only happens in the first few seconds after world load. Waiting for a moment until the frame rate got stable prevents the crash

**Comment by covers1624** [comment]
I Know what this is, Please open an issue on the ProjectRed github and link to this one.
