### ISSUE TITLE
Compatibility with Forge 14.23.4.2705 (recommended version for 1.12.2)

### ISSUE THREAD

**Issue by BrainStone** [TheCBProject/CodeChickenLib#196]
I have noticed that CodeChickenLib requires at least 14.23.4.2718. Is there are particular reason for that? I'm asking because I plan to run a Modded Survival Server with Sponge. And SpongeForge is only compatible with the recommended version of Forge (currently 14.23.4.2705).

So if possible, it would be incredibly nice to have that mod being built against the recommended version of Forge, so that it can be used with SpongeForge servers.

If there's nothing specific you need that got added in the few versions, it shouldn't be much more than changing the Forge version in the `build.gradle` file.

**Comment by covers1624** [comment]
SpongeForge can run on non recomeneded forge versions your information here is incorrect. And yes, there are several reasons for using higher forge versions, namely bugfixes and features. Just update forge, SpongeForge works fine with newer versions.

**Comment by BrainStone** [comment]
Ok. Thanks! Let's hope I can get it high enough.
