### ISSUE TITLE
DigIconParticle problem

### ISSUE THREAD

**Issue by nikita488** [TheCBProject/CodeChickenLib#2]
So i add addDestroyEffects to my block and use DigIconParticle.addBlockDestroyEffects(world, Cuboid6.full, TestMod.textures, manager) so when i broke my block, digging particle looks weird :/
![image](https://cloud.githubusercontent.com/assets/6237881/17593818/dad4edee-5fef-11e6-91a8-3b95c0418441.png)

**Comment by covers1624** [comment]
Yes, it needs to be re written, ill get that done tomorrow.
