### ISSUE TITLE
Crash on Ubuntu Linux

### ISSUE THREAD

**Issue by QboiDev** [TheCBProject/CodeChickenLib#200]
---- Minecraft Crash Report ----
// Shall we play a game?

Time: 2018-10-12 20:18:42 CEST
Description: Initializing game

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from CodeChicken Lib (codechickenlib)
Caused by: codechicken.lib.configuration.ConfigFile$ConfigException: java.io.FileNotFoundException: /media/qjungblut/DATA/Minecraft Reality/config/codechickenlib.cfg (Bestandssysteem is alleen-lezen)
    at codechicken.lib.configuration.ConfigFile.write(ConfigFile.java:84)
    at codechicken.lib.configuration.ConfigFile.save(ConfigFile.java:94)
    at codechicken.lib.configuration.IConfigTag.save(IConfigTag.java:196)
    at codechicken.lib.internal.proxy.ProxyClient.loadConfig(ProxyClient.java:145)
    at codechicken.lib.CodeChickenLib.preInit(CodeChickenLib.java:51)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:624)
    at sun.reflect.GeneratedMethodAccessor14.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
    at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
    at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
    at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
    at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
    at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
    at com.google.common.eventbus.EventBus.post(EventBus.java:217)
    at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:218)
    at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:196)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
    at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
    at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
    at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
    at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
    at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
    at com.google.common.eventbus.EventBus.post(EventBus.java:217)
    at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:135)
    at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:627)
    at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:252)
    at net.minecraft.client.Minecraft.init(Minecraft.java:466)
    at net.minecraft.client.Minecraft.run(Minecraft.java:3929)
    at net.minecraft.client.main.Main.main(SourceFile:123)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.io.FileNotFoundException: /media/qjungblut/DATA/Minecraft Reality/config/codechickenlib.cfg (Bestandssysteem is alleen-lezen)
    at java.io.FileOutputStream.open0(Native Method)
    at java.io.FileOutputStream.open(FileOutputStream.java:270)
    at java.io.FileOutputStream.<init>(FileOutputStream.java:213)
    at java.io.FileOutputStream.<init>(FileOutputStream.java:162)
    at codechicken.lib.configuration.ConfigFile.write(ConfigFile.java:78)
    ... 44 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
  Minecraft Version: 1.12.2
  Operating System: Linux (amd64) version 4.15.0-36-generic
  Java Version: 1.8.0_181, Oracle Corporation
  Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Oracle Corporation
  Memory: 824757920 bytes (786 MB) / 1342177280 bytes (1280 MB) up to 6442450944 bytes (6144 MB)
  JVM Flags: 7 total; -Xmx6G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
  IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
  FML: MCP 9.42 Powered by Forge 14.23.5.2770 Optifine OptiFine_1.12.2_HD_U_E1 54 mods loaded, 54 mods active
       States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
       
       | State | ID                    | Version           | Source                                            | Signature                                |
       |:----- |:--------------------- |:----------------- |:------------------------------------------------- |:---------------------------------------- |
       | UCH   | minecraft             | 1.12.2            | minecraft.jar                                     | None                                     |
       | UCH   | mcp                   | 9.42              | minecraft.jar                                     | None                                     |
       | UCH   | FML                   | 8.0.99.99         | forge-1.12.2-14.23.5.2770.jar                     | e3c3d50c7c986df74c645c0ac54639741c90a557 |
       | UCH   | forge                 | 14.23.5.2770      | forge-1.12.2-14.23.5.2770.jar                     | e3c3d50c7c986df74c645c0ac54639741c90a557 |
       | UCH   | foamfixcore           | 7.7.4             | minecraft.jar                                     | None                                     |
       | UCH   | masterweapons         | 1.4.3             | [1.12.2] Master Weapons v1.4.3.jar                | None                                     |
       | UCH   | theworlditems2        | 1.2.1             | [1.12.2] The World Items 2 v1.2.1.jar             | None                                     |
       | UCH   | adminweapons          | 3.4               | adminweapons-v3.4-mc1.12.jar                      | None                                     |
       | UCH   | quark                 | r1.4-125          | Quark-r1.4-125.jar                                | None                                     |
       | UCH   | autoreglib            | 1.3-18            | AutoRegLib-1.3-18.jar                             | None                                     |
       | UCH   | betterinvisibility    | 1.0               | betterinvisibility-1.12-1.0.jar                   | None                                     |
       | UCH   | bibliocraft           | 2.4.5             | BiblioCraft[v2.4.5][MC1.12.2].jar                 | None                                     |
       | UCH   | biomesoplenty         | 7.0.1.2393        | BiomesOPlenty-1.12.2-7.0.1.2393-universal.jar     | None                                     |
       | UCH   | blur                  | 1.0.4-14          | Blur-1.0.4-14.jar                                 | None                                     |
       | UCH   | ctm                   | MC1.12.2-0.3.2.18 | CTM-MC1.12.2-0.3.2.18.jar                         | None                                     |
       | UCH   | chisel                | MC1.12.2-0.2.1.34 | Chisel-MC1.12.2-0.2.1.34.jar                      | None                                     |
       | UCH   | chiselsandbits        | 14.23             | chiselsandbits-14.23.jar                          | None                                     |
       | UCEE  | codechickenlib        | 3.2.2.353         | CodeChickenLib-1.12.2-3.2.2.353-universal.jar     | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
       | UC    | redstoneflux          | 2.0.2             | RedstoneFlux-1.12-2.0.2.3-universal.jar           | 8a6abf2cb9e141b866580d369ba6548732eff25f |
       | UC    | cofhcore              | 4.5.2             | CoFHCore-1.12.2-4.5.2.19-universal.jar            | None                                     |
       | UC    | cofhworld             | 1.2.0             | CoFHWorld-1.12.2-1.2.0.5-universal.jar            | 8a6abf2cb9e141b866580d369ba6548732eff25f |
       | UC    | customcursormod       | 1.2.2             | CustomCursorMod-1.2.2.jar                         | None                                     |
       | UC    | ptrmodellib           | 1.0.2             | PTRLib-1.0.2.jar                                  | None                                     |
       | UC    | props                 | 2.6.0             | Decocraft-2.6.0_1.12.2.jar                        | None                                     |
       | UC    | dungeonmobs           | 5.5.0             | dungeonmobs-5.5.0-MC1.12.2.jar                    | None                                     |
       | UC    | estop                 | 1.12.1            | estop-1.12.1.jar                                  | None                                     |
       | UC    | moreexplosives        | 1.0.2             | Even-More-Explosives-Mod-1.12.2.jar               | None                                     |
       | UC    | foamfix               | 0.9.9.1-1.12.2    | foamfix-0.9.9.1-1.12.2-anarchy.jar                | None                                     |
       | UC    | forgemultipartcbe     | 2.4.2.60          | ForgeMultipart-1.12.2-2.4.2.60-universal.jar      | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
       | UC    | microblockcbe         | 2.4.2.60          | ForgeMultipart-1.12.2-2.4.2.60-universal.jar      | None                                     |
       | UC    | minecraftmultipartcbe | 2.4.2.60          | ForgeMultipart-1.12.2-2.4.2.60-universal.jar      | None                                     |
       | UC    | fpsreducer            | 1.12.2-1.10.2     | FpsReducer-1.12.2-1.10.2.jar                      | None                                     |
       | UC    | ichunutil             | 7.1.4             | iChunUtil-1.12.2-7.1.4.jar                        | None                                     |
       | UC    | ironchest             | 1.12.2-7.0.46.831 | Iron-Chests-Mod-1.12.2.jar                        | None                                     |
       | UC    | journeymap            | 1.12.2-5.5.2      | journeymap-1.12.2-5.5.2.jar                       | None                                     |
       | UC    | malisiscore           | 1.12.2-6.4.0      | malisiscore-1.12.2-6.4.0.jar                      | None                                     |
       | UC    | malisisdoors          | 1.12.2-7.3.0      | malisisdoors-1.12.2-7.3.0.jar                     | None                                     |
       | UC    | mcmultipart           | 2.5.1             | MCMultiPart-2.5.1.jar                             | None                                     |
       | UC    | mobblocker            | 1.12-1.5.0        | mobblocker-1.12-1.5.0.jar                         | None                                     |
       | UC    | mrtjpcore             | 2.1.3.35          | MrTJPCore-1.12.2-2.1.3.35-universal.jar           | None                                     |
       | UC    | mtlib                 | 3.0.5             | MTLib-3.0.5.jar                                   | None                                     |
       | UC    | orbis_api             | 1.12.2-1.1.91     | orbis_api-1.12.2-1.1.91.jar                       | db341c083b1b8ce9160a769b569ef6737b3f4cdf |
       | UC    | orbis                 | 1.12.2-1.0.12     | orbis-1.12.2-1.0.12.jar                           | db341c083b1b8ce9160a769b569ef6737b3f4cdf |
       | UC    | harvestcraft          | 1.12.2u           | Pam's HarvestCraft 1.12.2u.jar                    | None                                     |
       | UC    | pneumaticcraft        | 1.12.2-0.6.8-219  | pneumaticcraft-repressurized-1.12.2-0.6.8-219.jar | None                                     |
       | UC    | redstonearsenal       | 2.5.1             | RedstoneArsenal-1.12.2-2.5.1.13-universal.jar     | 8a6abf2cb9e141b866580d369ba6548732eff25f |
       | UC    | spectrite             | 1.6.6             | spectrite-1.6.6.jar                               | 00119cfc089819bbcd2f9166a50c7f3df88ded78 |
       | UC    | tlsywen               | 1.0               | The-Last-Sword-You-Will-Ever-Need-Mod-1.12.2.jar  | None                                     |
       | UC    | torohealthmod         | 1.12.2-11         | torohealth-1.12.2-11.jar                          | None                                     |
       | UC    | uncraftingtable       | 1.8-beta6         | Uncrafting-Table-Mod-1.12.1.jar                   | None                                     |
       | UC    | ungrabmouse           | 2.2               | ungrabmouse-2.2.jar                               | None                                     |
       | UC    | vanillafix            | 1.0.9-97          | VanillaFix-1.0.9-97.jar                           | None                                     |
       | UC    | worldedit             | 6.1.8             | worldedit-forge-mc1.12-6.1.8-dist.jar             | None                                     |
       | UC    | justthetips           | 1.12-1.0.1.1      | justthetips-1.12-1.0.1.1.jar                      | None                                     |
  Loaded coremods (and transformers): MalisisCorePlugin (malisiscore-1.12.2-6.4.0.jar)
                                        
                                      BlurPlugin (Blur-1.0.4-14.jar)
                                        com.tterrag.blur.BlurTransformer
                                      CTMCorePlugin (CTM-MC1.12.2-0.3.2.18.jar)
                                        team.chisel.ctm.client.asm.CTMTransformer
                                      LoadingPlugin (Quark-r1.4-125.jar)
                                        vazkii.quark.base.asm.ClassTransformer
                                      VanillaFixLoadingPlugin (VanillaFix-1.0.9-97.jar)
                                        
                                      Do not report to Forge! Remove FoamFixAPI (or replace with FoamFixAPI-Lawful) and try again. (foamfix-0.9.9.1-1.12.2-anarchy.jar)
                                        pl.asie.foamfix.coremod.FoamFixTransformer
  GL info: ' Vendor: 'Intel Open Source Technology Center' Version: '3.0 Mesa 18.0.5' Renderer: 'Mesa DRI Intel(R) UHD Graphics 620 (Kabylake GT2) '
  Suspected Mods: CodeChicken Lib (codechickenlib)
  Launched Version: 1.12.2-forge1.12.2-14.23.5.2770
  LWJGL: 2.9.4
  OpenGL: Mesa DRI Intel(R) UHD Graphics 620 (Kabylake GT2)  GL version 3.0 Mesa 18.0.5, Intel Open Source Technology Center
  GL Caps: Using GL 1.3 multitexturing.
           Using GL 1.3 texture combiners.
           Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
           Shaders are available because OpenGL 2.1 is supported.
           VBOs are available because OpenGL 1.5 is supported.
  Using VBOs: Yes
  Is Modded: Definitely; Client brand changed to 'fml,forge'
  Type: Client (map_client.txt)
  Resource Packs: 
  Current Language: English (US)
  Profiler Position: N/A (disabled)
  CPU: 8x Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz

**Comment by covers1624** [comment]
`Bestandssysteem is alleen-lezen` -> `File system is read-only`. Your FS is mounted as ReadOnly, obviously things arent going to work.

**Comment by QboiDev** [comment]
Impossible. This file is mounted on the partition where the OS was installed, So it's not Read-Only. I can write in this file.

**Comment by QboiDev** [comment]
It can be, that the file was ReadOnly. (Maybe a Mistake with Forge.)

**Comment by QboiDev** [comment]
It was maybe that the library was not compatible with ext4 filesystem.

**Comment by covers1624** [comment]
No, somehow either the fs is read only or the file is. This is not a bug in ccl, this is a user bug. For the record, i run ubuntu myself, and is where i do all my dev work.

**Comment by Qplay123** [comment]
How can Minecraft write this file then??????

**Comment by QboiDev** [comment]
It was probably because it was a ntfs filesytem, and ubuntu doesn't support it fully by default, I was probably thinking if it works on windows, it works on linux. And that's not true in this case, I was 14 years old when I made this issue. (17 currently)
