### ISSUE TITLE
Caught an exception when trying to render a block

### ISSUE THREAD

**Issue by whiteeagle1985** [TheCBProject/CodeChickenLib#201]
https://pastebin.com/vRpasGEs

The blocks (connectors and cables from XNet) don't render but they do connect and transfer stuff. I've linked a pastebin of the game log at the top and here's the one of the log from the first time it happened: https://pastebin.com/Dwd889U1

Can you fix this problem, please?

**Comment by covers1624** [comment]
CCL does not hit any code path that could trigger the `Negative index` errors. However CCL has stopped your game from crashing because the XNet cable failed to render. If you want disable this feature in CCL simply turn off the config value.
