### ISSUE TITLE
game crashed - LoaderExceptionModCrash: Caught exception from CodeChicken Lib (codechickenlib)

### ISSUE THREAD

**Issue by alphawulf11** [TheCBProject/CodeChickenLib#204]
this is the crash report I don't know what to do
---- Minecraft Crash Report ----

WARNING: coremods are present:
  LoadingPlugin (Blood-Moon-Mod-1.12.2.jar)
  Inventory Tweaks Coremod (Inventory-Tweaks-Mod-1.12.2.jar)
  midnight (The-Midnight-Mod-1.12.2.jar)
  SHLoadingPlugin (Scaling-Health-Mod-1.12.2.jar)
  IvToolkit (IvToolkit-1.3.3-1.12.jar)
  DLFMLCorePlugin (DynamicLights-1.12.2.jar)
Contact their authors BEFORE contacting forge

// Daisy, daisy...

Time: 10/26/18 4:05 PM
Description:
There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from CodeChicken Lib (codechickenlib)
Caused by: codechicken.lib.configuration.ConfigFile$ConfigException: codechicken.lib.configuration.ConfigParseException: Invalid value type  , @Line:1,                                                                                                                               
	at codechicken.lib.configuration.ConfigFile.load(ConfigFile.java:61)
	at codechicken.lib.configuration.ConfigFile.<init>(ConfigFile.java:43)
	at codechicken.lib.configuration.ConfigFile.<init>(ConfigFile.java:29)
	at codechicken.lib.configuration.ConfigFile.<init>(ConfigFile.java:19)
	at codechicken.lib.CodeChickenLib.preInit(CodeChickenLib.java:50)

**Comment by alphawulf11** [comment]
this is all of it

**Comment by alphawulf11** [comment]
* isnt

**Comment by alphawulf11** [comment]
this is all of it
---- Minecraft Crash Report ----

WARNING: coremods are present:
  LoadingPlugin (Blood-Moon-Mod-1.12.2.jar)
  Inventory Tweaks Coremod (Inventory-Tweaks-Mod-1.12.2.jar)
  midnight (The-Midnight-Mod-1.12.2.jar)
  SHLoadingPlugin (Scaling-Health-Mod-1.12.2.jar)
  IvToolkit (IvToolkit-1.3.3-1.12.jar)
  DLFMLCorePlugin (DynamicLights-1.12.2.jar)
Contact their authors BEFORE contacting forge

// Daisy, daisy...

Time: 10/26/18 4:05 PM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from CodeChicken Lib (codechickenlib)
Caused by: codechicken.lib.configuration.ConfigFile$ConfigException: codechicken.lib.configuration.ConfigParseException: Invalid value type  , @Line:1,                                                                                                                               
	at codechicken.lib.configuration.ConfigFile.load(ConfigFile.java:61)
	at codechicken.lib.configuration.ConfigFile.<init>(ConfigFile.java:43)
	at codechicken.lib.configuration.ConfigFile.<init>(ConfigFile.java:29)
	at codechicken.lib.configuration.ConfigFile.<init>(ConfigFile.java:19)
	at codechicken.lib.CodeChickenLib.preInit(CodeChickenLib.java:50)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:624)
	at sun.reflect.GeneratedMethodAccessor9.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:218)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:196)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:135)
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:627)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:252)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:466)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:377)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: codechicken.lib.configuration.ConfigParseException: Invalid value type  , @Line:1,                                                                                                                               
	at codechicken.lib.configuration.ConfigTag.parseTag(ConfigTag.java:92)
	at codechicken.lib.configuration.ConfigFile.load(ConfigFile.java:59)
	... 44 more


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 445794640 bytes (425 MB) / 805306368 bytes (768 MB) up to 2147483648 bytes (2048 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2768 Optifine OptiFine_1.12.2_HD_U_E1 76 mods loaded, 76 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID                          | Version                  | Source                                         | Signature                                |
	|:----- |:--------------------------- |:------------------------ |:---------------------------------------------- |:---------------------------------------- |
	| UCH   | minecraft                   | 1.12.2                   | minecraft.jar                                  | None                                     |
	| UCH   | mcp                         | 9.42                     | minecraft.jar                                  | None                                     |
	| UCH   | FML                         | 8.0.99.99                | forge-1.12.2-14.23.5.2768.jar                  | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCH   | forge                       | 14.23.5.2768             | forge-1.12.2-14.23.5.2768.jar                  | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCH   | ivtoolkit                   | 1.3.3-1.12               | minecraft.jar                                  | None                                     |
	| UCH   | swordskillsapi              | 1.1.0                    | 1.12.2-SwordSkillsApi-1.1.0.jar                | None                                     |
	| UCH   | dynamicswordskills          | 1.12.2-6.0.1             | 1.12.2-DynamicSwordSkills-6.0.1.jar            | None                                     |
	| UCH   | additionalstructures        | 1.3.0                    | Additional-Structures-Mod-1.12.2.jar           | None                                     |
	| UCEE  | codechickenlib              | 3.2.2.353                | CodeChickenLib-1.12.2-3.2.2.353-universal.jar  | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| UC    | ancientwarfare              | 1.12.2-2.6.1.298         | ancientwarfare-1.12.2-2.6.1.298.jar            | None                                     |
	| UC    | buildcraftlib               | 7.99.14                  | BuildCraft-Mod-1.12.2.jar                      | None                                     |
	| UC    | buildcraftcore              | 7.99.14                  | BuildCraft-Mod-1.12.2.jar                      | None                                     |
	| UC    | ancientwarfareautomation    | 1.12.2-2.6.1.298         | ancientwarfare-1.12.2-2.6.1.298.jar            | None                                     |
	| UC    | ancientwarfarenpc           | 1.12.2-2.6.1.298         | ancientwarfare-1.12.2-2.6.1.298.jar            | None                                     |
	| UC    | ancientwarfarestructure     | 1.12.2-2.6.1.298         | ancientwarfare-1.12.2-2.6.1.298.jar            | None                                     |
	| UC    | ancientwarfarevehicle       | 1.12.2-2.6.1.298         | ancientwarfare-1.12.2-2.6.1.298.jar            | None                                     |
	| UC    | autopickup                  | 2.5                      | Auto-Pickup-Mod-1.12.jar                       | None                                     |
	| UC    | baubles                     | 1.5.2                    | Baubles-1.12-1.5.2.jar                         | None                                     |
	| UC    | bloodmoon                   | 1.5.3                    | Blood-Moon-Mod-1.12.2.jar                      | d72e0dd57935b3e9476212aea0c0df352dd76291 |
	| UC    | bookshelf                   | 2.3.559                  | Bookshelf-1.12.2-2.3.559.jar                   | d476d1b22b218a10d845928d1665d45fce301b27 |
	| UC    | botania                     | r1.10-354                | Botania-Mod-1.12.2.jar                         | None                                     |
	| UC    | buildcraftbuilders          | 7.99.14                  | BuildCraft-Mod-1.12.2.jar                      | None                                     |
	| UC    | buildcraftenergy            | 7.99.14                  | BuildCraft-Mod-1.12.2.jar                      | None                                     |
	| UC    | buildcraftfactory           | 7.99.14                  | BuildCraft-Mod-1.12.2.jar                      | None                                     |
	| UC    | buildcraftrobotics          | 7.99.14                  | BuildCraft-Mod-1.12.2.jar                      | None                                     |
	| UC    | buildcraftsilicon           | 7.99.14                  | BuildCraft-Mod-1.12.2.jar                      | None                                     |
	| UC    | buildcrafttransport         | 7.99.14                  | BuildCraft-Mod-1.12.2.jar                      | None                                     |
	| UC    | configurablecane            | 1.0                      | Configurable-Cane-Mod-1.12.2.jar               | None                                     |
	| UC    | extendedrenderer            | v1.0                     | CoroUtil-1.12.1.jar                            | None                                     |
	| UC    | coroutil                    | 1.12.1-1.2.11            | CoroUtil-1.12.1.jar                            | None                                     |
	| UC    | configmod                   | v1.0                     | CoroUtil-1.12.1.jar                            | None                                     |
	| UC    | cosmeticarmorreworked       | 1.12.2-v1                | CosmeticArmorReworked-1.12.2-v1.jar            | aaaf83332a11df02406e9f266b1b65c1306f0f76 |
	| UC    | customizeddungeonloot       | 1.0.2                    | Customized-Dungeon-Loot-Mod-1.12.2.jar         | None                                     |
	| UC    | cyclopscore                 | 0.11.5                   | CyclopsCore-1.12.2-0.11.5.jar                  | bd0353b3e8a2810d60dd584e256e364bc3bedd44 |
	| UC    | torohealthmod               | 1.12.2-11                | Damage-Indicators-1.12.2.jar                   | None                                     |
	| UC    | dynamiclights               | 1.4.9                    | DynamicLights-1.12.2.jar                       | None                                     |
	| UC    | dynamiclights_onfire        | 1.0.7                    | DynamicLights-1.12.2.jar                       | None                                     |
	| UC    | dynamiclights_creepers      | 1.0.6                    | DynamicLights-1.12.2.jar                       | None                                     |
	| UC    | dynamiclights_dropitems     | 1.1.0                    | DynamicLights-1.12.2.jar                       | None                                     |
	| UC    | dynamiclights_entityclasses | 1.0.1                    | DynamicLights-1.12.2.jar                       | None                                     |
	| UC    | dynamiclights_mobequipment  | 1.1.0                    | DynamicLights-1.12.2.jar                       | None                                     |
	| UC    | dynamiclights_flamearrows   | 1.0.1                    | DynamicLights-1.12.2.jar                       | None                                     |
	| UC    | dynamiclights_floodlights   | 1.0.3                    | DynamicLights-1.12.2.jar                       | None                                     |
	| UC    | dynamiclights_otherplayers  | 1.0.9                    | DynamicLights-1.12.2.jar                       | None                                     |
	| UC    | dynamiclights_theplayer     | 1.1.3                    | DynamicLights-1.12.2.jar                       | None                                     |
	| UC    | eplus                       | 5.0.169                  | EnchantingPlus-1.12.2-5.0.169.jar              | d476d1b22b218a10d845928d1665d45fce301b27 |
	| UC    | enchdesc                    | 1.1.8                    | Enchantment-Descriptions-Mod-1.12.2.jar        | d476d1b22b218a10d845928d1665d45fce301b27 |
	| UC    | epicsiegemod                | 13.163                   | EpicSiegeMod-13.163.jar                        | None                                     |
	| UC    | everlastingabilities        | 1.3.16                   | EverlastingAbilities-1.12.2-1.3.16.jar         | bd0353b3e8a2810d60dd584e256e364bc3bedd44 |
	| UC    | extrautils2                 | 1.0                      | Extra-Utilities-Mod-1.12.2.jar                 | None                                     |
	| UC    | fencejumper                 | 1.0.3                    | fencejumper-1.12-1.0.3.jar                     | None                                     |
	| UC    | harvestchevsky              | b1                       | Gentle-Harvest-Mod-1.12.2.jar                  | None                                     |
	| UC    | gokistats                   | @version@                | Goki-Stats-Mod-1.12.2.jar                      | None                                     |
	| UC    | guideapi                    | 1.12-2.1.6-61            | Guide-API-1.12-2.1.6-61.jar                    | None                                     |
	| UC    | ic2                         | 2.8.100-ex112            | Industrial-Craft-2-Mod-Experimental-1.12.2.jar | de041f9f6187debbc77034a344134053277aa3b0 |
	| UC    | inventorytweaks             | 1.63+release.109.220f184 | Inventory-Tweaks-Mod-1.12.2.jar                | 55d2cd4f5f0961410bf7b91ef6c6bf00a766dcbe |
	| UC    | ironbackpacks               | 1.12.2-3.0.7-10          | IronBackpacks-1.12.2-3.0.7-10.jar              | None                                     |
	| UC    | ironchest                   | 1.12.2-7.0.40.824        | ironchest-1.12.2-7.0.40.824.jar                | None                                     |
	| UC    | jei                         | 4.9.1.168                | jei_1.12.2-4.9.1.168.jar                       | None                                     |
	| UC    | levelup2                    | ${version}               | Level+Up!+2-1.1.22-1.12 (1).jar                | None                                     |
	| UC    | weaponlevels                | 2.1.1                    | Levels-2-Mod-1.12.2.jar                        | None                                     |
	| UC    | lootbags                    | 2.5.1                    | LootBags-Mod-1.12.2.jar                        | None                                     |
	| UC    | modnametooltip              | 1.10.0                   | Mod-Name-Tooltip-Mod-1.12.2.jar                | None                                     |
	| UC    | monk                        | 1.0                      | monk-mod-1.2.jar                               | None                                     |
	| UC    | quickleafdecay              | 1.2.4                    | QuickLeafDecay-MC1.12.1-1.2.4.jar              | None                                     |
	| UC    | reccomplex                  | 1.4.5                    | RecurrentComplex-1.4.5.1.jar                   | None                                     |
	| UC    | roguelike                   | 1.8.0                    | RoguelikeDungeons-1.12.2-1.8.0.jar             | None                                     |
	| UC    | ruins                       | 17.1                     | Ruins-1.12.2.jar                               | None                                     |
	| UC    | rwbym                       | 2.0                      | RWBY-Models-Mod-1.12.2.jar                     | None                                     |
	| UC    | silentlib                   | 2.2.9                    | Silent-Lib-1.12.1.jar                          | None                                     |
	| UC    | scalinghealth               | 1.3.0                    | Scaling-Health-Mod-1.12.2.jar                  | None                                     |
	| UC    | twilightforest              | 3.7.424                  | twilightforest-1.12.2-3.7.424-universal.jar    | None                                     |
	| UC    | worldedit                   | 6.1.8                    | WorldEdit-1.12.jar                             | None                                     |
	| UC    | xaerominimap                | 1.13.9                   | Xaeros-Minimap-Mod-1.12.jar                    | None                                     |
	| UC    | zombieawareness             | 1.12.1-1.11.10           | Zombie-Awareness-Mod-1.12.1.jar                | None                                     |
	| UC    | midnight                    | 0.1.0                    | The-Midnight-Mod-1.12.2.jar                    | None                                     |

	Loaded coremods (and transformers): 
LoadingPlugin (Blood-Moon-Mod-1.12.2.jar)
  lumien.bloodmoon.asm.ClassTransformer
Inventory Tweaks Coremod (Inventory-Tweaks-Mod-1.12.2.jar)
  invtweaks.forge.asm.ContainerTransformer
midnight (The-Midnight-Mod-1.12.2.jar)
  com.mushroom.midnight.core.transformer.MidnightClassTransformer
SHLoadingPlugin (Scaling-Health-Mod-1.12.2.jar)
  net.silentchaos512.scalinghealth.asm.SHClassTransformer
IvToolkit (IvToolkit-1.3.3-1.12.jar)
  
DLFMLCorePlugin (DynamicLights-1.12.2.jar)
  atomicstryker.dynamiclights.common.DLTransformer
	OptiFine Version: OptiFine_1.12.2_HD_U_E1
	OptiFine Build: 20180628-111228
	Render Distance Chunks: 8
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.5.13497 Compatibility Profile Context 23.20.813.512
	OpenGlRenderer: AMD Radeon(TM) Vega 8 Graphics
	OpenGlVendor: ATI Technologies Inc.
	CpuCount: 8

**Comment by alphawulf11** [comment]
what does it mean?

Thank you in advance

**Comment by covers1624** [comment]
Delete the old CCL config in your configs folder. `config/codechickenlib.cfg`
