### ISSUE TITLE
Codechickenlib crashing 

### ISSUE THREAD

**Issue by Shadow0K** [TheCBProject/CodeChickenLib#206]
this keeps crashing my game, here what it says:

The game crashed whilst there was a severe problem during mod loading that has caused the game to fail
Error: net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from CodeChicken Lib (codechickenlib)

crash report:
---- Minecraft Crash Report ----

WARNING: coremods are present:
  MixinLoaderForge (Valkyrien-Warfare-Mod-1.12.2.jar)
  Inventory Tweaks Coremod (InventoryTweaks-1.64-dev.jar)
  MovingWorldCore (MovingWorld-Mod-1.12.jar)
  TheBetweenlandsLoadingPlugin (TheBetweenlands-3.3.12-core.jar)
Contact their authors BEFORE contacting forge

// I bet Cylons wouldn't have this problem.

Time: 10/27/18 4:00 PM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from CodeChicken Lib (codechickenlib)
Caused by: codechicken.lib.configuration.ConfigFile$ConfigException: codechicken.lib.configuration.ConfigParseException: Invalid value type d, @Line:20, dump_asm=true
	at codechicken.lib.configuration.ConfigFile.load(ConfigFile.java:61)
	at codechicken.lib.configuration.ConfigFile.<init>(ConfigFile.java:43)
	at codechicken.lib.configuration.ConfigFile.<init>(ConfigFile.java:29)
	at codechicken.lib.configuration.ConfigFile.<init>(ConfigFile.java:19)
	at codechicken.lib.CodeChickenLib.preInit(CodeChickenLib.java:50)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:624)
	at sun.reflect.GeneratedMethodAccessor9.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:218)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:196)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:135)
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:627)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:252)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:466)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:377)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: codechicken.lib.configuration.ConfigParseException: Invalid value type d, @Line:20, dump_asm=true
	at codechicken.lib.configuration.ConfigTag.parseTag(ConfigTag.java:92)
	at codechicken.lib.configuration.ConfigFile.load(ConfigFile.java:59)
	... 44 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 339416424 bytes (323 MB) / 805306368 bytes (768 MB) up to 6442450944 bytes (6144 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx6G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=16M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2768 Optifine OptiFine_1.12.2_HD_U_C8 48 mods loaded, 48 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID                                           | Version                      | Source                                        | Signature                                |
	|:----- |:-------------------------------------------- |:---------------------------- |:--------------------------------------------- |:---------------------------------------- |
	| UCH   | minecraft                                    | 1.12.2                       | minecraft.jar                                 | None                                     |
	| UCH   | mcp                                          | 9.42                         | minecraft.jar                                 | None                                     |
	| UCH   | FML                                          | 8.0.99.99                    | forge-1.12.2-14.23.5.2768.jar                 | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCH   | forge                                        | 14.23.5.2768                 | forge-1.12.2-14.23.5.2768.jar                 | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCH   | com.elytradev.movingworld.common.asm.coremod |                              | minecraft.jar                                 | None                                     |
	| UCH   | orbis_api                                    | 1.12.2-1.1.3                 | orbis_api-1.12.2-1.1.3.jar                    | None                                     |
	| UCH   | aether                                       | 1.12.2-1.0.6                 | aether_ii-1.12.2-1.0.6.jar                    | None                                     |
	| UCEE  | codechickenlib                               | 3.2.2.353                    | CodeChickenLib-1.12.2-3.2.2.353-universal.jar | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| UC    | ancientwarfare                               | 1.12.2-2.6.1.318             | ancientwarfare-1.12.2-2.6.1.318.jar           | None                                     |
	| UC    | ancientwarfareautomation                     | 1.12.2-2.6.1.318             | ancientwarfare-1.12.2-2.6.1.318.jar           | None                                     |
	| UC    | ancientwarfarenpc                            | 1.12.2-2.6.1.318             | ancientwarfare-1.12.2-2.6.1.318.jar           | None                                     |
	| UC    | ancientwarfarestructure                      | 1.12.2-2.6.1.318             | ancientwarfare-1.12.2-2.6.1.318.jar           | None                                     |
	| UC    | ancientwarfarevehicle                        | 1.12.2-2.6.1.318             | ancientwarfare-1.12.2-2.6.1.318.jar           | None                                     |
	| UC    | backpack                                     | 3.0.2                        | Backpacks-Mod-1.12.2.jar                      | None                                     |
	| UC    | bibliocraft                                  | 2.4.5                        | BiblioCraft-Mod-1.12.2.jar                    | None                                     |
	| UC    | biomesoplenty                                | 7.0.1.2297                   | Biomes-O-Plenty-Mod-1.12.2.jar                | None                                     |
	| UC    | guideapi                                     | 1.12-2.1.5-60                | Guide-API-1.12-2.1.5-60.jar                   | None                                     |
	| UC    | bloodmagic                                   | 1.12.2-2.2.12-97             | BloodMagic-1.12.2-2.2.12-97.jar               | None                                     |
	| UC    | customnpcs                                   | 1.12                         | Custom-NPCs-Mod-1.12.2.jar                    | None                                     |
	| UC    | movingworld                                  | 1.12-6.342                   | MovingWorld-Mod-1.12.jar                      | None                                     |
	| UC    | davincisvessels                              | @DVESSELSVER@                | Davincis-Vessels-Mod-1.12.jar                 | None                                     |
	| UC    | lootablebodies                               | 2.4.0                        | DrCyanosLootableBodies_1.12-2.4.0.jar         | None                                     |
	| UC    | dynamictrees                                 | 1.12.2-0.7.8                 | DynamicTrees-1.12.2-0.7.8.jar                 | None                                     |
	| UC    | placebo                                      | 1.2.0                        | Placebo-1.12.2-1.2.0 (1).jar                  | None                                     |
	| UC    | hexxitgear                                   | 2.7.0                        | Hexxit+Gear-1.12.2-2.7.0.jar                  | None                                     |
	| UC    | infernalmobs                                 | 1.7.3                        | Infernal-Mobs-Mod-1.12.2.jar                  | None                                     |
	| UC    | inventorytweaks                              | 1.64-dev+release.110.b4fac73 | InventoryTweaks-1.64-dev.jar                  | 55d2cd4f5f0961410bf7b91ef6c6bf00a766dcbe |
	| UC    | ironchest                                    | 1.12.2-7.0.46.831            | ironchest-1.12.2-7.0.46.831.jar               | None                                     |
	| UC    | jei                                          | 4.12.0.216                   | jei_1.12.2-4.12.0.216.jar                     | None                                     |
	| UC    | journeymap                                   | 1.12.2-5.5.2                 | journeymap-1.12.2-5.5.2.jar                   | None                                     |
	| UC    | landlust                                     | 1.12.2-0.3.5                 | landlust-1.12.2-0.3.5.jar                     | None                                     |
	| UC    | lunatriuscore                                | 1.2.0.42                     | LunatriusCore-1.12.2-1.2.0.42-universal.jar   | None                                     |
	| UC    | mantle                                       | 1.12-1.3.1.21                | Mantle-Mod-1.12.1(1).jar                      | None                                     |
	| UC    | modnametooltip                               | 1.10.0                       | modnametooltip_1.12.2-1.10.0.jar              | None                                     |
	| UC    | nei                                          | 2.4.1                        | Not-Enough-Items-1.12.2-Recommended.jar       | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| UC    | reforged                                     | 0.7.5                        | Reforged-Mod-1.12.jar                         | None                                     |
	| UC    | roguelike                                    | 1.7.2                        | Roguelike-Dungeons-Mod-1.12.2.jar             | None                                     |
	| UC    | schematica                                   | 1.8.0.169                    | Schematica-1.12.2-1.8.0.169-universal.jar     | None                                     |
	| UC    | secretroomsmod                               | 5.1.13                       | Secret-Rooms-Mod-1.12.2.jar                   | None                                     |
	| UC    | tconstruct                                   | 1.12.2-2.10.1.84             | TConstruct-1.12.2-2.10.1.84.jar               | None                                     |
	| UC    | lostquiver                                   | 1.0 - MC 1.12.2              | The-Lost-Quiver-Mod-1.12.2.jar                | None                                     |
	| UC    | tinkersjei                                   | 1.0                          | Tinkers-JEI-Mod-1.12.2.jar                    | None                                     |
	| UC    | torohealthmod                                | 1.12.2-11                    | torohealth-1.12.2-11.jar                      | None                                     |
	| UC    | toroquest                                    | 1.12.2-5.2                   | ToroQuest-Mod-1.12.2.jar                      | None                                     |
	| UC    | treechopper                                  | 1.2.4                        | Tree-Chopper-Mod-1.12.2.jar                   | None                                     |
	| UC    | twilightforest                               | 3.5.263                      | twilightforest-1.12.2-3.5.263-universal.jar   | None                                     |
	| UC    | valkyrienwarfare                             | 0.9_alpha                    | Valkyrien-Warfare-Mod-1.12.2.jar              | None                                     |
	| UC    | thebetweenlands                              | 3.3.12                       | TheBetweenlands-3.3.12-universal.jar          | 38067d6878811efb38b6a045521cfd80b9b60b38 |

	Loaded coremods (and transformers): 
MixinLoaderForge (Valkyrien-Warfare-Mod-1.12.2.jar)
  
Inventory Tweaks Coremod (InventoryTweaks-1.64-dev.jar)
  invtweaks.forge.asm.ContainerTransformer
MovingWorldCore (MovingWorld-Mod-1.12.jar)
  
TheBetweenlandsLoadingPlugin (TheBetweenlands-3.3.12-core.jar)
  thebetweenlands.core.TheBetweenlandsClassTransformer
	GL info: ' Vendor: 'Intel' Version: '4.4.0 - Build 20.19.15.4531' Renderer: 'Intel(R) HD Graphics 5500'
	Pulsar/tconstruct loaded Pulses: 
		- TinkerCommons (Enabled/Forced)
		- TinkerWorld (Enabled/Not Forced)
		- TinkerTools (Enabled/Not Forced)
		- TinkerHarvestTools (Enabled/Forced)
		- TinkerMeleeWeapons (Enabled/Forced)
		- TinkerRangedWeapons (Enabled/Forced)
		- TinkerModifiers (Enabled/Forced)
		- TinkerSmeltery (Enabled/Not Forced)
		- TinkerGadgets (Enabled/Not Forced)
		- TinkerOredict (Enabled/Forced)
		- TinkerIntegration (Enabled/Forced)
		- TinkerFluids (Enabled/Forced)
		- TinkerMaterials (Enabled/Forced)
		- TinkerModelRegister (Enabled/Forced)

	OptiFine Version: OptiFine_1.12.2_HD_U_C8
	Render Distance Chunks: 16
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.4.0 - Build 20.19.15.4531
	OpenG

**Comment by P3rf3ctXZer0** [comment]
Dupe of https://github.com/TheCBProject/CodeChickenLib/issues/205

**Comment by covers1624** [comment]
Delete the old CCL config. `config/codechickenlib.cfg`

**Comment by P3rf3ctXZer0** [comment]
It doesn't fix serveside login hangup @covers1624

**Comment by Shadow0K** [comment]
thank you
its not crashing anymore
