### ISSUE TITLE
Crashing While Launching (Can anyone help?) Version 1.12.2

### ISSUE THREAD

**Issue by BusterGaming** [TheCBProject/CodeChickenLib#207]
Hey i'm just trying to use this mod to play single player stuff with but it keeps crashing and I don't know why can anyone help me out?

Here is the crash log
---- Minecraft Crash Report ----

WARNING: coremods are present:
  Inventory Tweaks Coremod (InventoryTweaks-1.63.jar)
  EnderCorePlugin (EnderCore-1.12.2-0.5.43.jar)
  CubicChunksCoreMod (CubicChunks-1.12.2-0.0.884.0-SNAPSHOT-all.jar)
  AppleCore (AppleCore-mc1.12.2-3.1.4.jar)
  OpenModsCorePlugin (OpenModsLib-1.12.2-0.12.1.jar)
  CubicGenCoreMod (CubicWorldGen-1.12.2-0.0.28.0-SNAPSHOT-all.jar)
Contact their authors BEFORE contacting forge

// Who set us up the TNT?

Time: 11/4/18 5:30 PM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from CodeChicken Lib (codechickenlib)
Caused by: codechicken.lib.configuration.ConfigFile$ConfigException: codechicken.lib.configuration.ConfigParseException: Invalid value type d, @Line:6, dump_asm=true
	at codechicken.lib.configuration.ConfigFile.load(ConfigFile.java:61)
	at codechicken.lib.configuration.ConfigFile.<init>(ConfigFile.java:43)
	at codechicken.lib.configuration.ConfigFile.<init>(ConfigFile.java:29)
	at codechicken.lib.configuration.ConfigFile.<init>(ConfigFile.java:19)
	at codechicken.lib.CodeChickenLib.preInit(CodeChickenLib.java:50)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:624)
	at sun.reflect.GeneratedMethodAccessor8.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:218)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:196)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:135)
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:627)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:252)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:466)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:377)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: codechicken.lib.configuration.ConfigParseException: Invalid value type d, @Line:6, dump_asm=true
	at codechicken.lib.configuration.ConfigTag.parseTag(ConfigTag.java:92)
	at codechicken.lib.configuration.ConfigFile.load(ConfigFile.java:59)
	... 44 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1467317824 bytes (1399 MB) / 2583691264 bytes (2464 MB) up to 6442450944 bytes (6144 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx6G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2768 77 mods loaded, 76 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID                                | Version                  | Source                                          | Signature                                |
	|:----- |:--------------------------------- |:------------------------ |:----------------------------------------------- |:---------------------------------------- |
	| UCH   | minecraft                         | 1.12.2                   | minecraft.jar                                   | None                                     |
	| UCH   | mcp                               | 9.42                     | minecraft.jar                                   | None                                     |
	| UCH   | FML                               | 8.0.99.99                | forge-1.12.2-14.23.5.2768.jar                   | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCH   | forge                             | 14.23.5.2768             | forge-1.12.2-14.23.5.2768.jar                   | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCH   | openmodscore                      | 0.12.1                   | minecraft.jar                                   | None                                     |
	| UCH   | biomesoplenty                     | 7.0.1.2399               | BiomesOPlenty-1.12.2-7.0.1.2399-universal.jar   | None                                     |
	| UCH   | baubles                           | 1.5.2                    | Baubles-1.12-1.5.2.jar                          | None                                     |
	| UCH   | jei                               | 4.12.1.217               | jei_1.12.2-4.12.1.217.jar                       | None                                     |
	| UCH   | thaumcraft                        | 6.1.BETA26               | Thaumcraft-1.12.2-6.1.BETA26.jar                | None                                     |
	| UCH   | botania                           | r1.10-357                | Botania+r1.10-357.jar                           | None                                     |
	| UCH   | redstoneflux                      | 2.1.0                    | RedstoneFlux-1.12-2.1.0.6-universal.jar         | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| UCH   | cofhcore                          | 4.6.1                    | CoFHCore-1.12.2-4.6.1.22-universal.jar          | None                                     |
	| UCH   | craftstudioapi                    | 1.0.0                    | CraftStudio-1.0.0.93-mc1.12-alpha.jar           | None                                     |
	| UCH   | harvestcraft                      | 1.12.2z                  | Pam's+HarvestCraft+1.12.2za.jar                 | None                                     |
	| UCH   | twilightforest                    | 3.8.689                  | twilightforest-1.12.2-3.8.689-universal.jar     | None                                     |
	| UCH   | animania                          | 1.6.0.2                  | animania-1.12.2-1.6.0.2.jar                     | None                                     |
	| UCH   | applecore                         | 3.1.4                    | AppleCore-mc1.12.2-3.1.4.jar                    | None                                     |
	| UCH   | appleskin                         | 1.0.9                    | AppleSkin-mc1.12-1.0.9.jar                      | None                                     |
	| UCH   | baublelicious                     | 1.4.0-4                  | Baublelicious-1.4.0-4.jar                       | None                                     |
	| UCH   | bibliocraft                       | 2.4.5                    | BiblioCraft[v2.4.5][MC1.12.2].jar               | None                                     |
	| UCH   | chameleon                         | 1.12-4.1.3               | Chameleon-1.12-4.1.3.jar                        | None                                     |
	| UCH   | clumps                            | 3.1.1                    | Clumps-3.1.1.jar                                | None                                     |
	| UCEE  | codechickenlib                    | 3.2.2.353                | CodeChickenLib-1.12.2-3.2.2.353-universal.jar   | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| UC    | cofhworld                         | 1.3.0                    | CoFHWorld-1.12.2-1.3.0.6-universal.jar          | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| UC    | crafttweaker                      | 4.1.11                   | CraftTweaker2-1.12-4.1.11.jar                   | None                                     |
	| UC    | ctgui                             | 1.0.0                    | CraftTweaker2-1.12-4.1.11.jar                   | None                                     |
	| UC    | crafttweakerjei                   | 2.0.2                    | CraftTweaker2-1.12-4.1.11.jar                   | None                                     |
	| UC    | cubicchunks                       | 0.0.9999.0               | CubicChunks-1.12.2-0.0.884.0-SNAPSHOT-all.jar   | None                                     |
	| UC    | cubicgen                          | 1.12.2-0.0.28.0-SNAPSHOT | CubicWorldGen-1.12.2-0.0.28.0-SNAPSHOT-all.jar  | None                                     |
	| UC    | ptrmodellib                       | 1.0.3                    | PTRLib-1.0.3.jar                                | None                                     |
	| UC    | props                             | 2.6.2                    | Decocraft-2.6.2_1.12.2.jar                      | None                                     |
	| UC    | endercore                         | 1.12.2-0.5.43            | EnderCore-1.12.2-0.5.43.jar                     | None                                     |
	| UC    | thermalfoundation                 | 2.6.1                    | ThermalFoundation-1.12.2-2.6.1.22-universal.jar | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| UC    | thermalexpansion                  | 5.5.2                    | ThermalExpansion-1.12.2-5.5.2.39-universal.jar  | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| UC    | enderio                           | 5.0.37                   | EnderIO-1.12.2-5.0.37.jar                       | None                                     |
	| UC    | enderiointegrationtic             | 5.0.37                   | EnderIO-1.12.2-5.0.37.jar                       | None                                     |
	| UC    | enderiobase                       | 5.0.37                   | EnderIO-1.12.2-5.0.37.jar                       | None                                     |
	| UC    | enderioconduits                   | 5.0.37                   | EnderIO-1.12.2-5.0.37.jar                       | None                                     |
	| UC    | enderioconduitsappliedenergistics | 5.0.37                   | EnderIO-1.12.2-5.0.37.jar                       | None                                     |
	| UC    | enderioconduitsopencomputers      | 5.0.37                   | EnderIO-1.12.2-5.0.37.jar                       | None                                     |
	| UC    | refinedstorage                    | 1.6.9                    | refinedstorage-1.6.9.jar                        | None                                     |
	| UC    | enderioconduitsrefinedstorage     | 5.0.37                   | EnderIO-1.12.2-5.0.37.jar                       | None                                     |
	| UC    | ic2                               | 2.8.73-ex112             | industrialcraft-2-2.8.73-ex112.jar              | de041f9f6187debbc77034a344134053277aa3b0 |
	| UC    | forestry                          | 5.8.1.322                | forestry_1.12.2-5.8.1.322.jar                   | None                                     |
	| UC    | enderiointegrationforestry        | 5.0.37                   | EnderIO-1.12.2-5.0.37.jar                       | None                                     |
	| UC    | enderiointegrationticlate         | 5.0.37                   | EnderIO-1.12.2-5.0.37.jar                       | None                                     |
	| UC    | enderiomachines                   | 5.0.37                   | EnderIO-1.12.2-5.0.37.jar                       | None                                     |
	| UC    | enderiopowertools                 | 5.0.37                   | EnderIO-1.12.2-5.0.37.jar                       | None                                     |
	| UC    | extrautils2                       | 1.0                      | extrautils2-1.12-1.9.8.jar                      | None                                     |
	| UC    | fastbench                         | 1.5.3                    | FastWorkbench-1.12.2-1.5.3.jar                  | None                                     |
	| UC    | cfm                               | 5.15.0                   | furniture-5.15.0-1.12.2.jar                     | None                                     |
	| UC    | gravestone                        | 1.10.1                   | gravestone-1.10.1.jar                           | None                                     |
	| UC    | grimoireofgaia                    | 1.6.7                    | GrimoireOfGaia3-1.12.2-1.6.7.jar                | None                                     |
	| UC    | inventorypets                     | 1.5.3.1                  | inventorypets-1.12-1.5.3.1.jar                  | None                                     |
	| UC    | inventorytweaks                   | 1.63+release.109.220f184 | InventoryTweaks-1.63.jar                        | 55d2cd4f5f0961410bf7b91ef6c6bf00a766dcbe |
	| UC    | ironbackpacks                     | 1.12.2-3.0.8-12          | IronBackpacks-1.12.2-3.0.8-12.jar               | None                                     |
	| UC    | ironchest                         | 1.12.2-7.0.40.824        | ironchest-1.12.2-7.0.40.824.jar                 | None                                     |
	| UC    | jeibees                           | 0.9.0.5                  | jeibees-0.9.0.5-mc1.12.2.jar                    | None                                     |
	| UC    | journeymap                        | 1.12.2-5.5.2             | journeymap-1.12.2-5.5.2.jar                     | None                                     |
	| UC    | jeresources                       | 0.8.5.27                 | JustEnoughResources-1.12.2-0.8.5.27.jar         | None                                     |
	| UC    | magicbees                         | 1.0                      | MagicBees-1.12.2-3.1.10.jar                     | None                                     |
	| UC    | mantle                            | 1.12-1.3.3.39            | Mantle-1.12-1.3.3.39.jar                        | None                                     |
	| UC    | mob_grinding_utils                | 0.3.11                   | MobGrindingUtils-0.3.11.jar                     | None                                     |
	| UC    | naturescompass                    | 1.5.1                    | NaturesCompass-1.12.2-1.5.1.jar                 | None                                     |
	| UC    | openmods                          | 0.12.1                   | OpenModsLib-1.12.2-0.12.1.jar                   | d2a9a8e8440196e26a268d1f3ddc01b2e9c572a5 |
	| UC    | openblocks                        | 1.8                      | OpenBlocks-1.12.2-1.8.jar                       | d2a9a8e8440196e26a268d1f3ddc01b2e9c572a5 |
	| UC    | placebo                           | 1.5.0                    | Placebo-1.12.2-1.5.0.jar                        | None                                     |
	| UC    | projecte                          | 1.12-PE1.3.0             | ProjectE-1.12-PE1.3.0.jar                       | None                                     |
	| UC    | redstonearsenal                   | 2.6.1                    | RedstoneArsenal-1.12.2-2.6.1.15-universal.jar   | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| UC    | thermalcultivation                | 0.3.1                    | ThermalCultivation-1.12.2-0.3.1.8-universal.jar | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| UC    | thermaldynamics                   | 2.5.3                    | ThermalDynamics-1.12.2-2.5.3.16-universal.jar   | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| UC    | toastcontrol                      | 1.7.1                    | Toast+Control-1.12.2-1.7.1.jar                  | None                                     |
	| UC    | torchmaster                       | 1.6.4.62                 | torchmaster_1.12.2-1.6.4.62.jar                 | 5e9a436b366831c8f54a7e80b015784da69278c6 |
	| UC    | wailaharvestability               | 1.1.12                   | WailaHarvestability-mc1.12-1.1.12.jar           | None                                     |
	| UC    | wanionlib                         | 1.12.2-1.7               | WanionLib-1.12.2-1.7.jar                        | None                                     |
	| UC    | unidict                           | 1.12.2-2.9.1             | UniDict-1.12.2-2.9.1.jar                        | None                                     |
	| UD    | cubicchunkscore                   | @@VERSION@@              | minecraft.jar                                   | None                                     |

	Loaded coremods (and transformers): 
Inventory Tweaks Coremod (InventoryTweaks-1.63.jar)
  invtweaks.forge.asm.ContainerTransformer
EnderCorePlugin (EnderCore-1.12.2-0.5.43.jar)
  com.enderio.core.common.transform.EnderCoreTransformer
  com.enderio.core.common.transform.SimpleMixinPatcher
CubicChunksCoreMod (CubicChunks-1.12.2-0.0.884.0-SNAPSHOT-all.jar)
  
AppleCore (AppleCore-mc1.12.2-3.1.4.jar)
  squeek.applecore.asm.TransformerModuleHandler
OpenModsCorePlugin (OpenModsLib-1.12.2-0.12.1.jar)
  openmods.core.OpenModsClassTransformer
CubicGenCoreMod (CubicWorldGen-1.12.2-0.0.28.0-SNAPSHOT-all.jar)
  
	GL info: ' Vendor: 'Intel' Version: '4.3.0 - Build 20.19.15.4531' Renderer: 'Intel(R) HD Graphics 4600'
	OpenModsLib class transformers: [llama_null_fix:FINISHED],[horse_base_null_fix:FINISHED],[pre_world_render_hook:FINISHED],[player_render_hook:FINISHED],[horse_null_fix:FINISHED]

**Comment by covers1624** [comment]
Delete the old config file for ccl. `config/codechickenlib.cfg`
