### ISSUE TITLE
Error: net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from CodeChicken Lib (codechickenlib)

### ISSUE THREAD

**Issue by IANTHEGREAT144** [TheCBProject/CodeChickenLib#208]
Minecraft Keeps crashing because The game crashed whilst there was a severe problem during mod loading that has caused the game to fail Error: net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from CodeChicken Lib (codechickenlib)

Plz help

**Comment by covers1624** [comment]
You have provided literally no information, Please provide the crash report via gist or pastebin.

**Comment by xElementzx** [comment]
*facepalm*
