### ISSUE TITLE
The game crashed whilst there was a severe problem during mod loading that has caused the game to fail

### ISSUE THREAD

**Issue by TealsHipHealz** [TheCBProject/CodeChickenLib#209]
Error: net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Not Enough Items (nei) 

(https://github.com/TheCBProject/CodeChickenLib/files/2564583/crash-2018-11-08_21.17.37-client.txt)

**Comment by TealsHipHealz** [comment]
I only have this crash when I have 'CodeChickenLib' in my mods folder

**Comment by TealsHipHealz** [comment]
bump i guess?

**Comment by Jark5455** [comment]
i have the same thing but its an exception from codechickenlib

**Comment by Sixthcrow** [comment]
Try deleting the config file in the .minecraft\config folder. codechickenlib.cfg in this case. Helped me and got notenoughitems working too.

**Comment by covers1624** [comment]
Update NEI, a fix was pushed for this. Caused by changes in forge.
