### ISSUE TITLE
net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from CodeChicken Lib (codechickenlib)

### ISSUE THREAD

**Issue by iJoeyMonster** [TheCBProject/CodeChickenLib#210]
This has probably already been reported but I'm giving my report as well. 

https://pastebin.com/CHURLdaN

I get this whenever I try to start my game. 

Edit: Forge and all mods are updated to their latest version. I also checked to make sure 1.12.2 is also updated to the latest file.

**Comment by covers1624** [comment]
delete the old CCL config in your config folder. `config/codechickenlib.cfg`
