### ISSUE TITLE
Minecraft crashing while Loading Forge Mods.

### ISSUE THREAD

**Issue by policeMarcus** [TheCBProject/CodeChickenLib#215]
Alright, so I downloaded some Mods and put them into the Mods folder. Everything was normal until I was required to use CodeChickenLib In Thermal Expansion... I opened Minecraft and clicked "Play", Minecraft Loaded in the Modd   Buildcraft - Buildcraft Lib - CodeChickenLib *Crash*
CodeChicken Lib moke my Forge Crash!? What the hell is that shit! 

Note: I tried other versions of Codechickenlib, Also checked and I have the latest Forge for 1.12.2. I think I shall try the Recommended Version instead of the Latest ---

Edit 2018-12-04: I tried using the Recommended version of Forge, Didnt work...

Crash Report

---- Minecraft Crash Report ----

WARNING: coremods are present:
  EnderCorePlugin (EnderCore-1.12.2-0.5.43.jar)
  Inventory Tweaks Coremod (InventoryTweaks-1.64-dev.jar)
  IELoadingPlugin (ImmersiveEngineering-core-0.12-86.jar)
  CTMCorePlugin (CTM-MC1.12.2-0.3.3.22.jar)
Contact their authors BEFORE contacting forge

// Uh... Did I do that?

Time: 12/4/18 7:55 PM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from CodeChicken Lib (codechickenlib)
Caused by: codechicken.lib.configuration.ConfigFile$ConfigException: codechicken.lib.configuration.ConfigParseException: Invalid value type d, @Line:6, dump_asm=true
	at codechicken.lib.configuration.ConfigFile.load(ConfigFile.java:61)
	at codechicken.lib.configuration.ConfigFile.<init>(ConfigFile.java:43)
	at codechicken.lib.configuration.ConfigFile.<init>(ConfigFile.java:29)
	at codechicken.lib.configuration.ConfigFile.<init>(ConfigFile.java:19)
	at codechicken.lib.CodeChickenLib.preInit(CodeChickenLib.java:50)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:624)
	at sun.reflect.GeneratedMethodAccessor8.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:136)
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:627)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:252)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:467)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: codechicken.lib.configuration.ConfigParseException: Invalid value type d, @Line:6, dump_asm=true
	at codechicken.lib.configuration.ConfigTag.parseTag(ConfigTag.java:92)
	at codechicken.lib.configuration.ConfigFile.load(ConfigFile.java:59)
	... 44 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 336514968 bytes (320 MB) / 1073741824 bytes (1024 MB) up to 3221225472 bytes (3072 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx3G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2794 51 mods loaded, 51 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID                                | Version                      | Source                                          | Signature                                |
	|:----- |:--------------------------------- |:---------------------------- |:----------------------------------------------- |:---------------------------------------- |
	| LCH   | minecraft                         | 1.12.2                       | minecraft.jar                                   | None                                     |
	| LCH   | mcp                               | 9.42                         | minecraft.jar                                   | None                                     |
	| LCH   | FML                               | 8.0.99.99                    | forge-1.12.2-14.23.5.2794.jar                   | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCH   | forge                             | 14.23.5.2794                 | forge-1.12.2-14.23.5.2794.jar                   | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCH   | bonsaitrees                       | 1.1.1                        | bonsaitrees-1.1.1-b138.jar                      | None                                     |
	| LCH   | buildcraftlib                     | 7.99.19                      | buildcraft-7.99.19.jar                          | None                                     |
	| LCH   | buildcraftcore                    | 7.99.19                      | buildcraft-7.99.19.jar                          | None                                     |
	| LCH   | buildcraftbuilders                | 7.99.19                      | buildcraft-7.99.19.jar                          | None                                     |
	| LCH   | buildcraftenergy                  | 7.99.19                      | buildcraft-7.99.19.jar                          | None                                     |
	| LCH   | buildcraftfactory                 | 7.99.19                      | buildcraft-7.99.19.jar                          | None                                     |
	| LCH   | buildcraftrobotics                | 7.99.19                      | buildcraft-7.99.19.jar                          | None                                     |
	| LCH   | buildcrafttransport               | 7.99.19                      | buildcraft-7.99.19.jar                          | None                                     |
	| LCH   | buildcraftsilicon                 | 7.99.19                      | buildcraft-7.99.19.jar                          | None                                     |
	| LCH   | chameleon                         | 1.12-4.1.3                   | Chameleon-1.12-4.1.3.jar                        | None                                     |
	| LCH   | chesttransporter                  | 2.8.8                        | ChestTransporter-1.12.2-2.8.8.jar               | None                                     |
	| LCH   | ctm                               | MC1.12.2-0.3.3.22            | CTM-MC1.12.2-0.3.3.22.jar                       | None                                     |
	| LCH   | chisel                            | MC1.12.2-0.2.1.35            | Chisel-MC1.12.2-0.2.1.35.jar                    | None                                     |
	| LCE   | codechickenlib                    | 3.2.1.351                    | CodeChickenLib-1.12.2-3.2.1.351-universal.jar   | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| LC    | redstoneflux                      | 2.1.0                        | RedstoneFlux-1.12-2.1.0.6-universal.jar         | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| LC    | cofhcore                          | 4.6.1                        | CoFHCore-1.12.2-4.6.1.22-universal.jar          | None                                     |
	| LC    | cofhworld                         | 1.3.0                        | CoFHWorld-1.12.2-1.3.0.6-universal (1).jar      | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| LC    | endercore                         | 1.12.2-0.5.43                | EnderCore-1.12.2-0.5.43.jar                     | None                                     |
	| LC    | jei                               | 4.13.1.226                   | jei_1.12.2-4.13.1.226.jar                       | None                                     |
	| LC    | thermalfoundation                 | 2.6.1                        | ThermalFoundation-1.12.2-2.6.1.22-universal.jar | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| LC    | thermalexpansion                  | 5.5.2                        | ThermalExpansion-1.12.2-5.5.2.39-universal.jar  | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| LC    | enderio                           | 5.0.38                       | EnderIO-1.12.2-5.0.38.jar                       | None                                     |
	| LC    | enderiointegrationtic             | 5.0.38                       | EnderIO-1.12.2-5.0.38.jar                       | None                                     |
	| LC    | enderiobase                       | 5.0.38                       | EnderIO-1.12.2-5.0.38.jar                       | None                                     |
	| LC    | enderioconduits                   | 5.0.38                       | EnderIO-1.12.2-5.0.38.jar                       | None                                     |
	| LC    | enderioconduitsappliedenergistics | 5.0.38                       | EnderIO-1.12.2-5.0.38.jar                       | None                                     |
	| LC    | enderioconduitsopencomputers      | 5.0.38                       | EnderIO-1.12.2-5.0.38.jar                       | None                                     |
	| LC    | enderioconduitsrefinedstorage     | 5.0.38                       | EnderIO-1.12.2-5.0.38.jar                       | None                                     |
	| LC    | enderiointegrationforestry        | 5.0.38                       | EnderIO-1.12.2-5.0.38.jar                       | None                                     |
	| LC    | mantle                            | 1.12-1.3.3.39                | Mantle-1.12-1.3.3.39.jar                        | None                                     |
	| LC    | tconstruct                        | 1.12.2-2.11.0.106            | TConstruct-1.12.2-2.11.0.106.jar                | None                                     |
	| LC    | enderiointegrationticlate         | 5.0.38                       | EnderIO-1.12.2-5.0.38.jar                       | None                                     |
	| LC    | enderiomachines                   | 5.0.38                       | EnderIO-1.12.2-5.0.38.jar                       | None                                     |
	| LC    | enderiopowertools                 | 5.0.38                       | EnderIO-1.12.2-5.0.38.jar                       | None                                     |
	| LC    | valkyrielib                       | 1.12.2-2.0.18.3              | valkyrielib-1.12.2-2.0.18.3.jar                 | None                                     |
	| LC    | environmentaltech                 | 1.12.2-2.0.18.2              | environmentaltech-1.12.2-2.0.18.2.jar           | None                                     |
	| LC    | waila                             | 1.8.26                       | Hwyla-1.8.26-B41_1.12.2.jar                     | None                                     |
	| LC    | inventorytweaks                   | 1.64-dev+release.117.7221546 | InventoryTweaks-1.64-dev.jar                    | 55d2cd4f5f0961410bf7b91ef6c6bf00a766dcbe |
	| LC    | ironchest                         | 1.12.2-7.0.54.838            | ironchest-1.12.2-7.0.54.838.jar                 | None                                     |
	| LC    | journeymap                        | 1.12.2-5.5.3                 | journeymap-1.12.2-5.5.3.jar                     | None                                     |
	| LC    | oreexcavation                     | 1.4.133                      | OreExcavation-1.4.133.jar                       | None                                     |
	| LC    | harvestcraft                      | 1.12.2z                      | Pam's+HarvestCraft+1.12.2za.jar                 | None                                     |
	| LC    | storagedrawers                    | 1.12-5.3.5                   | StorageDrawers-1.12.2-5.3.8.jar                 | None                                     |
	| LC    | tp                                | 3.2.31                       | tinyprogressions-1.12.2-3.3.31-Release.jar      | None                                     |
	| LC    | universalmodifiers                | 1.12.2-1.0.16.1              | valkyrielib-1.12.2-2.0.18.3.jar                 | None                                     |
	| LC    | wailaharvestability               | 1.1.12                       | WailaHarvestability-mc1.12-1.1.12.jar           | None                                     |
	| LC    | immersiveengineering              | 0.12-86                      | ImmersiveEngineering-0.12-86.jar                | 4cb49fcde3b43048c9889e0a3d083225da926334 |

	Loaded coremods (and transformers): 
EnderCorePlugin (EnderCore-1.12.2-0.5.43.jar)
  com.enderio.core.common.transform.EnderCoreTransformer
  com.enderio.core.common.transform.SimpleMixinPatcher
Inventory Tweaks Coremod (InventoryTweaks-1.64-dev.jar)
  invtweaks.forge.asm.ContainerTransformer
IELoadingPlugin (ImmersiveEngineering-core-0.12-86.jar)
  blusunrize.immersiveengineering.common.asm.IEClassTransformer
CTMCorePlugin (CTM-MC1.12.2-0.3.3.22.jar)
  team.chisel.ctm.client.asm.CTMTransformer
	GL info: ' Vendor: 'Intel' Version: '4.4.0 - Build 21.20.16.4550' Renderer: 'Intel(R) HD Graphics 530'
	Pulsar/tconstruct loaded Pulses: 
		- TinkerCommons (Enabled/Forced)
		- TinkerWorld (Enabled/Not Forced)
		- TinkerTools (Enabled/Not Forced)
		- TinkerHarvestTools (Enabled/Forced)
		- TinkerMeleeWeapons (Enabled/Forced)
		- TinkerRangedWeapons (Enabled/Forced)
		- TinkerModifiers (Enabled/Forced)
		- TinkerSmeltery (Enabled/Not Forced)
		- TinkerGadgets (Enabled/Not Forced)
		- TinkerOredict (Enabled/Forced)
		- TinkerIntegration (Enabled/Forced)
		- TinkerFluids (Enabled/Forced)
		- TinkerMaterials (Enabled/Forced)
		- TinkerModelRegister (Enabled/Forced)
		- chiselIntegration (Enabled/Not Forced)
		- wailaIntegration (Enabled/Not Forced)

**Comment by covers1624** [comment]
Duplicate, Delete your old ccl config, `config/codechickenlib.cfg`

**Comment by policeMarcus** [comment]
Can't find what you are trying to tell me
http://prntscr.com/lrnvf2

http://prntscr.com/lrnvq0

Can I get a Stage instruction ?

**Comment by covers1624** [comment]
What? In your minecraft directory, next to the mods folder, you have a folder called `config` inside that folder there is a file `codechickenlib.cfg`, delete that file.

**Comment by policeMarcus** [comment]
Got it, Thanks!
