### ISSUE TITLE
Crashing in Forge/MC 1.12.2 "LoaderExceptionModCrash" [Crash report now included]

### ISSUE THREAD

**Issue by ShplootleJess** [TheCBProject/CodeChickenLib#217]
Not sure why my game is crashing all of a sudden, it worked fine a week ago. Full error code states: Error: net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from CodeChicken Lib (codechickenlib)

**Comment by covers1624** [comment]
Please provide the actual craah report.

**Comment by ShplootleJess** [comment]
[Link to the full crash report](https://pastebin.com/DdzvVa1Q)

**Comment by MineRobber9000** [comment]
Duplicate, delete `config/codechickenlib.cfg` under your game directory.

**Comment by ShplootleJess** [comment]
> Duplicate, delete `config/codechickenlib.cfg` under your game directory.

Not sure if I'm "duplicating" right but I copy/pasted a new one and deleted the old one, and it still crashes the same. Problem not resolved yet.

**Comment by ShplootleJess** [comment]
> Please provide the actual craah report.

I can't seem to load any version newer than 3.1.8.341 and even then, NEI causes issues so your mods aren't compatible with the latest versions of Forge. Please fix

**Comment by MineRobber9000** [comment]
> Duplicate

Means that this issue is a duplicate of a previous issue.

#194 is the earliest instance I can find of this.
