### ISSUE TITLE
Move Inventory package from CCC to CCL

### ISSUE THREAD

**Issue by nikita488** [TheCBProject/CodeChickenLib#22]
I see that CCL 1.7.10 has classes like ContainerExtended, ContainerSynchronised, SlotDummy, SlotDummyOutput, etc but CCL 1.10.2+ don't have this and i see that this classes now in CCC...

**Comment by covers1624** [comment]
They were probably moved during the 1.8 update by cb, everything will be removed from CCC to CCL in time, there is still some things i need to sort out first.

**Comment by covers1624** [comment]
This will be done in the 1.11 update.

**Comment by covers1624** [comment]
Done in 1.11
