### ISSUE TITLE
Crash With CCL

### ISSUE THREAD

**Issue by GreatOrator** [TheCBProject/CodeChickenLib#221]
https://pastebin.com/4RqufUWm

Getting this crash repeatedly even when trying to go back a version or two.

Happens during startup, seems like during preinit and referencing blockstate model loader

mc 1.12.x forge 14.23.5.2796

FYI, if i mismatch ccl and forge multipart versions it loads to tell me of the mismatch

**Comment by GreatOrator** [comment]
I think I may have pinpointed the cause.

I was loading up in MultiMC when the crash occurs, yet in the Curse Client it does not.  The only difference is the way they reference the minecraft directory.  A recent update with MultiMC places the directory as .minecraft where in the past it would only be minecraft.  I stumbled across this because a different mod was having issues with finding resources (but no crash) and it was because of this directory change.

**Comment by iDarper** [comment]
What was your fix Multimc wise? i get this issue with the newest pack version.

**Comment by GreatOrator** [comment]
I have not found one yet, and I have not loaded it for some time now to see if any further multimc releases may have fixed it.

**Comment by Drezkil** [comment]
I tried All The Versions of CCL and only the oldest worked

**Comment by covers1624** [comment]
This is completely out of my control, sorry.
