### ISSUE TITLE
Disable ConfigSync

### ISSUE THREAD

**Issue by tjsd** [TheCBProject/CodeChickenLib#222]
Hi!
I was wondering if there is anyway to turn of the config sync check when a client connects. Since this causes additional timeouts on top of evertyhing else going on in 1.12.2 packs.
CodeChickenLib-ConfigSync.

[Netty Server IO #1/INFO] [CodeChickenLib-ConfigSync]: Skipping config sync, No mods have registered a syncable config.

This is the server message, if there is a way to add a config option in codechickenlib.cfg like
B;"ConfigSync-Enabled"=false/true

**Comment by covers1624** [comment]
Ccl is not causing timeouts, as that message says, its skipping config sync, that means nothing happened. Ccl attempts sync directly after client-server handshake, usually earlier than anyone else doing config syncing. Something else is causing the game to time out, a slow connection or large amounts of data being synced to the client is likely the cause.
