### ISSUE TITLE
Finish installing and...CRASH again and again

### ISSUE THREAD

**Issue by Zervito** [TheCBProject/CodeChickenLib#223]
All mods works until installed codeChickenLib, and i cant see the problem.

[crash-2019-02-20_17.15.15-client.txt](https://github.com/TheCBProject/CodeChickenLib/files/2885446/crash-2019-02-20_17.15.15-client.txt)

[development console.txt](https://github.com/TheCBProject/CodeChickenLib/files/2885468/development.console.txt)

Thanks you.

**Comment by Drezkil** [comment]
I tried All The Versions and only the oldest worked

**Comment by covers1624** [comment]
Update Forge, and NEI.
