### ISSUE TITLE
CCL crashing with all 1.12.2 packs on new PC

### ISSUE THREAD

**Issue by iDarper** [TheCBProject/CodeChickenLib#225]
I recently bought a new machine, (Intel I7, 16 gigs ram, GTX 1060) and Any pack I try to load that has codechickenlib gives me a crash report. This happens on both MultiMC and Twitch.

Has anyone else had this issue?

https://pastebin.com/tHf04hmz Crash report is Stoneblock 2, but happens on Compaction, and also FTB Ultimate Reloaded.

**Comment by Drezkil** [comment]
I have the same problem try an older version.
It's not from your computer

**Comment by Drezkil** [comment]
I tried All The Versions and only the oldest worked

**Comment by covers1624** [comment]
Make sure you aren't running the game from a OneDrive folder, otherwise there is nothing i can do about this and the code related is slated for removal.

**Comment by Drezkil** [comment]
Okay now i can't even play without Thermal Foundation Shouting "Hey !! You must have CCL 1.2.2 to work !" 
But this coremod is corupted plz Help !!

**Comment by covers1624** [comment]
The crash stated above, literelly is caused by running Minecraft from a OneDrive folder. Move your instance.
