### ISSUE TITLE
Crash on mod initialization during launch

### ISSUE THREAD

**Issue by Goldenschmidt** [TheCBProject/CodeChickenLib#229]
Heya!

I got a weird issue on my hand. Apparently, CodeChickenLib is making my game crash during the mod initialization while in the launch sequence.

I only have the core mod on, so there shouldn't be any conflicts.

The crash-log is embedded here:
[crash-2019-03-22_12.55.25-client.txt](https://github.com/TheCBProject/CodeChickenLib/files/2996364/crash-2019-03-22_12.55.25-client.txt)

Hope this can help you.

-Goldenschmidt

**Comment by astridos2go** [comment]
I had the same issue. Apparently, this is a known issue and can be solved by deleting your old `/config/codechicken.cfg` file. Deleting this config file solved the issue for me. See this thread for more info https://github.com/TheCBProject/CodeChickenLib/issues/227 Hope this helps!
