### ISSUE TITLE
net.minecraftforge.fml.common.LoaderExceptionModCrash

### ISSUE THREAD

**Issue by Xiaminou** [TheCBProject/CodeChickenLib#23]
Crash on startup after updating CCL: http://pastebin.com/NGAEv9mF

**Comment by covers1624** [comment]
Remove ccl build 101 from /mods/1.10.2/

**Comment by Xiaminou** [comment]
Oh, derp, Curse should know to do that...
And I've always been wondering, how come some mods are in subfolders? is there any good reason for that?

**Comment by covers1624** [comment]
Nothing they can do unfortunately, All due to the way CCL is now distributed.
