### ISSUE TITLE
Crash when giving an item/block that doesn't exist

### ISSUE THREAD

**Issue by Insane96** [TheCBProject/CodeChickenLib#231]
Tried to give me an item from ex nihilo with id exnihilo:item_pebble. Meta for this item goes up to 3, but I've given myself the meta 4, the game crashed and I can no longer enter the world.

Full Crash Report: https://hastebin.com/iderecaxuj.sql

**Comment by necrogami** [comment]
I believe this is a Exnihilo Creatio problem see line 22 of your crash.
