### ISSUE TITLE
Help !

### ISSUE THREAD

**Issue by Drezkil** [TheCBProject/CodeChickenLib#234]
Do you have an hint of how to fix the coremod constant crashing ?
because this is making me depressive to not being able to use thermal foundation :'(

**Comment by MineRobber9000** [comment]
Hi @Drezkil!

If you would post a crashlog, that would really help- that usually has all the info we need to figure out why something broke!

The game should tell you where to find the crash log after it crashes.

**Comment by Drezkil** [comment]
Maybe later, 
It's been three months since this crash happened and because the game erase the past crashlogs it's impossible to find.
If I find a new issue I'll may tell you.
