### ISSUE TITLE
crashing after updating chicken mods to newer versions

### ISSUE THREAD

**Issue by SDUBZ** [TheCBProject/CodeChickenLib#24]
[crash-2016-12-17_12.14.33-client.txt](https://github.com/TheCBProject/CodeChickenLib/files/658576/crash-2016-12-17_12.14.33-client.txt)

forge:1.10.2-2185
chicken mod versions:
ChickenChunks {2.2.0.52}
 CodeChickenLib 2.5.0.178
CodeChickenCore{2.4.0.100}
EnderStorage{2.2.0.95}

**Comment by covers1624** [comment]
Wait for pending BrandonsCore update.
