### ISSUE TITLE
Codechickenlib Crashes

### ISSUE THREAD

**Issue by ghost** [TheCBProject/CodeChickenLib#244]
The game crashed whilst there was a severe problem during mod loading that has caused the game to fail
The game crashed whilst there was a severe problem during mod loading that has caused the game to fail
Error: net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from CodeChicken Lib (codechickenlib)

Please Help

MODS i'm trying to load:
https://user-images.githubusercontent.com/40472447/59998553-a240fd00-9657-11e9-864f-d6c0af583333.png

**Comment by ghost** [comment]
(https://user-images.githubusercontent.com/40472447/59998626-cbfa2400-9657-11e9-970e-e1daa2dd3faa.png)

**Comment by Rumaruka** [comment]
Crashlog please
