### ISSUE TITLE
codechickenlib

### ISSUE THREAD

**Issue by KoBaPhIl** [TheCBProject/CodeChickenLib#247]
The game crashed whilst there was a severe problem during mod loading that has caused the game to fail
Error: net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from CodeChicken Lib (codechickenlib)

**Comment by MineRobber9000** [comment]
Please post more info.

If the stack trace includes `ConfigFileException: Invalid type 'd'` or similar, you may be suffering from a known error. Delete your config (`.minecraft/config/codechicken.cfg` IIRC) and the issue should solve itself.
