### ISSUE TITLE
Incompatability with Immersive Engineering

### ISSUE THREAD

**Issue by Ribbons0121R121** [TheCBProject/CodeChickenLib#248]
tried to change tab to immersive engineering stuff and it crashed. looked at the crash report and it said teslator, aka the tesla item from Immersive Engineering. cant render it with codechickenlib installed for some reason :/
[crash-2019-07-13_10.38.17-client.txt](https://github.com/TheCBProject/CodeChickenLib/files/3388951/crash-2019-07-13_10.38.17-client.txt)

**Comment by MineRobber9000** [comment]
>A tessellation of a flat surface is the tiling of a plane using one or more geometric shapes, called tiles, with no overlaps and no gaps. In mathematics, tessellations can be generalized to higher dimensions and a variety of geometries. A periodic tiling has a repeating pattern.

Minecraft's class for doing this is the Tessellator class, which is where you got that from; not the tessellator from IE.

After looking at the stack trace myself, it seems to me like weaponlib (a coremod at the top of the crash report) is intercepting the render somehow and changing the item in a way that is not good and causing a crash further down the pipeline.

Can you try just installing IE and CCL (**only**) and see if that still crashes?
