### ISSUE TITLE
[CodeChickenLib-ConfigSync]: Skipping config sync, No mods have registered a syncable config.

### ISSUE THREAD

**Issue by xXPJMXx** [TheCBProject/CodeChickenLib#250]
Hey guys ive seen this problem in other threads but just could´nt find a solution.
My game neither my server crashes, but i just cant join the server...
Does any one have a (if posible) simple solution for that ?
My server is running a Ryzen 5 1600 at 60% load // Overload ??
I also dont get a crash report, but the console is showing me the following Text.

[Console Window.txt](https://github.com/TheCBProject/CodeChickenLib/files/3435836/Console.Window.txt)

**Comment by covers1624** [comment]
CCL prints that line very early in the connection pipeline, just because its the last thing printed doesnt mean its the problem. There is nothing wrong on CCL's side here.
