### ISSUE TITLE
Blocks disappearing

### ISSUE THREAD

**Issue by Larsz11** [TheCBProject/CodeChickenLib#251]
When i have logistics pipes and project red installed together the frames from project red
with covers or panels from Forge-multipart they disappear.

this is what the console displays when that happens.
[JM-task-4/ERROR] [CodeChickenLib]: Fatal exception thrown whilst baking block model for: projectred-expansion:machine2[tile_idx=5]

is this an problem with this mod? or am i doing someting wrong?

Log file:
https://paste.ee/p/GLTMG

**Comment by Agrax** [comment]
Experiencing something similar:

https://pastebin.com/NRRXKvwx

**Comment by FoxMcloud5655** [comment]
It looks to me that this isn't something CodeChickenLib would do; it's only providing the means to bake the model, not actually providing it.

projectred-expansion:machine2 is the model that's failing.

**Comment by covers1624** [comment]
Ignore those, Journey map does stuff.
