### ISSUE TITLE
crash caused by something?

### ISSUE THREAD

**Issue by cockatiel-navi** [TheCBProject/CodeChickenLib#252]
---- Minecraft Crash Report ----

WARNING: coremods are present:
  AALoadingPlugin (arcanearchives-0.2.0.1.jar)
  HCASM (HammerCore-1.12.2-2.0.4.7.jar)
  CorePlugin (ForgeEndertech-1.12.2-4.4.21.1-build.0377.jar)
  ForgelinPlugin (Forgelin-1.8.2.jar)
  CTMCorePlugin (CTM-MC1.12.2-0.3.3.22.jar)
  llibrary (llibrary-core-1.0.11-1.12.2.jar)
  Quark Plugin (Quark-r1.5-159.jar)
  CamPatchingLoader (CMDCam_v1.4.3_mc1.12.2.jar)
  MMFMLCorePlugin (MultiMine-1.12.2.jar)
  LibrarianLib Plugin (librarianlib-1.12.2-4.19.1-release.jar)
  wings (wings-1.1.3-1.12.2.jar)
  FMLModule (mdxlib-3.0.0.18.jar)
  FarseekCoreMod (Farseek-1.12-2.3.2.jar)
  CreativePatchingLoader (CreativeCore_v1.9.52_mc1.12.2.jar)
Contact their authors BEFORE contacting forge

// Don't be sad, have a hug! <3

Time: 8/6/19 12:00 PM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from CodeChicken Lib (codechickenlib)
Caused by: codechicken.lib.configuration.ConfigFile$ConfigException: codechicken.lib.configuration.ConfigParseException: Invalid value type d, @Line:20, dump_asm=true
	at codechicken.lib.configuration.ConfigFile.load(ConfigFile.java:61)
	at codechicken.lib.configuration.ConfigFile.<init>(ConfigFile.java:43)
	at codechicken.lib.configuration.ConfigFile.<init>(ConfigFile.java:29)
	at codechicken.lib.configuration.ConfigFile.<init>(ConfigFile.java:19)
	at codechicken.lib.CodeChickenLib.preInit(CodeChickenLib.java:50)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:637)
	at sun.reflect.GeneratedMethodAccessor9.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:136)
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:627)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:252)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:467)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: codechicken.lib.configuration.ConfigParseException: Invalid value type d, @Line:20, dump_asm=true
	at codechicken.lib.configuration.ConfigTag.parseTag(ConfigTag.java:92)
	at codechicken.lib.configuration.ConfigFile.load(ConfigFile.java:59)
	... 44 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 332638656 bytes (317 MB) / 872415232 bytes (832 MB) up to 2147483648 bytes (2048 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2838 128 mods loaded, 127 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID                                   | Version           | Source                                               | Signature                                |
	|:----- |:------------------------------------ |:----------------- |:---------------------------------------------------- |:---------------------------------------- |
	| LCH   | minecraft                            | 1.12.2            | minecraft.jar                                        | None                                     |
	| LCH   | mcp                                  | 9.42              | minecraft.jar                                        | None                                     |
	| LCH   | FML                                  | 8.0.99.99         | forge-1.12.2-14.23.5.2838.jar                        | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCH   | forge                                | 14.23.5.2838      | forge-1.12.2-14.23.5.2838.jar                        | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCH   | creativecoredummy                    | 1.0.0             | minecraft.jar                                        | None                                     |
	| LCH   | securitycraft                        | v1.8.12           | [1.12.2]+SecurityCraft+v1.8.12.jar                   | None                                     |
	| LCH   | quarryplus                           | 1.1.2             | AdditionalEnchantedMiner-1.12.2-1.1.2-universal.jar  | 617a4e95f0af9de5402bb9883abe0f53a6bfa230 |
	| LCH   | quarryplus_ct                        | 1.1.2             | AdditionalEnchantedMiner-1.12.2-1.1.2-universal.jar  | 617a4e95f0af9de5402bb9883abe0f53a6bfa230 |
	| LCH   | airhop                               | 1.0.1             | AirHop-v1.0.1-1.12.2.jar                             | 12d137bcc36051a1c2c8ea7211cfc1da1c6e9dea |
	| LCH   | animalnet                            | v1.12.2 b1        | animalnet-v1.12.2+b1.jar                             | None                                     |
	| LCH   | charset                              | 0.5.6.2           | Charset-Lib-0.5.6.2.jar                              | None                                     |
	| LCH   | jei                                  | 4.15.0.268        | jei_1.12.2-4.15.0.268.jar                            | None                                     |
	| LCH   | appleskin                            | 1.0.9             | AppleSkin-mc1.12-1.0.9.jar                           | None                                     |
	| LCH   | baubles                              | 1.5.2             | Baubles-1.12-1.5.2.jar                               | None                                     |
	| LCH   | gbook_snapshot                       | 2.9.1.s5          | Guidebook-1.12.2-2.9.1.s5.jar                        | None                                     |
	| LCH   | arcanearchives                       | 0.2.0.1           | arcanearchives-0.2.0.1.jar                           | None                                     |
	| LCH   | architecturecraft                    | @VERSION@         | architecturecraft-1.12-3.80.jar                      | None                                     |
	| LCH   | csb_armorstand                       | 1.0.4             | ArmorStandGUI-1.12-1.0.4.jar                         | None                                     |
	| LCH   | artemislib                           | 1.0.6             | ArtemisLib-1.12.2-v1.0.6.jar                         | None                                     |
	| LCH   | autocrafter                          | 4.3               | autocrafter-4.3.jar                                  | None                                     |
	| LCH   | quark                                | r1.5-159          | Quark-r1.5-159.jar                                   | None                                     |
	| LCH   | autoreglib                           | 1.3-30            | AutoRegLib-1.3-30.jar                                | None                                     |
	| LCH   | xijun                                | 1.0               | Bacteria1.12.2-1.2.jar                               | None                                     |
	| LCH   | buildcraftlib                        | 7.99.24.1         | buildcraft-all-7.99.24.1.jar                         | None                                     |
	| LCH   | buildcraftcore                       | 7.99.24.1         | buildcraft-all-7.99.24.1.jar                         | None                                     |
	| LCH   | buildcraftbuilders                   | 7.99.24.1         | buildcraft-all-7.99.24.1.jar                         | None                                     |
	| LCH   | buildcrafttransport                  | 7.99.24.1         | buildcraft-all-7.99.24.1.jar                         | None                                     |
	| LCH   | buildcraftsilicon                    | 7.99.24.1         | buildcraft-all-7.99.24.1.jar                         | None                                     |
	| LCH   | crafttweaker                         | 4.1.19            | CraftTweaker2-1.12-4.1.19.jar                        | None                                     |
	| LCH   | buildcraftcompat                     | 7.99.24.1         | buildcraft-all-7.99.24.1.jar                         | None                                     |
	| LCH   | buildcraftenergy                     | 7.99.24.1         | buildcraft-all-7.99.24.1.jar                         | None                                     |
	| LCH   | buildcraftfactory                    | 7.99.24.1         | buildcraft-all-7.99.24.1.jar                         | None                                     |
	| LCH   | buildcraftrobotics                   | 7.99.24.1         | buildcraft-all-7.99.24.1.jar                         | None                                     |
	| LCH   | cd4017be_lib                         | 6.4.5             | CD4017BE_lib-1.12.2-6.4.5.jar                        | None                                     |
	| LCH   | ceilingtorch                         | v1.0.1            | ceilingtorch-1.12.2-v1.0.1.jar                       | None                                     |
	| LCH   | chanceglobe                          | v1.2.1            | ceilingtorch-1.12.2-v1.0.1.jar                       | None                                     |
	| LCH   | ctm                                  | MC1.12.2-0.3.3.22 | CTM-MC1.12.2-0.3.3.22.jar                            | None                                     |
	| LCH   | chisel                               | MC1.12.2-0.2.1.35 | Chisel-MC1.12.2-0.2.1.35.jar                         | None                                     |
	| LCH   | cmdcam                               | 1.4.0             | CMDCam_v1.4.3_mc1.12.2.jar                           | None                                     |
	| LCE   | codechickenlib                       | 3.2.3.357         | CodeChickenLib-1.12.2-3.2.3.357-universal.jar        | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| LC    | redstoneflux                         | 2.1.0             | RedstoneFlux-1.12-2.1.0.6-universal.jar              | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| LC    | cofhcore                             | 4.6.3             | CoFHCore-1.12.2-4.6.3.27-universal.jar               | None                                     |
	| LC    | potioncore                           | 1.8_for_1.12.2    | PotionCore-1.8_for_1.12.2.jar                        | None                                     |
	| LC    | compot                               | 1.1               | CombinedPotions-1.12-1.1.jar                         | None                                     |
	| LC    | mantle                               | 1.12-1.3.3.39     | Mantle-1.12-1.3.3.39.jar                             | None                                     |
	| LC    | tconstruct                           | 1.12.2-2.12.0.115 | TConstruct-1.12.2-2.12.0.115.jar                     | None                                     |
	| LC    | conarm                               | 1.2.3             | conarm-1.12.2-1.2.3.jar                              | 5d5b8aee896a4f5ea3f3114784742662a67ad32f |
	| LC    | concreteconversion                   | 1.2.1             | Concrete+Conversion-1.12.2-1.2.1.jar                 | None                                     |
	| LC    | extendedrenderer                     | v1.0              | coroutil-1.12.1-1.2.32.jar                           | None                                     |
	| LC    | coroutil                             | 1.12.1-1.2.32     | coroutil-1.12.1-1.2.32.jar                           | None                                     |
	| LC    | configmod                            | v1.0              | coroutil-1.12.1-1.2.32.jar                           | None                                     |
	| LC    | cosmeticarmorreworked                | 1.12.2-v4         | CosmeticArmorReworked-1.12.2-v4.jar                  | aaaf83332a11df02406e9f266b1b65c1306f0f76 |
	| LC    | cosmeticarmorreworked|tombmanygraves | 1.12.2-v4         | CosmeticArmorReworked-1.12.2-v4.jar                  | aaaf83332a11df02406e9f266b1b65c1306f0f76 |
	| LC    | craftable_ores                       | 0.1.0             | craftable-ores-0.1.0.jar                             | None                                     |
	| LC    | ctgui                                | 1.0.0             | CraftTweaker2-1.12-4.1.19.jar                        | None                                     |
	| LC    | crafttweakerjei                      | 2.0.3             | CraftTweaker2-1.12-4.1.19.jar                        | None                                     |
	| LC    | creativecore                         | 1.9.9             | CreativeCore_v1.9.52_mc1.12.2.jar                    | None                                     |
	| LC    | croparia                             | 2.4               | Croparia-2.4.1.jar                                   | None                                     |
	| LC    | effortlessbuilding                   | 1.12.2-2.11       | effortlessbuilding-1.12.2-2.11.jar                   | None                                     |
	| LC    | enchxchg                             | 1.0.6             | enchxchg-1.12.2-1.0.6.jar                            | None                                     |
	| LC    | enderstorage                         | 2.4.6.137         | EnderStorage-1.12.2-2.4.6.137-universal.jar          | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| LC    | enemyz                               | 0.1.1             | Enemyz-1.12.2-0.0.1.jar                              | None                                     |
	| LC    | extraglass                           | 1.20              | extra-glass-1.20.jar                                 | None                                     |
	| LC    | farseek                              | 2.3.2             | Farseek-1.12-2.3.2.jar                               | None                                     |
	| LC    | faufil                               | 1.0.2             | Faucets+and+Filters-1.0.2.jar                        | None                                     |
	| LC    | forgeendertech                       | 1.12.2-4.4.21.1   | ForgeEndertech-1.12.2-4.4.21.1-build.0377.jar        | None                                     |
	| LC    | forgelin                             | 1.8.2             | Forgelin-1.8.2.jar                                   | None                                     |
	| LC    | ftblib                               | 5.4.3.118         | FTBLib-5.4.3.118.jar                                 | None                                     |
	| LC    | ichunutil                            | 7.2.1             | iChunUtil-1.12.2-7.2.1.jar                           | 4db5c2bd1b556f252a5b8b54b256d381b2a0a6b8 |
	| LC    | generallaymansaestheticspyingscreen  | 7.0.0             | GeneralLaymansAestheticSpyingScreen-1.12.2-7.0.0.jar | None                                     |
	| LC    | guideapi                             | 1.12-2.1.8-63     | Guide-API-1.12-2.1.8-63.jar                          | None                                     |
	| LC    | hammercore                           | 2.0.4.7           | HammerCore-1.12.2-2.0.4.7.jar                        | 4d7b29cd19124e986da685107d16ce4b49bc0a97 |
	| LC    | waila                                | 1.8.26            | Hwyla-1.8.26-B41_1.12.2.jar                          | None                                     |
	| LC    | llibrary                             | 1.7.18            | llibrary-1.7.18-1.12.2.jar                           | b9f30a813bee3b9dd5652c460310cfcd54f6b7ec |
	| LC    | iceandfire                           | 1.7.1             | iceandfire-1.7.1-1.12.2.jar                          | None                                     |
	| LC    | inspirations                         | 1.12.2-0.2.4      | Inspirations-1.12.2-0.2.4.jar                        | None                                     |
	| LC    | invisiblights                        | 3.0-8             | invisiblights-3.1-9.jar                              | None                                     |
	| LC    | ironchest                            | 1.12.2-7.0.64.843 | ironchest-1.12.2-7.0.64.843.jar                      | None                                     |
	| LC    | fluidtank                            | 4.3               | LargeFluidTank-4.3.jar                               | None                                     |
	| LC    | fluidtank_ae2                        | 4.3               | LargeFluidTank-4.3.jar                               | None                                     |
	| LC    | fluidtank_theoneprobe                | 4.3               | LargeFluidTank-4.3.jar                               | None                                     |
	| LC    | shadowmc                             | 3.8.0             | ShadowMC-1.12-3.8.0.jar                              | None                                     |
	| LC    | largeveins                           | @VERSION@         | LargeVeins-1.12-1.1.0.jar                            | None                                     |
	| LC    | librarianlib                         | 4.19.1            | librarianlib-1.12.2-4.19.1-release.jar               | None                                     |
	| LC    | liquidblocks                         | 1.4               | liquid_blocks-1.4.jar                                | None                                     |
	| LC    | longerdays                           | 1.0.4             | longerdays-1.0.4.jar                                 | None                                     |
	| LC    | mcjtylib_ng                          | 3.5.4             | mcjtylib-1.12-3.5.4.jar                              | None                                     |
	| LC    | mcmultipart                          | 2.5.3             | MCMultiPart-2.5.3.jar                                | None                                     |
	| LC    | mdxlib                               | 3.0.0.18          | mdxlib-3.0.0.18.jar                                  | None                                     |
	| LC    | mightyarchitect                      | 0.3.0             | mightyarchitect-0.3.0.jar                            | None                                     |
	| LC    | multimine                            | 1.6.0             | MultiMine-1.12.2.jar                                 | None                                     |
	| LC    | multimob                             | 1.0.5             | multimob-1.0.5.jar                                   | None                                     |
	| LC    | torotraits                           | 1.12-1            | torotraits-1.12-1.jar                                | None                                     |
	| LC    | nemesissystem                        | 1.12.1-2          | nemesissystem-1.12.1-2.jar                           | None                                     |
	| LC    | yurtmod                              | 9.5.0             | NomadicTents-1.12.2-9.5.0.jar                        | None                                     |
	| LC    | oreberries                           | 0.5.0             | oreberries-1.12.x-0.5.0.jar                          | None                                     |
	| LC    | parachutemod                         | 1.7.4             | parachutemod-1.12.2-1.7.4-446.jar                    | None                                     |
	| LC    | patchouli                            | 1.0-19            | Patchouli-1.0-19.jar                                 | None                                     |
	| LC    | portality                            | 1.0-SNAPSHOT      | portality-1.12.2-1.2.3-15.jar                        | None                                     |
	| LC    | randomenchantments                   | @VERSION@         | randomenchantments-0.0.13.jar                        | None                                     |
	| LC    | randomloot                           | 1.4.4             | randomloot+1.6.1.jar                                 | None                                     |
	| LC    | restrictions                         | 1.3.0             | restrictions-1.12-1.3.0.jar                          | None                                     |
	| LC    | roguelike                            | 1.8.0             | RoguelikeDungeons-1.12.2-1.8.0.jar                   | None                                     |
	| LC    | simplefluidtanks                     | 1.12.2-1.7.1.2    | simplefluidtanks-1.12.2-1.7.1.2.jar                  | None                                     |
	| LC    | valkyrielib                          | 1.12.2-2.0.20.1   | valkyrielib-1.12.2-2.0.20.1.jar                      | None                                     |
	| LC    | simplegenerators                     | 1.12.2-2.0.20.2   | simplegenerators-1.12.2-2.0.20.2.jar                 | None                                     |
	| LC    | simplequarry                         | 26r               | SimpleQuarry-1.12.2-26r.jar                          | 4d7b29cd19124e986da685107d16ce4b49bc0a97 |
	| LC    | storagenetwork                       | 1.7.8             | SimpleStorageNetwork-1.12.2-1.7.8.jar                | 1bc8f8dbe770187a854cef35dad0ff40ba441bbe |
	| LC    | yukarilib                            | 1.3.0             | YukariLib-1.12-1.3.0.jar                             | None                                     |
	| LC    | solidxp                              | 1.4.0-beta        | SolidXp-1.4.0-b2.jar                                 | None                                     |
	| LC    | speedyhoppers                        | 1.1.13            | speedyhoppers-1.1.13.jar                             | None                                     |
	| LC    | streams                              | 0.4.7             | Streams-1.12-0.4.7.jar                               | None                                     |
	| LC    | sync                                 | 7.1.0             | Sync-1.12.2-7.1.0.jar                                | 4db5c2bd1b556f252a5b8b54b256d381b2a0a6b8 |
	| LC    | teslacorelib                         | 1.0.15            | tesla-core-lib-1.12.2-1.0.15.jar                     | d476d1b22b218a10d845928d1665d45fce301b27 |
	| LC    | timecore                             | 1.0.0             | TimeCore-1.12.2-1.0.0.jar                            | None                                     |
	| LC    | tmechworks                           | 2.0               | TMechworks-1.12.2-1.0.0.jar                          | None                                     |
	| LC    | universalmodifiers                   | 1.12.2-1.0.16.1   | valkyrielib-1.12.2-2.0.20.1.jar                      | None                                     |
	| LC    | veinminer                            | 0.38.2            | VeinMiner-1.12-0.38.2.647+b31535a.jar                | None                                     |
	| LC    | veinminermodsupport                  | 0.38.2            | VeinMiner-1.12-0.38.2.647+b31535a.jar                | None                                     |
	| LC    | walljump                             | 1.12.2-1.2.1      | walljump-1.12.2-1.2.1.jar                            | None                                     |
	| LC    | wings                                | 1.1.3             | wings-1.1.3-1.12.2.jar                               | None                                     |
	| LC    | bauble_wings                         | 1.0.0             | wings-1.1.3-1.12.2.jar                               | None                                     |
	| LC    | xaerominimap                         | 1.16              | Xaeros_Minimap_1.16_Forge_1.12.jar                   | None                                     |
	| LC    | kiwi                                 | 0.5.3.32          | Kiwi-1.12.2-0.5.3.32.jar                             | None                                     |
	| LC    | librarianliblate                     | 4.19.1            | librarianlib-1.12.2-4.19.1-release.jar               | None                                     |
	| LC    | mysticallib                          | 1.12.2-1.3.1      | mysticallib-1.12.2-1.3.1.jar                         | None                                     |
	| LC    | teslacorelib_registries              | 1.0.15            | tesla-core-lib-1.12.2-1.0.15.jar                     | None                                     |
	| UD    | mobends_wings                        | 1.0.0             | wings-1.1.3-1.12.2.jar                               | None                                     |

	Loaded coremods (and transformers): 
AALoadingPlugin (arcanearchives-0.2.0.1.jar)
  
HCASM (HammerCore-1.12.2-2.0.4.7.jar)
  com.zeitheron.hammercore.asm.HammerCoreTransformer
CorePlugin (ForgeEndertech-1.12.2-4.4.21.1-build.0377.jar)
  
ForgelinPlugin (Forgelin-1.8.2.jar)
  
CTMCorePlugin (CTM-MC1.12.2-0.3.3.22.jar)
  team.chisel.ctm.client.asm.CTMTransformer
llibrary (llibrary-core-1.0.11-1.12.2.jar)
  net.ilexiconn.llibrary.server.core.plugin.LLibraryTransformer
  net.ilexiconn.llibrary.server.core.patcher.LLibraryRuntimePatcher
Quark Plugin (Quark-r1.5-159.jar)
  vazkii.quark.base.asm.ClassTransformer
CamPatchingLoader (CMDCam_v1.4.3_mc1.12.2.jar)
  com.creativemd.cmdcam.transform.CamTransformer
MMFMLCorePlugin (MultiMine-1.12.2.jar)
  atomicstryker.multimine.common.fmlmagic.MMTransformer
LibrarianLib Plugin (librarianlib-1.12.2-4.19.1-release.jar)
  com.teamwizardry.librarianlib.asm.LibLibTransformer
wings (wings-1.1.3-1.12.2.jar)
  me.paulf.wings.server.asm.WingsRuntimePatcher
  me.paulf.wings.server.asm.mobends.WingsMoBendsRuntimePatcher
FMLModule (mdxlib-3.0.0.18.jar)
  com.asx.mdx.AccessTransformer
FarseekCoreMod (Farseek-1.12-2.3.2.jar)
  farseek.core.FarseekClassTransformer
CreativePatchingLoader (CreativeCore_v1.9.52_mc1.12.2.jar)
  
	Pulsar/tconstruct loaded Pulses: 
		- TinkerCommons (Enabled/Forced)
		- TinkerWorld (Enabled/Not Forced)
		- TinkerTools (Enabled/Not Forced)
		- TinkerHarvestTools (Enabled/Forced)
		- TinkerMeleeWeapons (Enabled/Forced)
		- TinkerRangedWeapons (Enabled/Forced)
		- TinkerModifiers (Enabled/Forced)
		- TinkerSmeltery (Enabled/Not Forced)
		- TinkerGadgets (Enabled/Not Forced)
		- TinkerOredict (Enabled/Forced)
		- TinkerIntegration (Enabled/Forced)
		- TinkerFluids (Enabled/Forced)
		- TinkerMaterials (Enabled/Forced)
		- TinkerModelRegister (Enabled/Forced)
		- chiselIntegration (Enabled/Not Forced)
		- wailaIntegration (Enabled/Not Forced)

	Hammer Core Information: FluidDictionary Info: Registered 2 fluids.
OreDictionary Info: Registered 166 names; 194 stacks.
Pastebin Connection: Okay.
Dependent Mods:
    -Simple Quarry (simplequarry) @26r

	Pulsar/inspirations loaded Pulses: 
		- InspirationsShared (Enabled/Forced)
		- InspirationsBuilding (Enabled/Not Forced)
		- InspirationsUtility (Enabled/Not Forced)
		- InspirationsTools (Enabled/Not Forced)
		- InspirationsRecipes (Enabled/Not Forced)
		- InspirationsTweaks (Enabled/Not Forced)
		- InspirationsShared (Enabled/Forced)
		- WailaPlugin (Enabled/Not Forced)

	Pulsar/tmechworks loaded Pulses: 
		- wailaIntegration (Enabled/Not Forced)

**Comment by covers1624** [comment]
Delete the old CCL config.
