### ISSUE TITLE
Crash problem

### ISSUE THREAD

**Issue by Ajsixflags** [TheCBProject/CodeChickenLib#254]
Only had these mods in the folder
CodeChickenLib-1.12.2-3.2.2.353
CoFHCore-1.12.2-4.6.3.27
CoFHWorld-1.12.2-1.3.1.7
RedstoneFlux-1.12-2.1.0.6
ThermalDynamics-1.12.2-2.5.5.21
ThermalExpansion-1.12.2-5.5.4.43
ThermalFoundation-1.12.2-2.6.3.27

The game crashed whilst there was a severe problem during mod loading that has caused the game to fail
Error: net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from CodeChicken Lib (codechickenlib)
[crash-2019-08-06_17.58.07-client.txt](https://github.com/TheCBProject/CodeChickenLib/files/3474482/crash-2019-08-06_17.58.07-client.txt)

**Comment by covers1624** [comment]
Delete the old CCL config file.
