### ISSUE TITLE
crash problem

### ISSUE THREAD

**Issue by seoksdream** [TheCBProject/CodeChickenLib#256]
i tried running minecraft with the codechicken installed and it told me this ?? 

The game crashed whilst there was a severe problem during mod loading that has caused the game to fail
Error: net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Not Enough Items (nei)

i know there's the same problem for everyone else and i tried deleting the CCL file thing but it would just make its own again to replace the one i deleted.

**Comment by covers1624** [comment]
You need to provide your logs, I can literally do nothing with just 'it broke', furthermore you have posted on the wrong tracker, Please post this on NEI's Issue tracker.
