### ISSUE TITLE
Crash on preview with render 1.10.2

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [TheCBProject/CodeChickenLib#26]
Crash log Client
https://gist.github.com/P3rf3ctXZer0/8388ac073384c73b24383eb12715ef13

Full Log Client
https://gist.github.com/P3rf3ctXZer0/348661140d32f88659cdaf8306dbdfc4

So yeah my modpack is kind of huge. I hope that you can help fix it. Since it crashed when I rendered the preview of the prefab mod.

**Comment by covers1624** [comment]
Did you ever find the fix for this, seems to be another mod at fault here.

**Comment by P3rf3ctXZer0** [comment]
No. I am going to run a bunch of tests today.

**Comment by covers1624** [comment]
How did those tests go?

**Comment by P3rf3ctXZer0** [comment]
Crap what was the bug again? it hasn't occurred since I updated Code Chicken Lib I will reopen if it becomes an issue again.
