### ISSUE TITLE
Crash on opening any modpack with CodeChickenLib

### ISSUE THREAD

**Issue by Joelifer123** [TheCBProject/CodeChickenLib#261]
The game crashes whenever I open any modpack and everything implies that it is CodeChickenLib causing the crash.
Attached is one of the many crash reports
[crash-2019-09-03_20.06.10-client.txt](https://github.com/TheCBProject/CodeChickenLib/files/3571055/crash-2019-09-03_20.06.10-client.txt)

**Comment by covers1624** [comment]
Don't run Minecraft from a one drive folder.

**Comment by Joelifer123** [comment]
Ahh, that would be why.
I have changed it from a onedrive folder and now it works.
Thanks for the tip
