### ISSUE TITLE
Crash connected with Gamestage Books

### ISSUE THREAD

**Issue by happybandit360** [TheCBProject/CodeChickenLib#266]
I'd had no issues with Gamestage Books until I updated CodeChicken Lib, then I began to experience random crashes, which I see has been an issue in the past. I had been on CodeChicken Lib 1.12.2-3.2.3.357-universal, but backed down to CodeChicken Lib 1.12.2-3.2.2.353-universal and everything seemed to work. However, I just experienced another crash and wanted to pass along the crash report in case it would be useful to you.

Crash Report - https://paste.ee/p/AkmtN

I shared this same report with the Gamestage Books dev.

**Comment by happybandit360** [comment]
Updated to CodeChickenLib-1.12.2-3.2.3.358-universal.jar and continue to have the same issue.
Most recent crash log - https://paste.ee/p/q8yCA - It appears to be mostly identical to the original.
Crash log from test server - https://paste.dimdev.org/feheyamufe.mccrash

**Comment by covers1624** [comment]
They are attempting to render a null ItemStack. This is not a ccl issue, ItemStacks have been nonnull since 1.11
