### ISSUE TITLE
chickenbones.net is down, together with maven

### ISSUE THREAD

**Issue by vaartis** [TheCBProject/CodeChickenLib#274]
The site seems to be down, together with maven. The result is that mods that depend on CodeChickenLib cannot be built, or at least cannot fetch the library. For me personally, gradle seems to hang when trying to check maven for some reason, even though all the files are in place.

**Comment by covers1624** [comment]
I am aware that the server is down, I have contacted ChickenBones about the issue and he is waiting for a reply from the host.

**Comment by jkrumpholc** [comment]
Any progress?

**Comment by covers1624** [comment]
A lotta funky, funky stuff has gone down. Currently scraping a mirror K4Unl has of 'chickenbones.net/maven', I am in the process of rebuilding things and at least getting maven back online.

**Comment by vaartis** [comment]
Seems like maven is now back up! Thank you. I'll close the issue now.

**Comment by covers1624** [comment]
Correct! Maven is back online again!
It has been merged with my maven, 'https://maven.covers1624.net/'
Likely ill just make 'chickenbones.net/maven' 301 to that later.
