### ISSUE TITLE
ServerUtils.isPlayerOP hangs main thread with calls to mojang api

### ISSUE THREAD

**Issue by clienthax** [TheCBProject/CodeChickenLib#277]
Can this be changed to use the forge permission system, this has caused hangs of over 15m on my server during loading.
https://mcforge.readthedocs.io/en/latest/utilities/permissionapi/

![image](https://user-images.githubusercontent.com/1056270/71623210-ca935080-2bd2-11ea-8f6c-06381046555e.png)

**Comment by covers1624** [comment]
This has been addressed in 1.15+
