### ISSUE TITLE
CodeChickenLib Crashing

### ISSUE THREAD

**Issue by Ultra8prime** [TheCBProject/CodeChickenLib#278]
---- Minecraft Crash Report ----

WARNING: coremods are present:
  MicdoodlePlugin (MicdoodleCore-1.12.2.jar)
  IELoadingPlugin (ImmersiveEngineering-core-0.12-89.jar)
  Inventory Tweaks Coremod (InventoryTweaks-1.63.jar)
  CTMCorePlugin (CTM-MC1.12.2-1.0.1.30.jar)
  OpenModsCorePlugin (OpenModsLib-1.12.2-0.12.2.jar)
  Techguns Core (techguns-1.12.2-2.0.2.0_pre3.1.jar)
Contact their authors BEFORE contacting forge

// Surprise! Haha. Well, this is awkward.

Time: 1/7/20 10:55 PM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from CodeChicken Lib (codechickenlib)
Caused by: codechicken.lib.configuration.ConfigFile$ConfigException: codechicken.lib.configuration.ConfigParseException: Invalid value type d, @Line:20, dump_asm=true
	at codechicken.lib.configuration.ConfigFile.load(ConfigFile.java:61)
	at codechicken.lib.configuration.ConfigFile.<init>(ConfigFile.java:43)
	at codechicken.lib.configuration.ConfigFile.<init>(ConfigFile.java:29)
	at codechicken.lib.configuration.ConfigFile.<init>(ConfigFile.java:19)
	at codechicken.lib.CodeChickenLib.preInit(CodeChickenLib.java:50)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:637)
	at sun.reflect.GeneratedMethodAccessor8.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:136)
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:627)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:252)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:467)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: codechicken.lib.configuration.ConfigParseException: Invalid value type d, @Line:20, dump_asm=true
	at codechicken.lib.configuration.ConfigTag.parseTag(ConfigTag.java:92)
	at codechicken.lib.configuration.ConfigFile.load(ConfigFile.java:59)
	... 44 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 309281840 bytes (294 MB) / 1073741824 bytes (1024 MB) up to 8589934592 bytes (8192 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx8G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2836 Optifine OptiFine_1.12.2_HD_U_F5 70 mods loaded, 70 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID                   | Version                  | Source                                             | Signature                                |
	|:----- |:-------------------- |:------------------------ |:-------------------------------------------------- |:---------------------------------------- |
	| LCH   | minecraft            | 1.12.2                   | minecraft.jar                                      | None                                     |
	| LCH   | mcp                  | 9.42                     | minecraft.jar                                      | None                                     |
	| LCH   | FML                  | 8.0.99.99                | forge-1.12.2-14.23.5.2836.jar                      | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCH   | forge                | 14.23.5.2836             | forge-1.12.2-14.23.5.2836.jar                      | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCH   | micdoodlecore        |                          | minecraft.jar                                      | None                                     |
	| LCH   | openmodscore         | 0.12.2                   | minecraft.jar                                      | None                                     |
	| LCH   | techguns_core        | 1.12.2-1.0               | minecraft.jar                                      | None                                     |
	| LCH   | damageindicatorsmod  | 1.0                      | [1.12.2]DamageIndicatorsMod-3.5.1.jar              | None                                     |
	| LCH   | jei                  | 4.15.0.291               | jei_1.12.2-4.15.0.291.jar                          | None                                     |
	| LCH   | abyssalcraft         | 1.9.15                   | AbyssalCraft-1.12.2-1.9.15.jar                     | 220f10d3a93b3ff5fbaa7434cc629d863d6751b9 |
	| LCH   | ccm                  | 1.0                      | ccm-1.0.jar                                        | None                                     |
	| LCH   | ctm                  | MC1.12.2-1.0.1.30        | CTM-MC1.12.2-1.0.1.30.jar                          | None                                     |
	| LCH   | chisel               | MC1.12.2-1.0.1.44        | Chisel-MC1.12.2-1.0.1.44.jar                       | None                                     |
	| LCH   | mantle               | 1.12-1.3.3.55            | Mantle-1.12-1.3.3.55.jar                           | None                                     |
	| LCH   | baubles              | 1.5.2                    | Baubles-1.12-1.5.2 (1).jar                         | None                                     |
	| LCH   | thaumcraft           | 6.1.BETA26               | Thaumcraft-1.12.2-6.1.BETA26.jar                   | None                                     |
	| LCH   | twilightforest       | 3.10.1013                | twilightforest-1.12.2-3.10.1013-universal.jar      | None                                     |
	| LCH   | tconstruct           | 1.12.2-2.13.0.171        | TConstruct-1.12.2-2.13.0.171.jar                   | None                                     |
	| LCH   | acintegration        | 1.9.0                    | AbyssalCraft+Integration-1.12.2-1.9.0.jar          | 220f10d3a93b3ff5fbaa7434cc629d863d6751b9 |
	| LCH   | appleskin            | 1.0.9                    | AppleSkin-mc1.12-1.0.9.jar                         | None                                     |
	| LCH   | appliedenergistics2  | rv6-stable-7             | appliedenergistics2-rv6-stable-7.jar               | dfa4d3ac143316c6f32aa1a1beda1e34d42132e5 |
	| LCH   | bonsaitrees          | 1.1.3                    | bonsaitrees-1.1.3-b156.jar                         | None                                     |
	| LCH   | botania              | r1.10-361                | Botania+r1.10-361.jar                              | None                                     |
	| LCE   | codechickenlib       | 3.2.2.353                | CodeChickenLib-1.12.2.jar                          | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| LC    | redstoneflux         | 2.1.0                    | RedstoneFlux-1.12-2.1.0.6-universal (1).jar        | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| LC    | brandonscore         | 2.4.17                   | BrandonsCore-1.12.2-2.4.17.208-universal.jar       | None                                     |
	| LC    | chameleon            | 1.12-4.1.3               | Chameleon-1.12-4.1.3.jar                           | None                                     |
	| LC    | placebo              | 1.6.0                    | Placebo-1.12.2-1.6.0.jar                           | None                                     |
	| LC    | clickmachine         | 1.2.0                    | ClickMachine-1.12.2-1.2.0.jar                      | None                                     |
	| LC    | cofhcore             | 4.6.3                    | CoFHCore-1.12.2-4.6.3.27-universal.jar             | None                                     |
	| LC    | cofhworld            | 1.3.1                    | CoFHWorld-1.12.2-1.3.1.7-universal.jar             | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| LC    | cyberware            | 0.2.11.22                | cyberware-1.12.2-0.2.11.22.jar                     | None                                     |
	| LC    | cyclopscore          | 1.6.0                    | CyclopsCore-1.12.2-1.6.0.jar                       | bd0353b3e8a2810d60dd584e256e364bc3bedd44 |
	| LC    | thermalfoundation    | 2.6.3                    | ThermalFoundation-1.12.2-2.6.3.27-universal.jar    | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| LC    | draconicevolution    | 2.3.24                   | Draconic-Evolution-1.12.2-2.3.24.349-universal.jar | None                                     |
	| LC    | enderstorage         | 2.4.5.135                | EnderStorage-1.12.2-2.4.5.135-universal.jar        | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| LC    | energyconverters     | 1.3.0.15                 | energyconverters_1.12.2-1.3.0.15.jar               | None                                     |
	| LC    | evilcraft            | 0.10.78                  | EvilCraft-1.12.2-0.10.78.jar                       | bd0353b3e8a2810d60dd584e256e364bc3bedd44 |
	| LC    | evilcraftcompat      | 1.0.0                    | EvilCraft-1.12.2-0.10.78.jar                       | None                                     |
	| LC    | extrautils2          | 1.0                      | extrautils2-1.12-1.9.9.jar                         | None                                     |
	| LC    | cfm                  | 6.3.1                    | furniture-6.3.1-1.12.2.jar                         | None                                     |
	| LC    | ic2                  | 2.8.170-ex112            | industrialcraft-2-2.8.170-ex112.jar                | de041f9f6187debbc77034a344134053277aa3b0 |
	| LC    | galacticraftcore     | 4.0.2.220                | Galacticraft-Mod-1.12.2.jar                        | None                                     |
	| LC    | ichunutil            | 7.2.2                    | iChunUtil-1.12.2-7.2.2.jar                         | 4db5c2bd1b556f252a5b8b54b256d381b2a0a6b8 |
	| LC    | hats                 | 7.1.0                    | Hats-1.12.2-7.1.0.jar                              | 4db5c2bd1b556f252a5b8b54b256d381b2a0a6b8 |
	| LC    | theoneprobe          | 1.4.28                   | theoneprobe-1.12-1.4.28.jar                        | None                                     |
	| LC    | immersiveengineering | 0.12-89                  | ImmersiveEngineering-0.12-89.jar                   | 4cb49fcde3b43048c9889e0a3d083225da926334 |
	| LC    | immersivecables      | 1.3.2                    | ImmersiveCables-1.12.2-1.3.2.jar                   | None                                     |
	| LC    | inventoryspam        | 1.0.5                    | Inventory-Spam-Mod-1.12.2.jar                      | None                                     |
	| LC    | inventorytweaks      | 1.63+release.109.220f184 | InventoryTweaks-1.63.jar                           | 55d2cd4f5f0961410bf7b91ef6c6bf00a766dcbe |
	| LC    | ironbackpacks        | 1.12.2-3.0.8-12          | IronBackpacks-1.12.2-3.0.8-12.jar                  | None                                     |
	| LC    | journeymap           | 1.12.2-5.5.6             | journeymap-1.12.2-5.5.6.jar                        | None                                     |
	| LC    | mcjtylib_ng          | 3.5.4                    | mcjtylib-1.12-3.5.4.jar                            | None                                     |
	| LC    | moreoverlays         | 1.15.1                   | More-Overlays-Mod-1.12.2.jar                       | None                                     |
	| LC    | nuclearcraft         | 2.18o                    | NuclearCraft-2.18o-1.12.2.jar                      | None                                     |
	| LC    | openmods             | 0.12.2                   | OpenModsLib-1.12.2-0.12.2.jar                      | d2a9a8e8440196e26a268d1f3ddc01b2e9c572a5 |
	| LC    | openblocks           | 1.8.1                    | OpenBlocks-1.12.2-1.8.1.jar                        | d2a9a8e8440196e26a268d1f3ddc01b2e9c572a5 |
	| LC    | oreexcavation        | 1.4.137                  | OreExcavation-1.4.137.jar                          | None                                     |
	| LC    | projecte             | 1.12.2-PE1.4.1           | ProjectE-1.12.2-PE1.4.1.jar                        | None                                     |
	| LC    | realdrops            | 1.2.14                   | RealisticItemDrops-1.2.14.jar                      | None                                     |
	| LC    | rftools              | 7.72                     | rftools-1.12-7.72.jar                              | None                                     |
	| LC    | storagedrawers       | 1.12.2-5.4.0             | StorageDrawers-1.12.2-5.4.0.jar                    | None                                     |
	| LC    | techguns             | 2.0.2.0                  | techguns-1.12.2-2.0.2.0_pre3.1.jar                 | None                                     |
	| LC    | thaumicjei           | 1.6.0                    | ThaumicJEI-1.12.2-1.6.0-27.jar                     | None                                     |
	| LC    | thaumicenergistics   | 2.2.3                    | thaumicenergistics-2.2.3.jar                       | None                                     |
	| LC    | thaumicequivalence   | 1.12.2-1.0.5             | ThaumicEquivalence-1.12.2-1.0.5.jar                | None                                     |
	| LC    | tcinventoryscan      | 2.0.10                   | ThaumicInventoryScanning_1.12.2-2.0.10.jar         | None                                     |
	| LC    | tinkersjei           | 1.2                      | tinkersjei-1.2.jar                                 | None                                     |
	| LC    | xlfoodmod            | 1.12.2-1.9.1             | XL-Food-Mod-1.12.2-1.9.1.jar                       | None                                     |
	| LC    | industrialwires      | 1.7-36                   | IndustrialWires-1.7-36.jar                         | 7e11c175d1e24007afec7498a1616bef0000027d |

	Loaded coremods (and transformers): 
MicdoodlePlugin (MicdoodleCore-1.12.2.jar)
  micdoodle8.mods.miccore.MicdoodleTransformer
IELoadingPlugin (ImmersiveEngineering-core-0.12-89.jar)
  blusunrize.immersiveengineering.common.asm.IEClassTransformer
Inventory Tweaks Coremod (InventoryTweaks-1.63.jar)
  invtweaks.forge.asm.ContainerTransformer
CTMCorePlugin (CTM-MC1.12.2-1.0.1.30.jar)
  team.chisel.ctm.client.asm.CTMTransformer
OpenModsCorePlugin (OpenModsLib-1.12.2-0.12.2.jar)
  openmods.core.OpenModsClassTransformer
Techguns Core (techguns-1.12.2-2.0.2.0_pre3.1.jar)
  techguns.core.TechgunsASMTransformer
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 432.00' Renderer: 'GeForce GTX 1080/PCIe/SSE2'
	OpenModsLib class transformers: [llama_null_fix:FINISHED],[horse_base_null_fix:FINISHED],[pre_world_render_hook:FINISHED],[player_render_hook:FINISHED],[horse_null_fix:FINISHED]
	Pulsar/tconstruct loaded Pulses: 
		- TinkerCommons (Enabled/Forced)
		- TinkerWorld (Enabled/Not Forced)
		- TinkerTools (Enabled/Not Forced)
		- TinkerHarvestTools (Enabled/Forced)
		- TinkerMeleeWeapons (Enabled/Forced)
		- TinkerRangedWeapons (Enabled/Forced)
		- TinkerModifiers (Enabled/Forced)
		- TinkerSmeltery (Enabled/Not Forced)
		- TinkerGadgets (Enabled/Not Forced)
		- TinkerOredict (Enabled/Forced)
		- TinkerIntegration (Enabled/Forced)
		- TinkerFluids (Enabled/Forced)
		- TinkerMaterials (Enabled/Forced)
		- TinkerModelRegister (Enabled/Forced)
		- chiselIntegration (Enabled/Not Forced)
		- theoneprobeIntegration (Enabled/Not Forced)

	AE2 Version: stable rv6-stable-7 for Forge 14.23.5.2768
	OptiFine Version: OptiFine_1.12.2_HD_U_F5
	OptiFine Build: 20191204-141934
	Render Distance Chunks: 16
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.6.0 NVIDIA 432.00
	OpenGlRenderer: GeForce GTX 1080/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 8
Not sure what the problem is

**Comment by covers1624** [comment]
https://github.com/TheCBProject/CodeChickenLib/issues/270
