### ISSUE TITLE
CodeChickenLib seems to crash Minecraft?

### ISSUE THREAD

**Issue by MianReplicate** [TheCBProject/CodeChickenLib#286]
Since Ancient Warfare 2 needs this mod I installed it. But then the problem comes, one of my performance mods Vanilla Fix. Apparently it has confirmed that this mod causes my game to crash but idk why. I tried manually installing it too, but it didn't work so I would like some help. Here is the pastebin for the crash https://paste.dimdev.org/obofaholoh.mccrash

**Comment by covers1624** [comment]
https://github.com/TheCBProject/CodeChickenLib/issues/270
