### ISSUE TITLE
Cannot Build mod

### ISSUE THREAD

**Issue by Erfgs45** [TheCBProject/CodeChickenLib#287]
mc says this:
"Caused by: codechicken.lib.configuration.ConfigParseException: Invalid value type d, @Line:20, dump_asm=true
	at codechicken.lib.configuration.ConfigTag.parseTag(ConfigTag.java:92)
	at codechicken.lib.configuration.ConfigFile.load(ConfigFile.java:59)" how should I fix this?

**Comment by Erfgs45** [comment]
| LCE   | codechickenlib                      | 3.2.3.358           | CodeChickenLib-1.12.2-3.2.3.358-universal.jar        | f1850c39b2516232a2108a7bd84d1cb5df93b261 |

**Comment by covers1624** [comment]
https://github.com/TheCBProject/CodeChickenLib/issues/270
