### ISSUE TITLE
Game crash: CCL Has caught an exception whilst rendering an item.

### ISSUE THREAD

**Issue by RisingInIris2017** [TheCBProject/CodeChickenLib#288]
#### Mod version:
CCL Mod Version: CodeChickenLib-1.12.2-3.2.3.358
Suspected mod Forestry Version: forestry_1.12.2-5.8.2.387
Both the latest versions on CurseForge.

#### Forge version:

forge-1.12.2-14.23.5.2847

#### Singleplayer or Multiplayer:

Both singleplayer and multiplayer.

#### Installed mods:
In crash-report will you see a list for all installed mod.

## Link to full crash log
https://paste.ubuntu.com/p/FqJr4Tg5tG/

#### How to reproduce:

1. Use a tool with Silk Touch to harvest a Forestry Mod's leaf block.
2. Pick it up, and then open the Inventory.
3. Game crashes.
4. Every time the Inventory is opened, game crashes.

I do not know what happened, so I decided to turn to you dear devs.
I will post the same issue to [Forestry's GitHub](https://github.com/ForestryMC/ForestryMC/issues/2522).

Looks forward to your reply!
Thanks in advance!

**Comment by covers1624** [comment]
This is a non ccl issue, ccl just caught forestrys model throwing an exception and decided to enhance the log output. Purely as a work around, based on what i see in that crash, there is an experimental config option in ccl you can enable to try and recover the game state after an item crashes rendering.
