### ISSUE TITLE
Error when starting 1.12.2 server with only this mod

### ISSUE THREAD

**Issue by ghost** [TheCBProject/CodeChickenLib#290]
---- Minecraft Crash Report ----

WARNING: coremods are present:
  BCModPlugin (backpacks+1.12.2+-+3.5.8.jar)
  LoadingPlugin (Xaeros_Minimap_20.3.0_Forge_1.12.jar)
Contact their authors BEFORE contacting forge

// Oh - I know what I did wrong!

Time: 2/15/20 3:03 PM
Description: Exception in server tick loop

Missing Mods:
	unknown : need [14.23.5.2806,): have 14.23.5.2768

net.minecraftforge.fml.common.MissingModsException: Mod chisel (Chisel) requires [forge@[14.23.5.2806,)]
	at net.minecraftforge.fml.common.Loader.sortModList(Loader.java:264)
	at net.minecraftforge.fml.common.Loader.loadMods(Loader.java:570)
	at net.minecraftforge.fml.server.FMLServerHandler.beginServerLoading(FMLServerHandler.java:98)
	at net.minecraftforge.fml.common.FMLCommonHandler.onServerStart(FMLCommonHandler.java:333)
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:125)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:486)
	at java.lang.Thread.run(Thread.java:748)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Linux (amd64) version 3.10.0-1062.1.2.el7.x86_64
	Java Version: 1.8.0_222, Oracle Corporation
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 379068320 bytes (361 MB) / 558891008 bytes (533 MB) up to 3728736256 bytes (3556 MB)
	JVM Flags: 5 total; -Xmx4000M -Xms128M -XX:+UnlockExperimentalVMOptions -XX:MaxMetaspaceSize=320M -XX:MetaspaceSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2768 11 mods loaded, 11 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID                | Version           | Source                                        | Signature                                |
	|:----- |:----------------- |:----------------- |:--------------------------------------------- |:---------------------------------------- |
	| U     | minecraft         | 1.12.2            | minecraft.jar                                 | None                                     |
	| U     | mcp               | 9.42              | minecraft.jar                                 | None                                     |
	| U     | FML               | 8.0.99.99         | forge-1.12.2-14.23.5.2768-universal.jar       | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| U     | forge             | 14.23.5.2768      | forge-1.12.2-14.23.5.2768-universal.jar       | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| U     | xaerominimap_core | 1.12.2-1.0        | minecraft.jar                                 | None                                     |
	| U     | backpacks16840    | 3.5.8             | backpacks+1.12.2+-+3.5.8.jar                  | None                                     |
	| U     | chisel            | MC1.12.2-1.0.1.44 | Chisel-MC1.12.2-1.0.1.44.jar                  | None                                     |
	| U     | codechickenlib    | 3.2.3.358         | CodeChickenLib-1.12.2-3.2.3.358-universal.jar | None                                     |
	| U     | gravestone        | 1.10.1            | gravestone-1.10.1.jar                         | None                                     |
	| U     | jei               | 4.15.0.268        | jei_1.12.2-4.15.0.268.jar                     | None                                     |
	| U     | nei               | 2.4.2             | NotEnoughItems-1.12.2-2.4.2.240-universal.jar | None                                     |

	Loaded coremods (and transformers): 
BCModPlugin (backpacks+1.12.2+-+3.5.8.jar)
  brad16840.core.ClassTransformer
LoadingPlugin (Xaeros_Minimap_20.3.0_Forge_1.12.jar)
  xaero.common.core.transformer.ChunkTransformer
  xaero.common.core.transformer.NetHandlerPlayClientTransformer
	Profiler Position: N/A (disabled)
	Is Modded: Definitely; Server brand changed to 'fml,forge'
	Type: Dedicated Server (map_server.txt)

**Comment by covers1624** [comment]
You dont have only this mod installed, you have others too. and Chisel is complaining about the forge version `Mod chisel (Chisel) requires [forge@[14.23.5.2806,)]`
