### ISSUE TITLE
The game crashed whilst there was a severe problem during mod loading that has caused the game to fail Error: net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Goki Stats (gokistats)

### ISSUE THREAD

**Issue by RideBack7** [TheCBProject/CodeChickenLib#291]
https://paste.ubuntu.com/p/yz5bcTtH66/

---- Minecraft Crash Report ----  WARNING: coremods are present:   llibrary (llibrary-core-1.0.11-1.12.2.jar)   Inventory Tweaks Coremod (InventoryTweaks_1.64_dev.jar)   McLib core mod (mclib-1.0.4-1.12.2.jar) Contact their authors BEFORE contacting forge  // I bet Cylons wouldn't have this problem.  Time: 2/22/20 2:46 PM Description: There was a severe problem during mod loading that has caused the game to fail  net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Goki Stats (gokistats) Caused by: java.lang.NullPointerException 	at net.infstudio.goki.api.stat.StatBase.reload(StatBase.java:76) 	at net.infstudio.goki.common.stat.damage.DamageSourceProtectionStat.reload(DamageSourceProtectionStat.java:34) 	at net.infstudio.goki.common.config.Configurable.reloadConfig(Configurable.java:23) 	at net.infstudio.goki.GokiStats$$Lambda$698/2044905319.accept(Unknown Source) 	at java.lang.Iterable.forEach(Iterable.java:75) 	at net.infstudio.goki.GokiStats.preInit(GokiStats.java:70) 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) 	at java.lang.reflect.Method.invoke(Method.java:497) 	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:637) 	at sun.reflect.GeneratedMethodAccessor8.invoke(Unknown Source) 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) 	at java.lang.reflect.Method.invoke(Method.java:497) 	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91) 	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150) 	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76) 	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399) 	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71) 	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116) 	at com.google.common.eventbus.EventBus.post(EventBus.java:217) 	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219) 	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197) 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) 	at java.lang.reflect.Method.invoke(Method.java:497) 	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91) 	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150) 	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76) 	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399) 	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71) 	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116) 	at com.google.common.eventbus.EventBus.post(EventBus.java:217) 	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:136) 	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:629) 	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:252) 	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:467) 	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378) 	at net.minecraft.client.main.Main.main(SourceFile:123) 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) 	at java.lang.reflect.Method.invoke(Method.java:497) 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)   A detailed walkthrough of the error, its code path and all known details is as follows: ---------------------------------------------------------------------------------------  -- System Details -- Details: 	Minecraft Version: 1.12.2 	Operating System: Windows 10 (amd64) version 10.0 	Java Version: 1.8.0_51, Oracle Corporation 	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation 	Memory: 388231168 bytes (370 MB) / 939524096 bytes (896 MB) up to 6442450944 bytes (6144 MB) 	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx6G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M 	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0 	FML: MCP 9.42 Powered by Forge 14.23.5.2847 43 mods loaded, 42 mods active 	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored  	\| State \| ID                  \| Version                      \| Source                                             \| Signature                                \| 	\|:----- \|:------------------- \|:---------------------------- \|:-------------------------------------------------- \|:---------------------------------------- \| 	\| LCH   \| minecraft           \| 1.12.2                       \| minecraft.jar                                      \| None                                     \| 	\| LCH   \| mcp                 \| 9.42                         \| minecraft.jar                                      \| None                                     \| 	\| LCH   \| FML                 \| 8.0.99.99                    \| forge-1.12.2-14.23.5.2847.jar                      \| None                                     \| 	\| LCH   \| forge               \| 14.23.5.2847                 \| forge-1.12.2-14.23.5.2847.jar                      \| None                                     \| 	\| LCH   \| voxelmap            \| 1.9.11                       \| forgemod_voxelmap-1.9.11_for_1.12.2.jar            \| None                                     \| 	\| LCH   \| bspkrscore          \| 7.6.0.1                      \| 1.12bspkrsCore_universal_7.6.0.1.jar               \| None                                     \| 	\| LCH   \| armorstatushud      \| 1.43.0                       \| 1.12ArmorStatusHUD_client_1.43.0.jar               \| None                                     \| 	\| LCH   \| treecapitator       \| 1.43.0                       \| 1.12TreeCapitator_client_1.43.0.jar                \| None                                     \| 	\| LCH   \| baubles             \| 1.5.2                        \| Baubles_1.12_1.5.2.jar                             \| None                                     \| 	\| LCH   \| bookshelf           \| 2.3.590                      \| Bookshelf_1.12.2_2.3.590.jar                       \| d476d1b22b218a10d845928d1665d45fce301b27 \| 	\| LCH   \| jei                 \| 4.15.0.293                   \| jei_1.12.2_4.15.0.293.jar                          \| None                                     \| 	\| LCH   \| thaumcraft          \| 6.1.BETA26                   \| Thaumcraft_1.12.2_6.1.BETA26.jar                   \| None                                     \| 	\| LCH   \| botania             \| r1.10-363                    \| Botania_1.12.2_r1.10_363.jar                       \| None                                     \| 	\| LCH   \| codechickenlib      \| 3.2.3.358                    \| CodeChickenLib-1.12.2-3.2.3.358-universal.jar      \| f1850c39b2516232a2108a7bd84d1cb5df93b261 \| 	\| LCH   \| redstoneflux        \| 2.1.0                        \| RedstoneFlux-1.12-2.1.0.6-universal.jar            \| 8a6abf2cb9e141b866580d369ba6548732eff25f \| 	\| LCH   \| brandonscore        \| 2.4.18                       \| BrandonsCore-1.12.2-2.4.18.210-universal.jar       \| None                                     \| 	\| LCH   \| buildcraftlib       \| 7.99.24.4                    \| buildcraft_1.12.2_all_7.99.24.4.jar                \| None                                     \| 	\| LCH   \| buildcraftcore      \| 7.99.24.4                    \| buildcraft_1.12.2_all_7.99.24.4.jar                \| None                                     \| 	\| LCH   \| buildcraftbuilders  \| 7.99.24.4                    \| buildcraft_1.12.2_all_7.99.24.4.jar                \| None                                     \| 	\| LCH   \| buildcrafttransport \| 7.99.24.4                    \| buildcraft_1.12.2_all_7.99.24.4.jar                \| None                                     \| 	\| LCH   \| buildcraftsilicon   \| 7.99.24.4                    \| buildcraft_1.12.2_all_7.99.24.4.jar                \| None                                     \| 	\| LCH   \| buildcraftcompat    \| 7.99.24.4                    \| buildcraft_1.12.2_all_7.99.24.4.jar                \| None                                     \| 	\| LCH   \| buildcraftenergy    \| 7.99.24.4                    \| buildcraft_1.12.2_all_7.99.24.4.jar                \| None                                     \| 	\| LCH   \| buildcraftfactory   \| 7.99.24.4                    \| buildcraft_1.12.2_all_7.99.24.4.jar                \| None                                     \| 	\| LCH   \| buildcraftrobotics  \| 7.99.24.4                    \| buildcraft_1.12.2_all_7.99.24.4.jar                \| None                                     \| 	\| LCH   \| draconicevolution   \| 2.3.25                       \| Draconic-Evolution-1.12.2-2.3.25.351-universal.jar \| None                                     \| 	\| LCH   \| eplus               \| 5.0.178                      \| EnchantingPlus_1.12.2_5.0.178.jar                  \| d476d1b22b218a10d845928d1665d45fce301b27 \| 	\| LCH   \| globalxp            \| v1.4.10                      \| globalxp_1.12.2_v1.4.10.jar                        \| None                                     \| 	\| LCE   \| gokistats           \| 1.2.8                        \| gokistats-1.2.8.jar                                \| None                                     \| 	\| LC    \| gravestone          \| 1.10.0                       \| gravestone_mc1.12.2_1.10.0.jar                     \| None                                     \| 	\| LC    \| infernalmobs        \| 1.7.3                        \| InfernalMobs_1.12.2.jar                            \| None                                     \| 	\| LC    \| inventorytweaks     \| 1.64-dev+release.123.f374f4b \| InventoryTweaks_1.64_dev.jar                       \| 55d2cd4f5f0961410bf7b91ef6c6bf00a766dcbe \| 	\| LC    \| ironchest           \| 1.12.2-7.0.67.844            \| ironchest_1.12.2_7.0.67.844.jar                    \| None                                     \| 	\| LC    \| lycanitesmobs       \| 2.0.2.2 - MC 1.12.2          \| lycanitesmobs_1.12.2_2.0.2.2.jar                   \| None                                     \| 	\| LC    \| mclib               \| 1.0.4                        \| mclib-1.0.4-1.12.2.jar                             \| None                                     \| 	\| LC    \| metamorph           \| 1.1.10                       \| metamorph-1.1.10-1.12.2.jar                        \| None                                     \| 	\| LC    \| llibrary            \| 1.7.19                       \| llibrary_1.7.19_1.12.2.jar                         \| b9f30a813bee3b9dd5652c460310cfcd54f6b7ec \| 	\| LC    \| mowziesmobs         \| 1.5.4                        \| mowziesmobs_1.12.2_1.5.4.jar                       \| None                                     \| 	\| LC    \| projecte            \| 1.12.2-PE1.4.0               \| ProjectE_1.12.2_PE1.4.0.jar                        \| None                                     \| 	\| LC    \| thaumictinkerer     \| 1.12.2-5.0-353c71c           \| thaumictinkerer_1.12.2_5.0_353c71c.jar             \| None                                     \| 	\| LC    \| torohealthmod       \| 1.12.2-11                    \| torohealth_1.12.2_11.jar                           \| None                                     \| 	\| LC    \| twilightforest      \| 3.10.1013                    \| twilightforest_1.12.2_3.10.1013_universal.jar      \| None                                     \| 	\| UD    \| mclib_core          \| 1.0.4                        \| minecraft.jar                                      \| None                                     \|  	Loaded coremods (and transformers):  llibrary (llibrary-core-1.0.11-1.12.2.jar)   net.ilexiconn.llibrary.server.core.plugin.LLibraryTransformer   net.ilexiconn.llibrary.server.core.patcher.LLibraryRuntimePatcher Inventory Tweaks Coremod (InventoryTweaks_1.64_dev.jar)   invtweaks.forge.asm.ContainerTransformer McLib core mod (mclib-1.0.4-1.12.2.jar)   mchorse.mclib.core.McLibCMClassTransformer 	GL info: ' Vendor: 'ATI Technologies Inc.' Version: '4.6.13559 Compatibility Profile Context 26.20.12028.2' Renderer: 'AMD Radeon (TM) R7 370 Series'
--

**Comment by covers1624** [comment]
Literelly not my mod, and please use [gist](https://gist.github.com/)
