### ISSUE TITLE
Game crashes everytime when using NEI, CodeChicken Lib and JEI

### ISSUE THREAD

**Issue by Intybyte** [TheCBProject/CodeChickenLib#292]
Here is the crash report

---- Minecraft Crash Report ----
// Hi. I'm Minecraft, and I'm a crashaholic.

Time: 2020-03-10 14:10:05 CET
Description: Initializing game

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from CodeChicken Lib (codechickenlib)
Caused by: codechicken.lib.configuration.ConfigFile$ConfigException: codechicken.lib.configuration.ConfigParseException: Invalid value type d, @Line:6, dump_asm=true
    at codechicken.lib.configuration.ConfigFile.load(ConfigFile.java:61)
    at codechicken.lib.configuration.ConfigFile.<init>(ConfigFile.java:43)
    at codechicken.lib.configuration.ConfigFile.<init>(ConfigFile.java:29)
    at codechicken.lib.configuration.ConfigFile.<init>(ConfigFile.java:19)
    at codechicken.lib.CodeChickenLib.preInit(CodeChickenLib.java:50)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:637)
    at sun.reflect.GeneratedMethodAccessor8.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
    at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
    at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
    at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
    at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
    at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
    at com.google.common.eventbus.EventBus.post(EventBus.java:217)
    at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219)
    at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
    at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
    at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
    at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
    at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
    at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
    at com.google.common.eventbus.EventBus.post(EventBus.java:217)
    at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:136)
    at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:629)
    at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:252)
    at net.minecraft.client.Minecraft.init(Minecraft.java:467)
    at net.minecraft.client.Minecraft.run(Minecraft.java:3931)
    at net.minecraft.client.main.Main.main(SourceFile:123)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: codechicken.lib.configuration.ConfigParseException: Invalid value type d, @Line:6, dump_asm=true
    at codechicken.lib.configuration.ConfigTag.parseTag(ConfigTag.java:92)
    at codechicken.lib.configuration.ConfigFile.load(ConfigFile.java:59)
    ... 44 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
  Minecraft Version: 1.12.2
  Operating System: Windows 8.1 (amd64) version 6.3
  Java Version: 1.8.0_51, Oracle Corporation
  Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
  Memory: 461553176 bytes (440 MB) / 2954551296 bytes (2817 MB) up to 6227755008 bytes (5939 MB)
  JVM Flags: 6 total; -Xmx6G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn2G -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump
  IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
  FML: MCP 9.42 Powered by Forge 14.23.5.2847 Optifine OptiFine_1.12.2_HD_U_F5 80 mods loaded, 80 mods active
       States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
       
       | State | ID                          | Version                  | Source                                          | Signature                                |
       |:----- |:--------------------------- |:------------------------ |:----------------------------------------------- |:---------------------------------------- |
       | LCH   | minecraft                   | 1.12.2                   | minecraft.jar                                   | None                                     |
       | LCH   | mcp                         | 9.42                     | minecraft.jar                                   | None                                     |
       | LCH   | FML                         | 8.0.99.99                | forge-1.12.2-14.23.5.2847.jar                   | None                                     |
       | LCH   | forge                       | 14.23.5.2847             | forge-1.12.2-14.23.5.2847.jar                   | None                                     |
       | LCH   | openmodscore                | 0.12.2                   | minecraft.jar                                   | None                                     |
       | LCH   | foamfixcore                 | 7.7.4                    | minecraft.jar                                   | None                                     |
       | LCH   | fastbench                   | 1.7.3                    | FastWorkbench-1.12.2-1.7.3.jar                  | None                                     |
       | LCH   | actuallyadditions           | 1.12.2-r151              | ActuallyAdditions-1.12.2-r151-2.jar             | None                                     |
       | LCH   | aoa3                        | 3.2.4                    | AoA3-3.2.4.jar                                  | 8bddeac148843f40e0b9f69201be2f4b3071700d |
       | LCH   | applecore                   | 3.2.0                    | AppleCore-mc1.12.2-3.2.0.jar                    | None                                     |
       | LCH   | jei                         | 4.15.0.291               | jei_1.12.2-4.15.0.291.jar                       | None                                     |
       | LCH   | quark                       | r1.6-177                 | Quark-r1.6-177.jar                              | None                                     |
       | LCH   | autoreglib                  | 1.3-32                   | AutoRegLib-1.3-32.jar                           | None                                     |
       | LCH   | baubles                     | 1.5.2                    | Baubles-1.12-1.5.2.jar                          | None                                     |
       | LCH   | betterbuilderswands         | 0.11.1                   | BetterBuildersWands-1.12-0.11.1.245+69d0d70.jar | None                                     |
       | LCH   | bettercaves                 | 1.12.2                   | bettercaves-1.12.2-1.4.0.jar                    | None                                     |
       | LCH   | bloodmoon                   | 1.5.3                    | Bloodmoon-MC1.12.2-1.5.3.jar                    | d72e0dd57935b3e9476212aea0c0df352dd76291 |
       | LCH   | bonsaitrees                 | 1.1.4                    | bonsaitrees-1.1.4-b170.jar                      | None                                     |
       | LCH   | carryon                     | 1.12.3                   | CarryOn+MC1.12.2+v1.12.3.jar                    | 55e88f24d04398481ae6f1ce76f65fd776f14227 |
       | LCH   | chameleon                   | 1.12-4.1.3               | Chameleon-1.12-4.1.3.jar                        | None                                     |
       | LCH   | ctm                         | MC1.12.2-1.0.1.30        | CTM-MC1.12.2-1.0.1.30.jar                       | None                                     |
       | LCH   | chisel                      | MC1.12.2-1.0.1.44        | Chisel-MC1.12.2-1.0.1.44.jar                    | None                                     |
       | LCE   | codechickenlib              | 3.2.3.358                | CodeChickenLib-1.12.2-3.2.3.358-universal.jar   | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
       | LC    | compactstorage              | 3.1                      | CompactStorage-3.1-12.jar                       | None                                     |
       | LC    | compatched                  | 1.6.0                    | ComPatchedStorage-1.12.2-1.6.0.jar              | None                                     |
       | LC    | cucumber                    | 1.1.3                    | Cucumber-1.12.2-1.1.3.jar                       | None                                     |
       | LC    | cyclicmagic                 | 1.19.20                  | Cyclic-1.12.2-1.19.21.jar                       | 0e5cb559be7d03f3fc18b8cba547d663e25f28af |
       | LC    | cyclopscore                 | 1.6.1                    | CyclopsCore-1.12.2-1.6.1.jar                    | bd0353b3e8a2810d60dd584e256e364bc3bedd44 |
       | LC    | dynamiclights               | 1.4.9                    | DynamicLights-1.12.2.jar                        | None                                     |
       | LC    | dynamiclights_onfire        | 1.0.7                    | DynamicLights-1.12.2.jar                        | None                                     |
       | LC    | dynamiclights_creepers      | 1.0.6                    | DynamicLights-1.12.2.jar                        | None                                     |
       | LC    | dynamiclights_dropitems     | 1.1.0                    | DynamicLights-1.12.2.jar                        | None                                     |
       | LC    | dynamiclights_entityclasses | 1.0.1                    | DynamicLights-1.12.2.jar                        | None                                     |
       | LC    | dynamiclights_mobequipment  | 1.1.0                    | DynamicLights-1.12.2.jar                        | None                                     |
       | LC    | dynamiclights_flamearrows   | 1.0.1                    | DynamicLights-1.12.2.jar                        | None                                     |
       | LC    | dynamiclights_floodlights   | 1.0.3                    | DynamicLights-1.12.2.jar                        | None                                     |
       | LC    | dynamiclights_otherplayers  | 1.0.9                    | DynamicLights-1.12.2.jar                        | None                                     |
       | LC    | dynamiclights_theplayer     | 1.1.3                    | DynamicLights-1.12.2.jar                        | None                                     |
       | LC    | everlastingabilities        | 1.5.2                    | EverlastingAbilities-1.12.2-1.5.2.jar           | bd0353b3e8a2810d60dd584e256e364bc3bedd44 |
       | LC    | mantle                      | 1.12-1.3.3.55            | Mantle-1.12-1.3.3.55.jar                        | None                                     |
       | LC    | tconstruct                  | 1.12.2-2.13.0.179        | TConstruct-1.12.2-2.13.0.179.jar                | None                                     |
       | LC    | extrautils2                 | 1.0                      | extrautils2-1.12-1.9.9.jar                      | None                                     |
       | LC    | fastfurnace                 | 1.3.1                    | FastFurnace-1.12.2-1.3.1.jar                    | None                                     |
       | LC    | fastleafdecay               | v14                      | FastLeafDecay-v14.jar                           | None                                     |
       | LC    | firstaid                    | 1.6.                     | firstaid-1.6.6.jar                              | 7904c4e13947c8a616c5f39b26bdeba796500722 |
       | LC    | foamfix                     | 0.10.10-1.12.2           | foamfix-0.10.10-1.12.2.jar                      | None                                     |
       | LC    | foodexpansion               | 1.3                      | FoodExpansion1.3.3-1.12.2.jar                   | None                                     |
       | LC    | forgelin                    | 1.8.3                    | Forgelin-1.8.3.jar                              | None                                     |
       | LC    | ftblib                      | 5.4.4.5                  | FTBLib-5.4.4.5.jar                              | None                                     |
       | LC    | inventorytweaks             | 1.63+release.109.220f184 | InventoryTweaks-1.63.jar                        | 55d2cd4f5f0961410bf7b91ef6c6bf00a766dcbe |
       | LC    | ironbackpacks               | 1.12.2-3.0.8-12          | IronBackpacks-1.12.2-3.0.8-12.jar               | None                                     |
       | LC    | ironchest                   | 1.12.2-7.0.67.844        | ironchest-1.12.2-7.0.72.847.jar                 | None                                     |
       | LC    | ironfurnaces                | 1.3.5                    | ironfurnaces-1.3.5.jar                          | None                                     |
       | LC    | journeymap                  | 1.12.2-5.5.9             | journeymap-1.12.2-5.5.9.jar                     | None                                     |
       | LC    | shadowmc                    | 3.8.0                    | ShadowMC-1.12-3.8.0.jar                         | None                                     |
       | LC    | leveluphp                   | 1.12.2-1.4.0             | leveluphp-1.12.2-1.4.0.jar                      | None                                     |
       | LC    | metallurgy                  | 0.3.3                    | Metallurgy-4-Reforged-0.3.3.jar                 | None                                     |
       | LC    | morebuckets                 | 1.0.4                    | MoreBuckets-1.12.2-1.0.4.jar                    | None                                     |
       | LC    | mousetweaks                 | 2.10                     | MouseTweaks-2.10-mc1.12.2.jar                   | None                                     |
       | LC    | neat                        | 1.4-17                   | Neat+1.4-17.jar                                 | None                                     |
       | LC    | plustic                     | 7.1.6.1                  | plustic-7.1.6.1.jar                             | None                                     |
       | LC    | netherendingores            | 1.12.2-1.3               | Netherending-Ores-1.12.2-1.3.jar                | None                                     |
       | LC    | recipehandler               | 0.13                     | NoMoreRecipeConflict-0.13(1.12.2).jar           | None                                     |
       | LC    | nei                         | 2.4.3                    | NotEnoughItems-1.12.2-2.4.3.245-universal.jar   | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
       | LC    | offlineskins                | 1.12.2-v6                | OfflineSkins-1.12.2-v6.jar                      | aaaf83332a11df02406e9f266b1b65c1306f0f76 |
       | LC    | openmods                    | 0.12.2                   | OpenModsLib-1.12.2-0.12.2.jar                   | d2a9a8e8440196e26a268d1f3ddc01b2e9c572a5 |
       | LC    | openblocks                  | 1.8.1                    | OpenBlocks-1.12.2-1.8.1.jar                     | d2a9a8e8440196e26a268d1f3ddc01b2e9c572a5 |
       | LC    | oreexcavation               | 1.4.140                  | OreExcavation-1.4.140.jar                       | None                                     |
       | LC    | potioncore                  | 1.8_for_1.12.2           | PotionCore-1.8_for_1.12.2.jar                   | None                                     |
       | LC    | storagenetwork              | 1.7.8                    | SimpleStorageNetwork-1.12.2-1.7.8.jar           | 1bc8f8dbe770187a854cef35dad0ff40ba441bbe |
       | LC    | storagedrawers              | 1.12.2-5.4.0             | StorageDrawers-1.12.2-5.4.0.jar                 | None                                     |
       | LC    | theoneprobe                 | 1.4.28                   | theoneprobe-1.12-1.4.28.jar                     | None                                     |
       | LC    | tinkersjei                  | 1.2                      | tinkersjei-1.2.jar                              | None                                     |
       | LC    | tinkertoolleveling          | 1.12.2-1.1.0.DEV.b23e769 | TinkerToolLeveling-1.12.2-1.1.0.jar             | None                                     |
       | LC    | tinymobfarm                 | 1.0.5                    | TinyMobFarm-1.12.2-1.0.5.jar                    | None                                     |
       | LC    | vanillafix                  | 1.0.10-SNAPSHOT          | VanillaFix-1.0.10-99.jar                        | None                                     |
       | LC    | walljump                    | 1.3.2                    | walljump-1.12.2-1.3.2.jar                       | None                                     |
       | LC    | woolintostrings             | 1.0.2                    | WoolIntoStrings-1.12.2-1.0.2 (1).jar            | None                                     |
       | LC    | xpbook                      | v1.1.4                   | xptome-1.12.2-v1.1.4.jar                        | None                                     |
       | LC    | solcarrot                   | 1.8.3                    | solcarrot-1.12.2-1.8.3.jar                      | None                                     |
  Loaded coremods (and transformers): ForgelinPlugin (Forgelin-1.8.3.jar)
                                        
                                      Inventory Tweaks Coremod (InventoryTweaks-1.63.jar)
                                        invtweaks.forge.asm.ContainerTransformer
                                      offlineskins (OfflineSkins-1.12.2-v6-core.jar)
                                        lain.mods.skins.init.forge.asm.ASMTransformer
                                      Quark Plugin (Quark-r1.6-177.jar)
                                        vazkii.quark.base.asm.ClassTransformer
                                      AppleCore (AppleCore-mc1.12.2-3.2.0.jar)
                                        squeek.applecore.asm.TransformerModuleHandler
                                      CTMCorePlugin (CTM-MC1.12.2-1.0.1.30.jar)
                                        team.chisel.ctm.client.asm.CTMTransformer
                                      VanillaFixLoadingPlugin (VanillaFix-1.0.10-99.jar)
                                        
                                      Do not report to Forge! (If you haven't disabled the FoamFix coremod, try disabling it in the config! Note that this bit of text will still appear.) (foamfix-0.10.10-1.12.2.jar)
                                        pl.asie.foamfix.coremod.FoamFixTransformer
                                      OpenModsCorePlugin (OpenModsLib-1.12.2-0.12.2.jar)
                                        openmods.core.OpenModsClassTransformer
                                      DLFMLCorePlugin (DynamicLights-1.12.2.jar)
                                        atomicstryker.dynamiclights.common.DLTransformer
                                      LoadingPlugin (Bloodmoon-MC1.12.2-1.5.3.jar)
                                        lumien.bloodmoon.asm.ClassTransformer
  OpenModsLib class transformers: [llama_null_fix:FINISHED],[horse_base_null_fix:FINISHED],[pre_world_render_hook:FINISHED],[player_render_hook:FINISHED],[horse_null_fix:FINISHED]
  Pulsar/tconstruct loaded Pulses: - TinkerCommons (Enabled/Forced)
                                   - TinkerWorld (Enabled/Not Forced)
                                   - TinkerTools (Enabled/Not Forced)
                                   - TinkerHarvestTools (Enabled/Forced)
                                   - TinkerMeleeWeapons (Enabled/Forced)
                                   - TinkerRangedWeapons (Enabled/Forced)
                                   - TinkerModifiers (Enabled/Forced)
                                   - TinkerSmeltery (Enabled/Not Forced)
                                   - TinkerGadgets (Enabled/Not Forced)
                                   - TinkerOredict (Enabled/Forced)
                                   - TinkerIntegration (Enabled/Forced)
                                   - TinkerFluids (Enabled/Forced)
                                   - TinkerMaterials (Enabled/Forced)
                                   - TinkerModelRegister (Enabled/Forced)
                                   - chiselIntegration (Enabled/Not Forced)
                                   - theoneprobeIntegration (Enabled/Not Forced)
                                   - quarkIntegration (Enabled/Not Forced)
  Suspected Mods: CodeChicken Lib (codechickenlib)
  Launched Version: 1.12.2-forge1.12.2-14.23.5.2847
  LWJGL: 2.9.4
  OpenGL: AMD Radeon(TM) R5 Graphics GL version 4.5.13542 Compatibility Profile Context 25.20.14012.10001, ATI Technologies Inc.
  GL Caps: Using GL 1.3 multitexturing.
           Using GL 1.3 texture combiners.
           Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
           Shaders are available because OpenGL 2.1 is supported.
           VBOs are available because OpenGL 1.5 is supported.
  Using VBOs: Yes
  Is Modded: Definitely; Client brand changed to 'fml,forge'
  Type: Client (map_client.txt)
  Resource Packs: vanilla, file/OreOverhaulRelease_1.9.zip
  Current Language: English (US)
  Profiler Position: N/A (disabled)
  CPU: 2x AMD A9-9420 RADEON R5, 5 COMPUTE CORES 2C+3G

**Comment by rwilliaise** [comment]
Delete the CCL config. It is trying to parse a pre-1.12.2 config.

**Comment by jetblade** [comment]
> 
> 
> Delete the CCL config. It is trying to parse a pre-1.12.2 config.

does it also work with the @line20?

**Comment by MineRobber9000** [comment]
Yes. See #270.
