### ISSUE TITLE
[1.12.2] Fatally missing registry entries

### ISSUE THREAD

**Issue by OKAlumnus** [TheCBProject/CodeChickenLib#293]
Hosting modded server with friends :( and they are waiting for 2 of us to finish and start hosting it was suppose to be done yesterday but blahbalhbalhb labh labhl abhl bahl bhl balht then this happend
Title pops up then when i try again it says this https://gyazo.com/1745f8e69363e7d2f0d18c05374e42ea
in the console this is the only thing that is said when i get kicked https://hastebin.com/ovalelufuv.pl

**Comment by covers1624** [comment]
Your client is missing recipes, literelly nothing to do with CCL, and i have no idea how to track that down.
