### ISSUE TITLE
Delete the CCL config. It is trying to parse a pre-1.12.2 config.

### ISSUE THREAD

**Issue by jetblade** [TheCBProject/CodeChickenLib#295]
Delete the CCL config. It is trying to parse a pre-1.12.2 config.

_Originally posted by @rajawilliams in https://github.com/TheCBProject/CodeChickenLib/issues/292#issuecomment-605472048_

does that also work with this?

---- Minecraft Crash Report ----

WARNING: coremods are present:
  BCModPlugin (backpacks 1.12.2 - 3.5.8.jar)
  CreativePatchingLoader (CreativeCore_v1.9.90_mc1.12.2.jar)
  OpenEyePlugin (OpenEye-1.12.2-0.8.jar)
  LittlePatchingLoader (LittleTiles_v1.5.0-pre198_mc1.12.2.jar)
  Quark Plugin (Quark-r1.6-177.jar)
  AppleCore (AppleCore-mc1.12.2-3.2.0.jar)
  CTMCorePlugin (CTM-MC1.12.2-1.0.1.30.jar)
  ForgelinPlugin (Forgelin-1.8.4.jar)
  MekanismCoremod (Mekanism-1.12.2-9.8.3.390.jar)
  LoadingPlugin (LoadingProfiler-MC1.12-1.3.jar)
  EnderCorePlugin (EnderCore-1.12.2-0.5.73-core.jar)
  NWRTweak (redstonepaste-mc1.12-1.7.5.jar)
  IELoadingPlugin (ImmersiveEngineering-core-0.12-89.jar)
  ShetiPhian-ASM (ShetiPhian-ASM-1.12.0.jar)
  LoadingPlugin (ResourceLoader-MC1.12.1-1.5.3.jar)
  Inventory Tweaks Coremod (InventoryTweaks-1.64+dev.150.jar)
  ColorUtilityCorePlugin (ColorUtility-universal-1.0.4.jar)
Contact their authors BEFORE contacting forge

// Hi. I'm Minecraft, and I'm a crashaholic.

Time: 3/31/20 7:26 PM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from CodeChicken Lib (codechickenlib)
Caused by: codechicken.lib.configuration.ConfigFile$ConfigException: codechicken.lib.configuration.ConfigParseException: Invalid value type d, @Line:20, dump_asm=true
	at codechicken.lib.configuration.ConfigFile.load(ConfigFile.java:61)
	at codechicken.lib.configuration.ConfigFile.<init>(ConfigFile.java:43)
	at codechicken.lib.configuration.ConfigFile.<init>(ConfigFile.java:29)
	at codechicken.lib.configuration.ConfigFile.<init>(ConfigFile.java:19)
	at codechicken.lib.CodeChickenLib.preInit(CodeChickenLib.java:50)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:637)
	at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:136)
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:629)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:252)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:467)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: codechicken.lib.configuration.ConfigParseException: Invalid value type d, @Line:20, dump_asm=true
	at codechicken.lib.configuration.ConfigTag.parseTag(ConfigTag.java:92)
	at codechicken.lib.configuration.ConfigFile.load(ConfigFile.java:59)
	... 44 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1408975944 bytes (1343 MB) / 2752512000 bytes (2625 MB) up to 6442450944 bytes (6144 MB)
	JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx6912m -Xms256m -XX:PermSize=256m
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2847 Optifine OptiFine_1.12.2_HD_U_F5 166 mods loaded, 166 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID                                    | Version                         | Source                                               | Signature                                |
	|:----- |:------------------------------------- |:------------------------------- |:---------------------------------------------------- |:---------------------------------------- |
	| LCH   | minecraft                             | 1.12.2                          | minecraft.jar                                        | None                                     |
	| LCH   | mcp                                   | 9.42                            | minecraft.jar                                        | None                                     |
	| LCH   | FML                                   | 8.0.99.99                       | forge-1.12.2-14.23.5.2847.jar                        | None                                     |
	| LCH   | forge                                 | 14.23.5.2847                    | forge-1.12.2-14.23.5.2847.jar                        | None                                     |
	| LCH   | ColorUtility                          | 1.0.4                           | minecraft.jar                                        | None                                     |
	| LCH   | creativecoredummy                     | 1.0.0                           | minecraft.jar                                        | None                                     |
	| LCH   | littletilescore                       | 1.0.0                           | minecraft.jar                                        | None                                     |
	| LCH   | OpenEye                               | 0.8                             | OpenEye-1.12.2-0.8.jar                               | None                                     |
	| LCH   | actuallyadditions                     | 1.12.2-r151                     | ActuallyAdditions-1.12.2-r151-2.jar                  | None                                     |
	| LCH   | akashictome                           | 1.2-12                          | AkashicTome-1.2-12.jar                               | None                                     |
	| LCH   | applecore                             | 3.2.0                           | AppleCore-mc1.12.2-3.2.0.jar                         | None                                     |
	| LCH   | charset                               | 0.5.6.4                         | Charset-0.5.6.4.jar                                  | None                                     |
	| LCH   | crafttweaker                          | 4.1.20                          | CraftTweaker2-1.12-4.1.20.jar                        | None                                     |
	| LCH   | mtlib                                 | 3.0.6                           | MTLib-3.0.6.jar                                      | None                                     |
	| LCH   | modtweaker                            | 4.0.17                          | modtweaker-4.0.17.jar                                | None                                     |
	| LCH   | jei                                   | 4.15.0.293                      | jei_1.12.2-4.15.0.293.jar                            | None                                     |
	| LCH   | appleskin                             | 1.0.9                           | AppleSkin-mc1.12-1.0.9.jar                           | None                                     |
	| LCH   | ctm                                   | MC1.12.2-1.0.1.30               | CTM-MC1.12.2-1.0.1.30.jar                            | None                                     |
	| LCH   | appliedenergistics2                   | rv6-stable-7                    | appliedenergistics2-rv6-stable-7.jar                 | dfa4d3ac143316c6f32aa1a1beda1e34d42132e5 |
	| LCH   | mantle                                | 1.12-1.3.3.55                   | Mantle-1.12-1.3.3.55.jar                             | None                                     |
	| LCH   | chisel                                | MC1.12.2-1.0.1.44               | Chisel-MC1.12.2-1.0.1.44.jar                         | None                                     |
	| LCH   | endercore                             | 1.12.2-0.5.73                   | EnderCore-1.12.2-0.5.73.jar                          | None                                     |
	| LCE   | codechickenlib                        | 3.2.2.353                       | CodeChickenLib-1.12.2.jar                            | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| LC    | redstoneflux                          | 2.1.0                           | RedstoneFlux-1.12-2.1.0.6-universal.jar              | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| LC    | cofhcore                              | 4.6.3                           | CoFHCore-1.12.2-4.6.3.27-universal.jar               | None                                     |
	| LC    | cofhworld                             | 1.3.1                           | CoFHWorld-1.12.2-1.3.1.7-universal.jar               | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| LC    | thermalfoundation                     | 2.6.3                           | ThermalFoundation-1.12.2-2.6.3.27-universal.jar      | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| LC    | thermalexpansion                      | 5.5.4                           | ThermalExpansion-1.12.2-5.5.4.43-universal.jar       | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| LC    | enderio                               | 5.1.55                          | EnderIO-1.12.2-5.1.55.jar                            | None                                     |
	| LC    | enderiointegrationtic                 | 5.1.55                          | EnderIO-1.12.2-5.1.55.jar                            | None                                     |
	| LC    | tombstone                             | 3.6.5                           | tombstone-3.6.5-1.12.2.jar                           | None                                     |
	| LC    | quark                                 | r1.6-177                        | Quark-r1.6-177.jar                                   | None                                     |
	| LC    | tconstruct                            | 1.12.2-2.13.0.171               | TConstruct-1.12.2-2.13.0.171.jar                     | None                                     |
	| LC    | thedragonlib                          | 1.12.2-5.3.0                    | thedragonlib-1.12.2-5.3.0.jar                        | None                                     |
	| LC    | armorplus                             | 1.12.2-11.26.1.65               | armorplus-1.12.2-11.26.1.65.jar                      | None                                     |
	| LC    | atlcraft                              | MC1.12-Ver1.9                   | ATLCraftCandlesMod(MC1.12-Ver1.9).jar                | None                                     |
	| LC    | biomesoplenty                         | 7.0.1.2444                      | BiomesOPlenty-1.12.2-7.0.1.2444-universal.jar        | None                                     |
	| LC    | atop                                  | 1.5                             | ATOP-1.12.2-v.1.5.jar                                | None                                     |
	| LC    | autoreglib                            | 1.3-32                          | AutoRegLib-1.3-32.jar                                | None                                     |
	| LC    | backpacks16840                        | 3.5.8                           | backpacks 1.12.2 - 3.5.8.jar                         | None                                     |
	| LC    | base                                  | 3.13.0                          | base-1.12.2-3.13.0.jar                               | None                                     |
	| LC    | bedbugs                               | @VERSION@                       | BedBugs-1.12-1.0.1.jar                               | None                                     |
	| LC    | betteradvancements                    | 0.1.0.77                        | BetterAdvancements-1.12.2-0.1.0.77.jar               | None                                     |
	| LC    | betterbuilderswands                   | 0.13.2                          | BetterBuildersWands-1.12.2-0.13.2.271+5997513.jar    | None                                     |
	| LC    | betterquesting                        | 3.5.320                         | BetterQuesting-3.5.320.jar                           | None                                     |
	| LC    | blockdrops                            | 1.4.0                           | blockdrops-1.12.2-1.4.0.jar                          | None                                     |
	| LC    | bonsaitrees                           | 1.1.4                           | bonsaitrees-1.1.4-b170.jar                           | None                                     |
	| LC    | buildcraftlib                         | 7.99.24.6                       | buildcraft-all-7.99.24.6.jar                         | None                                     |
	| LC    | buildcraftcore                        | 7.99.24.6                       | buildcraft-all-7.99.24.6.jar                         | None                                     |
	| LC    | buildcraftbuilders                    | 7.99.24.6                       | buildcraft-all-7.99.24.6.jar                         | None                                     |
	| LC    | buildcrafttransport                   | 7.99.24.6                       | buildcraft-all-7.99.24.6.jar                         | None                                     |
	| LC    | buildcraftsilicon                     | 7.99.24.6                       | buildcraft-all-7.99.24.6.jar                         | None                                     |
	| LC    | buildcraftcompat                      | 7.99.24.6                       | buildcraft-all-7.99.24.6.jar                         | None                                     |
	| LC    | buildcraftenergy                      | 7.99.24.6                       | buildcraft-all-7.99.24.6.jar                         | None                                     |
	| LC    | buildcraftfactory                     | 7.99.24.6                       | buildcraft-all-7.99.24.6.jar                         | None                                     |
	| LC    | buildcraftrobotics                    | 7.99.24.6                       | buildcraft-all-7.99.24.6.jar                         | None                                     |
	| LC    | ceramics                              | 1.12-1.3.7                      | Ceramics-1.12-1.3.7.jar                              | None                                     |
	| LC    | chameleon                             | 1.12-4.1.3                      | Chameleon-1.12-4.1.3.jar                             | None                                     |
	| LC    | chesttransporter                      | 2.8.8                           | ChestTransporter-1.12.2-2.8.8.jar                    | None                                     |
	| LC    | chiselsandbits                        | 14.33                           | chiselsandbits-14.33.jar                             | None                                     |
	| LC    | shadowmc                              | 3.8.0                           | ShadowMC-1.12-3.8.0.jar                              | None                                     |
	| LC    | clipboard                             | @VERSION@                       | Clipboard-1.12-1.3.0.jar                             | None                                     |
	| LC    | clumps                                | 3.1.2                           | Clumps-3.1.2.jar                                     | None                                     |
	| LC    | morpheus                              | 1.12.2-3.5.106                  | Morpheus-1.12.2-3.5.106.jar                          | None                                     |
	| LC    | comforts                              | 1.4.1.2                         | comforts-1.12.2-1.4.1.2.jar                          | 5d5b8aee896a4f5ea3f3114784742662a67ad32f |
	| LC    | conarm                                | 1.2.5.3                         | conarm-1.12.2-1.2.5.3.jar                            | 2484ef4d131fdc0dca0647aa21b7b944ddb935a1 |
	| LC    | controlling                           | 3.0.8                           | Controlling-3.0.8.jar                                | None                                     |
	| LC    | cookingforblockheads                  | 6.5.0                           | CookingForBlockheads_1.12.2-6.5.0.jar                | None                                     |
	| LC    | corail_pillar_extension_biomesoplenty | 4.0.1                           | corail_pillar_extension_biomesoplenty-4.0.1-1.12.jar | None                                     |
	| LC    | corail_pillar_extension_chisel        | 4.0.0                           | corail_pillar_extension_chisel-4.0.0-1.12.jar        | None                                     |
	| LC    | corail_pillar_extension_quark         | 4.0.0                           | corail_pillar_extension_quark-4.0.0-1.12.jar         | None                                     |
	| LC    | ctgui                                 | 1.0.0                           | CraftTweaker2-1.12-4.1.20.jar                        | None                                     |
	| LC    | crafttweakerjei                       | 2.0.3                           | CraftTweaker2-1.12-4.1.20.jar                        | None                                     |
	| LC    | creativecore                          | 1.9.9                           | CreativeCore_v1.9.90_mc1.12.2.jar                    | None                                     |
	| LC    | custommainmenu                        | 2.0.9.1                         | CustomMainMenu-MC1.12.2-2.0.9.1.jar                  | None                                     |
	| LC    | customnpcs                            | 1.12                            | CustomNPCs_1.12.2-(01Oct19).jar                      | None                                     |
	| LC    | journeymap                            | 1.12.2-5.5.6                    | journeymap-1.12.2-5.5.6.jar                          | None                                     |
	| LC    | defaultoptions                        | 9.2.8                           | DefaultOptions_1.12.2-9.2.8.jar                      | None                                     |
	| LC    | durabilityshow                        | 5.0.0                           | Durability Show-1.12-5.0.0.jar                       | None                                     |
	| LC    | dynamictrees                          | 1.12.2-0.9.6                    | DynamicTrees-1.12.2-0.9.6.jar                        | None                                     |
	| LC    | dynamictreesbop                       | 1.12.2-1.4.1e                   | DynamicTreesBOP-1.12.2-1.4.1e.jar                    | None                                     |
	| LC    | earthworks                            | 1.3.4.3                         | Earthworks-1.12-1.3.6.jar                            | None                                     |
	| LC    | elevatorid                            | 1.3.14                          | ElevatorMod-1.12.2-1.3.14.jar                        | None                                     |
	| LC    | csb_ench_table                        | 1.1.3                           | EnchantingTable-1.12-1.1.3.jar                       | None                                     |
	| LC    | enderiobase                           | 5.1.55                          | EnderIO-1.12.2-5.1.55.jar                            | None                                     |
	| LC    | enderioconduits                       | 5.1.55                          | EnderIO-1.12.2-5.1.55.jar                            | None                                     |
	| LC    | enderioconduitsappliedenergistics     | 5.1.55                          | EnderIO-1.12.2-5.1.55.jar                            | None                                     |
	| LC    | enderioconduitsopencomputers          | 5.1.55                          | EnderIO-1.12.2-5.1.55.jar                            | None                                     |
	| LC    | enderioconduitsrefinedstorage         | 5.1.55                          | EnderIO-1.12.2-5.1.55.jar                            | None                                     |
	| LC    | enderiointegrationforestry            | 5.1.55                          | EnderIO-1.12.2-5.1.55.jar                            | None                                     |
	| LC    | enderiointegrationticlate             | 5.1.55                          | EnderIO-1.12.2-5.1.55.jar                            | None                                     |
	| LC    | enderiomachines                       | 5.1.55                          | EnderIO-1.12.2-5.1.55.jar                            | None                                     |
	| LC    | enderiopowertools                     | 5.1.55                          | EnderIO-1.12.2-5.1.55.jar                            | None                                     |
	| LC    | enderzoo                              | 1.12.1-1.4.0.49                 | EnderZoo-1.12.1-1.4.0.49.jar                         | None                                     |
	| LC    | expandedbonemeal                      | 1.2.1                           | expandedbonemeal-1.11-1.2.1.jar                      | None                                     |
	| LC    | tschipplib                            | 1.1.3                           | TschippLib MC1.12.2 v1.1.3.jar                       | None                                     |
	| LC    | extraambiance                         | 1.0.1                           | ExtraAmbiance MC1.12 v1.0.1.jar                      | None                                     |
	| LC    | extrabitmanipulation                  | 1.12.2-3.4.1                    | ExtraBitManipulation-1.12.2-3.4.1.jar                | None                                     |
	| LC    | extrautils2                           | 1.0                             | extrautils2-1.12-1.9.9.jar                           | None                                     |
	| LC    | fairylights                           | 2.1.10                          | fairylights-2.1.10-1.12.2.jar                        | None                                     |
	| LC    | farmingforblockheads                  | 3.1.28                          | FarmingForBlockheads_1.12.2-3.1.28.jar               | None                                     |
	| LC    | foamflower                            | 1.12.2-1.0.0.0-beta1            | foamflower-1.12.2-1.0.0.0-beta1.jar                  | None                                     |
	| LC    | forgelin                              | 1.8.4                           | Forgelin-1.8.4.jar                                   | None                                     |
	| LC    | waila                                 | 1.8.26                          | Hwyla-1.8.26-B41_1.12.2.jar                          | None                                     |
	| LC    | ic2                                   | 2.8.196-ex112                   | industrialcraft-2-2.8.196-ex112.jar                  | de041f9f6187debbc77034a344134053277aa3b0 |
	| LC    | inventorytweaks                       | 1.64+dev.150.7168e7a            | InventoryTweaks-1.64+dev.150.jar                     | 55d2cd4f5f0961410bf7b91ef6c6bf00a766dcbe |
	| LC    | ironchest                             | 1.12.2-7.0.67.844               | ironchest-1.12.2-7.0.72.847.jar                      | None                                     |
	| LC    | itlt                                  | 1.0.0                           | itlt-1.12.2-1.0.2.jar                                | None                                     |
	| LC    | jaff                                  | 1.7_for_1.12                    | JustAFewFish-1.7_for_1.12.jar                        | None                                     |
	| LC    | jeresources                           | 0.9.2.60                        | JustEnoughResources-1.12.2-0.9.2.60.jar              | None                                     |
	| LC    | kleeslabs                             | 5.4.12                          | KleeSlabs_1.12.2-5.4.12.jar                          | None                                     |
	| LC    | laggoggles                            | FAT-1.12.2-4.9                  | LagGoggles-FAT-1.12.2-4.9.jar                        | None                                     |
	| LC    | leverbuttonlights                     | 1.12.2-1.5                      | leverbuttonlights-1.12.2-3.2.9.jar                   | None                                     |
	| LC    | limelib                               | 1.7.12                          | limelib-1.12.2-1.7.12.jar                            | None                                     |
	| LC    | littletiles                           | 1.5.0                           | LittleTiles_v1.5.0-pre198_mc1.12.2.jar               | None                                     |
	| LC    | llor                                  | 1.1.6-mc1.12.2                  | LLOverlayReloaded-1.1.6-mc1.12.2.jar                 | None                                     |
	| LC    | loadingprofiler                       | 1.1                             | LoadingProfiler-MC1.12-1.3.jar                       | None                                     |
	| LC    | mekanism                              | 1.12.2-9.8.3.390                | Mekanism-1.12.2-9.8.3.390.jar                        | None                                     |
	| LC    | minemenu                              | 1.6.11                          | MineMenu-1.12.2-1.6.11-universal.jar                 | None                                     |
	| LC    | mousetweaks                           | 2.10                            | MouseTweaks-2.10-mc1.12.2.jar                        | None                                     |
	| LC    | multiplelights                        | 1.0.2                           | MultipleLights-1.12.x-1.0.2.jar                      | None                                     |
	| LC    | neat                                  | 1.4-17                          | Neat 1.4-17.jar                                      | None                                     |
	| LC    | netherportalfix                       | 5.3.17                          | NetherPortalFix_1.12.1-5.3.17.jar                    | None                                     |
	| LC    | recipehandler                         | 0.13                            | NoMoreRecipeConflict-0.13(1.12.2).jar                | None                                     |
	| LC    | oreexcavation                         | 1.4.143                         | OreExcavation-1.4.143.jar                            | None                                     |
	| LC    | getalltheseeds                        | 1.12a                           | Pam's Get all the Seeds! 1.12a.jar                   | None                                     |
	| LC    | harvestcraft                          | 1.12.2zb                        | Pam's HarvestCraft 1.12.2zf.jar                      | None                                     |
	| LC    | ping                                  | 1.4.5                           | Ping-1.12.2-1.4.5.jar                                | None                                     |
	| LC    | placebo                               | 1.6.0                           | Placebo-1.12.2-1.6.0.jar                             | None                                     |
	| LC    | shetiphiancore                        | 3.5.9                           | shetiphiancore-1.12.0-3.5.9.jar                      | None                                     |
	| LC    | platforms                             | 1.4.6                           | platforms-1.12.0-1.4.6.jar                           | None                                     |
	| LC    | progressiveautomation                 | 1.7.8                           | ProgressiveAutomation-1.12.2-1.7.8.jar               | None                                     |
	| LC    | questbook                             | 3.1.1-1.12                      | questbook-3.1.1-1.12.jar                             | None                                     |
	| LC    | recycler                              | 3.2.4                           | recycler-3.2.4-1.12.jar                              | None                                     |
	| LC    | redstonepaste                         | 1.7.5                           | redstonepaste-mc1.12-1.7.5.jar                       | None                                     |
	| LC    | resourceloader                        | 1.5.3                           | ResourceLoader-MC1.12.1-1.5.3.jar                    | d72e0dd57935b3e9476212aea0c0df352dd76291 |
	| LC    | woodenshears                          | @MAJOR@.@MINOR@.@REVIS@.@BUILD@ | SBM-WoodenShears-1.12-0.0.1b8.jar                    | None                                     |
	| LC    | shulkerbox                            | 1.3.2                           | shulkerbox-1.3.2.jar                                 | None                                     |
	| LC    | signpost                              | 1.08.3                          | signpost-1.12.2-1.08.3.jar                           | None                                     |
	| LC    | simplylight                           | 1.12.2-0.8.7                    | simplylight-1.12.2-0.8.7.jar                         | None                                     |
	| LC    | snad                                  | 1.12.1-1.7.09.16a               | Snad-1.12.1-1.7.09.16a.jar                           | None                                     |
	| LC    | sophisticatedwolves                   | 3.13.8                          | SophisticatedWolves-1.12.2-3.13.8.jar                | None                                     |
	| LC    | spartanshields                        | 1.5.4                           | SpartanShields-1.12.2-1.5.4.jar                      | None                                     |
	| LC    | bq_standard                           | 3.4.173                         | StandardExpansion-3.4.173.jar                        | None                                     |
	| LC    | storagedrawers                        | 1.12.2-5.4.0                    | StorageDrawers-1.12.2-5.4.0.jar                      | None                                     |
	| LC    | storagedrawersextra                   | @VERSION@                       | StorageDrawersExtras-1.12-3.1.0.jar                  | None                                     |
	| LC    | tinkersaddons                         | 1.0.7                           | Tinkers' Addons-1.12.1-1.0.7.jar                     | None                                     |
	| LC    | tinkertoolleveling                    | 1.12.2-1.1.0.DEV.b23e769        | TinkerToolLeveling-1.12.2-1.1.0.jar                  | None                                     |
	| LC    | tp                                    | 3.2.34                          | tinyprogressions-1.12.2-3.3.34-Release.jar           | None                                     |
	| LC    | toastcontrol                          | 1.8.1                           | Toast Control-1.12.2-1.8.1.jar                       | None                                     |
	| LC    | trashslot                             | 8.4.10                          | TrashSlot_1.12.2-8.4.10.jar                          | None                                     |
	| LC    | vefluids                              | 0.11.0.17                       | VE-FluidHandling-1.12.2-0.11.0b17.jar                | None                                     |
	| LC    | vending                               | 1.12.2-3.0.1.2                  | vending-1.12.2-3.0.1.2.jar                           | None                                     |
	| LC    | waddles                               | 0.6.0                           | Waddles-1.12.2-0.6.0.jar                             | None                                     |
	| LC    | wailaharvestability                   | 1.1.12                          | WailaHarvestability-mc1.12-1.1.12.jar                | None                                     |
	| LC    | wawla                                 | 2.5.273                         | Wawla-1.12.2-2.5.273.jar                             | d476d1b22b218a10d845928d1665d45fce301b27 |
	| LC    | woodenbucket                          | 0.3.0.22                        | WoodenBuckets-1.12.2-0.3.0b22.jar                    | None                                     |
	| LC    | xtones                                | 1.12-1.0.8-11                   | Xtones-1.12-1.0.8-11.jar                             | None                                     |
	| LC    | gbook                                 | 2.9.2                           | Guidebook-1.12.2-2.9.2.jar                           | None                                     |
	| LC    | immersiveengineering                  | 0.12-89                         | ImmersiveEngineering-0.12-89.jar                     | 4cb49fcde3b43048c9889e0a3d083225da926334 |
	| LC    | structurize                           | 1.12.2-0.10.124-ALPHA           | structurize-1.12.2-0.10.124-ALPHA.jar                | None                                     |
	| LC    | minecolonies                          | 1.12.2-0.10.654-BETA            | minecolonies-1.12.2-0.10.654-BETA-universal.jar      | None                                     |
	| LC    | orelib                                | 3.6.0.1                         | OreLib-1.12.2-3.6.0.1.jar                            | 7a2128d395ad96ceb9d9030fbd41d035b435753a |
	| LC    | reauth                                | 3.6.0                           | reauth-3.6.0.jar                                     | daba0ec4df71b6da841768c49fb873def208a1e3 |
	| LC    | supertools                            | 1.12.2-null                     | VanillaPlusTools-1.2.jar                             | None                                     |
	| LC    | corail_pillar                         | 4.2.1                           | corail_pillar-4.2.1-1.12.jar                         | None                                     |

	Loaded coremods (and transformers): 
BCModPlugin (backpacks 1.12.2 - 3.5.8.jar)
  brad16840.core.ClassTransformer
CreativePatchingLoader (CreativeCore_v1.9.90_mc1.12.2.jar)
  
OpenEyePlugin (OpenEye-1.12.2-0.8.jar)
  openeye.asm.MultiTransformer
LittlePatchingLoader (LittleTiles_v1.5.0-pre198_mc1.12.2.jar)
  com.creativemd.littletiles.LittleTilesTransformer
Quark Plugin (Quark-r1.6-177.jar)
  vazkii.quark.base.asm.ClassTransformer
AppleCore (AppleCore-mc1.12.2-3.2.0.jar)
  squeek.applecore.asm.TransformerModuleHandler
CTMCorePlugin (CTM-MC1.12.2-1.0.1.30.jar)
  team.chisel.ctm.client.asm.CTMTransformer
ForgelinPlugin (Forgelin-1.8.4.jar)
  
MekanismCoremod (Mekanism-1.12.2-9.8.3.390.jar)
  mekanism.coremod.KeybindingMigrationHelper
LoadingPlugin (LoadingProfiler-MC1.12-1.3.jar)
  lumien.loadingprofiler.asm.ClassTransformer
EnderCorePlugin (EnderCore-1.12.2-0.5.73-core.jar)
  com.enderio.core.common.transform.EnderCoreTransformer
  com.enderio.core.common.transform.SimpleMixinPatcher
NWRTweak (redstonepaste-mc1.12-1.7.5.jar)
  net.fybertech.nwr.NWRTransformer
IELoadingPlugin (ImmersiveEngineering-core-0.12-89.jar)
  blusunrize.immersiveengineering.common.asm.IEClassTransformer
ShetiPhian-ASM (ShetiPhian-ASM-1.12.0.jar)
  shetiphian.asm.ClassTransformer
LoadingPlugin (ResourceLoader-MC1.12.1-1.5.3.jar)
  lumien.resourceloader.asm.ClassTransformer
Inventory Tweaks Coremod (InventoryTweaks-1.64+dev.150.jar)
  invtweaks.forge.asm.ContainerTransformer
ColorUtilityCorePlugin (ColorUtility-universal-1.0.4.jar)
  com.Axeryok.ColorUtility.ColorUtilityTransformer
	GL info: ' Vendor: 'ATI Technologies Inc.' Version: '4.6.13571 Compatibility Profile Context 19.9.3 26.20.13025.1004' Renderer: 'Radeon (TM) RX 480 Graphics'
	AE2 Version: stable rv6-stable-7 for Forge 14.23.5.2768
	Pulsar/tconstruct loaded Pulses: 
		- TinkerCommons (Enabled/Forced)
		- TinkerWorld (Enabled/Not Forced)
		- TinkerTools (Enabled/Not Forced)
		- TinkerHarvestTools (Enabled/Forced)
		- TinkerMeleeWeapons (Enabled/Forced)
		- TinkerRangedWeapons (Enabled/Forced)
		- TinkerModifiers (Enabled/Forced)
		- TinkerSmeltery (Enabled/Not Forced)
		- TinkerGadgets (Enabled/Not Forced)
		- TinkerOredict (Enabled/Forced)
		- TinkerIntegration (Enabled/Forced)
		- TinkerFluids (Enabled/Forced)
		- TinkerMaterials (Enabled/Forced)
		- TinkerModelRegister (Enabled/Forced)
		- chiselIntegration (Enabled/Not Forced)
		- chiselsandbitsIntegration (Enabled/Not Forced)
		- wailaIntegration (Enabled/Not Forced)
		- quarkIntegration (Enabled/Not Forced)

	OptiFine Version: OptiFine_1.12.2_HD_U_F5
	OptiFine Build: 20191204-141934
	Render Distance Chunks: 18
	Mipmaps: 0
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: BSL_v7.1.04.1.zip
	OpenGlVersion: 4.6.13571 Compatibility Profile Context 19.9.3 26.20.13025.1004
	OpenGlRenderer: Radeon (TM) RX 480 Graphics
	OpenGlVendor: ATI Technologies Inc.
	CpuCount: 12

**Comment by MineRobber9000** [comment]
Yes. Most `codechicken.lib.configuration.ConfigParseException`, if not all, are caused by the config issue. See #270.

**Comment by Mikiriko** [comment]
> Yes. Most `codechicken.lib.configuration.ConfigParseException`, if not all, are caused by the config issue. See #270.

i also have the same problem but it still wont let me play it and keeps crashing

**Comment by rwilliaise** [comment]
It is probably unrelated to the config parser if it crashes even after deleting the config. Please create a new issue and attach a crash log.
