### ISSUE TITLE
an error during startup prevented minecraft from starting. please help!

### ISSUE THREAD

**Issue by borkedchicken** [TheCBProject/CodeChickenLib#296]
https://paste.dimdev.org/nikureroce.mccrash

---- Minecraft Crash Report ----
// You should try our sister game, Minceraft!

Time: 2020-04-14 21:04:20 BST
Description: Initializing game

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from CodeChicken Lib (codechickenlib)
Caused by: java.lang.NoClassDefFoundError: codechicken/lib/util/ResourceUtils
    at codechicken.lib.configuration.ConfigFile.load(ConfigFile.java:53)
    at codechicken.lib.configuration.ConfigFile.<init>(ConfigFile.java:43)
    at codechicken.lib.configuration.ConfigFile.<init>(ConfigFile.java:29)
    at codechicken.lib.configuration.ConfigFile.<init>(ConfigFile.java:19)
    at codechicken.lib.CodeChickenLib.preInit(CodeChickenLib.java:50)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:637)
    at sun.reflect.GeneratedMethodAccessor9.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
    at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
    at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
    at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
    at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
    at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
    at com.google.common.eventbus.EventBus.post(EventBus.java:217)
    at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219)
    at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
    at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
    at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
    at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
    at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
    at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
    at com.google.common.eventbus.EventBus.post(EventBus.java:217)
    at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:136)
    at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:629)
    at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:252)
    at net.minecraft.client.Minecraft.init(Minecraft.java:467)
    at net.minecraft.client.Minecraft.run(Minecraft.java:3931)
    at net.minecraft.client.main.Main.main(SourceFile:123)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.ClassNotFoundException: codechicken.lib.util.ResourceUtils
    at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
    ... 45 more
Caused by: java.lang.SecurityException: class "codechicken.lib.util.ResourceUtils"'s signer information does not match signer information of other classes in the same package
    at java.lang.ClassLoader.checkCerts(ClassLoader.java:895)
    at java.lang.ClassLoader.preDefineClass(ClassLoader.java:665)
    at java.lang.ClassLoader.defineClass(ClassLoader.java:758)
    at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
    at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182)
    ... 47 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
  Minecraft Version: 1.12.2
  Operating System: Windows 10 (amd64) version 10.0
  Java Version: 1.8.0_51, Oracle Corporation
  Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
  Memory: 987369584 bytes (941 MB) / 1610612736 bytes (1536 MB) up to 5368709120 bytes (5120 MB)
  JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx5G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
  IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
  FML: MCP 9.42 Powered by Forge 14.23.5.2847 130 mods loaded, 130 mods active
       States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
       
       | State | ID                   | Version                  | Source                                             | Signature                                |
       |:----- |:-------------------- |:------------------------ |:-------------------------------------------------- |:---------------------------------------- |
       | LCH   | minecraft            | 1.12.2                   | minecraft.jar                                      | None                                     |
       | LCH   | mcp                  | 9.42                     | minecraft.jar                                      | None                                     |
       | LCH   | FML                  | 8.0.99.99                | forge-1.12.2-14.23.5.2847.jar                      | None                                     |
       | LCH   | forge                | 14.23.5.2847             | forge-1.12.2-14.23.5.2847.jar                      | None                                     |
       | LCH   | ivtoolkit            | 1.3.3-1.12               | minecraft.jar                                      | None                                     |
       | LCH   | otgcore              | 1.12.2 - v8.3            | minecraft.jar                                      | None                                     |
       | LCH   | controllable         | 0.8.0                    | controllable-1.12.2-0.8.0.jar                      | None                                     |
       | LCH   | foamfixcore          | 7.7.4                    | minecraft.jar                                      | None                                     |
       | LCH   | adventurebags        | 0.9.1                    | ab-1.12.2-0.9.1b-0.9.1.jar                         | None                                     |
       | LCH   | forgeendertech       | 1.12.2-4.4.20.0          | ForgeEndertech-1.12.2-4.4.20.0-build.0354.jar      | None                                     |
       | LCH   | adlods               | 1.12.2-1.0.5.0           | AdLods-1.12.2-1.0.5.0-build.0354.jar               | None                                     |
       | LCH   | aether_legacy        | 1.4.4                    | aether_legacy-1.12.2-v1.4.4.jar                    | None                                     |
       | LCH   | applecore            | 3.2.0                    | AppleCore-mc1.12.2-3.2.0.jar                       | None                                     |
       | LCH   | jei                  | 4.15.0.268               | jei_1.12.2-4.15.0.268.jar                          | None                                     |
       | LCH   | appleskin            | 1.0.9                    | AppleSkin-mc1.12-1.0.9.jar                         | None                                     |
       | LCH   | ctm                  | MC1.12.2-0.3.3.22        | CTM-MC1.12.2-0.3.3.22.jar                          | None                                     |
       | LCH   | appliedenergistics2  | rv6-stable-6             | appliedenergistics2-rv6-stable-6.jar               | dfa4d3ac143316c6f32aa1a1beda1e34d42132e5 |
       | LCH   | aquaculture          | 1.6.8                    | Aquaculture-1.12.2-1.6.8.jar                       | None                                     |
       | LCH   | baubles              | 1.5.2                    | Baubles-1.12-1.5.2.jar                             | None                                     |
       | LCH   | atum                 | 2.0.11                   | Atum-1.12.2-2.0.11.jar                             | None                                     |
       | LCH   | quark                | r1.5-156                 | Quark-r1.5-156.jar                                 | None                                     |
       | LCH   | autoreglib           | 1.3-30                   | AutoRegLib-1.3-30.jar                              | None                                     |
       | LCH   | backpacks16840       | 3.5.6                    | backpacks 1.12.2 - 3.5.6.jar                       | None                                     |
       | LCH   | battletowers         | 1.6.5                    | BattleTowers-1.12.2.jar                            | None                                     |
       | LCH   | baublelicious        | 1.4.0-4                  | Baublelicious-1.4.0-4.jar                          | None                                     |
       | LCH   | betteradvancements   | 0.1.0.77                 | BetterAdvancements-1.12.2-0.1.0.77.jar             | None                                     |
       | LCH   | betterbedrockgen     | 6.0.2                    | BetterBedrockGenerator-1.12-6.1.1.jar              | None                                     |
       | LCH   | chesttransporter     | 2.8.8                    | ChestTransporter-1.12.2-2.8.8.jar                  | None                                     |
       | LCE   | codechickenlib       | 3.2.2.353                | CodeChickenLib-1.12.2-3.2.2.353-universal.jar      | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
       | LC    | redstoneflux         | 2.1.0                    | RedstoneFlux-1.12-2.1.0.6-universal.jar            | 8a6abf2cb9e141b866580d369ba6548732eff25f |
       | LC    | cofhcore             | 4.6.3                    | CoFHCore-1.12.2-4.6.3.27-universal.jar             | None                                     |
       | LC    | cofhworld            | 1.3.1                    | CoFHWorld-1.12.2-1.3.1.7-universal.jar             | 8a6abf2cb9e141b866580d369ba6548732eff25f |
       | LC    | crafttweaker         | 4.1.20                   | CraftTweaker2-1.12-4.1.20.562.jar                  | None                                     |
       | LC    | cookingforblockheads | 6.4.70                   | CookingForBlockheads_1.12.2-6.4.70.jar             | None                                     |
       | LC    | craftstudioapi       | 1.0.0                    | CraftStudioAPI-universal-1.0.1.95-mc1.12-alpha.jar | None                                     |
       | LC    | ctgui                | 1.0.0                    | CraftTweaker2-1.12-4.1.20.562.jar                  | None                                     |
       | LC    | crafttweakerjei      | 2.0.3                    | CraftTweaker2-1.12-4.1.20.562.jar                  | None                                     |
       | LC    | creeperconfetti      | 1.4.2                    | creeperconfetti-1.4.2.jar                          | None                                     |
       | LC    | dawnoftime           | 0.1                      | dawnoftime-alpha-1.0.2.jar                         | None                                     |
       | LC    | dimdoors             | 3.0.9+287                | DimensionalDoors-3.0.9-287.jar                     | None                                     |
       | LC    | doggytalents         | 1.15.0.0                 | DoggyTalents-1.12.2-1.15.0.0-universal.jar         | None                                     |
       | LC    | dldungeonsjbg        | 1.12.5                   | DoomlikeDungeons-1.12.5-MC1.12.2.jar               | None                                     |
       | LC    | gottschcore          | 1.7.0                    | GottschCore-mc1.12.2-f14.23.5.2768-v1.7.0.jar      | None                                     |
       | LC    | dungeons2            | 1.7.1                    | Dungeons2-mc1.12.2-f14.23.5.2768-v1.7.1.jar        | None                                     |
       | LC    | dungeontactics       | DT-0.16.5                | DungeonTactics-1.12.2-0.16.5.jar                   | None                                     |
       | LC    | dynamictrees         | 1.12.2-0.9.7             | DynamicTrees-1.12.2-0.9.7.jar                      | None                                     |
       | LC    | ebwizardry           | 4.1.4                    | Electroblob's Wizardry - 4.1.4 - MC 1.12.2.jar     | None                                     |
       | LC    | enchdesc             | 1.1.13                   | EnchantmentDescriptions-1.12.2-1.1.13.jar          | d476d1b22b218a10d845928d1665d45fce301b27 |
       | LC    | minerva              | 1.0.13                   | minerva-library-1.0.13.jar                         | b851b8b7c7f4d8d0e910ff27618150ba80c026ec |
       | LC    | extraalchemy         | 0.5.3                    | extraalchemy-0.5.3.jar                             | b851b8b7c7f4d8d0e910ff27618150ba80c026ec |
       | LC    | extraanvils          | @VERSION@                | extraanvils-0.8b.jar                               | None                                     |
       | LC    | mantle               | 1.12-1.3.3.55            | Mantle-1.12-1.3.3.55.jar                           | None                                     |
       | LC    | twilightforest       | 3.10.1013                | twilightforest-1.12.2-3.10.1013-universal.jar      | None                                     |
       | LC    | tconstruct           | 1.12.2-2.12.0.135        | TConstruct-1.12.2-2.12.0.135.jar                   | None                                     |
       | LC    | extrautils2          | 1.0                      | extrautils2-1.12-1.9.9.jar                         | None                                     |
       | LC    | foamfix              | 0.10.5-1.12.2            | foamfix-0.10.5-1.12.2.jar                          | None                                     |
       | LC    | forestry             | 5.8.2.387                | forestry_1.12.2-5.8.2.387.jar                      | None                                     |
       | LC    | forgelin             | 1.8.2                    | Forgelin-1.8.2.jar                                 | None                                     |
       | LC    | giacomosfoundry      | 1.3.13                   | GiacomosFoundry-1.12.2-1.3.13.jar                  | None                                     |
       | LC    | grapplemod           | 1.12.2-v11.1             | grapplemod-v11.1-1.12.2.jar                        | None                                     |
       | LC    | gravestone           | 1.10.1                   | gravestone-1.10.1.jar                              | None                                     |
       | LC    | hammercore           | 2.0.4.7                  | HammerCore-1.12.2-2.0.4.7.jar                      | 4d7b29cd19124e986da685107d16ce4b49bc0a97 |
       | LC    | heroicarmory         | 1.1.3                    | heroicarmory-1.2.0.jar                             | None                                     |
       | LC    | ichunutil            | 7.2.1                    | iChunUtil-1.12.2-7.2.1.jar                         | 4db5c2bd1b556f252a5b8b54b256d381b2a0a6b8 |
       | LC    | ikwid                | 1.0.2                    | ikwid-1.0.2.jar                                    | None                                     |
       | LC    | improvedbackpacks    | 1.12.2-1.5.0.0           | ImprovedBackpacks-1.12.2-1.5.0.0.jar               | None                                     |
       | LC    | infinitylib          | 1.12.2-1.12.0            | infinitylib-1.12.0.jar                             | None                                     |
       | LC    | inventorypets        | 2.0.1                    | inventorypets-1.12-2.0.1.jar                       | None                                     |
       | LC    | inventorytweaks      | 1.63+release.109.220f184 | InventoryTweaks-1.63.jar                           | 55d2cd4f5f0961410bf7b91ef6c6bf00a766dcbe |
       | LC    | ironbackpacks        | 1.12.2-3.0.8-12          | IronBackpacks-1.12.2-3.0.8-12.jar                  | None                                     |
       | LC    | ironchest            | 1.12.2-7.0.67.844        | ironchest-1.12.2-7.0.67.844.jar                    | None                                     |
       | LC    | jeibees              | 0.9.0.5                  | jeibees-0.9.0.5-mc1.12.2.jar                       | None                                     |
       | LC    | journeymap           | 1.12.2-5.5.4             | journeymap-1.12.2-5.5.4.jar                        | None                                     |
       | LC    | justenoughdimensions | 1.5.5                    | justenoughdimensions-1.12.1-1.5.5.jar              | 2b03e1423915a189b8094816baa18f239d576dff |
       | LC    | jeresources          | 0.8.5.27                 | JustEnoughResources-1.12.2-0.8.5.27.jar            | None                                     |
       | LC    | keywizard            | 1.12.2-1.6               | keywizard-1.12.2-1.6.jar                           | None                                     |
       | LC    | limelib              | 1.7.12                   | limelib-1.12.2-1.7.12.jar                          | None                                     |
       | LC    | livingenchantment    | 3.1.9                    | living_enchantment-3.1.9.jar                       | None                                     |
       | LC    | lunatriuscore        | 1.2.0.42                 | LunatriusCore-1.12.2-1.2.0.42-universal.jar        | None                                     |
       | LC    | magicbees            | 1.0                      | MagicBees-1.12.2-3.1.10.jar                        | None                                     |
       | LC    | radixcore            | 1.12.x-2.2.1             | RadixCore-1.12.x-2.2.1-universal.jar               | None                                     |
       | LC    | mca                  | 1.12.2-5.3.1             | MCA-1.12.x-5.3.1-universal.jar                     | None                                     |
       | LC    | mcjtylib_ng          | 3.5.3                    | mcjtylib-1.12-3.5.3.jar                            | None                                     |
       | LC    | megaloot             | 0.2.30                   | megaloot-1.12.2-0.2.30.jar                         | None                                     |
       | LC    | mjrlegendslib        | 1.12.2-1.1.8             | MJRLegendsLib-1.12.2-1.1.8.jar                     | b02331787272ec3515ebe63ecdeea0d746653468 |
       | LC    | modnametooltip       | 1.10.0                   | modnametooltip_1.12.2-1.10.0.jar                   | None                                     |
       | LC    | multimob             | 1.0.5                    | multimob-1.0.5.jar                                 | None                                     |
       | LC    | neat                 | 1.4-17                   | Neat 1.4-17.jar                                    | None                                     |
       | LC    | yurtmod              | 9.5.2                    | NomadicTents-1.12.2-9.5.2.jar                      | None                                     |
       | LC    | recipehandler        | 0.13                     | NoMoreRecipeConflict-0.13(1.12.2).jar              | None                                     |
       | LC    | openterraingenerator | v8.3                     | OpenTerrainGenerator-1.12.2+-+v8.3.jar             | None                                     |
       | LC    | overpoweredarmorbar  | @VERSION@                | overloadedarmorbar-1.0.4g.jar                      | None                                     |
       | LC    | patchouli            | 1.0-19                   | Patchouli-1.0-19.jar                               | None                                     |
       | LC    | potioncore           | 1.6_for_1.12.2           | PotionCore-1.6_for_1.12.2.jar                      | None                                     |
       | LC    | primitivemobs        | 1.2.3a                   | primitivemobs-1.2.3a.jar                           | None                                     |
       | LC    | pvj                  | 1.6.3                    | ProjectVibrantJourneys-1.12.2-1.6.3.jar            | None                                     |
       | LC    | qualitytools         | 1.0.6_for_1.12.2         | QualityTools-1.0.6_for_1.12.2.jar                  | None                                     |
       | LC    | quarkoddities        | 1                        | QuarkOddities-1.12.2.jar                           | None                                     |
       | LC    | reborncore           | 3.13.12.447              | RebornCore-1.12.2-3.13.12.447-universal.jar        | 8727a3141c8ec7f173b87aa78b9b9807867c4e6b |
       | LC    | refinedstorage       | 1.6.14                   | refinedstorage-1.6.14.jar                          | 57893d5b90a7336e8c63fe1c1e1ce472c3d59578 |
       | LC    | additionalstructures | 2.3.1                    | Rex's-Additional-Structures-1.12.x-(v.2.3.1).jar   | None                                     |
       | LC    | rftools              | 7.71                     | rftools-1.12-7.71.jar                              | None                                     |
       | LC    | rftoolscontrol       | 2.0.2                    | rftoolsctrl-1.12-2.0.2.jar                         | None                                     |
       | LC    | roguelike            | 1.8.0                    | RoguelikeDungeons-1.12.2-1.8.0.jar                 | None                                     |
       | LC    | roughtweaks          | 1.0                      | roughTweaks0.2.4-1.12.2.jar                        | None                                     |
       | LC    | silentlib            | 3.0.13                   | SilentLib-1.12.2-3.0.13+167.jar                    | None                                     |
       | LC    | scalinghealth        | 1.3.36                   | ScalingHealth-1.12.2-1.3.36+140.jar                | None                                     |
       | LC    | storagenetwork       | 1.7.10                   | SimpleStorageNetwork-1.12.2-1.7.10.jar             | None                                     |
       | LC    | skewers              | 1.1                      | Skewers-1.1.jar                                    | None                                     |
       | LC    | slimyboyos           | 1.0.0                    | SlimyBoyos-1.0.0.jar                               | None                                     |
       | LC    | snad                 | 1.12.1-1.7.09.16a        | Snad-1.12.1-1.7.09.16a.jar                         | None                                     |
       | LC    | stg                  | 1.12.2-1.2.3             | stg-1.12.2-1.2.3.jar                               | None                                     |
       | LC    | supersticksword      | v1.0.0.13                | supersticksword-1.0.0.8.jar                        | None                                     |
       | LC    | sync                 | 7.1.0                    | Sync-1.12.2-7.1.0.jar                              | 4db5c2bd1b556f252a5b8b54b256d381b2a0a6b8 |
       | LC    | thermalfoundation    | 2.6.3                    | ThermalFoundation-1.12.2-2.6.3.27-universal.jar    | 8a6abf2cb9e141b866580d369ba6548732eff25f |
       | LC    | thermalexpansion     | 5.5.4                    | ThermalExpansion-1.12.2-5.5.4.43-universal.jar     | 8a6abf2cb9e141b866580d369ba6548732eff25f |
       | LC    | thermalcultivation   | 0.3.6                    | ThermalCultivation-1.12.2-0.3.6.1-universal.jar    | None                                     |
       | LC    | thermaldynamics      | 2.5.5                    | ThermalDynamics-1.12.2-2.5.5.21-universal.jar      | 8a6abf2cb9e141b866580d369ba6548732eff25f |
       | LC    | thermalinnovation    | 0.3.6                    | ThermalInnovation-1.12.2-0.3.6.1-universal.jar     | None                                     |
       | LC    | treasure2            | 1.3.0                    | Treasure2-mc1.12.2-f14.23.5.2768-v1.3.0.jar        | None                                     |
       | LC    | tumbleweed           | 1.11-0.4.5               | tumbleweed-1.11-0.4.5.jar                          | None                                     |
       | LC    | vanillafix           | 1.0.10-SNAPSHOT          | VanillaFix-1.0.10-99.jar                           | None                                     |
       | LC    | walljump             | 1.12.2-1.2.3             | walljump-1.12.2-1.2.3.jar                          | None                                     |
       | LC    | wanionlib            | 1.12.2-2.2               | WanionLib-1.12.2-2.2.jar                           | None                                     |
       | LC    | wawla                | 2.5.273                  | Wawla-1.12.2-2.5.273.jar                           | d476d1b22b218a10d845928d1665d45fce301b27 |
       | LC    | waystones            | 4.0.67                   | Waystones_1.12.2-4.0.67.jar                        | None                                     |
       | LC    | wearablebackpacks    | 3.1.4                    | WearableBackpacks-1.12.2-3.1.4.jar                 | None                                     |
       | LC    | thebetweenlands      | 3.5.9                    | TheBetweenlands-3.5.9-universal.jar                | 38067d6878811efb38b6a045521cfd80b9b60b38 |
       | LC    | midnight             | 0.3.5                    | themidnight-0.3.5.jar                              | None                                     |
       | LC    | unidict              | 1.12.2-2.9.2             | UniDict-1.12.2-2.9.2.jar                           | None                                     |
  Loaded coremods (and transformers): Do not report to Forge! (If you haven't disabled the FoamFix coremod, try disabling it in the config! Note that this bit of text will still appear.) (foamfix-0.10.5-1.12.2.jar)
                                        pl.asie.foamfix.coremod.FoamFixTransformer
                                      AppleCore (AppleCore-mc1.12.2-3.2.0.jar)
                                        squeek.applecore.asm.TransformerModuleHandler
                                      HCASM (HammerCore-1.12.2-2.0.4.7.jar)
                                        com.zeitheron.hammercore.asm.HammerCoreTransformer
                                      midnight (themidnight-0.3.5.jar)
                                        com.mushroom.midnight.core.transformer.MidnightClassTransformer
                                      OTGCorePlugin (OTG-Core.jar)
                                        com.pg85.otg.forge.asm.excluded.OTGClassTransformer
                                      TheBetweenlandsLoadingPlugin (TheBetweenlands-3.5.9-core.jar)
                                        thebetweenlands.core.TheBetweenlandsClassTransformer
                                      CorePlugin (ForgeEndertech-1.12.2-4.4.20.0-build.0354.jar)
                                        
                                      ForgelinPlugin (Forgelin-1.8.2.jar)
                                        
                                      Born in a Barn (Born In A Barn V1.8-1.12-1.1.jar)
                                        com.chocohead.biab.BornInABarn
                                      CTMCorePlugin (CTM-MC1.12.2-0.3.3.22.jar)
                                        team.chisel.ctm.client.asm.CTMTransformer
                                      Quark Plugin (Quark-r1.5-156.jar)
                                        vazkii.quark.base.asm.ClassTransformer
                                      Inventory Tweaks Coremod (InventoryTweaks-1.63.jar)
                                        invtweaks.forge.asm.ContainerTransformer
                                      VanillaFixLoadingPlugin (VanillaFix-1.0.10-99.jar)
                                        
                                      Controllable (controllable-1.12.2-0.8.0.jar)
                                        com.mrcrayfish.controllable.asm.ControllableTransformer
                                      IvToolkit (IvToolkit-1.3.3-1.12.jar)
                                        
                                      BCModPlugin (backpacks 1.12.2 - 3.5.6.jar)
                                        brad16840.core.ClassTransformer
  GL info: ' Vendor: 'Intel' Version: '4.6.0 - Build 26.20.100.6911' Renderer: 'Intel(R) UHD Graphics'
  AE2 Version: stable rv6-stable-6 for Forge 14.23.5.2768
  Pulsar/tconstruct loaded Pulses: - TinkerCommons (Enabled/Forced)
                                   - TinkerWorld (Enabled/Not Forced)
                                   - TinkerTools (Enabled/Not Forced)
                                   - TinkerHarvestTools (Enabled/Forced)
                                   - TinkerMeleeWeapons (Enabled/Forced)
                                   - TinkerRangedWeapons (Enabled/Forced)
                                   - TinkerModifiers (Enabled/Forced)
                                   - TinkerSmeltery (Enabled/Not Forced)
                                   - TinkerGadgets (Enabled/Not Forced)
                                   - TinkerOredict (Enabled/Forced)
                                   - TinkerIntegration (Enabled/Forced)
                                   - TinkerFluids (Enabled/Forced)
                                   - TinkerMaterials (Enabled/Forced)
                                   - TinkerModelRegister (Enabled/Forced)
  Hammer Core Information: FluidDictionary Info: Registered 2 fluids.
                           OreDictionary Info: Registered 171 names; 196 stacks.
                           Pastebin Connection: Okay.
                           Dependent Mods: None.
  Suspected Mods: CodeChicken Lib (codechickenlib)
  Launched Version: 1.12.2-forge1.12.2-14.23.5.2847
  LWJGL: 2.9.4
  OpenGL: Intel(R) UHD Graphics GL version 4.6.0 - Build 26.20.100.6911, Intel
  GL Caps: Using GL 1.3 multitexturing.
           Using GL 1.3 texture combiners.
           Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
           Shaders are available because OpenGL 2.1 is supported.
           VBOs are available because OpenGL 1.5 is supported.
  Using VBOs: No
  Is Modded: Definitely; Client brand changed to 'fml,forge'
  Type: Client (map_client.txt)
  Resource Packs: 
  Current Language: English (US)
  Profiler Position: N/A (disabled)
  CPU: 8x Intel(R) Core(TM) i5-10210U CPU @ 1.60GHz

**Comment by borkedchicken** [comment]
thanks for helping : D

**Comment by covers1624** [comment]
https://github.com/TheCBProject/CodeChickenLib/issues/270

**Comment by borkedchicken** [comment]
hello @covers1624 thank you for re-opening this issue that had already been sorted just to give me the wrong answer. :D it did not work and was not the issue. thank you for not helping :D

**Comment by INEEDHELP12321** [comment]
sasa
