### ISSUE TITLE
Issue Loading Minecraft With CodeChickenLib ( Version - 3.2.3.357 ) 

### ISSUE THREAD

**Issue by MkMlklksdd** [TheCBProject/CodeChickenLib#298]
---- Minecraft Crash Report ----

WARNING: coremods are present:
  ForgelinPlugin (Forgelin-1.8.4.jar)
  EnderCorePlugin (EnderCore-1.12.2-0.5.73-core.jar)
  CTMCorePlugin (CTM-MC1.12.2-1.0.2.31.jar)
Contact their authors BEFORE contacting forge

// There are four lights!

Time: 4/18/20 7:27 PM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from CodeChicken Lib (codechickenlib)
Caused by: codechicken.lib.configuration.ConfigFile$ConfigException: codechicken.lib.configuration.ConfigParseException: Invalid value type d, @Line:20, dump_asm=true
	at codechicken.lib.configuration.ConfigFile.load(ConfigFile.java:61)
	at codechicken.lib.configuration.ConfigFile.<init>(ConfigFile.java:43)
	at codechicken.lib.configuration.ConfigFile.<init>(ConfigFile.java:29)
	at codechicken.lib.configuration.ConfigFile.<init>(ConfigFile.java:19)
	at codechicken.lib.CodeChickenLib.preInit(CodeChickenLib.java:50)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:637)
	at sun.reflect.GeneratedMethodAccessor8.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:136)
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:629)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:252)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:467)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: codechicken.lib.configuration.ConfigParseException: Invalid value type d, @Line:20, dump_asm=true
	at codechicken.lib.configuration.ConfigTag.parseTag(ConfigTag.java:92)
	at codechicken.lib.configuration.ConfigFile.load(ConfigFile.java:59)
	... 44 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 513360328 bytes (489 MB) / 1073741824 bytes (1024 MB) up to 2147483648 bytes (2048 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2847 Optifine OptiFine_1.12.2_HD_U_E3 59 mods loaded, 59 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID                                | Version                  | Source                                        | Signature                                |
	|:----- |:--------------------------------- |:------------------------ |:--------------------------------------------- |:---------------------------------------- |
	| LCH   | minecraft                         | 1.12.2                   | minecraft.jar                                 | None                                     |
	| LCH   | mcp                               | 9.42                     | minecraft.jar                                 | None                                     |
	| LCH   | FML                               | 8.0.99.99                | forge-1.12.2-14.23.5.2847.jar                 | None                                     |
	| LCH   | forge                             | 14.23.5.2847             | forge-1.12.2-14.23.5.2847.jar                 | None                                     |
	| LCH   | blockcraftery                     | 1.12.2-1.3.1             | blockcraftery-1.12.2-1.3.1.jar                | None                                     |
	| LCH   | bonsaitrees                       | 1.1.4                    | bonsaitrees-1.1.4-b170.jar                    | None                                     |
	| LCH   | chameleon                         | 1.12-4.1.3               | Chameleon-1.12-4.1.3.jar                      | None                                     |
	| LCE   | codechickenlib                    | 3.2.3.357                | CodeChickenLib-1.12.2-3.2.3.357-universal.jar | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| LC    | chickenchunks                     | 2.4.2.74                 | ChickenChunks-1.12.2-2.4.2.74-universal.jar   | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| LC    | ctm                               | MC1.12.2-1.0.2.31        | CTM-MC1.12.2-1.0.2.31.jar                     | None                                     |
	| LC    | jei                               | 4.15.0.291               | jei_1.12.2-4.15.0.291.jar                     | None                                     |
	| LC    | chisel                            | MC1.12.2-1.0.2.45        | Chisel-MC1.12.2-1.0.2.45.jar                  | None                                     |
	| LC    | chiselsandbits                    | 14.33                    | chiselsandbits-14.33.jar                      | None                                     |
	| LC    | cucumber                          | 1.1.3                    | Cucumber-1.12.2-1.1.3.jar                     | None                                     |
	| LC    | elevatorid                        | 1.3.14                   | ElevatorMod-1.12.2-1.3.14.jar                 | None                                     |
	| LC    | endercore                         | 1.12.2-0.5.73            | EnderCore-1.12.2-0.5.73.jar                   | None                                     |
	| LC    | enderio                           | 5.1.55                   | EnderIO-1.12.2-5.1.55.jar                     | None                                     |
	| LC    | enderiointegrationtic             | 5.1.55                   | EnderIO-1.12.2-5.1.55.jar                     | None                                     |
	| LC    | enderiobase                       | 5.1.55                   | EnderIO-1.12.2-5.1.55.jar                     | None                                     |
	| LC    | enderioconduits                   | 5.1.55                   | EnderIO-1.12.2-5.1.55.jar                     | None                                     |
	| LC    | enderioconduitsappliedenergistics | 5.1.55                   | EnderIO-1.12.2-5.1.55.jar                     | None                                     |
	| LC    | enderioconduitsopencomputers      | 5.1.55                   | EnderIO-1.12.2-5.1.55.jar                     | None                                     |
	| LC    | refinedstorage                    | 1.6.15                   | refinedstorage-1.6.15.jar                     | 57893d5b90a7336e8c63fe1c1e1ce472c3d59578 |
	| LC    | enderioconduitsrefinedstorage     | 5.1.55                   | EnderIO-1.12.2-5.1.55.jar                     | None                                     |
	| LC    | enderiointegrationforestry        | 5.1.55                   | EnderIO-1.12.2-5.1.55.jar                     | None                                     |
	| LC    | mantle                            | 1.12-1.3.3.55            | Mantle-1.12-1.3.3.55.jar                      | None                                     |
	| LC    | tconstruct                        | 1.12.2-2.13.0.183        | TConstruct-1.12.2-2.13.0.183.jar              | None                                     |
	| LC    | enderiointegrationticlate         | 5.1.55                   | EnderIO-1.12.2-5.1.55.jar                     | None                                     |
	| LC    | enderiomachines                   | 5.1.55                   | EnderIO-1.12.2-5.1.55.jar                     | None                                     |
	| LC    | enderiopowertools                 | 5.1.55                   | EnderIO-1.12.2-5.1.55.jar                     | None                                     |
	| LC    | enderstorage                      | 2.4.6.137                | EnderStorage-1.12.2-2.4.6.137-universal.jar   | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| LC    | forgelin                          | 1.8.4                    | Forgelin-1.8.4.jar                            | None                                     |
	| LC    | exnihilocreatio                   | 1.12.2-0.4.7.2           | exnihilocreatio-1.12.2-0.4.7.2.jar            | None                                     |
	| LC    | excompressum                      | 3.0.31                   | ExCompressum_1.12.2-3.0.31.jar                | None                                     |
	| LC    | extrautils2                       | 1.0                      | extrautils2-1.12-1.9.9.jar                    | None                                     |
	| LC    | zerocore                          | 1.12.2-0.1.2.8           | zerocore-1.12.2-0.1.2.8.jar                   | None                                     |
	| LC    | bigreactors                       | 1.12.2-0.4.5.67          | ExtremeReactors-1.12.2-0.4.5.67.jar           | None                                     |
	| LC    | ironbackpacks                     | 1.12.2-3.0.8-12          | IronBackpacks-1.12.2-3.0.8-12.jar             | None                                     |
	| LC    | ironchest                         | 1.12.2-7.0.67.844        | ironchest-1.12.2-7.0.72.847.jar               | None                                     |
	| LC    | journeymap                        | 1.12.2-5.7.1             | journeymap-1.12.2-5.7.1.jar                   | None                                     |
	| LC    | mcjtylib_ng                       | 3.5.4                    | mcjtylib-1.12-3.5.4.jar                       | None                                     |
	| LC    | mob_grinding_utils                | 0.3.13                   | MobGrindingUtils-0.3.13.jar                   | None                                     |
	| LC    | morpheus                          | 1.12.2-3.5.106           | Morpheus-1.12.2-3.5.106.jar                   | None                                     |
	| LC    | mysticalagriculture               | 1.7.5                    | MysticalAgriculture-1.12.2-1.7.5.jar          | None                                     |
	| LC    | mysticalagradditions              | 1.3.2                    | MysticalAgradditions-1.12.2-1.3.2.jar         | None                                     |
	| LC    | oreexcavation                     | 1.4.150                  | OreExcavation-1.4.150.jar                     | None                                     |
	| LC    | pixelmon                          | 7.2.2                    | Pixelmon-1.12.2-7.2.2-universal.jar           | None                                     |
	| LC    | reborncore                        | 3.19.3.524               | RebornCore-1.12.2-3.19.3.524-universal.jar    | 8727a3141c8ec7f173b87aa78b9b9807867c4e6b |
	| LC    | rebornstorage                     | 1.0.0                    | RebornStorage-1.12.2-3.3.4.1.jar              | None                                     |
	| LC    | redstoneflux                      | 2.1.1                    | RedstoneFlux-1.12-2.1.1.1-universal.jar       | None                                     |
	| LC    | rftools                           | 7.73                     | rftools-1.12-7.73.jar                         | None                                     |
	| LC    | valkyrielib                       | 1.12.2-2.0.20.1          | valkyrielib-1.12.2-2.0.20.1.jar               | None                                     |
	| LC    | simplegenerators                  | 1.12.2-2.0.20.2          | simplegenerators-1.12.2-2.0.20.2.jar          | None                                     |
	| LC    | simplyjetpacks                    | 2.2.14.67                | SimplyJetpacks2-1.12.2-2.2.14.67.jar          | None                                     |
	| LC    | storagedrawers                    | 1.12.2-5.4.1             | StorageDrawers-1.12.2-5.4.1.jar               | None                                     |
	| LC    | tinkertoolleveling                | 1.12.2-1.1.0.DEV.b23e769 | TinkerToolLeveling-1.12.2-1.1.0.jar           | None                                     |
	| LC    | tp                                | 3.2.34                   | tinyprogressions-1.12.2-3.3.34-Release.jar    | None                                     |
	| LC    | universalmodifiers                | 1.12.2-1.0.16.1          | valkyrielib-1.12.2-2.0.20.1.jar               | None                                     |
	| LC    | mysticallib                       | 1.12.2-1.7.0             | mysticallib-1.12.2-1.7.0.jar                  | None                                     |

	Loaded coremods (and transformers): 
ForgelinPlugin (Forgelin-1.8.4.jar)
  
EnderCorePlugin (EnderCore-1.12.2-0.5.73-core.jar)
  com.enderio.core.common.transform.EnderCoreTransformer
  com.enderio.core.common.transform.SimpleMixinPatcher
CTMCorePlugin (CTM-MC1.12.2-1.0.2.31.jar)
  team.chisel.ctm.client.asm.CTMTransformer
	GL info: ' Vendor: 'Intel' Version: '4.6.0 - Build 26.20.100.7323' Renderer: 'Intel(R) UHD Graphics 610'
	Pulsar/tconstruct loaded Pulses: 
		- TinkerCommons (Enabled/Forced)
		- TinkerWorld (Enabled/Not Forced)
		- TinkerTools (Enabled/Not Forced)
		- TinkerHarvestTools (Enabled/Forced)
		- TinkerMeleeWeapons (Enabled/Forced)
		- TinkerRangedWeapons (Enabled/Forced)
		- TinkerModifiers (Enabled/Forced)
		- TinkerSmeltery (Enabled/Not Forced)
		- TinkerGadgets (Enabled/Not Forced)
		- TinkerOredict (Enabled/Forced)
		- TinkerIntegration (Enabled/Forced)
		- TinkerFluids (Enabled/Forced)
		- TinkerMaterials (Enabled/Forced)
		- TinkerModelRegister (Enabled/Forced)
		- chiselIntegration (Enabled/Not Forced)
		- chiselsandbitsIntegration (Enabled/Not Forced)

**Comment by borkedchicken** [comment]
try deleteing the config

**Comment by MkMlklksdd** [comment]
This was the 1st thing I tried, ive also allowed java through my firewall

**Comment by MkMlklksdd** [comment]
It seems to be an issue wirh something else, as i can run it fine in the twitch launcher

**Comment by MineRobber9000** [comment]
#270
