### ISSUE TITLE
Crash on World Load - 1.10.2 Forge Stable Build

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [TheCBProject/CodeChickenLib#30]
https://gist.github.com/P3rf3ctXZer0/b18fc78740c1922b4bf97d9fbbe7c388

**Comment by covers1624** [comment]
Try without optifine. This is not a ccl issue either, Block: pokecube:tradingtable[facing=east,tmc=false] is the broken block, i suspect its a conflict between that mod and optifine.

**Comment by P3rf3ctXZer0** [comment]
Okay no.
