### ISSUE TITLE
CCL has an exeption rendering pretty much ALL blocks forge1.12.2-14.23.5.2854 ccl-2.3.2.358

### ISSUE THREAD

**Issue by velocityraptor-real** [TheCBProject/CodeChickenLib#300]
After changing the forge client config, (force threaded chunk rendering. doesn't matter if from true to false or false to true, just changing it) the whole world won't render.

[CCL_error.txt](https://github.com/TheCBProject/CodeChickenLib/files/4694088/CCL_error.txt)
![2020-05-28_09 48 11](https://user-images.githubusercontent.com/56190563/83114523-54cfda00-a0c9-11ea-8a27-fef19cfcbe46.png)

**Comment by covers1624** [comment]
Optifine breaks a lot of things, and apparently ProjectRed frames are one of those. Remove Optifine and/or report this issue to them.
