### ISSUE TITLE
Using on 1.15.2

### ISSUE THREAD

**Issue by hohserg1** [TheCBProject/CodeChickenLib#301]
My log: https://pastebin.com/33ZFJnWJ
build.gradle: https://pastebin.com/Phps99ru
How to reproduce:
1. setup forge mdk
2. add `compile fileTree("./libs/")` to dependencies to build.gradle
3. refresh Gradle
4. try to runClient

CCL version: CodeChickenLib-1.15.2-3.3.0.373-universal
forge version: net.minecraftforge:forge:1.15.2-31.2.0

**Comment by covers1624** [comment]
You need to use deobf dependencies.
add the following to your repositories block
```
repositories {
    maven { url = "https://maven.covers1624.net/" }
}
```
and add a dependency like so
```
dependencies {
    compile fg.deobf("codechicken:CodeChickenLib:<version>:universal")
}
```

**Comment by hohserg1** [comment]
Thx for quick answer!

**Comment by hohserg1** [comment]
What's different between
http://chickenbones.net/maven/codechicken/CodeChickenLib/
and
https://maven.covers1624.net/codechicken/CodeChickenLib/
?

**Comment by covers1624** [comment]
None, they are the same web server now. `chickenbones.net` can also be used with https now just fyi.
