### ISSUE TITLE
"Ore exists" recipe condition passes even if there are no matching items

### ISSUE THREAD

**Issue by phantamanta44** [TheCBProject/CodeChickenLib#303]
In particular, if a mod registers an ore name without registering any items under that name, the condition will still pass despite this ore ingredient being unsatisfiable.

I propose replacing [the check for ore name existence](https://github.com/TheCBProject/CodeChickenLib/blob/1.12.x/src/main/java/codechicken/lib/recipe/OreExistsConditionalFactory.java#L19) with a check for the existence matching items:
```java
return () -> !OreDictionary.getOres(ore, false).isEmpty();
```

This fixes issues such as phantamanta44/tinkers-evolution#8, where Avaritia uses [an ore-exists recipe condition](https://github.com/Morpheus1101/Avaritia/blob/1.12.2/src/main/resources/assets/avaritia/avaritia_recipes/compressor/flux_singularity.json#L14) to register fluxed electrum singularities despite there being no items matching the `blockElectrumFlux` key.

**Comment by covers1624** [comment]
This has been sitting here a while, but unfortunately, 1.12 hasn't been supported for a really long time.
