### ISSUE TITLE
Crash CodeChicken Lib

### ISSUE THREAD

**Issue by JeansMFJ** [TheCBProject/CodeChickenLib#304]
[crash-2020-07-03_17.05.23-client.txt](https://github.com/TheCBProject/CodeChickenLib/files/4870342/crash-2020-07-03_17.05.23-client.txt)

**Comment by covers1624** [comment]
You clearly didn't look for existing issues or see README tag on the pinned issue.
https://github.com/TheCBProject/CodeChickenLib/issues/270
