### ISSUE TITLE
The game crashed whilst there was a severe problem during mod loading that has caused the game to fail Error: net.minecraftforge.fml.common.LoaderException: java.lang.VerifyError: Expecting a stackmap frame at branch target 17

### ISSUE THREAD

**Issue by oRevive** [TheCBProject/CodeChickenLib#306]
I recently installed some new mods and I get this crash report (Most mods on the report are old and worked perfectly)
---- Minecraft Crash Report ----

WARNING: coremods are present:
  FMLLoadingPlugin (ModCore_Container-1.0.jar)
  OptifinePatcherTweaker (Patcher-1.2 (1.8.9).jar)
  LabyModCoreMod (LabyMod-3.jar)
  PatcherTweaker (Patcher-1.2 (1.8.9).jar)
  FMLLoadingPlugin (Scrollable Tooltips-1.2 (1.8.9).jar)
  SkyblockAddonsLoadingPlugin (SkyblockAddons-1.5.2-for-MC-1.8.9.jar)
  FMLLoadingPlugin (AutoGG-3.4 (1.8.9).jar)
  RenderPlayerAPIPlugin (RenderPlayerAPI-1.8.9-1.0.jar)
  Main (OAM-CosmeticsMod.jar)
  PlayerAPIPlugin (PlayerAPI-1.8.9-1.0.jar)
  FMLLoadingPlugin (Skypixel-0.0.6.jar)
Contact their authors BEFORE contacting forge

// There are four lights!

Time: 7/16/20 10:23 AM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderException: java.lang.VerifyError: Expecting a stackmap frame at branch target 17
Exception Details:
  Location:
    net/minecraft/client/gui/GuiNewChat.func_146230_a(I)V @13: if_acmpne
  Reason:
    Expected stackmap frame at this location.
  Bytecode:
    0x0000000: 2ab4 002b b400 36b4 003c b200 3fa6 0004
    0x0000010: b12a b600 433d 033e 0336 042a b400 29b9
    0x0000020: 0048 0100 3605 2ab4 002b b400 36b4 004c
    0x0000030: 124d 6a12 4e62 3806 1505 9d00 04b1 2ab6
    0x0000040: 0052 9900 0504 3e2a b600 5638 072a b600
    0x0000050: 5986 1707 6eb8 005f 3608 b800 640d 1265
    0x0000060: b200 6a99 0006 126b 660b b800 6f17 0717
    0x0000070: 070c b800 7203 3609 1509 2ab4 0074 602a
    0x0000080: b400 29b9 0048 0100 a200 fe15 091c a200
    0x0000090: f82a b400 2915 092a b400 7460 b900 7802
    0x00000a0: 00c0 007a 3a0a 190a c700 06a7 00d5 1b19
    0x00000b0: 0ab6 007d 6436 0b15 0b11 00c8 a100 071d
    0x00000c0: 9900 c015 0b87 1400 7e6f 390c 0f18 0c67
    0x00000d0: 390c 180c 1400 806b 390c 180c 0e0f b800
    0x00000e0: 8539 0c18 0c18 0c6b 390c 1400 8618 0c6b
    0x00000f0: 8e36 0e1d 9900 0811 00ff 360e 150e 8617
    0x0000100: 066a 8b36 0e84 0401 150e 06a4 0075 0336
    0x0000110: 0f15 0974 1009 6836 1015 0f15 10b2 008a
    0x0000120: 9a00 1d10 0964 150f 1508 6007 6015 10b8
    0x0000130: 008f 150e 6805 6c10 1878 b800 9319 0ab6
    0x0000140: 0097 0315 1010 0964 150e b800 9d19 0ab6
    0x0000150: 0097 b900 a301 003a 11b8 00a6 2ab4 002b
    0x0000160: b400 aa19 1115 0f86 1510 1008 6486 12ab
    0x0000170: 150e 1018 7860 b600 b157 b800 b4b8 00b7
    0x0000180: 8409 01a7 fef5 1d99 0092 2ab4 002b b400
    0x0000190: aab4 00ba 3609 12bb 0b0b b800 6f15 0515
    0x00001a0: 0968 1505 6036 0a15 0415 0968 1504 6036
    0x00001b0: 0b2a b400 7415 0b68 1505 6c36 1215 0b15
    0x00001c0: 0b68 150a 6c36 1315 0a15 0b9f 004e 1512
    0x00001d0: 9e00 0911 00aa a700 0510 6036 0e2a b400
    0x00001e0: bd99 0008 12be a700 0512 bf36 0f03 1512
    0x00001f0: 7405 1512 7415 1364 150f 150e 1018 7860
    0x0000200: b800 9305 1512 7404 1512 7415 1364 12c0
    0x0000210: 150e 1018 7860 b800 93b8 00c3 b1       

	at net.minecraftforge.fml.common.LoadController.transition(LoadController.java:162)
	at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:739)
	at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:310)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:495)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:329)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.VerifyError: Expecting a stackmap frame at branch target 17
Exception Details:
  Location:
    net/minecraft/client/gui/GuiNewChat.func_146230_a(I)V @13: if_acmpne
  Reason:
    Expected stackmap frame at this location.
  Bytecode:
    0x0000000: 2ab4 002b b400 36b4 003c b200 3fa6 0004
    0x0000010: b12a b600 433d 033e 0336 042a b400 29b9
    0x0000020: 0048 0100 3605 2ab4 002b b400 36b4 004c
    0x0000030: 124d 6a12 4e62 3806 1505 9d00 04b1 2ab6
    0x0000040: 0052 9900 0504 3e2a b600 5638 072a b600
    0x0000050: 5986 1707 6eb8 005f 3608 b800 640d 1265
    0x0000060: b200 6a99 0006 126b 660b b800 6f17 0717
    0x0000070: 070c b800 7203 3609 1509 2ab4 0074 602a
    0x0000080: b400 29b9 0048 0100 a200 fe15 091c a200
    0x0000090: f82a b400 2915 092a b400 7460 b900 7802
    0x00000a0: 00c0 007a 3a0a 190a c700 06a7 00d5 1b19
    0x00000b0: 0ab6 007d 6436 0b15 0b11 00c8 a100 071d
    0x00000c0: 9900 c015 0b87 1400 7e6f 390c 0f18 0c67
    0x00000d0: 390c 180c 1400 806b 390c 180c 0e0f b800
    0x00000e0: 8539 0c18 0c18 0c6b 390c 1400 8618 0c6b
    0x00000f0: 8e36 0e1d 9900 0811 00ff 360e 150e 8617
    0x0000100: 066a 8b36 0e84 0401 150e 06a4 0075 0336
    0x0000110: 0f15 0974 1009 6836 1015 0f15 10b2 008a
    0x0000120: 9a00 1d10 0964 150f 1508 6007 6015 10b8
    0x0000130: 008f 150e 6805 6c10 1878 b800 9319 0ab6
    0x0000140: 0097 0315 1010 0964 150e b800 9d19 0ab6
    0x0000150: 0097 b900 a301 003a 11b8 00a6 2ab4 002b
    0x0000160: b400 aa19 1115 0f86 1510 1008 6486 12ab
    0x0000170: 150e 1018 7860 b600 b157 b800 b4b8 00b7
    0x0000180: 8409 01a7 fef5 1d99 0092 2ab4 002b b400
    0x0000190: aab4 00ba 3609 12bb 0b0b b800 6f15 0515
    0x00001a0: 0968 1505 6036 0a15 0415 0968 1504 6036
    0x00001b0: 0b2a b400 7415 0b68 1505 6c36 1215 0b15
    0x00001c0: 0b68 150a 6c36 1315 0a15 0b9f 004e 1512
    0x00001d0: 9e00 0911 00aa a700 0510 6036 0e2a b400
    0x00001e0: bd99 0008 12be a700 0512 bf36 0f03 1512
    0x00001f0: 7405 1512 7415 1364 150f 150e 1018 7860
    0x0000200: b800 9305 1512 7404 1512 7415 1364 12c0
    0x0000210: 150e 1018 7860 b800 93b8 00c3 b1       

	at net.minecraft.client.gui.GuiIngame.<init>(GuiIngame.java:101)
	at net.minecraftforge.client.GuiIngameForge.<init>(GuiIngameForge.java:80)
	at revamp.sidebarmod.gui.GuiSidebarIngame.<init>(GuiSidebarIngame.java:16)
	at revamp.sidebarmod.SidebarMod.init(SidebarMod.java:34)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:560)
	at sun.reflect.GeneratedMethodAccessor2.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:211)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:189)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:118)
	at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:737)
	... 10 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.8.9
	Operating System: Windows 10 (amd64) version 10.0
	CPU: 4x Intel(R) Core(TM) i5-7400 CPU @ 3.00GHz
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1352202640 bytes (1289 MB) / 2067005440 bytes (1971 MB) up to 2067005440 bytes (1971 MB)
	JVM Flags: 26 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx2G -Xms2G -Xmn768m -XX:+DisableExplicitGC -XX:+UseConcMarkSweepGC -XX:+UseParNewGC -XX:+UseNUMA -XX:+CMSParallelRemarkEnabled -XX:MaxTenuringThreshold=15 -XX:MaxGCPauseMillis=30 -XX:GCPauseIntervalMillis=150 -XX:+UseAdaptiveGCBoundary -XX:-UseGCOverheadLimit -XX:+UseBiasedLocking -XX:SurvivorRatio=8 -XX:TargetSurvivorRatio=90 -XX:MaxTenuringThreshold=15 -XX:+UseFastAccessorMethods -XX:+UseCompressedOops -XX:+OptimizeStringConcat -XX:+AggressiveOpts -XX:ReservedCodeCacheSize=2048m -XX:+UseCodeCacheFlushing -XX:SoftRefLRUPolicyMSPerMB=10000 -XX:ParallelGCThreads=10
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.19 Powered by Forge 11.15.1.2318 Optifine OptiFine_1.8.9_HD_U_I3 26 mods loaded, 26 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHI	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHI	FML{8.0.99.99} [Forge Mod Loader] (forge-1.8.9-11.15.1.2318-1.8.9.jar) 
	UCHI	Forge{11.15.1.2318} [Minecraft Forge] (forge-1.8.9-11.15.1.2318-1.8.9.jar) 
	UCHI	oldanimations{2.4.2} [OldAnimationsMod] (minecraft.jar) 
	UCHI	PlayerAPI{1.0} [Player API] (minecraft.jar) 
	UCHI	RenderPlayerAPI{1.0} [Render Player API] (minecraft.jar) 
	UCHI	modcore{0.1.35} [ModCore] (Sk1er Modcore-0.1.35 (1.8.9).jar) 
	UCHI	pownspotionhud{1.0} [pownspotionhud] (1.8.9_Powns_PotionEffect_HUD_-_1.0.jar) 
	UCHI	blockoverlay{2.1} [BlockOverlay] ([1.8.9] BlockOverlay-v2.1.jar) 
	UCHI	keystrokesmod{KMV5} [KeystrokesMod] ([1.8.9] Keystrokes Mod V5 PORT by Seno (OFP).jar) 
	UCHI	pownscoordshud{1.0} [Powns' Coords HUD] ([1.8.9] Powns Coords HUD - 1.0.jar) 
	UCHI	pownstogglesneak{3.0} [pownstogglesneak] ([1.8.9] Powns ToggleSneak - 3.0.jar) 
	UCHE	sidebarmod{2.0} [Sidebar Mod Revamp] ([1.8.9] Sidebar Mod Revamp.jar) 
	UCHI	autogg{3.4} [AutoGG] (AutoGG-3.4 (1.8.9).jar) 
	UCHI	autotip{3.0} [Autotip] (Autotip-3.0 [1.8-1.12.2].jar) 
	UCHI	DiscordRP{1.2.4} [DiscordRP] (DiscordRP-1.2.4.jar) 
	UCHI	labymod{3.6.12} [LabyMod] (LabyMod-3.jar) 
	UCHI	modcore_example_mod{1.0} [ModCore Container Mod] (ModCore_Container-1.0.jar) 
	UCHI	patcher{1.2} [Patcher] (Patcher-1.2 (1.8.9).jar) 
	UCHI	quickplay{2.0.3} [Quickplay] (Quickplay-1.8.9-2.0.3.jar) 
	UCHI	text_overflow_scroll{1.2} [Scrollable Tooltips] (Scrollable Tooltips-1.2 (1.8.9).jar) 
	UCHI	hypixel_auto_complete{1.0} [Hypixel Autocomplete Mod] (Sk1er Hypixel Autocomplete Mod-1.0.jar) 
	UCHI	skyblockaddons{1.5.2} [SkyBlock Addons] (SkyblockAddons-1.5.2-for-MC-1.8.9.jar) 
	UCHI	skypixel{0.0.6} [Skypixel] (Skypixel-0.0.6.jar) 
	UCHI	timechanger{1.0} [TimeChanger] (TimeChanger-1.0 (1.8.9).jar) 
	UCHI	publictogglechat{2.1.0} [§6Hypixel §7-§a ToggleChat] (ToggleChat-2.1.0-SNAPSHOT.jar) 
	Loaded coremods (and transformers): 
FMLLoadingPlugin (ModCore_Container-1.0.jar)
  
OptifinePatcherTweaker (Patcher-1.2 (1.8.9).jar)
  club.sk1er.patcher.tweaker.optifine.OptifineClassTransformer
LabyModCoreMod (LabyMod-3.jar)
  net.labymod.core.asm.LabyModTransformer
PatcherTweaker (Patcher-1.2 (1.8.9).jar)
  club.sk1er.mods.core.forge.ClassTransformer
  club.sk1er.patcher.tweaker.ClassTransformer
FMLLoadingPlugin (Scrollable Tooltips-1.2 (1.8.9).jar)
  club.sk1er.mods.overflowscroll.forge.ClassTransformer
SkyblockAddonsLoadingPlugin (SkyblockAddons-1.5.2-for-MC-1.8.9.jar)
  codes.biscuit.skyblockaddons.tweaker.SkyblockAddonsTransformer
FMLLoadingPlugin (AutoGG-3.4 (1.8.9).jar)
  club.sk1er.mods.core.forge.ClassTransformer
RenderPlayerAPIPlugin (RenderPlayerAPI-1.8.9-1.0.jar)
  api.player.forge.RenderPlayerAPITransformer
Main (OAM-CosmeticsMod.jar)
  com.spiderfrog.main.ClassTransformer
PlayerAPIPlugin (PlayerAPI-1.8.9-1.0.jar)
  api.player.forge.PlayerAPITransformer
FMLLoadingPlugin (Skypixel-0.0.6.jar)
  io.prplz.skypixel.asm.ClassTransformer
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 442.74' Renderer: 'GeForce GTX 1050 Ti/PCIe/SSE2'

**Comment by covers1624** [comment]
I have no idea why you are reporting this to here, this has nothing to do with anything CCL does or touches.
