### ISSUE TITLE
cannot delete the config file

### ISSUE THREAD

**Issue by star-krafter** [TheCBProject/CodeChickenLib#308]
I cannot find the config file you asked to delete and when I delete it the forge loader says the codechickenlib cannot be found.

**Comment by star-krafter** [comment]
also the thing you asked to delete doesn't exist in the configeration file and still comes up with the error

**Comment by star-krafter** [comment]
also when I delete the codechickenlib file which isn't in the configuration file an error comes up saying that codechickenlib doesn't exist in the file

**Comment by star-krafter** [comment]
i tried deleting the config file and it still came up with the error

**Comment by covers1624** [comment]
https://github.com/TheCBProject/CodeChickenLib/issues/270
Whatever launcher you use to launch the game, Twitch, FTBApp, Multimc, there should be a button to open the folder the install resides in, once you have done that, follow the instructions in the issue I linked. If the issue persists after deleting _a_ config file, then you deleted the wrong one.
