### ISSUE TITLE
Using CCL on forge 1.12 latest

### ISSUE THREAD

**Issue by hohserg1** [TheCBProject/CodeChickenLib#309]
When I try to use CCL on forge 1.12.2-14.23.5.2854(latest and recomended version)
And I got such crash:
```
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderException: codechickenlib Failed to load new mod instance.
	at net.minecraftforge.fml.common.FMLModContainer.constructMod(FMLModContainer.java:606)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
```
Full crash: https://gist.github.com/hohserg1/b30e2e79cf54eae28bf830cc252c7bd9

My build.gradle:
```groovy
repositories {
    maven {
        name = "chickenbones"

        url = "https://chickenbones.net/maven" //or https://maven.covers1624.net/
    }
}

dependencies {
    compile "codechicken:CodeChickenLib:1.12.2-3.2.3.358:deobf"
    minecraft 'net.minecraftforge:forge:1.12.2-14.23.5.2854'
```
Full build.gradle: https://gist.github.com/hohserg1/366dda0f6f3bdeda30b0ea697f3ac709

**Comment by covers1624** [comment]
CCL is not compatible with ForgeGradle 3, it does not provide necessary environment variables standard with ForgeGradle 2.

**Comment by hohserg1** [comment]
But adding CCL to forge 1.14 workspace by such way work fine. Why?

**Comment by covers1624** [comment]
Because CCL 1.14 changed to work with FG3, whilst 1.12 has not because it cannot. The 'Latest'  build of Forge 1.12 has no functional changes compared to `14.23.5.2847`, and exists purely as an example of using FG3 for older things. Just use FG2 for 1.12.
