### ISSUE TITLE
Make BlockStateLoader not yell at blocks using ICCBlockRenderer

### ISSUE THREAD

**Issue by Dragon2488** [TheCBProject/CodeChickenLib#31]
Because technically for BlockStateLoader these blocks missing models.

**Comment by covers1624** [comment]
Just register a DummyModel to the inventory and normal ModelResourceLocations, use a StateMap.Builder.ignore to remove all blockstates from the model def and it will default to normal and use the dummy model.

**Comment by covers1624** [comment]
Its technically not possible to do this automatically unless i do some hacky stuff.
