### ISSUE TITLE
CodeChicken crash while Initializing my modpack

### ISSUE THREAD

**Issue by Motelux** [TheCBProject/CodeChickenLib#312]
My minecraft is in 1.12.2 and im using codechicken 3.2.3.358. Idk what is causing this because this crash doesnt happen all the time. So there are moments when i can play. Here is the report:

---- Minecraft Crash Report ----
// Hey, that tickles! Hehehe!

Time: 2020-09-08 10:55:01 COT
Description: Initializing game

java.lang.ExceptionInInitializerError
    at codechicken.lib.CodeChickenLib.<init>(CodeChickenLib.java:44)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
    at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
    at java.lang.reflect.Constructor.newInstance(Unknown Source)
    at java.lang.Class.newInstance(Unknown Source)
    at net.minecraftforge.fml.common.ILanguageAdapter$JavaAdapter.getNewInstance(ILanguageAdapter.java:191)
    at net.minecraftforge.fml.common.FMLModContainer.constructMod(FMLModContainer.java:599)
    at sun.reflect.GeneratedMethodAccessor11.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
    at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
    at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
    at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
    at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
    at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
    at com.google.common.eventbus.EventBus.post(EventBus.java:217)
    at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219)
    at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
    at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
    at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
    at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
    at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
    at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
    at com.google.common.eventbus.EventBus.post(EventBus.java:217)
    at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:136)
    at net.minecraftforge.fml.common.Loader.loadMods(Loader.java:595)
    at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:232)
    at net.minecraft.client.Minecraft.init(Minecraft.java:467)
    at net.minecraft.client.Minecraft.run(Minecraft.java:3931)
    at net.minecraft.client.main.Main.main(SourceFile:123)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.RuntimeException: java.util.ConcurrentModificationException
    at codechicken.lib.reflect.ObfMapping$ObfRemapper.<init>(ObfMapping.java:57)
    at codechicken.lib.reflect.ObfMapping.<clinit>(ObfMapping.java:159)
    ... 43 more
Caused by: java.util.ConcurrentModificationException
    at java.util.HashMap$HashIterator.nextNode(Unknown Source)
    at java.util.HashMap$ValueIterator.next(Unknown Source)
    at codechicken.lib.reflect.ObfMapping$ObfRemapper.<init>(ObfMapping.java:41)
    ... 44 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
  Minecraft Version: 1.12.2
  Operating System: Windows 10 (amd64) version 10.0
  Java Version: 1.8.0_251, Oracle Corporation
  Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
  Memory: 1685036408 bytes (1606 MB) / 2310012928 bytes (2203 MB) up to 5726797824 bytes (5461 MB)
  JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx6144m -XX:MaxPermSize=512m
  IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
  FML: MCP 9.42 Powered by Forge 14.23.5.2847 Optifine OptiFine_1.12.2_HD_U_F5 184 mods loaded, 183 mods active
       States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
       
       | State | ID                                           | Version                     | Source                                             | Signature                                |
       |:----- |:-------------------------------------------- |:--------------------------- |:-------------------------------------------------- |:---------------------------------------- |
       | LC    | minecraft                                    | 1.12.2                      | minecraft.jar                                      | None                                     |
       | LC    | mcp                                          | 9.42                        | minecraft.jar                                      | None                                     |
       | LC    | FML                                          | 8.0.99.99                   | modpack.jar                                        | None                                     |
       | LC    | forge                                        | 14.23.5.2847                | modpack.jar                                        | None                                     |
       | LC    | advancedrocketrycore                         | 1                           | minecraft.jar                                      | None                                     |
       | LC    | creativecoredummy                            | 1.0.0                       | minecraft.jar                                      | None                                     |
       | LC    | otgcore                                      | 1.12.2 - v8.3               | minecraft.jar                                      | None                                     |
       | LC    | com.elytradev.movingworld.common.asm.coremod |                             | minecraft.jar                                      | None                                     |
       | LC    | foamfixcore                                  | 7.7.4                       | minecraft.jar                                      | None                                     |
       | LC    | randompatches                                | 1.12.2-1.21.0.0             | randompatches-1.12.2-1.21.0.0.jar                  | None                                     |
       | LC    | techguns_core                                | 1.12.2-1.0                  | minecraft.jar                                      | None                                     |
       | LC    | crafttweaker                                 | 4.1.20                      | CraftTweaker2-1.12-4.1.20.564.jar                  | None                                     |
       | LC    | mtlib                                        | 3.0.6                       | MTLib-3.0.6.jar                                    | None                                     |
       | LC    | modtweaker                                   | 4.0.18                      | modtweaker-4.0.18.jar                              | None                                     |
       | LC    | jei                                          | 4.15.0.291                  | jei_1.12.2-4.15.0.291.jar                          | None                                     |
       | LC    | abyssalcraft                                 | 1.10.2                      | 10.AbyssalCraft-1.12.2-1.10.2.jar                  | 220f10d3a93b3ff5fbaa7434cc629d863d6751b9 |
       | LC    | backups                                      | 1.5.6                       | 140.Backups-1.12.2-1.5.6 (1).jar                   | None                                     |
       | LC    | travelersbackpack                            | 1.0.34                      | 150.TravelersBackpack-1.12.2-1.0.34.jar            | None                                     |
       | LC    | peruanoscraft                                | 1.0.0                       | 170.PeruanoCraft+1.12.2++V0.5.2.jar                | None                                     |
       | LC    | argentina_food_mod                           | 1.0.0                       | 174.Argentina+Food+Mod+-+1.12.2+V.04 (1).jar       | None                                     |
       | LC    | mcef                                         | 1.11                        | 176.mcef-1.12.2-1.11.jar                           | None                                     |
       | LC    | webdisplays                                  | 1.1                         | 175.webdisplays-1.12.2-1.1 (1).jar                 | None                                     |
       | LC    | modcurrency                                  | 1.12-1.3.11                 | 177.Currency-1.12.0-1.3.11.jar                     | None                                     |
       | LC    | ic2                                          | 2.8.170-ex112               | 178.industrialcraft-2-2.8.170-ex112.jar            | de041f9f6187debbc77034a344134053277aa3b0 |
       | LC    | jeresources                                  | 0.9.2.60                    | 179.JustEnoughResources-1.12.2-0.9.2.60.jar        | None                                     |
       | LC    | architecturecraft                            | @VERSION@                   | 180.architecturecraft-1.12-3.98.jar                | None                                     |
       | LC    | craftpresence                                | v1.7.0                      | 181.CraftPresence-Forge-1.12.2-Beta-1.7.0.jar      | eca02c6a597321ad22340897683951ba5c76720a |
       | LC    | stacksize                                    | 1.1                         | 186.stacksize-1.12.2-1.0.jar                       | None                                     |
       | LC    | securitycraft                                | v1.8.17                     | [1.12.2]+SecurityCraft+v1.8.17.jar                 | None                                     |
       | LC    | bspkrscore                                   | 7.6.0.1                     | [1.12]bspkrsCore-universal-7.6.0.1.jar             | None                                     |
       | LC    | treecapitator                                | 1.43.0                      | [1.12]TreeCapitator-client-1.43.0.jar              | None                                     |
       | LC    | forgeendertech                               | 1.12.2-4.5.2.0              | ForgeEndertech-1.12.2-4.5.2.0-build.0459.jar       | None                                     |
       | LC    | adhooks                                      | 1.12.2-3.2.3.0              | AdHooks-1.12.2-3.2.3.0-build.0435.jar              | None                                     |
       | LC    | tombstone                                    | 3.7.2                       | tombstone-3.7.2-1.12.2.jar                         | None                                     |
       | LC    | advanced-fishing                             | 1.3.3                       | Advanced-Fishing-1.12.2-1.3.3.jar                  | None                                     |
       | LC    | libvulpes                                    | 0.4.2.-75                   | LibVulpes-1.12.2-0.4.2-75-universal.jar            | None                                     |
       | LC    | advancedrocketry                             | 1.7.0.-220                  | AdvancedRocketry-1.12.2-1.7.0-220-universal.jar    | None                                     |
       | LC    | aether_legacy                                | 1.4.4                       | aether_legacy-1.12.2-v1.4.4.jar                    | None                                     |
       | L     | codechickenlib                               | 3.2.3.358                   | CodeChickenLib-1.12.2-3.2.3.358-universal.jar      | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
       | L     | redstoneflux                                 | 2.1.1                       | RedstoneFlux-1.12-2.1.1.1-universal.jar            | None                                     |
       | L     | brandonscore                                 | 2.4.18                      | BrandonsCore-1.12.2-2.4.18.210-universal.jar       | None                                     |
       | L     | draconicevolution                            | 2.3.25                      | Draconic-Evolution-1.12.2-2.3.25.351-universal.jar | None                                     |
       | L     | againstthedragons                            | 1.2                         | againstthedragons1.12.2-1.2.jar                    | None                                     |
       | L     | ambience                                     | GRADLE:VERSION-GRADLE:BUILD | Ambience+1.1-10.jar                                | None                                     |
       | L     | ambientsounds                                | 3.0                         | AmbientSounds_v3.0.12_mc1.12.2.jar                 | None                                     |
       | L     | baubles                                      | 1.5.2                       | Baubles-1.12-1.5.2.jar                             | None                                     |
       | L     | botania                                      | r1.10-363                   | Botania+r1.10-363.jar                              | None                                     |
       | L     | craftstudioapi                               | 1.0.0                       | CraftStudioAPI-universal-1.0.1.95-mc1.12-alpha.jar | None                                     |
       | L     | openterraingenerator                         | v8.3                        | OpenTerrainGenerator-1.12.2+-+v8.3.jar             | None                                     |
       | L     | harvestcraft                                 | 1.12.2zb                    | Pam's+HarvestCraft+1.12.2zg.jar                    | None                                     |
       | L     | ctm                                          | MC1.12.2-1.0.2.31           | CTM-MC1.12.2-1.0.2.31.jar                          | None                                     |
       | L     | twilightforest                               | 3.10.1013                   | twilightforest-1.12.2-3.10.1013-universal.jar      | None                                     |
       | L     | animania                                     | 1.7.3                       | animania-1.12.2-1.7.3.jar                          | None                                     |
       | L     | appleskin                                    | 1.0.9                       | AppleSkin-mc1.12-1.0.9.jar                         | None                                     |
       | L     | aquaculture                                  | 1.6.8                       | Aquaculture-1.12.2-1.6.8.jar                       | None                                     |
       | L     | ebwizardry                                   | 4.2.11                      | ElectroblobsWizardry-4.2.11-MC1.12.2.jar           | None                                     |
       | L     | arcane_essentials                            | 1.0                         | Arcane+Essentials-0.9.2.jar                        | None                                     |
       | L     | astralsorcery                                | 1.10.22                     | astralsorcery-1.12.2-1.10.23.jar                   | None                                     |
       | L     | atum                                         | 2.0.17                      | Atum-1.12.2-2.0.17.jar                             | None                                     |
       | L     | aurora                                       | 1.0.0.8                     | Aurora-1.0.0.8.jar                                 | None                                     |
       | L     | quark                                        | r1.6-178                    | Quark-r1.6-178.jar                                 | None                                     |
       | L     | autoreglib                                   | 1.3-32                      | AutoRegLib-1.3-32.jar                              | None                                     |
       | L     | battletowers                                 | 1.6.5                       | BattleTowers-1.12.2_1.6.5.jar                      | None                                     |
       | L     | bibliocraft                                  | 2.4.5                       | BiblioCraft[v2.4.5][MC1.12.2].jar                  | None                                     |
       | L     | bookshelf                                    | 2.3.590                     | Bookshelf-1.12.2-2.3.590.jar                       | None                                     |
       | L     | bookworm                                     | 1.12.2-2.5.1                | bookworm-1.12.2-2.5.1.jar                          | None                                     |
       | L     | camera                                       | 1.0.9                       | camera-1.0.9.jar                                   | None                                     |
       | L     | cannibalism                                  | 5.6.4                       | Cannibalism-5.6.4-1.12.2.jar                       | None                                     |
       | L     | capsule                                      | 1.12.2-3.3.7                | Capsule-1.12.2-3.3.7.jar                           | None                                     |
       | L     | casinocraft                                  | v06                         | CasinoCraft_1.12.2_v07.jar                         | None                                     |
       | L     | chameleon                                    | 1.12-4.1.3                  | Chameleon-1.12-4.1.3.jar                           | None                                     |
       | L     | chesttransporter                             | 2.8.8                       | ChestTransporter-1.12.2-2.8.8.jar                  | None                                     |
       | L     | chickenchunks                                | 2.4.2.74                    | ChickenChunks-1.12.2-2.4.2.74-universal.jar        | None                                     |
       | L     | chisel                                       | MC1.12.2-1.0.2.45           | Chisel-MC1.12.2-1.0.2.45.jar                       | None                                     |
       | L     | chiselsandbits                               | 14.33                       | chiselsandbits-14.33.jar                           | None                                     |
       | L     | chococraft                                   | 0.9.8.0                     | chococraft_1.12.2-0.9.8.0.jar                      | None                                     |
       | L     | chunkpregenerator                            | 2.1                         | Chunk+Pregenerator+V1.12-2.2.jar                   | None                                     |
       | L     | clothingmodbetav04bytitoo8899                | v.0.4                       | Clothing+Mod+Beta+v.0.4+by+Titoo8899.jar           | None                                     |
       | L     | clumps                                       | 3.1.2                       | Clumps-3.1.2.jar                                   | None                                     |
       | L     | morpheus                                     | 1.12.2-3.5.106              | Morpheus-1.12.2-3.5.106.jar                        | None                                     |
       | L     | comforts                                     | 1.4.1.3                     | comforts-1.12.2-1.4.1.3.jar                        | None                                     |
       | L     | cookingforblockheads                         | 6.5.0                       | CookingForBlockheads_1.12.2-6.5.0.jar              | None                                     |
       | L     | cosmeticarmorreworked                        | 1.12.2-v5a                  | CosmeticArmorReworked-1.12.2-v5a.jar               | None                                     |
       | L     | ctgui                                        | 1.0.0                       | CraftTweaker2-1.12-4.1.20.564.jar                  | None                                     |
       | L     | crafttweakerjei                              | 2.0.3                       | CraftTweaker2-1.12-4.1.20.564.jar                  | None                                     |
       | L     | opframe                                      | 1.4.0                       | OnlinePicFrame_v1.4.37_mc1.12.2.jar                | None                                     |
       | L     | playerrevive                                 | 1.0                         | PlayerRevive_v1.2.32_mc1.12.2.jar                  | None                                     |
       | L     | creativecore                                 | 1.10.0                      | CreativeCore_v1.10.10_mc1.12.2.jar                 | None                                     |
       | L     | culinaryconstruct                            | 1.3.3.2                     | culinaryconstruct-1.3.3.2.jar                      | None                                     |
       | L     | customdisc                                   | 1.3                         | customdisc-1.3.jar                                 | None                                     |
       | L     | custommainmenu                               | 2.0.9.1                     | CustomMainMenu-MC1.12.2-2.0.9.1.jar                | None                                     |
       | L     | customspawner                                | 3.11.4                      | CustomMobSpawner-3.11.4.jar                        | None                                     |
       | L     | customnpcs                                   | 1.12                        | CustomNPCs_1.12.2-(01Oct19) (1).jar                | None                                     |
       | L     | cxlibrary                                    | 1.6.1                       | cxlibrary-1.12.1-1.6.1.jar                         | None                                     |
       | L     | movingworld                                  | 1.12-6.342                  | movingworld-1.12-6.342-full.jar                    | None                                     |
       | L     | davincisvessels                              | @DVESSELSVER@               | davincisvessels-1.12-6.340-full.jar                | None                                     |
       | L     | ptrmodellib                                  | 1.0.4                       | PTRLib-1.0.4.jar                                   | None                                     |
       | L     | props                                        | 2.6.3                       | Decocraft-2.6.3_1.12.2.jar                         | None                                     |
       | L     | mocreatures                                  | 12.0.5                      | DrZharks MoCreatures Mod-12.0.5.jar                | None                                     |
       | L     | elevatorid                                   | 1.3.14                      | ElevatorMod-1.12.2-1.3.14.jar                      | None                                     |
       | L     | mclib                                        | 1.0.4                       | mclib-1.0.4-1.12.2.jar                             | None                                     |
       | L     | emoticons                                    | 0.4.3                       | emoticons-0.4.3-1.12.2-dist.jar                    | None                                     |
       | L     | eplus                                        | 5.0.176                     | EnchantingPlus-1.12.2-5.0.176.jar                  | None                                     |
       | L     | enchdesc                                     | 1.1.15                      | EnchantmentDescriptions-1.12.2-1.1.15.jar          | None                                     |
       | L     | foamflower                                   | 1.12.2-1.0.0.0-beta1        | foamflower-1.12.2-1.0.0.0-beta1.jar                | None                                     |
       | L     | enderpay                                     | 1.12.2-1.0.1.0              | enderpay-1.12.2-1.0.1.0.jar                        | None                                     |
       | L     | minerva                                      | 1.0.13                      | minerva-library-1.0.13.jar                         | None                                     |
       | L     | extraalchemy                                 | 0.5.4                       | extraalchemy-forge-1.12-build11-0.5.4.jar          | None                                     |
       | L     | extra_spells                                 | 1.1.4                       | ExtraSpells-1.12.2-1.1.4.jar                       | None                                     |
       | L     | mantle                                       | 1.12-1.3.3.55               | Mantle-1.12-1.3.3.55.jar                           | None                                     |
       | L     | tconstruct                                   | 1.12.2-2.13.0.183           | TConstruct-1.12.2-2.13.0.183.jar                   | None                                     |
       | L     | extrautils2                                  | 1.0                         | extrautils2-1.12-1.9.9.jar                         | None                                     |
       | L     | fairylights                                  | 2.1.10                      | fairylights-2.1.10-1.12.2.jar                      | None                                     |
       | L     | farfromhome                                  | 1.0                         | Far_From_Home-1.12.2-4.0trial (1).jar              | None                                     |
       | L     | fastbench                                    | 1.7.3                       | FastWorkbench-1.12.2-1.7.3.jar                     | None                                     |
       | L     | fencejumper                                  | 1.0.5                       | fencejumper-1.12-1.0.5.jar                         | None                                     |
       | L     | foamfix                                      | 0.10.10-1.12.2              | foamfix-0.10.10-1.12.2.jar                         | None                                     |
       | L     | llibrary                                     | 1.7.19                      | llibrary-1.7.19-1.12.2.jar                         | None                                     |
       | L     | fossil                                       | 8.0.4                       | fossilsarcheology-8.0.4 (1).jar                    | None                                     |
       | L     | ftblib                                       | 5.4.7.0                     | FTBLib-5.4.7.0.jar                                 | None                                     |
       | L     | ftbutilities                                 | 5.4.0.124                   | FTBUtilities-5.4.0.124.jar                         | None                                     |
       | L     | cfm                                          | 6.3.1                       | furniture-6.3.1-1.12.2.jar                         | None                                     |
       | L     | ichunutil                                    | 7.2.2                       | iChunUtil-1.12.2-7.2.2.jar                         | None                                     |
       | L     | hats                                         | 7.1.0                       | Hats-1.12.2-7.1.0.jar                              | None                                     |
       | L     | waila                                        | 1.8.26                      | Hwyla-1.8.26-B41_1.12.2.jar                        | None                                     |
       | L     | iceandfire                                   | 1.8.4                       | iceandfire-1.8.4.jar                               | None                                     |
       | L     | improvedbackpacks                            | 1.12.2-1.5.0.0              | ImprovedBackpacks-1.12.2-1.5.0.0.jar               | None                                     |
       | L     | incontrol                                    | 3.9.16                      | incontrol-1.12-3.9.16.jar                          | None                                     |
       | L     | inventorysorter                              | 1.13.3+57                   | inventorysorter-1.12.2-1.13.3+57.jar               | None                                     |
       | L     | itlt                                         | 1.0.0                       | itlt-1.12.2-1.0.2.jar                              | None                                     |
       | L     | jojobizadv                                   | 0.5 - 1.12.2                | jojobizadv-2.1.jar                                 | None                                     |
       | L     | journeymap                                   | 1.12.2-5.7.1                | journeymap-1.12.2-5.7.1.jar                        | None                                     |
       | L     | jehc                                         | 1.7.0                       | just-enough-harvestcraft-1.12.2-1.7.0.jar          | None                                     |
       | L     | kineticclearlag                              | 1.4                         | Kinetic+Clear+LagV1.4.jar                          | None                                     |
       | L     | laggoggles                                   | FAT-1.12.2-4.9              | LagGoggles-FAT-1.12.2-4.9.jar                      | None                                     |
       | L     | leatherworks                                 | 1.78.0                      | LeatherWorks-1.12-1.78.0.42.jar                    | None                                     |
       | L     | libraryex                                    | 1.1.2                       | LibraryEx-1.12.2-1.1.2.jar                         | None                                     |
       | L     | millenaire                                   | Millénaire 8.0.1            | millenaire-1.12.2-8.0.1.jar                        | None                                     |
       | L     | mimic                                        | 1.5.0                       | Mimic.jar                                          | None                                     |
       | L     | modernlamps                                  | 1.0.3                       | ModernLights-1.0.3_1.12.jar                        | None                                     |
       | L     | morefurnaces                                 | 1.10.5                      | MoreFurnaces-1.12.2-1.10.6.jar                     | None                                     |
       | L     | moreswordonline                              | 5.5.0                       | MoreSwordOnline+V6.3.9+-+1.12.2.jar                | None                                     |
       | L     | mowziesmobs                                  | 1.5.4                       | mowziesmobs-1.5.4.jar                              | None                                     |
       | L     | netherex                                     | 2.1.3                       | NetherEx-1.12.2-2.1.3.jar                          | None                                     |
       | L     | recipehandler                                | 0.13                        | NoMoreRecipeConflict-0.13(1.12.2).jar              | None                                     |
       | L     | neid                                         | 1.5.4.4                     | NotEnoughIDs-1.5.4.4 (1).jar                       | None                                     |
       | L     | offlineskins                                 | 1.12.2-v5d                  | OfflineSkins-1.12.2-v5d.jar                        | None                                     |
       | L     | patchouli                                    | 1.0-20                      | Patchouli-1.0-20.jar                               | None                                     |
       | L     | potioncore                                   | 1.9_for_1.12.2              | PotionCore-1.9_for_1.12.2.jar                      | None                                     |
       | L     | quickhomes                                   | 1.2.2                       | QuickHomes-1.2.2.jar                               | None                                     |
       | L     | quickteleports                               | 1.1.0                       | quickteleports-1.1.0.jar                           | None                                     |
       | L     | radixcore                                    | 1.12.x-2.2.1                | RadixCore-1.12.x-2.2.1-universal.jar               | None                                     |
       | L     | reforged                                     | 0.7.5                       | Reforged-0.7.5-1.12+.jar                           | None                                     |
       | L     | xreliquary                                   | 1.12.2-1.3.4.796            | Reliquary-1.12.2-1.3.4.796.jar                     | None                                     |
       | L     | resourceloader                               | 1.5.3                       | ResourceLoader-MC1.12.1-1.5.3.jar                  | None                                     |
       | L     | roost                                        | 2.0.10                      | roost-1.12.2-2.0.10.jar                            | None                                     |
       | L     | rustic                                       | 1.1.3                       | rustic-1.1.3.jar                                   | None                                     |
       | L     | storagedrawers                               | 1.12.2-5.4.1                | StorageDrawers-1.12.2-5.4.1.jar                    | None                                     |
       | L     | surge                                        | 2.0.77                      | Surge-1.12.2-2.0.77.jar                            | None                                     |
       | L     | techguns                                     | 2.0.2.0                     | techguns-1.12.2-2.0.2.0_pre3.1.jar                 | None                                     |
       | L     | texfix                                       | 4.0                         | TexFix+V-1.12-4.0.jar                              | None                                     |
       | L     | tfspellpack                                  | 1.0.1                       | TFSpellPack-1.0.1-MC1.12.2.jar                     | None                                     |
       | L     | thutperms                                    | 2.1.12@                     | thutpermissions-1.12.2-2.1.12.jar                  | None                                     |
       | L     | timecore                                     | 1.0.1.1                     | TimeCore-1.12.2-1.0.1.1.jar                        | None                                     |
       | L     | tinkersjei                                   | 1.2                         | tinkersjei-1.2.jar                                 | None                                     |
       | L     | torchmaster                                  | 1.8.1.81                    | torchmaster_1.12.2-1.8.1.81.jar                    | None                                     |
       | L     | traverse                                     | 1.6.0                       | Traverse-1.12.2-1.6.0-69.jar                       | None                                     |
       | L     | ultimate_unicorn_mod                         | 1.5.16                      | ultimate_unicorn_mod-1.12.2-1.5.16 (1).jar         | None                                     |
       | L     | of                                           | 0.13.1                      | Useful+Interior+-+0.13.1+[1.12.2].jar              | None                                     |
       | L     | vanillafix                                   | 1.0.10-SNAPSHOT             | VanillaFix-1.0.10-99.jar                           | None                                     |
       | L     | kiwi                                         | 0.5.3.32                    | Kiwi-1.12.2-0.5.3.32.jar                           | None                                     |
       | L     | cuisine                                      | 0.5.22-build929             | Cuisine-0.5.22-build929.jar                        | None                                     |
       | L     | vanillafoodpantry                            | 4.3.1                       | vanillafoodpantry-mc1.12.2-4.3.1.jar               | None                                     |
       | L     | variedcommodities                            | 1.12.2                      | VariedCommodities_1.12.2(21nov19).jar              | None                                     |
       | L     | vending                                      | 1.12.2-3.0.1.2              | vending-1.12.2-3.0.1.2.jar                         | None                                     |
       | L     | wailaharvestability                          | 1.1.12                      | WailaHarvestability-mc1.12-1.1.12.jar              | None                                     |
       | L     | waystones                                    | 4.1.0                       | Waystones_1.12.2-4.1.0.jar                         | None                                     |
       | L     | worldutils                                   | 0.4.2                       | WWworldutils-1.12.2-0.4.2.jar                      | None                                     |
       | L     | zawa                                         | 1.12.2-2.0.2                | zawa-1.12.2-2.0.2.jar                              | None                                     |
       | L     | candymod                                     | 1.1.5                       | candyworld-1.1.5.jar                               | None                                     |
       | L     | structurize                                  | 1.12.2-0.10.277-RELEASE     | structurize-1.12.2-0.10.277-RELEASE.jar            | None                                     |
       | L     | minecolonies                                 | 1.12.2-0.11.804-RELEASE     | minecolonies-1.12.2-0.11.804-RELEASE-universal.jar | None                                     |
       | L     | thebetweenlands                              | 3.6.0                       | TheBetweenlands-3.6.0-universal.jar                | None                                     |
       | UD    | mclib_core                                   | 1.0.4                       | minecraft.jar                                      | None                                     |
  Loaded coremods (and transformers): AdvancedRocketryPlugin (AdvancedRocketry-1.12.2-1.7.0-220-universal.jar)
                                        zmaster587.advancedRocketry.asm.ClassTransformer
                                      OTGCorePlugin (OTG-Core.jar)
                                        com.pg85.otg.forge.asm.excluded.OTGClassTransformer
                                      AstralCore (astralsorcery-1.12.2-1.10.23.jar)
                                        
                                      CorePlugin (ForgeEndertech-1.12.2-4.5.2.0-build.0459.jar)
                                        
                                      CXLibraryCore (cxlibrary-1.12.1-1.6.1.jar)
                                        cubex2.cxlibrary.CoreModTransformer
                                      CTMCorePlugin (CTM-MC1.12.2-1.0.2.31.jar)
                                        team.chisel.ctm.client.asm.CTMTransformer
                                      McLib core mod (mclib-1.0.4-1.12.2.jar)
                                        mchorse.mclib.core.McLibCMClassTransformer
                                      Techguns Core (techguns-1.12.2-2.0.2.0_pre3.1.jar)
                                        techguns.core.TechgunsASMTransformer
                                      RandomPatches (randompatches-1.12.2-1.21.0.0.jar)
                                        com.therandomlabs.randompatches.core.RPTransformer
                                      llibrary (llibrary-core-1.0.11-1.12.2.jar)
                                        net.ilexiconn.llibrary.server.core.plugin.LLibraryTransformer
                                        net.ilexiconn.llibrary.server.core.patcher.LLibraryRuntimePatcher
                                      Quark Plugin (Quark-r1.6-178.jar)
                                        vazkii.quark.base.asm.ClassTransformer
                                      iceandfire (iceandfire-1.8.4.jar)
                                        com.github.alexthe666.iceandfire.patcher.IceAndFireRuntimePatcher
                                      Plugin (NotEnoughIDs-1.5.4.4 (1).jar)
                                        ru.fewizz.neid.asm.Transformer
                                      VanillaFixLoadingPlugin (VanillaFix-1.0.10-99.jar)
                                        
                                      Do not report to Forge! (If you haven't disabled the FoamFix coremod, try disabling it in the config! Note that this bit of text will still appear.) (foamfix-0.10.10-1.12.2.jar)
                                        pl.asie.foamfix.coremod.FoamFixTransformer
                                      ShutdownPatcher (mcef-1.12.2-1.11-coremod.jar)
                                        net.montoyo.mcef.coremod.ShutdownPatcher
                                      CreativePatchingLoader (CreativeCore_v1.10.10_mc1.12.2.jar)
                                        
                                      LoadingPlugin (ResourceLoader-MC1.12.1-1.5.3.jar)
                                        lumien.resourceloader.asm.ClassTransformer
                                      TheBetweenlandsLoadingPlugin (TheBetweenlands-3.6.0-core.jar)
                                        thebetweenlands.core.TheBetweenlandsClassTransformer
                                      SurgeLoadingPlugin (Surge-1.12.2-2.0.77.jar)
                                        
                                      MovingWorldCore (movingworld-1.12-6.342-full.jar)
                                        
                                      offlineskins (OfflineSkins-1.12.2-v5d-core.jar)
                                        lain.mods.skins.init.forge.asm.ASMTransformer
  GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 442.19' Renderer: 'GeForce GTX 970/PCIe/SSE2'
  Suspected Mods: CodeChicken Lib (codechickenlib)
  Launched Version: 1.12.2-forge1.12.2-14.23.5.2847
  LWJGL: 2.9.4
  OpenGL: GeForce GTX 970/PCIe/SSE2 GL version 4.6.0 NVIDIA 442.19, NVIDIA Corporation
  GL Caps: Using GL 1.3 multitexturing.
           Using GL 1.3 texture combiners.
           Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
           Shaders are available because OpenGL 2.1 is supported.
           VBOs are available because OpenGL 1.5 is supported.
  Using VBOs: Yes
  Is Modded: Definitely; Client brand changed to 'fml,forge'
  Type: Client (map_client.txt)
  Resource Packs: 
  Current Language: Español (España)
  Profiler Position: N/A (disabled)
  CPU: 16x AMD Ryzen 7 2700X Eight-Core Processor

Thanks everyone!

**Comment by covers1624** [comment]
Unfortunately, 1.12 is not supported anymore, and this appears to be a race condition with some internal maps inside forge that CCL reads.
I will note this down for any future 1.12 builds, however.
