### ISSUE TITLE
Crash While Playing (after config file deleted)

### ISSUE THREAD

**Issue by MoodyBlueSkies** [TheCBProject/CodeChickenLib#313]
I have to delete the config file to even play the game. Now it won't even let me join my own modded server if I lag. Now I can't even join because deleting the config file is temporary and I am now worrying that this is permanent.

When VanillaFix was installed (currently not in this crash report) it said that CodeChickenLib1.8+ was stopping Minecraft from launching. I found a temporary solution to delete the config file so Minecraft still runs.

[crash-2020-09-10_13.46.03-client.txt](https://github.com/TheCBProject/CodeChickenLib/files/5201153/crash-2020-09-10_13.46.03-client.txt)

**Comment by covers1624** [comment]
That crash report has nothing to do with CCL, DoubleSlabs is crashing your game when Waila tries to get data from one of its blocks.
