### ISSUE TITLE
How to use IClientPlayNetHandler/IServerPlayNetHandler in packet system

### ISSUE THREAD

**Issue by hohserg1** [TheCBProject/CodeChickenLib#314]
ICustomPacketHandler-s have a parameters of PlayNetHandlers. How to use it?
```java
void handlePacket(PacketCustom packet, Minecraft mc, IClientPlayNetHandler handler);
```
```java
void handlePacket(PacketCustom packet, ServerPlayerEntity sender, IServerPlayNetHandler handler);
```

**Comment by covers1624** [comment]
They are provided for extra context and are basically guaranteed to be their respective implementation classes.
You can use them for whatever you want, what are you trying to accomplish?
