### ISSUE TITLE
hello i have one problem look for my logs and try help me... 

### ISSUE THREAD

**Issue by halk6000** [TheCBProject/CodeChickenLib#316]
---- Minecraft Crash Report ----

WARNING: coremods are present:
  llibrary (llibrary-core-1.0.11-1.12.2.jar)
  LoadingPlugin (Blood-Moon-Mod-1.12.2.jar)
  MekanismCoremod (Mekanism-Mod-Core-1.12.2.jar)
  EnderCorePlugin (EnderCore-1.12.2-0.5.69-core.jar)
  ForgelinPlugin (Shadowfacts-Forgelin-1.12.2.jar)
  CorePlugin (ForgeEndertech-1.12.2-4.5.4.0-build.0534.jar)
Contact their authors BEFORE contacting forge

// I bet Cylons wouldn't have this problem.

Time: 10/31/20 1:49 PM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from CodeChicken Lib (codechickenlib)
Caused by: codechicken.lib.configuration.ConfigFile$ConfigException: codechicken.lib.configuration.ConfigParseException: Invalid value type d, @Line:20, dump_asm=true
	at codechicken.lib.configuration.ConfigFile.load(ConfigFile.java:61)
	at codechicken.lib.configuration.ConfigFile.<init>(ConfigFile.java:43)
	at codechicken.lib.configuration.ConfigFile.<init>(ConfigFile.java:29)
	at codechicken.lib.configuration.ConfigFile.<init>(ConfigFile.java:19)
	at codechicken.lib.CodeChickenLib.preInit(CodeChickenLib.java:50)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:637)
	at sun.reflect.GeneratedMethodAccessor8.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:136)
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:629)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:252)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:467)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: codechicken.lib.configuration.ConfigParseException: Invalid value type d, @Line:20, dump_asm=true
	at codechicken.lib.configuration.ConfigTag.parseTag(ConfigTag.java:92)
	at codechicken.lib.configuration.ConfigFile.load(ConfigFile.java:59)
	... 44 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 7 (amd64) version 6.1
	Java Version: 1.8.0_271, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 252046336 bytes (240 MB) / 865492992 bytes (825 MB) up to 5355339776 bytes (5107 MB)
	JVM Flags: 6 total; -Xmx5G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2854 56 mods loaded, 56 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID                                | Version           | Source                                         | Signature                                |
	|:----- |:--------------------------------- |:----------------- |:---------------------------------------------- |:---------------------------------------- |
	| LCH   | minecraft                         | 1.12.2            | minecraft.jar                                  | None                                     |
	| LCH   | mcp                               | 9.42              | minecraft.jar                                  | None                                     |
	| LCH   | FML                               | 8.0.99.99         | forge-1.12.2-14.23.5.2854.jar                  | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCH   | forge                             | 14.23.5.2854      | forge-1.12.2-14.23.5.2854.jar                  | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCH   | bspkrscore                        | 7.6.0.1           | [1.12]bspkrsCore-universal-7.6.0.1.jar         | None                                     |
	| LCH   | abyssalcraft                      | 1.9.4.14          | AbyssalCraft-1.12.2-1.9.4.14.jar               | 220f10d3a93b3ff5fbaa7434cc629d863d6751b9 |
	| LCH   | appliedenergistics2               | rv6-beta-1        | appliedenergistics2-rv6-beta-1.jar             | dfa4d3ac143316c6f32aa1a1beda1e34d42132e5 |
	| LCH   | babymobs                          | 1.5.5             | Baby-Mobs-Mod-1.12.2.jar                       | None                                     |
	| LCH   | backpack                          | 3.0.2             | backpack-3.0.2-1.12.2.jar                      | None                                     |
	| LCH   | baubles                           | 1.5.2             | Baubles-1.12-1.5.2.jar                         | None                                     |
	| LCH   | bettercreaturesreforged           | 1.0.0             | Better-Creatures-Mod-1.12.2.jar                | None                                     |
	| LCH   | bloodmoon                         | 1.5.3             | Blood-Moon-Mod-1.12.2.jar                      | d72e0dd57935b3e9476212aea0c0df352dd76291 |
	| LCH   | thaumcraft                        | 6.1.BETA26        | Thaumcraft-Mod-1.12.2.jar                      | None                                     |
	| LCH   | botania                           | r1.10-361         | Botania+r1.10-361.jar                          | None                                     |
	| LCH   | llibrary                          | 1.7.19            | llibrary-1.7.19-1.12.2.jar                     | b9f30a813bee3b9dd5652c460310cfcd54f6b7ec |
	| LCH   | cqrepoured                        | 1.21.9A           | Chocolate-Quest-Repoured-1.12.2-1.21.9A.jar    | None                                     |
	| LCE   | codechickenlib                    | 3.2.2.353         | CodeChickenLib-1.12.2-3.2.2.353-universal.jar  | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| LC    | redstoneflux                      | 2.1.1             | Redstone-Flux-API-1.12.2.jar                   | None                                     |
	| LC    | cofhcore                          | 4.6.6             | CoFHCore-1.12.2-4.6.6.1-universal.jar          | None                                     |
	| LC    | cofhworld                         | 1.4.0             | CoFHWorld-1.12.2-1.4.0.1-universal.jar         | None                                     |
	| LC    | dmonsters                         | 1.7               | Deadly+Monsters+1.71.jar                       | None                                     |
	| LC    | doggytalents                      | 1.15.1.4          | DoggyTalents-1.12.2-1.15.1.4-universal.jar     | None                                     |
	| LC    | dynamictrees                      | 1.12.2-0.9.5      | Dynamic-Trees-Mod-1.12.2.jar                   | None                                     |
	| LC    | endercore                         | 1.12.2-0.5.69     | EnderCore-1.12.2.jar                           | None                                     |
	| LC    | thermalfoundation                 | 2.6.7             | ThermalFoundation-1.12.2-2.6.7.1-universal.jar | None                                     |
	| LC    | thermalexpansion                  | 5.5.4             | Thermal-Expansion-Mod-1.12.2.jar               | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| LC    | enderio                           | 5.1.51            | Ender-IO-Mod-1.12.2.jar                        | None                                     |
	| LC    | enderiointegrationtic             | 5.1.51            | Ender-IO-Mod-1.12.2.jar                        | None                                     |
	| LC    | enderiobase                       | 5.1.51            | Ender-IO-Mod-1.12.2.jar                        | None                                     |
	| LC    | enderioconduits                   | 5.1.51            | Ender-IO-Mod-1.12.2.jar                        | None                                     |
	| LC    | enderioconduitsappliedenergistics | 5.1.51            | Ender-IO-Mod-1.12.2.jar                        | None                                     |
	| LC    | enderioconduitsopencomputers      | 5.1.51            | Ender-IO-Mod-1.12.2.jar                        | None                                     |
	| LC    | enderioconduitsrefinedstorage     | 5.1.51            | Ender-IO-Mod-1.12.2.jar                        | None                                     |
	| LC    | forestry                          | 5.8.2.408         | Forestry-Mod-1.12.2.jar                        | None                                     |
	| LC    | enderiointegrationforestry        | 5.1.51            | Ender-IO-Mod-1.12.2.jar                        | None                                     |
	| LC    | enderiointegrationticlate         | 5.1.51            | Ender-IO-Mod-1.12.2.jar                        | None                                     |
	| LC    | enderiomachines                   | 5.1.51            | Ender-IO-Mod-1.12.2.jar                        | None                                     |
	| LC    | enderiopowertools                 | 5.1.51            | Ender-IO-Mod-1.12.2.jar                        | None                                     |
	| LC    | gravestone                        | 1.10.2            | EuhDawsons-GraveStone-Mod-1.12.2.jar           | None                                     |
	| LC    | forgeendertech                    | 1.12.2-4.5.4.0    | ForgeEndertech-1.12.2-4.5.4.0-build.0534.jar   | None                                     |
	| LC    | mekanism                          | 1.12.2-9.8.3.390  | Mekanism-Mod-Core-1.12.2.jar                   | None                                     |
	| LC    | forgelin                          | 1.8.4             | Shadowfacts-Forgelin-1.12.2.jar                | None                                     |
	| LC    | tesla                             | 1.0.63            | Tesla-API-1.12.2.jar                           | d476d1b22b218a10d845928d1665d45fce301b27 |
	| LC    | teslacorelib                      | 1.0.15            | Tesla-Core-Lib-1.12.2.jar                      | d476d1b22b218a10d845928d1665d45fce301b27 |
	| LC    | industrialforegoing               | 1.12.2-1.12.2     | industrialforegoing-1.12.2-1.12.13-237.jar     | None                                     |
	| LC    | infernalmobs                      | 1.7.5             | InfernalMobs-1.12.2.jar                        | None                                     |
	| LC    | ironchest                         | 1.12.2-7.0.67.844 | ironchest-1.12.2-7.0.67.844.jar                | None                                     |
	| LC    | magicbees                         | 1.0               | Magic-Bees-Mod-1.12.2.jar                      | None                                     |
	| LC    | mca                               | 6.1.0             | MCA-1.12.2-6.1.0-universal.jar                 | None                                     |
	| LC    | mekanismgenerators                | 1.12.2-9.8.3.390  | Mekanism-Mod-Generators-1.12.2.jar             | None                                     |
	| LC    | mekanismtools                     | 1.12.2-9.8.3.390  | Mekanism-Mod-Tools-1.12.2.jar                  | None                                     |
	| LC    | mocreatures                       | 12.0.5            | Mo-Creatures-Mod-1.12.2.jar                    | None                                     |
	| LC    | pixelmon                          | 8.1.2             | Pixelmon-1.12.2-8.1.2-universal.jar            | None                                     |
	| LC    | trapcraft                         | v2.4.3a           | Trapcraft-1.12-v2.4.3a-universal.jar           | None                                     |
	| LC    | treecapitator                     | 1.43.0            | TreeCapitator-Mod-1.12.2.jar                   | None                                     |
	| LC    | teslacorelib_registries           | 1.0.15            | Tesla-Core-Lib-1.12.2.jar                      | None                                     |

	Loaded coremods (and transformers): 
llibrary (llibrary-core-1.0.11-1.12.2.jar)
  net.ilexiconn.llibrary.server.core.plugin.LLibraryTransformer
  net.ilexiconn.llibrary.server.core.patcher.LLibraryRuntimePatcher
LoadingPlugin (Blood-Moon-Mod-1.12.2.jar)
  lumien.bloodmoon.asm.ClassTransformer
MekanismCoremod (Mekanism-Mod-Core-1.12.2.jar)
  mekanism.coremod.KeybindingMigrationHelper
EnderCorePlugin (EnderCore-1.12.2-0.5.69-core.jar)
  com.enderio.core.common.transform.EnderCoreTransformer
  com.enderio.core.common.transform.SimpleMixinPatcher
ForgelinPlugin (Shadowfacts-Forgelin-1.12.2.jar)
  
CorePlugin (ForgeEndertech-1.12.2-4.5.4.0-build.0534.jar)
  
	GL info: ' Vendor: 'ATI Technologies Inc.' Version: '4.5.13469 Compatibility Profile Context 21.19.519.2' Renderer: 'AMD Radeon R7 250 Series'
	AE2 Version: beta rv6-beta-1 for Forge 14.23.3.2655

**Comment by covers1624** [comment]
#270
