### ISSUE TITLE
Publishing CCL at maven central

### ISSUE THREAD

**Issue by hohserg1** [TheCBProject/CodeChickenLib#317]
How about publishing CCL jars at maven central?
Benefits is simplest addition a dependency to projects

**Comment by covers1624** [comment]
Not gonna happen sorry, it's as simple as adding a singular line to your build script as can be seen [here](https://github.com/TheCBProject/EnderStorage/blob/master/build.gradle#L76).

Artifacts being published to my maven are an integral part of the build process and are used/scanned on the file system for several operations during the build process. In addition, I have the ability to demote builds from Jenkins, removing them from the maven completely, there are likely endpoints for maven central for this but I'm not interested in the extra development time to implement these when the current system works just fine as is.

**Comment by hohserg1** [comment]
I can help you with setup gradle for maven publication and with obtaining sonatype staging profile. 
Do I get it right that you use `gradle publish` command for build and upload jars to maven.covers1624.net?
