### ISSUE TITLE
Stoneblock 2 Crash - 3 Potential Causes

### ISSUE THREAD

**Issue by Phoenic1** [TheCBProject/CodeChickenLib#318]
[crash-2020-11-03_16.23.31-client.txt](https://github.com/TheCBProject/CodeChickenLib/files/5484473/crash-2020-11-03_16.23.31-client.txt)
VanillaFix says that this could be caused by Extra Utilities 2, Code Chicken Lib, or YABBA. I am sending this to all three.

**Comment by covers1624** [comment]
Not an issue with CCL, Yabba is trying to render the item for an ExtraUtilities block, however it's crashing.
