### ISSUE TITLE
Game crash upon Teleport 

### ISSUE THREAD

**Issue by jakob601** [TheCBProject/CodeChickenLib#319]
Description: When i return from an rftools Dimension using a transmitter/receiver set up the game crashes, usually when potion effects like nightvision are present. Rftolls author told me that the Problem seems to be from this mod.

Steps to reproduce: enter Dimension like end or custom dimension, return to overworld with Effect like nightvision from EnderIO or mystical agriculture armor present, game crashes

Logs: 
[crash-2020-11-03_20.44.33-server.txt](https://github.com/TheCBProject/CodeChickenLib/files/5485723/crash-2020-11-03_20.44.33-server.txt)
[2020-11-03-7.log.gz](https://github.com/TheCBProject/CodeChickenLib/files/5485724/2020-11-03-7.log.gz)

**Comment by covers1624** [comment]
Unfortunately 1.12 is no longer supported as im actively developing for 1.15+
