### ISSUE TITLE
Game hangs due to a CCL model not being rendered hanging the whole frame instead of just skipping the model

### ISSUE THREAD

**Issue by Snivine** [TheCBProject/CodeChickenLib#322]
So I don't know where to post this issue since the log doesn't provide any info about which mod caused the CCL model to not work properly so here it goes

Basically the mod instead of just crashing the game/skipping the frame it just hangs the whole game forcing the user to manually kill the process

here's the log if you need it in case you can find something useful

(also includes my mod list and hardware but I think you don't need the second one)

https://paste.ee/p/Udg8l

**Comment by covers1624** [comment]
Unfortunately, that's out of my control, someone didn't properly handle the model, and CCL returned the standard missing model, there's no more information available sadly. ThermalExpansion and ProjectRed are the only mods that _i_ know of that use the CCL Baked model system.
