### ISSUE TITLE
where do I delete config/codechickenlib.cfg from 

### ISSUE THREAD

**Issue by oisinos** [TheCBProject/CodeChickenLib#324]
I searched through mod file but cant find it. I am using the universal mod not debof. 
[crash-2020-11-25_00.03.49-client.txt](https://github.com/TheCBProject/CodeChickenLib/files/5593517/crash-2020-11-25_00.03.49-client.txt)

**Comment by oisinos** [comment]
(from the config issue)

**Comment by covers1624** [comment]
You will need to navigate to your config folder, depending on what launcher you are using(Vanilla launcher, Twitch, MultiMC, etc), it should be fairly easy to find some online resources on finding your config folder.

**Comment by oisinos** [comment]
thank you
