### ISSUE TITLE
CCL for 1.7.10 not exists in repo

### ISSUE THREAD

**Issue by hohserg1** [TheCBProject/CodeChickenLib#326]
I tried to add CCL 1.7.10 to my project through repositories `https://chickenbones.net/maven` or `https://maven.covers1624.net`.
But there's no CCL for this version of Minecraft. I solved adding CCL to project by loading CodeChickenCore 1.7.10 from Curse and adding to mods. CodeChickenCore downloaded  CCL 1.7.10 dev version.
Can you add CCL 1.7.10 to regular repo to make adding CCL 1.7.10 easier? I understand that 1.7.10 is not supported, but it is only adding existed version to repo, it doesn't require special support. Thanks!

**Comment by covers1624** [comment]
Prior to 1.8, CCL exists on Forge's maven, however, it's not indexed, I intend to merge it in with the existing maven when I find the time. The latest version of CCL available for 1.7 is `1.7.10-1.1.3.140`, you will not have to add any additional repositories in Gradle as Forge's maven is already provided by their gradle plugin.
