### ISSUE TITLE
Crash when attempting to pre-initialise CodeChicken Lib in 1.12.2

### ISSUE THREAD

**Issue by TheRetrodragon** [TheCBProject/CodeChickenLib#328]
This just started happening today. The game ran perfectly fine yesterday. No new mods have been installed since. I have already tried deleting the config but have the same error.

---- Minecraft Crash Report ----

WARNING: coremods are present:
  McLib core mod (mclib-2.1-1.12.2.jar)
  ForgelinPlugin (Forgelin-1.8.4.jar)
  midnight (themidnight-0.3.5.jar)
  OTGCorePlugin (OTG-Core.jar)
  CorePlugin (ForgeEndertech-1.12.2-4.5.4.0-build.0534.jar)
Contact their authors BEFORE contacting forge

// Uh... Did I do that?

Time: 12/16/20 8:05 PM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from CodeChicken Lib (codechickenlib)
Caused by: java.lang.NoSuchMethodError: net.minecraft.client.Minecraft.getMinecraft()Lnet/minecraft/client/Minecraft;
	at codechicken.lib.util.ResourceUtils.getResourceManager(ResourceUtils.java:35)
	at codechicken.lib.util.ResourceUtils.registerReloadListener(ResourceUtils.java:67)
	at codechicken.lib.render.particle.CustomParticleHandler.init(CustomParticleHandler.java:271)
	at codechicken.lib.internal.proxy.ProxyClient.preInit(ProxyClient.java:58)
	at codechicken.lib.CodeChickenLib.preInit(CodeChickenLib.java:52)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:637)
	at sun.reflect.GeneratedMethodAccessor9.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:136)
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:629)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:252)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:467)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 473018648 bytes (451 MB) / 1073741824 bytes (1024 MB) up to 4294967296 bytes (4096 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx4G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2854 Optifine OptiFine_1.12.2_HD_U_F5 61 mods loaded, 60 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID                    | Version           | Source                                           | Signature                                |
	|:----- |:--------------------- |:----------------- |:------------------------------------------------ |:---------------------------------------- |
	| LCH   | minecraft             | 1.12.2            | minecraft.jar                                    | None                                     |
	| LCH   | mcp                   | 9.42              | minecraft.jar                                    | None                                     |
	| LCH   | FML                   | 8.0.99.99         | forge-1.12.2-14.23.5.2854.jar                    | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCH   | forge                 | 14.23.5.2854      | forge-1.12.2-14.23.5.2854.jar                    | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCH   | otgcore               | 1.12.2 - v8.3     | minecraft.jar                                    | None                                     |
	| LCH   | netherbackport        | 1.0.0             | 0.0.5a-releasecandidate1.jar                     | None                                     |
	| LCH   | animalnet             | v1.12.2 b1        | animalnet-v1.12.2+b1.jar                         | None                                     |
	| LCH   | mmdlib                | 1.0.0-rc2         | MMDLib-1.12-1.0.0-rc2.36.jar                     | None                                     |
	| LCH   | basemetals            | 2.5.0-rc2         | BaseMetals-1.12-2.5.0-rc2.332(1).jar             | d476d1b22b218a10d845928d1665d45fce301b27 |
	| LCH   | bibliocraft           | 2.4.5             | BiblioCraft[v2.4.5][MC1.12.2].jar                | None                                     |
	| LCH   | blockarmor            | 2.4.12            | BlockArmor-1.12.2-2.4.12.jar                     | None                                     |
	| LCH   | chameleon             | 1.12-4.1.3        | Chameleon-1.12-4.1.3.jar                         | None                                     |
	| LCH   | chunkpregenerator     | 2.1               | Chunk+Pregenerator+V1.12-2.4E.jar                | None                                     |
	| LCE   | codechickenlib        | 3.2.3.358         | CodeChickenLib-1.12.2-3.2.3.358-deobf.jar        | None                                     |
	| LC    | cosmeticarmorreworked | 1.12.2-v5a        | CosmeticArmorReworked-1.12.2-v5a.jar             | aaaf83332a11df02406e9f266b1b65c1306f0f76 |
	| LC    | damageindicatorsmod   | 1.0               | Damage-Indicators-Mod-1.12.2.jar                 | None                                     |
	| LC    | dimdoors              | 3.0.9+287         | DimensionalDoors-3.0.9-287.jar                   | None                                     |
	| LC    | divinerpg             | 1.7.1             | DivineRPG-1.7.1.jar                              | None                                     |
	| LC    | openterraingenerator  | v8.3              | OpenTerrainGenerator-1.12.2+-+v8.3.jar           | None                                     |
	| LC    | dregora               | 1.0               | Dregora-1.12.2-v1.66.2.jar                       | None                                     |
	| LC    | endmetals             | 1.2.0-rc2         | EndMetals-1.12-1.2.0-rc2.67(1).jar               | d476d1b22b218a10d845928d1665d45fce301b27 |
	| LC    | endreborn             | 0.3.8             | EndReborn+[0.3.9].jar                            | None                                     |
	| LC    | forgeendertech        | 1.12.2-4.5.4.0    | ForgeEndertech-1.12.2-4.5.4.0-build.0534.jar     | None                                     |
	| LC    | forgelin              | 1.8.4             | Forgelin-1.8.4.jar                               | None                                     |
	| LC    | gemsplusplus          | 1.12.2-V7.0.4     | gemsplusplus-1.12.2-7.0.4.jar                    | None                                     |
	| LC    | geneticsreborn        | 1.28              | geneticsreborn-1.12-1.29.jar                     | None                                     |
	| LC    | ichunutil             | 7.2.2             | iChunUtil-1.12.2-7.2.2.jar                       | 4db5c2bd1b556f252a5b8b54b256d381b2a0a6b8 |
	| LC    | infeatures            | alpha1.4          | infeatures-alpha1.4.jar                          | None                                     |
	| LC    | ironchest             | 1.12.2-7.0.67.844 | ironchest-1.12.2-7.0.72.847.jar                  | None                                     |
	| LC    | jei                   | 4.15.0.291        | jei_1.12.2-4.15.0.291.jar                        | None                                     |
	| LC    | kk                    | 1.1.0.2           | Kingdom+Keys+Re+Coded-1.12.2-1.1.0.2-3087b93.jar | None                                     |
	| LC    | labyrinth             | ${version}        | Labyrinth-1.12.2-1.0.jar                         | None                                     |
	| LC    | mclib                 | 2.1               | mclib-2.1-1.12.2.jar                             | None                                     |
	| LC    | metamorph             | 1.2.3             | metamorph-1.2.3-1.12.2.jar                       | None                                     |
	| LC    | moreapples            | [1.12.2]          | moreapples2.2.1A.jar                             | None                                     |
	| LC    | mo_swords             | v5                | moSwords-1.12.2v5.jar                            | None                                     |
	| LC    | uteamcore             | 2.2.5.147         | u_team_core-1.12.2-2.2.5.147.jar                 | None                                     |
	| LC    | musicplayer           | 2.1.1.92          | music_player-1.12.2-2.1.1.92.jar                 | None                                     |
	| LC    | mmm                   | 1.0.8             | mutatedmobs-1.0.8.jar                            | None                                     |
	| LC    | mystcraft             | 0.13.7.06         | mystcraft-1.12.2-0.13.7.06.jar                   | None                                     |
	| LC    | nethermetals          | 1.2.0-rc2         | NetherMetals-1.12-1.2.0-rc2.76(1).jar            | d476d1b22b218a10d845928d1665d45fce301b27 |
	| LC    | nei                   | 2.4.3             | NotEnoughItems-1.12.2-2.4.3.245-universal.jar    | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| LC    | orespawn              | 3.3.1             | OreSpawn-1.12-3.3.1.179(1).jar                   | d476d1b22b218a10d845928d1665d45fce301b27 |
	| LC    | maats_plank_mod       | 1.4.1             | Planks_Mod-1.4.1.jar                             | None                                     |
	| LC    | poormetals            | 1.3.1             | Poor+Metals-1.3.1.jar                            | None                                     |
	| LC    | projecte              | 1.12.2-PE1.4.1    | ProjectE-1.12.2-PE1.4.1.jar                      | None                                     |
	| LC    | randores              | 2a9               | Randores-2.0.0-Pre3.jar                          | None                                     |
	| LC    | roguelike             | 1.8.0             | RoguelikeDungeons-1.12.2-1.8.0.jar               | None                                     |
	| LC    | storagenetwork        | 1.7.11            | SimpleStorageNetwork-1.12.2-1.7.11.jar           | 0e5cb559be7d03f3fc18b8cba547d663e25f28af |
	| LC    | simplygems            | 1.1.3             | simplygems-1.1.3.jar                             | None                                     |
	| LC    | mopickaxes            | 10.0: Final BETA  | Soletare's Mo' Pickaxes 10.0 Final BETA.jar      | None                                     |
	| LC    | storagedrawers        | 5.2.2             | StorageDrawers-1.12.2-5.4.2.jar                  | None                                     |
	| LC    | subcommonlib          | 1.2.0.1           | subcommonlib-sublib-1.12.2-1.2.0.4.jar           | None                                     |
	| LC    | telepads              | $version          | telepads-1.12.2-1.1.0.7.jar                      | None                                     |
	| LC    | twilightforest        | 3.10.1013         | twilightforest-1.12.2-3.10.1013-universal.jar    | None                                     |
	| LC    | undergroundbiomes     | 1.3.8             | UndergroundBiomesConstructs-1.12-1.3.8.jar       | None                                     |
	| LC    | useless_sword         | 1.0.9             | UselessSword-1.12.2-V1.0.9.jar                   | None                                     |
	| LC    | xaerominimap          | 1.18.6            | Xaeros_Minimap_1.18.6_Forge_1.12.jar             | None                                     |
	| LC    | midnight              | 0.3.5             | themidnight-0.3.5.jar                            | None                                     |
	| LC    | worldsretold          | 1.0.7             | Worlds+Retold-+(v1.0.7)+14.23.5.2784.jar         | None                                     |
	| UD    | mclib_core            | 2.1               | minecraft.jar                                    | None                                     |

	Loaded coremods (and transformers): 
McLib core mod (mclib-2.1-1.12.2.jar)
  mchorse.mclib.core.McLibCMClassTransformer
ForgelinPlugin (Forgelin-1.8.4.jar)
  
midnight (themidnight-0.3.5.jar)
  com.mushroom.midnight.core.transformer.MidnightClassTransformer
OTGCorePlugin (OTG-Core.jar)
  com.pg85.otg.forge.asm.excluded.OTGClassTransformer
CorePlugin (ForgeEndertech-1.12.2-4.5.4.0-build.0534.jar)
  
	GL info: ' Vendor: 'Intel' Version: '4.6.0 - Build 27.20.100.8682' Renderer: 'Intel(R) HD Graphics 530'
	OptiFine Version: OptiFine_1.12.2_HD_U_F5
	OptiFine Build: 20191204-141934
	Render Distance Chunks: 8
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.6.0 - Build 27.20.100.8682
	OpenGlRenderer: Intel(R) HD Graphics 530
	OpenGlVendor: Intel
	CpuCount: 4

**Comment by covers1624** [comment]
You have the `deobf` version of CCL installed, this is intended for mod developers and build systems to use.
You want the `universal` jar.
