### ISSUE TITLE
NPE if player isn't connected

### ISSUE THREAD

**Issue by Time6628** [TheCBProject/CodeChickenLib#33]
CodeChicken/EnderStorage tries to send a packet to the player before the player is connected, so the player is null which causes the server to crash.

Crash report: https://gist.github.com/Time6628/5839e1cf184ecc79871228025a5ba184

Pull request from 1.7.10 with the same/similar NPE: https://github.com/Chicken-Bones/CodeChickenLib/pull/54

**Comment by covers1624** [comment]
Yeah.. I've seen this issue and I have the same concerns as cb. I'll bring this up when I talk to him in a few days.

**Comment by covers1624** [comment]
https://github.com/TheCBProject/Feedback/issues/3
