### ISSUE TITLE
Issue

### ISSUE THREAD

**Issue by soulbladexvii** [TheCBProject/CodeChickenLib#333]
[latest.log](https://github.com/TheCBProject/CodeChickenLib/files/5758521/latest.log)

 can you please help with this error? it also says this on the minecraft launcher Error: cpw.mods.fml.common.LoaderException: java.lang.NoClassDefFoundError: codechicken/multipart/TMultiPart

**Comment by covers1624** [comment]
You need ForeMultipart installed: https://www.curseforge.com/minecraft/mc-mods/forge-multi-part
