### ISSUE TITLE
running CCL in eclipse

### ISSUE THREAD

**Issue by creep3rcrafter** [TheCBProject/CodeChickenLib#334]
[crash-2021-01-18_17.27.28-client.txt](https://github.com/TheCBProject/CodeChickenLib/files/5832884/crash-2021-01-18_17.27.28-client.txt)
I need CCL to run the thermal expansion series of mods in my dev environment I get the same error every time and I have tried the Universal and Deobucated jars.
I'm using eclipse and forge 1.12.2 - 14.23.5.2854

**Comment by covers1624** [comment]
You cannot use the new-old MDK builds as they do not provide the proper GradleStart context to CCL. You will need to use the MDK for forge `14.23.5.2847` and bellow.
