### ISSUE TITLE
Code Chicken Lib Doesnt Work

### ISSUE THREAD

**Issue by BoboTuck** [TheCBProject/CodeChickenLib#336]
Ive been having this problem for the entire day tehn i read a bit and i even deleted the config file for it and it reappears and crashes the game. Help!

**Comment by covers1624** [comment]
You have provided absolutely no information to debug this. Can you provide a Crash report? Your logs? Anything?
Simply saying 'its broken idk what do', doesn't help.

**Comment by BoboTuck** [comment]
Nevermind I tried again with deleteing the config with an older version and it worked. Sorry!
