### ISSUE TITLE
Can't find current version links

### ISSUE THREAD

**Issue by gabrielpda15** [TheCBProject/CodeChickenLib#338]
I realy don't know any where else to contact you guys about it...
the chickenbones [links website](https://chickenbones.net/Pages/links.html) always returns 404.
How i get the mods from now a days?
I saw that some repositories still updates but the release tab still empty.

**Comment by xElementzx** [comment]
https://www.curseforge.com/minecraft/mc-mods/codechicken-lib-1-8/files
