### ISSUE TITLE
SimpleBlockRenderer baking with improper UVs

### ISSUE THREAD

**Issue by MrTJP** [TheCBProject/CodeChickenLib#34]
I've noticed some problems with the SimpleBlockRenderer that I was not able to figure out.

The renderer uses the following method to obtain a UVTransform:
https://github.com/TheCBProject/CodeChickenLib/blob/master/src/main/java/codechicken/lib/model/blockbakery/SimpleBlockRenderer.java#L42

If the last component of the returned triple is a IconTransformation, then the model turns out fine, with block breaking animations working as they should.

However, should a MultiIconTransformation be returned, the block still looks fine normally but when trying to break it, the breaking textures are very wrong.

Another thing to note is that for either of these cases, the breaking particles are always using the blank icon purple/black texture.

**Comment by covers1624** [comment]
Ah, so. Come on ts and ill explain the pipe / help you implement particles.
