### ISSUE TITLE
Hello, I am currently getting this error read below

### ISSUE THREAD

**Issue by ghost** [TheCBProject/CodeChickenLib#344]
The game crashed whilst there was a severe problem during mod loading that has caused the game to fail
Error: net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from CodeChicken Lib (codechickenlib)
Exit Code: -1

this is the pastebin https://pastebin.com/W2CTuLpP. Sorry this is my first time posting on github.
I see people saying delete the ccl of chickencodelib. but it is still not working.

**Comment by covers1624** [comment]
You have a corrupt mod in your mods folder, look at your full log file and you should see some wanrnngs from FML about this.
