### ISSUE TITLE
Trouble Locating Methods.csv and Fileds.csv

### ISSUE THREAD

**Issue by nfcopier** [TheCBProject/CodeChickenLib#35]
My apologies for bringing up this old problem again. I am trying to add FMP as a dependency in my project. The project will be written for 1.7.10. I am developing on Linux with IntelliJ IDEA.

After some work, I managed to track down the folder containing the `.srg` files. But the ".csv" files are not located anywhere on my harddrive. I am sure I missed a step in the setup process.
Tasks I have run (from within IntelliJ):
setupDevWorkspace
idea
build

Which one I have I missed?

**Comment by covers1624** [comment]
Ah, So, in your global .gradle cache folder is where MCP mappings for 1.7 are kept.
So since you are on linux i have no idea where .gradle is located its usually in the users home directory, The actual folder you want to point CCL to is ".gradle/caches/minecraft/net/minecraftforge/forge/insertforgeversionhere/unpacked/conf/"
In 1.10 the issues with pulling this from the gradle start args have been resolved.

**Comment by nfcopier** [comment]
Yeah, things are often more difficult on Linux. I found the `.srg` files in `{myprojectfolder}/build/recompSrc`. But the `.csv` files weren't in that directory. I did a system wide search for the files and can confirm they are nowhere on my hard drive.

**Comment by covers1624** [comment]
Right, you should have a .gradle folder in ~/.gradle. This is the folder i am referring to.

**Comment by nfcopier** [comment]
Not there. But I am using the Gradle wrapper, not a universal install. Could that have something to do with it?

**Comment by nfcopier** [comment]
BTW, thanks for the help.

**Comment by covers1624** [comment]
Its a general gradle cache, thats where ForgeGradle dumps all dependencies and literally everything else. Either way, what forge version are you running?

**Comment by nfcopier** [comment]
Forge Version: 1.7.10 - 10.13.4.1614, which is the latest.

**Comment by covers1624** [comment]
Comment removed, issue was resolved.

**Comment by nfcopier** [comment]
You, sir, are a gentleman and a scholar.
