### ISSUE TITLE
JEI Crashing the game when trying to render a block from Draconic evolution after updating codechicken lib

### ISSUE THREAD

**Issue by Peca21** [TheCBProject/CodeChickenLib#355]
I updated my codeChickenLib today to codechickenlib:1.16.5-4.0.1.418 and since then I am crashing when searching items in JEI

Crash report: https://mclo.gs/VaEbpuF

Forge 1.16.5 36.1.4
Java 1.8.0-281 x64
jei-1.16.5-7.6.4.87
Draconic-Evolution-1.16.4-3.5.0-alpha4.1

Not sure if this is the problem in JEI, Draconic or CodeChickenLib, but it started crashing after the update.

**Comment by covers1624** [comment]
So, you're reporting a bug for a closed unreleased alpha version of DE, in the incorrect place.

I suggest you report your bug on the DE discord, in the correct place.

**Comment by Peca21** [comment]
I reported it here because it started crashing after I updated codechicken lib. I worked fine with same DE version and old codechicken lib. I also reported it on DE discord because I didn't know whos fault it is. Sorry I if did something wrong won't happen again.
