### ISSUE TITLE
Problem at 1.7.10

### ISSUE THREAD

**Issue by PVPM** [TheCBProject/CodeChickenLib#356]
I have a file with CodeChickenLib for 1.7.10 but when i run a modpack game keeps deleting it form mods folder and acting like there is missing lib. How to fix this? 
[latest.log](https://github.com/TheCBProject/CodeChickenLib/files/6395135/latest.log)

**Comment by covers1624** [comment]
Update CodeChickenCore. A new version was released to fix exactly this.
