### ISSUE TITLE
Problem at 1.12.2

### ISSUE THREAD

**Issue by Iamhappy123** [TheCBProject/CodeChickenLib#357]
Everytime i load in the latest version of codechickenlib in minecraft 1.12.2 and it crashes. I deleted the config and it still does not work. 

Crash Log:
[crash-2021-05-06_08.46.58-client.txt](https://github.com/TheCBProject/CodeChickenLib/files/6434268/crash-2021-05-06_08.46.58-client.txt)

**Comment by covers1624** [comment]
You have not deleted the correct config file. See https://github.com/TheCBProject/CodeChickenLib/issues/270
