### ISSUE TITLE
Crash on launching game

### ISSUE THREAD

**Issue by hohserg1** [TheCBProject/CodeChickenLib#361]
Minecraft version: 1.12.2
Forge version: 14.23.5.**2847**
mappings: stable_39
CCL version: 1.12.2-3.2.3.358 universal

I use CCL as dependency in my mod.
I simply run game and it happened. It was not happening before
![image](https://user-images.githubusercontent.com/35610168/119180559-1de09a00-ba79-11eb-958d-6852ba34cfe3.png)
![image](https://user-images.githubusercontent.com/35610168/119180863-8596e500-ba79-11eb-9e73-8c8d5de95bb2.png)

crash-log: https://gist.github.com/hohserg1/c125c8c1596c22410305b862067ff56a
build-script: https://github.com/ElegantNetworking/ElegantNetworking_1.12/blob/master/build.gradle

**Comment by hohserg1** [comment]
After refresh dependencies crash changed to
```java.lang.NoSuchMethodError: net.minecraft.util.ResourceLocation.getResourcePath()Ljava/lang/String;
	at codechicken.lib.model.loader.bakery.CCBakeryModelLoader.accepts(CCBakeryModelLoader.java:22)
	at net.minecraftforge.client.model.ModelLoaderRegistry.getModel(ModelLoaderRegistry.java:123)
	at net.minecraftforge.client.model.ModelLoader.registerVariant(ModelLoader.java:235)
	at net.minecraft.client.renderer.block.model.ModelBakery.loadBlock(ModelBakery.java:153)
	at net.minecraftforge.client.model.ModelLoader.loadBlocks(ModelLoader.java:223)
	at net.minecraftforge.client.model.ModelLoader.setupModelRegistry(ModelLoader.java:150)
	at net.minecraft.client.renderer.block.model.ModelManager.onResourceManagerReload(ModelManager.java:28)
```

**Comment by covers1624** [comment]
You will have to `deobfCompile` the `universal` jar unless you are using the same mcp mappings the `deobf` jar is compiled for.

**Comment by hohserg1** [comment]
Thx for answer!
Earlier able possible to put obfuscated mods to workspace of forge mdk 1.12.2 (2847 and less).
And all dependencies been deobfuscated automaticaly.
Something changed?

**Comment by creepercaway** [comment]
i dont know how to do that can you help me?

**Comment by hohserg1** [comment]
As example from my project: https://github.com/ElegantNetworking/ElegantNetworking_1.12/blob/master/build.gradle#L111
But it does not work anyway because: https://github.com/TheCBProject/CodeChickenLib/issues/309
@covers1624 can you fix CCL for 1.12.2 latest or explain why this thing happened?
As I understand, reason is missing of env property in fg3+ and missing `INameMappingService` in 1.12.2

**Comment by covers1624** [comment]
This is happening because the GradleStart wrapper doesn't exist anymore. I cannot fix this. 1.12 is not supported. I have moved on.

**Comment by hohserg1** [comment]
I fixed it: https://github.com/TheCBProject/CodeChickenLib/pull/369
Can you review?
