### ISSUE TITLE
My game crashed.

### ISSUE THREAD

**Issue by Nonicrix** [TheCBProject/CodeChickenLib#362]
Every time i get to codechikenlib it crashes. I restartedd my pc and it still crashed, I deleted my mods and downloaded them again and it still crashed. WHAT DO I DO?!
![Posnetek zaslona (181)](https://user-images.githubusercontent.com/86835765/124273522-68f1d080-db40-11eb-9de7-a83522222e75.png)

**Comment by Nonicrix** [comment]
https://paste.dimdev.org/qasaxodivu.mccrash

**Comment by Nonicrix** [comment]
https://paste.dimdev.org/qasaxodivu.mccrash

**Comment by Morpheus1101** [comment]
config issue, if this file exists, then Del it.. config/codechickenlib.cfg

**Comment by covers1624** [comment]
Duplicate of https://github.com/TheCBProject/CodeChickenLib/issues/270
