### ISSUE TITLE
1.7.10 Crashing. Can't read lib

### ISSUE THREAD

**Issue by Crazy-Techie** [TheCBProject/CodeChickenLib#363]
That is what I'm getting from the log as Minecraft tells me it crashes with an error code of 0 so no crash report. I will however give a copy of the latest log. It is the latest version and I'm not sure what is wrong with it.
[latest.log](https://github.com/TheCBProject/CodeChickenLib/files/6820165/latest.log)

**Comment by covers1624** [comment]
1.7.10 is not supported. However, it appears that the CCL jar is corrupt, remove it from `mods/1.7.10` and try again.

No more support will be provided.
