### ISSUE TITLE
Crash on opening server

### ISSUE THREAD

**Issue by Adrigamer2950** [TheCBProject/CodeChickenLib#364]
CodeChickenLib + EnderStorage causes crashes in my server.
But when I delete EnderStorage it doesn't crash!
Here is the error it throws:
![Captura](https://user-images.githubusercontent.com/58531641/125773399-256ab72d-98e5-4005-a7c0-e3dd39c0f283.PNG)

**Comment by covers1624** [comment]
You have a duplicated CodeChicklenLib jar. Delete it.

Additionally, 1.12 and CraftBukkit are not supported, use SpongeForge.
