### ISSUE TITLE
Crash With mod added to pack

### ISSUE THREAD

**Issue by alothmanmoe** [TheCBProject/CodeChickenLib#37]
Hello, so while adding CodeChickenLib to my modpack players would sometimes randomly crash with a crash report leading to codechickenlib
http://pastebin.com/btBsPvfF
thats the same crash all of them would get

**Comment by covers1624** [comment]
The stack references CCL yes, i use it to sniff block rendering and do stuff to models that have a specific marker, if it passes to the vanilla dispatcher (witch it did) then it is not my issue, this is InfinityRaders lib mod.
