### ISSUE TITLE
Cannot get a mod working for another mod that requires this mod on 1.16.3 Minecraft java forge

### ISSUE THREAD

**Issue by drherobrine897** [TheCBProject/CodeChickenLib#375]
I tried every version I could find non worked it is a mod called modern online picture frame you can file details here https://www.curseforge.com/minecraft/mc-mods/online-picture-frame
And in its download page located here https://www.curseforge.com/minecraft/mc-mods/online-picture-frame/files/3221381 it stated even in Minecraft that it requires this mod but whenever I install it it cannot work due to there no version for it but I know there probably is and I cannot locate it due to the GitHub page is not update the way I was suspecting it to be.
Can you please help fix this problem and I cannot update my Minecraft due to poor internet connection which means my internet having some problem due to the building I live in is a hotel or motel that was a storage unit in the 1990s and was Converter into a motel and hotel and didn't get wired up with wifi stuff like RJ45 Ethernet ports due to the cement so I using my mobile data on my tablet with it sim since it one of those mobile data tablets. Please email me at drherobrine01234@gmail.com for no response to this if needed

**Comment by covers1624** [comment]
There are some old unreleased 1.16.3 builds of CCL available over here on Maven. However, I highly recommend updating Minecraft, as there will be absolutely no support for this version of CCL.
https://nexus.covers1624.net/#browse/browse:maven-hosted:codechicken%2FCodeChickenLib%2F1.16.3-3.5.0.392%2FCodeChickenLib-1.16.3-3.5.0.392-universal.jar

**Comment by drherobrine897** [comment]
Thank you 6our effort is appreciated thanks again
