### ISSUE TITLE
Website button in Minecraft Mods screen links to wrong destination

### ISSUE THREAD

**Issue by NotFitForPurpose** [TheCBProject/CodeChickenLib#380]
The "Website" button in the Mods screen takes you to Github:
https://github.com/TheCBProject/CodeChickenLib
Should take you to Curseforge:
https://www.curseforge.com/minecraft/mc-mods/codechicken-lib-1-8
where the Jar file lives.

Minecraft tile screen:
o) Mods button
oo) "mods with updates" tick-box
ooo) CodeChickenLib
oooo) Website button

**Comment by covers1624** [comment]
This should be fixed in the latest release.
