### ISSUE TITLE
codechickenlib keeps sayin crap about forgemultipart

### ISSUE THREAD

**Issue by OctolingNexus** [TheCBProject/CodeChickenLib#383]
i have no clue wtf its saying since i dont have forge multipart i just want to use NEI and i cant even do that

The game crashed whilst there was a severe problem during mod loading that has caused the game to fail
Error: cpw.mods.fml.common.LoaderException: java.lang.NoClassDefFoundError: codechicken/multipart/JItemMultiPart
Exit Code: -1

**Comment by covers1624** [comment]
Unfortunately, any version other than those found on Minecraft 1.16 is not supported.

Additionally, for future issue reports, please be sure to attach your full crash report (found in the `crash-reports` folder, next to your `mods` folder), as the snippet you have provided, literally tells me nothing.
