### ISSUE TITLE
[1.16.5] Client crash

### ISSUE THREAD

**Issue by zISKo666** [TheCBProject/CodeChickenLib#384]
Hello there,

after reporting a crash in 2 diefferent locations i was sent here by @KnightMiner

https://github.com/SlimeKnights/TinkersConstruct/issues/4667#issue-1071511498

**Comment by KnightMiner** [comment]
To make this crash more interesting, the static intitialization creating the ItemEntity with a null world (which is invalid per the java docs) is never even used in the mod, its a `private static` variable. Deleting it would fix this problem with no downsides assuming no reflection.

**Comment by covers1624** [comment]
Minecraft does not have Javadocs as you are aware, these are community-driven docs and do not fully represent the 'API'. Not everyone uses these in their dev env, they are not always up-to-date and are frequently incorrect. (Maybe not with Parchment, but still).

In previous versions of Minecraft, 1.12 etc, it was possible to create entities with null worlds explicitly for rendering purposes, this was commonly used by many mods, Forge even had patches to this effect.

At _some_ point this changed and now entities require non-null worlds.

Yes, the code in question is dead, I haven't had time to nuke it.

This will be resolved in a future release of CCL.

**Comment by covers1624** [comment]
This should be resolved in CCL `4.0.5.438`, which is currently pending curse approval. 

Alternatively download it from maven over [here](https://nexus.covers1624.net/#browse/browse:maven-releases:codechicken%2FCodeChickenLib%2F1.16.5-4.0.5.438).
