### ISSUE TITLE
[1.16.5] Game is contuniously crashing on server after placing and breaking a torch w/ onDrawBlockHighlight error.

### ISSUE THREAD

**Issue by Richardo228** [TheCBProject/CodeChickenLib#386]
This may as well be some sort of mod incompatibility issue (probably with magnesium as it's a new mod in our modpack) and also only one of the players on the server is experiencing it but anyways, i couldnt find anything similar in existing issues.

[First crash](https://pastebin.com/bfKwPEqJ) happened as mentioned in the title, after the player had placed and broke a torch.
[Second crash ](https://pastebin.com/Jh1C0ydW) happened when the same player tried to rejoin the server.
If needed i can test the same location with another account, but from what i understand this is enough for the beginning.

Thank you in advance.

**Comment by covers1624** [comment]
You do not have the most up-to-date mods. Please update before reporting _any_ issues.

This issue has been fixed.
