### ISSUE TITLE
code chickenlib crashing

### ISSUE THREAD

**Issue by urmoter** [TheCBProject/CodeChickenLib#387]
crash report:
[crash-2021-04-14_13.37.47-client.txt](https://github.com/TheCBProject/CodeChickenLib/files/7804984/crash-2021-04-14_13.37.47-client.txt)

**Comment by covers1624** [comment]
How is this at all related to CodeChickenLib? You don't appear to have the mod installed..

I recommend reporting this to the AntMan mod authors.
