### ISSUE TITLE
code chicken lib crashes

### ISSUE THREAD

**Issue by endecraft** [TheCBProject/CodeChickenLib#388]
every time I try to start the NEI with core chicken code in version 1.6.2 (I tried also in 1.6.4) it crashes, I read the pinned issue, and directly no file is generated in the config folder that I can delete, that is the only mod that causes the crash, a crash report is not generated either, so the only thing left is the console log, I don't know if I didn't read something and that tells me how to fix it, but even so, I have the problem and i need help

**Comment by covers1624** [comment]
Unfortunately, 1.6 is not supported.
