### ISSUE TITLE
Why is code chicken lib causing my game to crash? I've tried deleting the config, reinstalling, and it still hasn't worked.

### ISSUE THREAD

**Issue by Hacker20Gaming** [TheCBProject/CodeChickenLib#392]
[latest.log](https://github.com/TheCBProject/CodeChickenLib/files/8304867/latest.log)
here's the log
[crash-2022-03-18_08.06.27-client.txt](https://github.com/TheCBProject/CodeChickenLib/files/8304870/crash-2022-03-18_08.06.27-client.txt)
heres the crash report

**Comment by covers1624** [comment]
You have a corrupt mod in your mods folder.

You will have to find it and remove it.
