### ISSUE TITLE
Client Crash when opening Inventory

### ISSUE THREAD

**Issue by Xiaminou** [TheCBProject/CodeChickenLib#40]
Crashed when opening my Inventory after updating CCL and some other mods.

Note: I played around with CoFH mods before adding them to my main pack and didn't have any crash.

Environnement: Server
Minecraft: 1.10.2
Forge: 2239
CCL: 2.5.6.224
Mods: [list.txt](https://github.com/TheCBProject/CodeChickenLib/files/811068/list.txt)

Crash Reports: 
[crash-2017-03-01_15.52.46-client.txt](https://github.com/TheCBProject/CodeChickenLib/files/811069/crash-2017-03-01_15.52.46-client.txt)
[crash-2017-03-01_15.42.09-client.txt](https://github.com/TheCBProject/CodeChickenLib/files/811070/crash-2017-03-01_15.42.09-client.txt)

**Comment by 0Navis0** [comment]
I get the same crash http://pastebin.com/wVmjHqtq

**Comment by covers1624** [comment]
Ahh, I need to push a new EnderStorage and WR-CBE.

**Comment by Xiaminou** [comment]
so downloading the latest from [here](http://chickenbones.net/Pages/links.html) would fix it?

**Comment by covers1624** [comment]
Yes, Can you verify that updating both ES and WR-CBE fixes the issue? if so ill hit my magic button and have them pushed to curse.

**Comment by Xiaminou** [comment]
Yup, just did. It's fixed.

**Comment by covers1624** [comment]
Sweet.
