### ISSUE TITLE
CodeChickenLib Crashing *I deleted the config and it still doesn't work*

### ISSUE THREAD

**Issue by S5PH4NT0M** [TheCBProject/CodeChickenLib#401]
---- Minecraft Crash Report ----

WARNING: coremods are present:
  EnderCorePlugin (EnderCore-1.12.2-0.5.76-core.jar)
  LucraftCoreCoreMod (LucraftCore-1.12.2-2.4.16.jar)
  ForgelinPlugin (Forgelin-1.8.4.jar)
  MekanismCoremod (Mekanism-1.12.2-9.8.3.390.jar)
  CXLibraryCore (cxlibrary-1.12.1-1.6.1.jar)
Contact their authors BEFORE contacting forge

// There are four lights!

Time: 4/9/22 3:04 AM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from CodeChicken Lib (codechickenlib)
Caused by: java.util.zip.ZipError: zip END header not found
	at com.sun.nio.zipfs.ZipFileSystem.zerror(ZipFileSystem.java:1605)
	at com.sun.nio.zipfs.ZipFileSystem.findEND(ZipFileSystem.java:1021)
	at com.sun.nio.zipfs.ZipFileSystem.initCEN(ZipFileSystem.java:1030)
	at com.sun.nio.zipfs.ZipFileSystem.<init>(ZipFileSystem.java:130)
	at com.sun.nio.zipfs.ZipFileSystemProvider.newFileSystem(ZipFileSystemProvider.java:139)
	at java.nio.file.FileSystems.newFileSystem(FileSystems.java:390)
	at codechicken.lib.model.loader.blockstate.CCBlockStateLoader.loadFactories(CCBlockStateLoader.java:83)
	at codechicken.lib.model.loader.blockstate.CCBlockStateLoader$$Lambda$329/1355779344.accept(Unknown Source)
	at java.util.ArrayList.forEach(ArrayList.java:1249)
	at codechicken.lib.model.loader.blockstate.CCBlockStateLoader.initialize(CCBlockStateLoader.java:73)
	at codechicken.lib.internal.proxy.ProxyClient.preInit(ProxyClient.java:59)
	at codechicken.lib.CodeChickenLib.preInit(CodeChickenLib.java:52)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:637)
	at sun.reflect.GeneratedMethodAccessor2.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:136)
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:629)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:252)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:467)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 527209344 bytes (502 MB) / 2232942592 bytes (2129 MB) up to 11453595648 bytes (10923 MB)
	JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx12288m -Xms256m
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2859 Optifine OptiFine_1.12.2_HD_U_G5 53 mods loaded, 53 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID                                | Version           | Source                                             | Signature                                |
	|:----- |:--------------------------------- |:----------------- |:-------------------------------------------------- |:---------------------------------------- |
	| LCH   | minecraft                         | 1.12.2            | minecraft.jar                                      | None                                     |
	| LCH   | mcp                               | 9.42              | minecraft.jar                                      | None                                     |
	| LCH   | FML                               | 8.0.99.99         | forge-1.12.2-14.23.5.2859.jar                      | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCH   | forge                             | 14.23.5.2859      | forge-1.12.2-14.23.5.2859.jar                      | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCH   | appliedenergistics2               | rv6-stable-7      | appliedenergistics2-rv6-stable-7.jar               | dfa4d3ac143316c6f32aa1a1beda1e34d42132e5 |
	| LCE   | codechickenlib                    | 3.2.3.358         | CodeChickenLib-1.12.2-3.2.3.358-universal.jar      | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| LC    | avaritia                          | 3.3.0             | Avaritia-1.12.2-3.3.0.37-universal.jar             | None                                     |
	| LC    | baubles                           | 1.5.2             | Baubles-1.12-1.5.2.jar                             | None                                     |
	| LC    | botania                           | r1.10-364         | Botania+r1.10-364.4.jar                            | None                                     |
	| LC    | redstoneflux                      | 2.1.1             | RedstoneFlux-1.12-2.1.1.1-universal.jar            | None                                     |
	| LC    | brandonscore                      | 2.4.20            | BrandonsCore-1.12.2-2.4.20.162-universal.jar       | None                                     |
	| LC    | cucumber                          | 1.1.3             | Cucumber-1.12.2-1.1.3.jar                          | None                                     |
	| LC    | cxlibrary                         | 1.6.1             | cxlibrary-1.12.1-1.6.1.jar                         | None                                     |
	| LC    | cyclicmagic                       | 1.20.12           | Cyclic-1.12.2-1.20.12.jar                          | 0e5cb559be7d03f3fc18b8cba547d663e25f28af |
	| LC    | draconicevolution                 | 2.3.28            | Draconic-Evolution-1.12.2-2.3.28.354-universal.jar | None                                     |
	| LC    | draconicadditions                 | 1.17.0            | Draconic-Additions-1.12.2-1.17.0.45-universal.jar  | None                                     |
	| LC    | endercore                         | 1.12.2-0.5.76     | EnderCore-1.12.2-0.5.76.jar                        | None                                     |
	| LC    | enderio                           | 5.3.70            | EnderIO-1.12.2-5.3.70.jar                          | None                                     |
	| LC    | enderiointegrationtic             | 5.3.70            | EnderIO-1.12.2-5.3.70.jar                          | None                                     |
	| LC    | enderiobase                       | 5.3.70            | EnderIO-1.12.2-5.3.70.jar                          | None                                     |
	| LC    | enderioconduits                   | 5.3.70            | EnderIO-1.12.2-5.3.70.jar                          | None                                     |
	| LC    | enderioconduitsappliedenergistics | 5.3.70            | EnderIO-1.12.2-5.3.70.jar                          | None                                     |
	| LC    | enderioconduitsopencomputers      | 5.3.70            | EnderIO-1.12.2-5.3.70.jar                          | None                                     |
	| LC    | enderioconduitsrefinedstorage     | 5.3.70            | EnderIO-1.12.2-5.3.70.jar                          | None                                     |
	| LC    | enderiointegrationforestry        | 5.3.70            | EnderIO-1.12.2-5.3.70.jar                          | None                                     |
	| LC    | enderiointegrationticlate         | 5.3.70            | EnderIO-1.12.2-5.3.70.jar                          | None                                     |
	| LC    | enderioinvpanel                   | 5.3.70            | EnderIO-1.12.2-5.3.70.jar                          | None                                     |
	| LC    | enderiomachines                   | 5.3.70            | EnderIO-1.12.2-5.3.70.jar                          | None                                     |
	| LC    | enderiopowertools                 | 5.3.70            | EnderIO-1.12.2-5.3.70.jar                          | None                                     |
	| LC    | extrautils2                       | 1.0               | extrautils2-1.12-1.9.9.jar                         | None                                     |
	| LC    | zerocore                          | 1.12.2-0.1.2.9    | zerocore-1.12.2-0.1.2.9.jar                        | None                                     |
	| LC    | bigreactors                       | 1.12.2-0.4.5.68   | ExtremeReactors-1.12.2-0.4.5.68.jar                | None                                     |
	| LC    | forgelin                          | 1.8.4             | Forgelin-1.8.4.jar                                 | None                                     |
	| LC    | fm                                | 1.8               | FunMod 1.9.jar                                     | None                                     |
	| LC    | gb                                | 1.1.206           | Gobber-1.12.2_1.1.207.jar                          | None                                     |
	| LC    | lucraftcore                       | 1.12.2-2.4.16     | LucraftCore-1.12.2-2.4.16.jar                      | None                                     |
	| LC    | heroesexpansion                   | 1.12.2-1.3.5      | HeroesExpansion-1.12.2-1.3.5.jar                   | None                                     |
	| LC    | mekanism                          | 1.12.2-9.8.3.390  | Mekanism-1.12.2-9.8.3.390.jar                      | None                                     |
	| LC    | teslacorelib                      | 1.0.18            | tesla-core-lib-1.12.2-1.0.18.jar                   | d476d1b22b218a10d845928d1665d45fce301b27 |
	| LC    | industrialforegoing               | 1.12.2-1.12.2     | industrialforegoing-1.12.2-1.12.13-237.jar         | None                                     |
	| LC    | ironchest                         | 1.12.2-7.0.67.844 | ironchest-1.12.2-7.0.72.847.jar                    | None                                     |
	| LC    | lostinfintystoneswepons           | 1.0.0             | Lost+Infinty+Stones (1).jar                        | None                                     |
	| LC    | magicalcrops                      | 1.0.1             | Magical-Crops-Mod-1.12.2.jar                       | None                                     |
	| LC    | morefurnaces                      | 1.10.5            | MoreFurnaces-1.12.2-1.10.6.jar                     | None                                     |
	| LC    | mysticalagriculture               | 1.7.5             | MysticalAgriculture-1.12.2-1.7.5.jar               | None                                     |
	| LC    | mysticalagradditions              | 1.3.2             | MysticalAgradditions-1.12.2-1.3.2.jar              | None                                     |
	| LC    | projecte                          | 1.12.2-PE1.4.1    | ProjectE-1.12.2-PE1.4.1.jar                        | None                                     |
	| LC    | projectex                         | 1.2.0.40          | ProjectEX-1.2.0.40.jar                             | None                                     |
	| LC    | valkyrielib                       | 1.12.2-2.0.20.1   | valkyrielib-1.12.2-2.0.20.1.jar                    | None                                     |
	| LC    | simplegenerators                  | 1.12.2-2.0.20.2   | simplegenerators-1.12.2-2.0.20.2.jar               | None                                     |
	| LC    | sm                                | 1.3               | Typical-Heroes-Mod-1.12.2.jar                      | None                                     |
	| LC    | universalmodifiers                | 1.12.2-1.0.16.1   | valkyrielib-1.12.2-2.0.20.1.jar                    | None                                     |
	| LC    | teslacorelib_registries           | 1.0.18            | tesla-core-lib-1.12.2-1.0.18.jar                   | None                                     |

	Loaded coremods (and transformers): 
EnderCorePlugin (EnderCore-1.12.2-0.5.76-core.jar)
  com.enderio.core.common.transform.EnderCoreTransformer
  com.enderio.core.common.transform.SimpleMixinPatcher
LucraftCoreCoreMod (LucraftCore-1.12.2-2.4.16.jar)
  lucraft.mods.lucraftcore.core.LCTransformer
ForgelinPlugin (Forgelin-1.8.4.jar)
  
MekanismCoremod (Mekanism-1.12.2-9.8.3.390.jar)
  mekanism.coremod.KeybindingMigrationHelper
CXLibraryCore (cxlibrary-1.12.1-1.6.1.jar)
  cubex2.cxlibrary.CoreModTransformer
	GL info: ' Vendor: 'Intel' Version: '4.6.0 - Build 27.20.100.8729' Renderer: 'Intel(R) UHD Graphics'
	AE2 Version: stable rv6-stable-7 for Forge 14.23.5.2768
	Ender IO: Found the following problem(s) with your installation (That does NOT mean that Ender IO caused the crash or was involved in it in any way. We add this information to help finding common problems, not as an invitation to post any crash you encounter to Ender IO's issue tracker. Always check the stack trace above to see which mod is most likely failing.):
                  * Optifine is installed. This is NOT supported.
                 This may (look up the meaning of 'may' in the dictionary if you're not sure what it means) have caused the error. Try reproducing the crash WITHOUT this/these mod(s) before reporting it.
	Authlib is : /C:/Users/zahma/curseforge/minecraft/Install/libraries/com/mojang/authlib/1.5.25/authlib-1.5.25.jar

	!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
	!!!You are looking at the diagnostics information, not at the crash.       !!!
	!!!Scroll up until you see the line with '---- Minecraft Crash Report ----'!!!
	!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

	OptiFine Version: OptiFine_1.12.2_HD_U_G5
	OptiFine Build: 20210124-142939
	Render Distance Chunks: 8
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.6.0 - Build 27.20.100.8729
	OpenGlRenderer: Intel(R) UHD Graphics
	OpenGlVendor: Intel
	CpuCount: 2

**Comment by covers1624** [comment]
You have a corrupt mod in your mods folder.

This should be obvious from your latest.log, if not, Mod jars are regular zip files, try opening them with 7zip, if it doesn't, its corrupt.
