### ISSUE TITLE
I need help

### ISSUE THREAD

**Issue by trainion12** [TheCBProject/CodeChickenLib#403]
Whenever I press the U key to see crafting recipes on Not Enough Items 1.7.10 it crashes the game
[crash-2022-05-18_21.57.33-client.txt](https://github.com/TheCBProject/CodeChickenLib/files/8716046/crash-2022-05-18_21.57.33-client.txt)

**Comment by covers1624** [comment]
1.7.10 is not supported anymore.

Modular powersuits's json recipes are broken.
