### ISSUE TITLE
I've read the "read me" thing but 1.12.2 doesn't work.

### ISSUE THREAD

**Issue by ghost** [TheCBProject/CodeChickenLib#405]
I downloaded the most recent version of the 1.12.2 one as a couple of mods I have are dependant on it. However it brings up the error which was shown. Is there any workaround to this? The mods I need it for is Thermal Dynamics and Thermal Expansion.

**Comment by covers1624** [comment]
Please provide crash reports in a new issue.

Saying it does not work is not helpful.
