### ISSUE TITLE
zip END header not found

### ISSUE THREAD

**Issue by Ninovui** [TheCBProject/CodeChickenLib#406]
It makes a time I can't open my 1.12.2 mods.

I tried to remove mods, change the chickenlib version, but nothing change.

I even got another error with Mixin, when it's not Codechickenlib.

I joined the devlog.
[debug-1.log](https://github.com/TheCBProject/CodeChickenLib/files/8760399/debug-1.log)

**Comment by covers1624** [comment]
You have a corrupt mod in your mods folder.

Mods are regular zip files, try to open them with 7zip, you'll find the broken one.
