### ISSUE TITLE
CCL Caught an exception rendering a block

### ISSUE THREAD

**Issue by CoolN4m3** [TheCBProject/CodeChickenLib#408]
I made a modpack for minecraft 1.12.2 and it gives the error "CCL Caught an exception rendering a block" When this text shows up on my screen the entire game freezes with 2 second intervals causing my game to literally run on 2 fps. What should I do?

**Comment by covers1624** [comment]
A good first step would be to read your massive log file as it will be spitting out all the debug information the mod author of the crashing bloc would require. Additionally you can use the provided coordinates to setblock it to air if you want it gone.
