### ISSUE TITLE
Codechicken error 

### ISSUE THREAD

**Issue by MalikBruda** [TheCBProject/CodeChickenLib#414]
I tried to start my new own created modpack but i cant start it because of an error with codechickenlib. first it says it has complications with some mods. I deleted every of those mods, then it shows me this: 
---- Minecraft Crash Report ----

WARNING: coremods are present:
Contact their authors BEFORE contacting forge

// Hey, that tickles! Hehehe!

Time: 7/25/22 12:13 AM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from CodeChicken Lib (codechickenlib)
Caused by: java.util.zip.ZipError: zip END header not found
	at com.sun.nio.zipfs.ZipFileSystem.zerror(ZipFileSystem.java:1605)
	at com.sun.nio.zipfs.ZipFileSystem.findEND(ZipFileSystem.java:1021)
	at com.sun.nio.zipfs.ZipFileSystem.initCEN(ZipFileSystem.java:1030)
	at com.sun.nio.zipfs.ZipFileSystem.<init>(ZipFileSystem.java:130)
	at com.sun.nio.zipfs.ZipFileSystemProvider.newFileSystem(ZipFileSystemProvider.java:139)
	at java.nio.file.FileSystems.newFileSystem(FileSystems.java:390)
	at codechicken.lib.model.loader.blockstate.CCBlockStateLoader.loadFactories(CCBlockStateLoader.java:83)
	at codechicken.lib.model.loader.blockstate.CCBlockStateLoader$$Lambda$121/927975956.accept(Unknown Source)
	at java.util.ArrayList.forEach(ArrayList.java:1249)
	at codechicken.lib.model.loader.blockstate.CCBlockStateLoader.initialize(CCBlockStateLoader.java:73)
	at codechicken.lib.internal.proxy.ProxyClient.preInit(ProxyClient.java:59)
	at codechicken.lib.CodeChickenLib.preInit(CodeChickenLib.java:52)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:637)
	at sun.reflect.GeneratedMethodAccessor2.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:136)
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:629)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:252)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:467)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1354568784 bytes (1291 MB) / 1579155456 bytes (1506 MB) up to 3817865216 bytes (3641 MB)
	JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx4096m -Xms256m
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2859 72 mods loaded, 72 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID                     | Version           | Source                                         | Signature                                |
	|:----- |:---------------------- |:----------------- |:---------------------------------------------- |:---------------------------------------- |
	| LCH   | minecraft              | 1.12.2            | minecraft.jar                                  | None                                     |
	| LCH   | mcp                    | 9.42              | minecraft.jar                                  | None                                     |
	| LCH   | FML                    | 8.0.99.99         | forge-1.12.2-14.23.5.2859.jar                  | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCH   | forge                  | 14.23.5.2859      | forge-1.12.2-14.23.5.2859.jar                  | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCH   | damageindicatorsmod    | 1.0               | [1.12.2]DamageIndicatorsMod-3.5.1.jar          | None                                     |
	| LCH   | baubles                | 1.5.2             | Baubles-1.12-1.5.2.jar                         | None                                     |
	| LCH   | artifacts              | 1.12.2-1.2.3      | Artifacts-1.12.2-1.2.3.jar                     | None                                     |
	| LCE   | codechickenlib         | 3.2.3.358         | CodeChickenLib-1.12.2-3.2.3.358-universal.jar  | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| LC    | avaritia               | 3.3.0             | Avaritia-Mod-1.12.2.jar                        | None                                     |
	| LC    | backpack               | 3.0.2             | backpack-3.0.2-1.12.2.jar                      | None                                     |
	| LC    | bno                    | 1.12.2-1.0.4.0    | Basic-Nether-Ores-Mod-1.12.2.jar               | None                                     |
	| LC    | battletowers           | 1.6.5             | BattleTowers-1.12.2.jar                        | None                                     |
	| LC    | beneficium             | 0.5.1             | Beneficium-Mod-1.12.2.jar                      | None                                     |
	| LC    | betterfurnacesreforged | 152               | BetterFurnacesReforged-1.12.2-1.5.2.jar        | None                                     |
	| LC    | bibliocraft            | 2.4.6             | BiblioCraft[v2.4.6][MC1.12.2].jar              | None                                     |
	| LC    | bookshelf              | 2.3.590           | Bookshelf-1.12.2-2.3.590.jar                   | d476d1b22b218a10d845928d1665d45fce301b27 |
	| LC    | bountifulbaubles       | 0.0.1             | Bountiful+Baubles-1.12.2-0.1.8.jar             | None                                     |
	| LC    | cases                  | 0.6.3             | cases-0.6.3.jar                                | None                                     |
	| LC    | castle_dungeons        | 1.3               | Castle-Dungeons-Mod-1.12.2.jar                 | None                                     |
	| LC    | catwalks               | 1.12.2-4.0.45     | Catwalks-4-Mod-1.12.2.jar                      | None                                     |
	| LC    | chameleon              | 1.12-4.1.3        | Chameleon-1.12-4.1.3.jar                       | None                                     |
	| LC    | chancecubes            | 1.12.2-5.0.2.385  | ChanceCubes-1.12.2-5.0.2.385.jar               | None                                     |
	| LC    | chesttransporter       | 2.8.8             | ChestTransporter-1.12.2-2.8.8.jar              | None                                     |
	| LC    | clumps                 | 3.1.2             | Clumps-3.1.2.jar                               | None                                     |
	| LC    | cosmeticarmorreworked  | 1.12.2-v5a        | CosmeticArmorReworked-1.12.2-v5a.jar           | aaaf83332a11df02406e9f266b1b65c1306f0f76 |
	| LC    | customizeddungeonloot  | 1.0.3             | Customized-Dungeon-Loot-1.12+-(v.1.0.3).jar    | None                                     |
	| LC    | cyclopscore            | 1.6.7             | CyclopsCore-1.12.2-1.6.7.jar                   | bd0353b3e8a2810d60dd584e256e364bc3bedd44 |
	| LC    | divinerpg              | 1.7.1             | DivineRPG-Mod-1.12.2.jar                       | None                                     |
	| LC    | dungeonsmod            | @VERSION@         | DungeonsMod-1.12.2-1.0.8.jar                   | None                                     |
	| LC    | eplus                  | 5.0.176           | EnchantingPlus-1.12.2-5.0.176.jar              | d476d1b22b218a10d845928d1665d45fce301b27 |
	| LC    | endercompass           | 1.2.6.2           | Ender-Compass-Mod-1.12.2.jar                   | None                                     |
	| LC    | everlastingabilities   | 1.5.3             | EverlastingAbilities-1.12.2-1.5.3.jar          | bd0353b3e8a2810d60dd584e256e364bc3bedd44 |
	| LC    | expandableinventory    | 1.4.0             | Expandable-Inventory-Mod-1.12.2.jar            | None                                     |
	| LC    | falling_tree           | 2.4.0             | FallingTree-1.12.2-2.4.0.jar                   | None                                     |
	| LC    | farlanders             | 1.0.1             | Farlanders-Mod-1.12.2.jar                      | None                                     |
	| LC    | findme                 | 1.1.0             | findme-1.12.2-1.1.0-8.jar                      | None                                     |
	| LC    | cfm                    | 6.3.0             | furniture-6.3.2-1.12.2.jar                     | None                                     |
	| LC    | gottschcore            | 1.15.0            | GottschCore-mc1.12.2-f14.23.5.2859-v1.15.0.jar | None                                     |
	| LC    | hopperducts            | 1.5               | hopperducts-mc1.12-1.5.jar                     | None                                     |
	| LC    | waila                  | 1.8.26            | Hwyla-1.8.26-B41_1.12.2.jar                    | None                                     |
	| LC    | ironchest              | 1.12.2-7.0.67.844 | ironchest-1.12.2-7.0.72.847.jar                | None                                     |
	| LC    | jei                    | 4.16.1.302        | jei_1.12.2-4.16.1.302.jar                      | None                                     |
	| LC    | keepinginventory       | 2.4               | Keeping-Inventory-Mod-1.12.2.jar               | None                                     |
	| LC    | lootbags               | 2.5.8.5           | LootBags-Mod-1.12.2.jar                        | None                                     |
	| LC    | lootoverhaul           | 1.2               | LootOverhaul-1.2.jar                           | None                                     |
	| LC    | lucky                  | 7.6.0             | lucky-block-forge-1.12.2-2.0.jar               | None                                     |
	| LC    | lunatriuscore          | 1.2.0.42          | LunatriusCore-1.12.2-1.2.0.42-universal.jar    | None                                     |
	| LC    | minergolems            | 2.1.1             | Miner-Golems-Mod-1.12.2.jar                    | None                                     |
	| LC    | mjrlegendslib          | 1.12.2-1.2.1      | MJRLegendsLib-1.12.2.jar                       | b02331787272ec3515ebe63ecdeea0d746653468 |
	| LC    | ore_canes              | 1.4.2             | Ore-Canes-Mod-1.12.2.jar                       | None                                     |
	| LC    | op_pickaxes_mod        | 1.0.0             | pickaxes.jar                                   | None                                     |
	| LC    | placebo                | 1.6.0             | Placebo-1.12.2-1.6.0.jar                       | None                                     |
	| LC    | potioncore             | 1.9_for_1.12.2    | Potion-Core-1.12.2.jar                         | None                                     |
	| LC    | rabbit-gui             | 1.12.2.2          | rabbit-gui-1.12.2.2.jar                        | None                                     |
	| LC    | randomloot             | 1.7.5             | randomloot-1.12.2-1.7.5.jar                    | None                                     |
	| LC    | roguelike              | 2.4.1             | RoguelikeDungeonsFnarEdition-1.12.2-2.4.1.jar  | None                                     |
	| LC    | schematica             | 1.8.0.169         | Schematica-1.12.2-1.8.0.169-universal.jar      | None                                     |
	| LC    | shipwrecks_winslow     | 2.0.0             | Shipwrecks-Mod-1.12.2.jar                      | None                                     |
	| LC    | stg                    | 1.12.2-1.2.3      | stg-1.12.2-1.2.3.jar                           | None                                     |
	| LC    | storagedrawers         | 5.2.2             | StorageDrawers-1.12.2-5.4.2.jar                | None                                     |
	| LC    | supertnt               | 1.0.1             | Super-TNT-Mod-1.12.2.jar                       | None                                     |
	| LC    | timecore               | 1.0.1.1           | TimeCore-1.12.2-1.0.1.1.jar                    | None                                     |
	| LC    | toolbelt               | 1.9.14            | ToolBelt-1.12.2-1.9.14.jar                     | None                                     |
	| LC    | trashslot              | 8.4.10            | TrashSlot_1.12.2-8.4.10.jar                    | None                                     |
	| LC    | treasure2              | 2.1.0             | Treasure2-mc1.12.2-f14.23.5.2859-v2.1.0.jar    | None                                     |
	| LC    | walljump               | 1.3.2             | walljump-1.12.2-1.3.2.jar                      | None                                     |
	| LC    | warpbook               | 1.12.2-3.3.4      | Warp-Book-Mod-1.12.2.jar                       | None                                     |
	| LC    | witherskelefix         | 2.6.3             | WitherSkeletonTweaks-1.12.2-2.6.3.jar          | None                                     |
	| LC    | xray                   | 2.0.0             | xray-1.12.2-1.6.0.jar                          | None                                     |
	| LC    | yamda                  | 0.0.0.yamda       | YAMDA-1.0.2.jar                                | None                                     |
	| LC    | zaraklib               | 0.0.4             | ZarakLib-1.12.2.jar                            | None                                     |
	| LC    | densemetals            | 2.0.0             | Dense-Metals-Mod-1.12.2.jar                    | d476d1b22b218a10d845928d1665d45fce301b27 |

	Loaded coremods (and transformers): 
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 456.71' Renderer: 'GeForce GTX 750 Ti/PCIe/SSE2'

Yes, i already tried to delete the config, but anyways it doesnt work, If anyone knows whats the problem, I would really appreciate it if you could help me.

**Comment by covers1624** [comment]
Please look at recently closed issues before making a new one.

You have a corrupt mod in your mods folder.
