### ISSUE TITLE
Crashes on launch up

### ISSUE THREAD

**Issue by AstaBlackheart** [TheCBProject/CodeChickenLib#416]
This is the crash report I get every time I try to launch the game

[crash-2022-07-29_18.34.59-client.txt](https://github.com/TheCBProject/CodeChickenLib/files/9224109/crash-2022-07-29_18.34.59-client.txt)

**Comment by covers1624** [comment]
Please check for already closed issues before submitting new ones.

You have a corrupt mod in your mods folder.
