### ISSUE TITLE
CodeChickenLib crashes when loading in 1.12.2

### ISSUE THREAD

**Issue by TheGrandPotato** [TheCBProject/CodeChickenLib#421]
CodeChickenLib crashes when loading in 1.12.2

I saw somewhere about certificates being updated in the 1.13 version.

This is what stood out to me:

class "codechicken.lib.util.ResourceUtils"'s signer information does not match signer information of other classes in the same package

Crash Report:

[crash-2022-10-01_11.20.50-client.txt](https://github.com/TheCBProject/CodeChickenLib/files/9690944/crash-2022-10-01_11.20.50-client.txt)

Any help would be monumentally appreciated.

**Comment by covers1624** [comment]
You have an older version of CCL installed inside your `mods` or `mods/1.X` folder, delete it.

**Comment by TheGrandPotato** [comment]
Thank you so much!
You are the best!

**Comment by TheGrandPotato** [comment]
I'm sorry to bother you but the error is still happening

[crash-2022-10-01_11.42.30-client.txt](https://github.com/TheCBProject/CodeChickenLib/files/9690973/crash-2022-10-01_11.42.30-client.txt)
