### ISSUE TITLE
Crashing at launch of a 1.7.10 modpack

### ISSUE THREAD

**Issue by GRIMSoulS** [TheCBProject/CodeChickenLib#422]
so i keep crashing and getting this crash log any help or ideas
[latest (1).log](https://github.com/TheCBProject/CodeChickenLib/files/9793421/latest.1.log)
[latest.log](https://github.com/TheCBProject/CodeChickenLib/files/9793422/latest.log)

**Comment by covers1624** [comment]
1.7.10 is not supported. Sorry.
