### ISSUE TITLE
crash in 1.12.2 when i open inventory

### ISSUE THREAD

**Issue by XvaleX10** [TheCBProject/CodeChickenLib#438]
[crash-2023-05-15_18.14.04-client.txt](https://github.com/TheCBProject/CodeChickenLib/files/11479843/crash-2023-05-15_18.14.04-client.txt)

**Comment by covers1624** [comment]
This has absolutely nothing to do with CCL.

Refined Storage failed to render an item, however, you have optifine installed. I highly recommend removing it.
