### ISSUE TITLE
Some conflict with Code chicken Lib, a texture pack, and microblocks.

### ISSUE THREAD

**Issue by kilaehuied** [TheCBProject/CodeChickenLib#444]
After some experimenting I was able to figure out that when I used a texture pack that even though blocks from forge microblocks could load, if I tried to look them up in jei, or have the block in a hand it would crash the world. Along with that when in my inventory the block wont even render, but I can still hover over it to get the item name. But when I put it in my hand it blue screens then in the crash log the only error message I could find is a java.lang.ArrayIndexOutOfBoundsException. And one more thing, it seems to be only happening with base game blocks that have been modified by microblocks.

crash report **https://github.com/kilaehuied/crash-2023-07-13_15.58.35-client/blob/main/crash-2023-07-13_15.58.35-client.txt**

**Comment by covers1624** [comment]
1.12.2 is no longer supported.
