### ISSUE TITLE
1.20.1 - Bug - Crash on startup

### ISSUE THREAD

**Issue by muggleorwizard** [TheCBProject/CodeChickenLib#460]
Description:
```
Caused by: java.lang.ClassCastException: class [Lcodechicken.lib.vec.Vector3; cannot be cast to class codechicken.lib.render.model.ModelMaterial ([Lcodechicken.lib.vec.Vector3; and codechicken.lib.render.model.ModelMaterial are in module codechickenlib@4.4.0.512 of loader 'TRANSFORMER' @70592729)
	at codechicken.lib.render.model.ModelMaterial$1.copyRange(ModelMaterial.java:14) ~[CodeChickenLib-1.20.1-4.4.0.512-universal.jar%23475!/:4.4.0.512] {re:classloading}
	at codechicken.lib.render.CCModel.copy(CCModel.java:590) ~[CodeChickenLib-1.20.1-4.4.0.512-universal.jar%23475!/:4.4.0.512] {re:classloading}
	at codechicken.lib.render.CCModel.copy(CCModel.java:793) ~[CodeChickenLib-1.20.1-4.4.0.512-universal.jar%23475!/:4.4.0.512] {re:classloading}
```

Crash Log:
https://bytebin.lucko.me/oZZ1uvCObS

Modpack: Ozone Skyblock Reborn

Crash report says Code Chicken Lib and Ender Chests 1.8+ are the issue. Also having a crash with Draconic Evolution that occurs sometimes with a different error. 
https://github.com/Draconic-Inc/Draconic-Evolution/issues/1838

**Comment by covers1624** [comment]
I have been unable to reproduce this issue at all. Scouring the code the only thing I can think of is somehow this is a concurrency issue when `AttributeKey` instances are being registered via class load, through different mods.

Can you please try this build of CCL <https://maven.covers1624.net/io/codechicken/CodeChickenLib/1.20.1-4.4.0.516/CodeChickenLib-1.20.1-4.4.0.516-universal.jar>

**Comment by muggleorwizard** [comment]
I'll give this a try, but I have not had this issue myself. Only a few people who play my pack have reported it (and I made sure they had not modified any files or mods). I will ask the people who had the issue to try this build. Thanks for the reply!

**Comment by muggleorwizard** [comment]
> I'll give this a try, but I have not had this issue myself. Only a few people who play my pack have reported it (and I made sure they had not modified any files or mods). I will ask the people who had the issue to try this build. Thanks for the reply!

This appears to have worked! A player who was getting the crash used the new jar file and they were no longer crashing on startup :) will this version be published to curseforge?

**Comment by covers1624** [comment]
> This appears to have worked! A player who was getting the crash used the new jar file and they were no longer crashing on startup :) will this version be published to curseforge?

Yes, this build will be published to CurseForge soon, I'd like more feedback from people experiencing this bug first. If none is received, I'll just roll it out on Monday.

**Comment by muggleorwizard** [comment]
> > This appears to have worked! A player who was getting the crash used the new jar file and they were no longer crashing on startup :) will this version be published to curseforge?
> 
> Yes, this build will be published to CurseForge soon, I'd like more feedback from people experiencing this bug first. If none is received, I'll just roll it out on Monday.

https://github.com/TheCBProject/CodeChickenLib/issues/461#issuecomment-2365334769 here is another success story

**Comment by muggleorwizard** [comment]
I've had about 10 people on my discord report success with the updated jar

**Comment by muggleorwizard** [comment]
I can send you report of successes if needed in order to have the curseforge release.

**Comment by covers1624** [comment]
No need, I simply forgot to hit the button :upside_down_face: 

This build should be available on CurseForge/Modrinth now (approval pending on CF).

**Comment by muggleorwizard** [comment]
Thank you so much!
