### ISSUE TITLE
Crashes on Startup

### ISSUE THREAD

**Issue by ChanGrape** [TheCBProject/CodeChickenLib#461]
Crashing on startup rendering an overlay with Ender Storage and Draconic Evolution interchangeably. Only fix I have found is to reinstall CodeChicken Lib every time I boot up the modpack I'm playing.

[https://pastebin.com/hUZLqac2](https://pastebin.com/hUZLqac2) -Ender Storage crash log
[https://pastebin.com/rAiRpU2v](https://pastebin.com/rAiRpU2v) -Draconic Evolution crash log

**Comment by FoxMcloud5655** [comment]
Duplicate of #460.

**Comment by muggleorwizard** [comment]
try what's posted here, it seems to work: https://github.com/TheCBProject/CodeChickenLib/issues/460#issuecomment-2358715796

**Comment by ChanGrape** [comment]
> try what's posted here, it seems to work: [#460 (comment)](https://github.com/TheCBProject/CodeChickenLib/issues/460#issuecomment-2358715796)

Tested about 30x today with no issues and this worked! Thanks!
