### ISSUE TITLE
Game Crash 1.12.2

### ISSUE THREAD

**Issue by 233Neon** [TheCBProject/CodeChickenLib#462]
[crash-2024-09-21_09.56.51-client.txt](https://github.com/user-attachments/files/17085264/crash-2024-09-21_09.56.51-client.txt)

The crash was caused by a java.util.ConcurrentModificationException during the initialization of CodeChickenLib. Probably Multiple threads or processes attempt to modify a collection (such as a HashMap) simultaneously without proper synchronization.

**Comment by covers1624** [comment]
1.12.2 is not supported anymore.

The map in question is not owned by CCL, it's `FMLDeobfuscatingRemapper.rawFieldMaps`.

I recommend removing some of your core mods until you find the offending mod.
