### ISSUE TITLE
Missing Mods GUI does not display

### ISSUE THREAD

**Issue by robaimes** [TheCBProject/CodeChickenLib#5]
With CCL / CCC installed, can't tell which one, if a mod has a missing mods exception, the forge GUI that would normally display, does not display and instead, the game crashes.

For example, if I installed RFTools without McJty Lib, forge would stop loading MC and prompt me that I am missing the McJty Lib. With CCL installed, this GUI doe not show.

http://pastebin.com/5Am1MQC1

The GUI acts as normal after removing CCL and CCC. (Plus EnderStorage, ChickenChunks and NEI)

**Comment by covers1624** [comment]
Interesting, ill look in to this.

**Comment by covers1624** [comment]
do you have JEI installed for NEI?

**Comment by robaimes** [comment]
Yeah, the missing mod was 'ZeroCore' for extreme reactors

**Comment by robaimes** [comment]
Version `2.2.3.72` of CCL appears to have fixed this problem. I'll update this if it happens again!
