### ISSUE TITLE
Problem with servers

### ISSUE THREAD

**Issue by hilariousppp** [TheCBProject/CodeChickenLib#53]
Running recommended version of Forge 1.11.2 server on Windows 10 with the Translocators mod, and some sort of exception is thrown when I start the server.
[crash-2017-06-04_20.54.26-server.txt](https://github.com/TheCBProject/CodeChickenLib/files/1051066/crash-2017-06-04_20.54.26-server.txt)

**Comment by covers1624** [comment]
This should now be fixed in the latest 1.11 build.
