### ISSUE TITLE
Crasheo by entities

### ISSUE THREAD

**Issue by HeberonYT** [TheCBProject/CodeChickenLib#54]
Hello
I have a Sponge 1.10.2 server and everything works normally, but sometimes when browsing new map the client crashes.
I have also identified that this crash happens when different types of drops fall on the floor, apparently it is random, sometimes it happens and others do not.
Here is the client report, the server does not mark any errors, it only seems to affect the client, and it seems to me that the server is not the problem.
I hope you can solve this problem.
Regards!

CrashReport: https://pastebin.com/raw/UpW0Psik

spongeforge-1.10.2-2281-5.2.0-BETA-2366.jar
CodeChickenLib-1.10.2-2.5.8.255-universal

**Comment by covers1624** [comment]
This crash has nothing to do with ccl. So what ever item you are dropping is breaking when being rendered, that is your issue.
