### ISSUE TITLE
Weird crash [1.10.2] MissingGUI?

### ISSUE THREAD

**Issue by MokahTGS** [TheCBProject/CodeChickenLib#55]
https://pastebin.com/riqeDNtK

Getting this crash when I update certain mods and those authors are calling out this Lib.  Updating to the most recent version doesn't change the crash.

**Comment by covers1624** [comment]
This has absolutely nothing to do with ccl, the only way to debug this is to remove mods 1 by 1 and see who is causing the crash.

**Comment by MokahTGS** [comment]
https://github.com/CoFH/Feedback/issues/220
