### ISSUE TITLE
 A fatal exception occurred during the server about to start event

### ISSUE THREAD

**Issue by CorneliusCornbread** [TheCBProject/CodeChickenLib#56]
From time to time when I try and load up or create a world, it will refuse to get beyond the loading screen and will spit this out into console:
[fml-client-latest.zip](https://github.com/TheCBProject/CodeChickenLib/files/1066759/fml-client-latest.zip)

I posted about this on the Forge forums and was told it was a problem with CodeChickenLib: http://www.minecraftforge.net/forum/topic/58551-a-fatal-exception-occurred-during-the-server-about-to-start-event/#comment-270395

I'm using forge version: 12.18.3.2316
MC version: 1.10.2
CodeChickenLib: 1.10.2-2.5.9.267-universal

UPDATE: It's now crashing consistently instead of every so often

**Comment by covers1624** [comment]
This should be fixed.
Edit: This is 1.10, Sorry but as this is an abstract issue, that only you seem to be having otherwise i would be blown up with this, Mitigation has been added in 1,11 but is not easy to port back to 1.10.
