### ISSUE TITLE
[1.11.2] Crash looking up fluid usages in JEI

### ISSUE THREAD

**Issue by Terpo** [TheCBProject/CodeChickenLib#57]
https://gist.github.com/Terpo/a3177de313aa198fbe118be0960cd1a4
with CodeChickenLib-1.11.2-2.7.0.268-universal.jar and forge 2315

I am not sure if it is your fault or even bookshelfs

**Comment by covers1624** [comment]
Neither myself or bookshelf, Advanced Rocketry issue.
