### ISSUE TITLE
Config file woes

### ISSUE THREAD

**Issue by elifoster** [TheCBProject/CodeChickenLib#6]
As you're aware, I've been struggling a bit to get CCLib to work in my dev environment for Flaxbeard's Steam Power. After doing a bit of debugging, I think I have found the culprit. When ASMHelper is initialized, it calls loadConfig. This references ObfMapping.obfuscated for the first time, so it calls ObfMapping's static initializer. The static initializer calls loadMCPRemapper, which creates a new MCPRemapper. The constructor for that class calls getConfFiles, which checks the GradleStart system vars for mappings. If the mapping files don't exist, it references ASMHelper.config. So, in short, ASMHelper.config is referenced while it is being initialized.

Here's a hierarchy of the problem

```
ASMHelper.config initializer {
  loadConfig
    ObfMapping.obfuscated
      loadMCPRemapper
        getConfFiles
          ASMHelper.config
}
```

**Comment by covers1624** [comment]
Ahh, sadly im out for the weekend, so ping me on irc in 2 days if i forget :P

**Comment by elifoster** [comment]
Alright. I sorta solved the issue by having two folders, snapshot/srgs and snapshot/1.10.2/srgs, because apparently Gradle wants both now?

**Comment by covers1624** [comment]
yeah, brandon mentioned something to me the other day about ccl not liking where mcp mappings are, maybe ill have it ask what version mappings you are using then just pull them from maven :P

**Comment by covers1624** [comment]
Latest build this should™ be fixed.
