### ISSUE TITLE
Client-side required?

### ISSUE THREAD

**Issue by EmanYm** [TheCBProject/CodeChickenLib#60]
What is the reason CCC/CCL (and now CCT, but I'm still running 1.10.2, so it's irrelivant) are required on the client side?  I'm trying to allow staff to use NEI/JEI but not regular players.  If the client does not have any "Chicken_Bones/covers1624 productions" installed do they really still need to have Core/Lib?

**Comment by covers1624** [comment]
1.12 This Might happen, but as it stands right now, i can't.
