### ISSUE TITLE
[Wireless Redstone CBE / FMP-CBE / 1.11.2] Crash with latest CCL

### ISSUE THREAD

**Issue by brisingraerowing** [TheCBProject/CodeChickenLib#62]
(As I didn't find an issues page for WR-CBE, I am putting this here)

WR-CBE and FMP-CBE crash with the latest CCL for 1.11.2, as there were a number of changes. I use WR-CBE to remotely enable / disable machines from my main control center, and I have found no other wireless redstone mods for 1.11.2.

Is there an update planned, or should I go a different route?

**Comment by covers1624** [comment]
FMP and Wireless Redstone are not released for 1.11 yet. FMP is undegoing some changes. Hopefully in the next week we should have a release for FMP.
