### ISSUE TITLE
[1.11.2] CodeChicken Lib v2.7.0.268 "java.lang.NullPointerException: Batching chunks"

### ISSUE THREAD

**Issue by Boomflex** [TheCBProject/CodeChickenLib#63]
https://pastebin.com/DTixvRyb

Crash for multiple users on the All the Mods 2 Official Server.

Any further information needed please don't hesitate to ask!

**Comment by covers1624** [comment]
Duplicate: https://github.com/TheCBProject/CodeChickenLib/issues/59
