### ISSUE TITLE
Crash In Creative Tab

### ISSUE THREAD

**Issue by TheXWolf** [TheCBProject/CodeChickenLib#64]
Typed Ender in the JEI box, crashed when I got to the next page.
Restarted, tried using creative search box, and changed page to next tab, crashed again.
Using most recent 1.11.2 ChukenChunks, EnderStorage, and CodeChickenLib as of today.

Crash:
https://pastebin.com/sfZxnBth

**Comment by covers1624** [comment]
Please provide me with the full report, not to be a dick at all but the crash report MC generates is there for a reason.

**Comment by TheXWolf** [comment]
No prob, sometimes I know the short stack is enough, here ya go:
Not sure if this is thermaldynamics or you honestly because TE/TD require CCLib, though it does looks like it's cofh trying to render something wasn't sure if it's based on your render item.
https://pastebin.com/UBEYwE93

**Comment by covers1624** [comment]
Update the CoFH mods, updates were pushed some time ago to accommodate changes made to CCL.

**Comment by TheXWolf** [comment]
Thanks for clearing it up, just updated all 4, was waiting for one tagged as release, my bad. Removed the "Ender" portion of the title for reference, that part was a jei fuck up.
