### ISSUE TITLE
CodeChickenLib not recognized? (1.10.2

### ISSUE THREAD

**Issue by katubug** [TheCBProject/CodeChickenLib#65]
Hi there. I've attached a screenshot of the error I received, and my mods folder. Obviously, the file IS there and should be recognized, so I don't know what the problem is. I tried the next previous version (255) and had the same error. When I experimented with putting them both in the folder, it did recognize them as being duplicated. Any ideas?

![enderstorage issues](https://user-images.githubusercontent.com/20935286/27844005-f53ef402-60e0-11e7-8af4-e48aca1a2b87.jpg)

**Comment by covers1624** [comment]
See: https://github.com/TheCBProject/EnderStorage/issues/41
