### ISSUE TITLE
ModelBakery still causing crashing even after 2.5.9.283

### ISSUE THREAD

**Issue by piedpipr314** [TheCBProject/CodeChickenLib#67]
P3pp3rF1y from https://github.com/skyboy/MineFactoryReloaded/issues/647  says this issue should have been fixed.
Crash report: https://pastebin.com/cdwKMYge
Log: https://pastebin.com/vm4SrPRb
I̶f̶ ̶I̶ ̶d̶o̶w̶n̶g̶r̶a̶d̶e̶ ̶J̶o̶u̶r̶n̶e̶y̶M̶a̶p̶ ̶t̶o̶ ̶1̶.̶1̶0̶.̶2̶-̶5̶.̶4̶.̶7̶,̶ ̶i̶t̶ ̶d̶o̶e̶s̶n̶'̶t̶ ̶c̶r̶a̶s̶h̶ ̶b̶u̶t̶ ̶s̶t̶i̶l̶l̶ ̶h̶a̶s̶ ̶t̶h̶e̶ ̶i̶s̶s̶u̶e̶ ̶i̶n̶ ̶t̶h̶e̶ ̶l̶o̶g̶ ̶f̶i̶l̶e̶.̶
Edit: It just crashed on me again testing this.

**Comment by piedpipr314** [comment]
This seems to me to be the same issue as https://github.com/TheCBProject/CodeChickenLib/issues/61 that you closed, so I don't know.

**Comment by covers1624** [comment]
No, this is the phantom mfr milk bucket crash.
