### ISSUE TITLE
Are these CCL errors? I have no idea

### ISSUE THREAD

**Issue by Xiaminou** [TheCBProject/CodeChickenLib#68]
I have no idea what's causing these errors, I've been crashing pretty randomly while doing mundane tasks like breaking or placing simple blocks.

[crash-2017-07-12_01.40.29-client.txt](https://github.com/TheCBProject/CodeChickenLib/files/1140508/crash-2017-07-12_01.40.29-client.txt)
[crash-2017-07-12_01.35.19-client.txt](https://github.com/TheCBProject/CodeChickenLib/files/1140511/crash-2017-07-12_01.35.19-client.txt)
[crash-2017-07-11_22.29.15-client.txt](https://github.com/TheCBProject/CodeChickenLib/files/1140509/crash-2017-07-11_22.29.15-client.txt)
[crash-2017-07-11_18.58.11-client.txt](https://github.com/TheCBProject/CodeChickenLib/files/1140507/crash-2017-07-11_18.58.11-client.txt)
[crash-2017-07-11_18.53.46-client.txt](https://github.com/TheCBProject/CodeChickenLib/files/1140512/crash-2017-07-11_18.53.46-client.txt)
[crash-2017-07-11_18.23.39-client.txt](https://github.com/TheCBProject/CodeChickenLib/files/1140510/crash-2017-07-11_18.23.39-client.txt)

**Comment by covers1624** [comment]
So these are some block failing to render ccl is in the stack yes but it has delegated the call to the vanilla renderer hence not ccl's issue. So the crash is actually caused by a null state inside the crashreport generation section of the render dispatcher, the only way to debug this is removing mods or what ever blocks are around in the chunk you are breaking things in needs to be tested.

**Comment by covers1624** [comment]
The one regarding chisel is probably an issue on TD's end that i need to fix, the cover renderer appears to not like chisel blocks.

**Comment by Xiaminou** [comment]
Oh right, I have a lot of laboratory blocks (from chisel) covers in my base.

As for debugging what's happening, I have 130 mods and it doesn't crash reliably so it'd take dozens of hours.

**Comment by Xiaminou** [comment]
any news on patching the chisel thermal dynamics cover crash? It's happening more and more.

**Comment by covers1624** [comment]
It's on my list, but will be a rewrite, just don't make covers out of chisel for the time being. I'm finishing up some critical systems in ccl first.
