### ISSUE TITLE
CCModelBakery needs way to set sprite per quad

### ISSUE THREAD

**Issue by MrTJP** [TheCBProject/CodeChickenLib#7]
Currently, an entire model can only be baked with a single sprite. This is a problem for models that use multiple TextureAtlasSprites for each of their quads.

**Comment by covers1624** [comment]
There is, setSprite, as long as the quad has finished baking the sprite can be set.

**Comment by covers1624** [comment]
oh, ModelBakery

**Comment by covers1624** [comment]
Easiest way i see is baking each individual part of the model in CCQuadBakery using the start and end vars and just combining the list afterwards.

**Comment by MrTJP** [comment]
Hmm. Since each UV has a Tex index, we could provide a multi-icon transformation and grab icons from that as the model bakes

**Comment by covers1624** [comment]
We would need a custom UV Transform to obey the current vertex index and change the UV transform based on that, thoughts?

**Comment by covers1624** [comment]
I was thinking a separate UVTransform like BakingIconUVTransform and a Builder for the transform, that essentially builds a start > end vertex range = UVTransform.

**Comment by covers1624** [comment]
The builder would be used to throw errors if ranges overlap.

**Comment by MrTJP** [comment]
Yea that sounds good to me. I'm not exactly sure what the texture sprite object in the quad is actually used for (considering UV is part of the vertex data), but it's probably worth making sure they match the actual texture being applied.

**Comment by covers1624** [comment]
I gotta go out for a bit but when i get back ill whip something up.

**Comment by covers1624** [comment]
Also, it looks like it it is used for(in vanilla at least) re-texturing baked quads in BakedQuadRetextured

**Comment by covers1624** [comment]
https://github.com/TheCBProject/CodeChickenLib/commit/cfc3ca1478a68090eb981f4f3c9f4f588c8cb168
