### ISSUE TITLE
Crash Initializing game [1.10.2]

### ISSUE THREAD

**Issue by eXtremeJR96** [TheCBProject/CodeChickenLib#70]
Hello,

When I launch the game, there is this crash (https://pastebin.com/M9gauYNp) that appears very often, on different mod and the game does not tell me which mod does everything crash! I look in the logs and crashes-reports but nothing of nothing except codechicken libs done:

https://pastebin.com/AgLUxkvj

Help, signed a french!

**Comment by covers1624** [comment]
That is not a crash, that is some verbose log output from ccl that has been fixed in later mc versions.

**Comment by eXtremeJR96** [comment]
So I have to go into 1.11.2?

**Comment by eXtremeJR96** [comment]
It would seem that this is a conflict between CodeChicken Lib and CoFH. I had this crash report after successfully starting the game and opening the inventory in creative:

https://pastebin.com/hkJXdTe4

I also sent it on the CoFH Github in case.
