### ISSUE TITLE
[Issue] 1.12 Preinit Fingerprint crash

### ISSUE THREAD

**Issue by accessdenied0** [TheCBProject/CodeChickenLib#71]
Hello CCL team,

I got an Issue and I can't figure out what causes it. It all started with my issue of Block ID's available in my MC instance.
I added [NEID](https://github.com/fewizz/NotEnoughIDs/issues/63#) and it worked fine. After I added the newest [version of Spectrite](https://github.com/Samuel-Harbord/SpectriteMod/issues/5#), [it started to crash](https://pastebin.com/rVA796yV). [I assumed it might be Spectrite](https://github.com/Samuel-Harbord/SpectriteMod/issues/5#), so I downgraded the version from Spectrite which worked. 
BUT after updating Cavern (1.9.0 to 1.9.3) [it started to crashing again.](https://pastebin.com/aBiZyEVv). 
Now I suspected [NEID](https://github.com/fewizz/NotEnoughIDs/issues/63#) but the first crash report seem not even include NEID which I know shouldn't be...
BUT what is now absolutely strange is: It worked a single time. 
[Now it is crashing again.](https://pastebin.com/NDUrJJku)

(All the crash links are different times and at the corresponding time in my story.)

I'm clueless what might causing it and I was hoping I can get some help here.

access_denied

**Comment by covers1624** [comment]
Someone / something is modifying a map inside FML whilst CCL is intializing some internal structures, Also update CCL, its custom fingerprint checker has been removed in the latest builds on cb's site.

**Comment by accessdenied0** [comment]
@covers1624
Thanks for the help.
_EDIT_ 
> Nevermind I'm stupid you meant unstable builds. I'll give it a shot.
