### ISSUE TITLE
Crash when rendering item in JEI

### ISSUE THREAD

**Issue by Laruae** [TheCBProject/CodeChickenLib#72]
Not sure who's issue this actually is, but there are certain items which will cause a crash to desktop when they attempt to render using JEI. Posting this here because a line refers to the codechicken render. 

JEI, Bookshelf, Thermal Expansion, and CodeChickenLib are all referenced in the log attached, however as I do not know which mod is actually causing this, I am posting this at each mod's GitHub issue section. 

Thanks!

[Minecraft 1.11.2 Crash Log.txt](https://github.com/TheCBProject/CodeChickenLib/files/1157857/Minecraft.1.11.2.Crash.Log.txt)

**Comment by covers1624** [comment]
Do exactly as lemming said, update your mods.
