### ISSUE TITLE
Crash when rendering microblock with broken texture

### ISSUE THREAD

**Issue by Garagoth** [TheCBProject/CodeChickenLib#73]
Took me a while but seems pretty easy after all, but I am still not sure where this should be reported.
Required for crash: JEI, forge multipart, lithos core resourcepack.

Due to resourcepack providing bad texture for bookshelf microblock, JEI crashes game as soon as it wants to render bookshelf microblocks (try searching for book).

[Crash report](https://gist.github.com/Garagoth/7af94f924a0dab749a8cf58711877b84)

Removing Lithos core or using different resourcepack makes the problem disappear, but still I guess this should not crash the game?

Also reported as [issue for JEI](https://github.com/mezz/JustEnoughItems/issues/944).

**Comment by covers1624** [comment]
This is due to some dumb reasons I'm yet to track down, close your jei issue.

**Comment by Garagoth** [comment]
If it helps: when I load game without resourcepack and show in JEI those bookshelf microblocks, all looks good.
Then, in same game I load another resourcepack, all is fine. Then I load Lithos Core and it still works, but bookshelf microblocks are all messed up (texture-wise) but does not crash. At least not everytime as I was able to see it once...

G.

**Comment by covers1624** [comment]
Can i have a copy of the resource pack used to create this crash.
Im assuming the pack changes the model, wanna test my fix.

**Comment by covers1624** [comment]
Can confirm they were changing the model and the current logic didn't take in to account that the bookshelf didnt have any "face quads", Its smarter now and will attempt to grab face quads, if none are found then it will attempt to grab any quad facing in the specific requested face, This will be changing in 1.12 to model squishing. But for now, if models look out of place when a MicroPart, that's not my problem, either that, a crash, or a missing sprite.

**Comment by Garagoth** [comment]
Yup, works like a charm. Thanks!
