### ISSUE TITLE
1.11.2 crash

### ISSUE THREAD

**Issue by jcmgamer** [TheCBProject/CodeChickenLib#74]
I've been getting this crash every couple of hours while playing.  https://pastebin.com/JNBKQHst  tterag1098 over at the chisel mod sent me here saying that codechicken lib was calling the method that crashed the client.

**Comment by jcmgamer** [comment]
Guess I'll take the 25 days of no response from the "maintainers" of these mods as a big FUCK YOU to us users reporting issues.  Peace.

**Comment by covers1624** [comment]
Literally I only wrap the entity renderer, there is nothing I do that vanilla doesn't do, and you seem to be the only person to ever have this issue and this code has been live for months in virtually every mod pack. It's not me. And you know before acting like an intitled cunt we all have lives and so modding is a hobby, before you lash out think about how much work we put in to our mods, we don't just smack our head on the keyboard and whack it on curse, consider this a warning, next time you will be banned from the tracker.
