### ISSUE TITLE
1.11.2 Unexpected error

### ISSUE THREAD

**Issue by drakray** [TheCBProject/CodeChickenLib#75]
https://pastebin.com/KmugEh27
Got that after trying to relog on server after quitting for dinner(not from crash)
only thing new is that not long before exiting, I placed 2 ThermalExp Cel and an Enervation Dynamo
got the same CTD multiple time, I manage to join the server, see ~3seconds of far map, then CTD.
Only Client is crashing.

**Comment by drakray** [comment]
I can go on my server as long as my clients do not load my house chunk.
As soon as the chunk is loaded on the client, CTD with above crashlog

**Comment by drakray** [comment]
Setting EnableShaderEffects=false in cofh/core/client.cfg get me https://pastebin.com/wKvZ4Ky3

**Comment by covers1624** [comment]
https://github.com/TheCBProject/CodeChickenLib/issues/80#issuecomment-324299689
