### ISSUE TITLE
Bakery Crash on startup when loading AE2Stuff:

### ISSUE THREAD

**Issue by Iomega0318** [TheCBProject/CodeChickenLib#77]
So I assume that since it's your mod that seems to be spitting out the crash log I should post it here, however I will link it on AE2Stuff as well just in case it's on their end.

I am using the latest of CodeChickenCore and CodeChickenLib as well as AE2Stuff for 1.10.2, all I have to do is add AE2Stuff to my mods folder and it will always crash on startup, after removing it loads just fine.

Here is the crash log:
http://paste.ubuntu.com/25181697/
and the forge log:
http://paste.ubuntu.com/25181700/

Let me know if you need anything else and thank you for any feedback you can provide!

**Comment by covers1624** [comment]
If you have mfr it's the phantom milk bucket issue. It has been reported thousands of times to mfr, go check their tracker for updates. Otherwise this is not me, I'm nowhere in that stack.

**Comment by Iomega0318** [comment]
Ahh gotcha, I had no idea. I just barely started using MFR again.

Thanks.
