### ISSUE TITLE
[1.12] Crash on startup (Gson)

### ISSUE THREAD

**Issue by Errandil85** [TheCBProject/CodeChickenLib#78]
I get the following error on startup of the game:

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from CodeChicken Lib (codechickenlib)
Caused by: java.lang.NoSuchMethodError: com.google.gson.GsonBuilder.setLenient()Lcom/google/gson/GsonBuilder;

I am not sure if this is related the the lib or the loader.
The loader I used is ATLauncher.
See paste for full crash report: https://pastebin.com/eHEpk6em

**Comment by Dominance** [comment]
I have narrowed this down to being a ATL issue. works fine on multiMC for instance.

Here is a report with just ccl by itself https://paste.ubuntu.com/25277846/

**Comment by covers1624** [comment]
Can I please have the full log, atl may be using the wrong Google gson version.

**Comment by Dominance** [comment]
It's not the library, I've ran md5 checks compared to vanilla Minecrafts Disturbed gson libraries. I've also used a library folder directly from multiMC which contains a working Google gson library which again works with multiMC but not ATL. I'm convinced it's a internal Java argument that ATL uses.

**Comment by Dominance** [comment]
Here is a log http://paste.atlauncher.com/view/67ba633c corresponding with the same crash

**Comment by covers1624** [comment]
Well no, literely the only thing that can cause this is an outdated lib. the log states that the correct lib is being loaded, something about the launcher must be loading an outdated lib in the classpath, possibly the launcher itself, Ive re worked things so it isnt using that method, but anyone else using it will crash.
