### ISSUE TITLE
Rendering Issue | 1.12

### ISSUE THREAD

**Issue by TheSpicePhantom** [TheCBProject/CodeChickenLib#80]
Hello, i got a problem that seems to happen very rarely, but I got it happening to me.
Since CofH Mods depend on the Mod "CodeChickenLib" and its rendering mechanics, this issue is going to be published here and on the Thermal Expansion Part of TeamCofH.
[This is my CrashReport](https://hastebin.com/raw/adonafunup)

Now to how I got this issue show up.
I placed down a Redstone Furnace and a Pulverizer, left the game to play a different game. I wanted to join back in my Base and the game crashed, i tried it 3 times! (All gave me the same result) I ended up deleting the furnace and pulverizer with MCEdit, which worked fine.

Please Help!

**Comment by drakray** [comment]
I got the same kind of error in 1.11.2 https://pastebin.com/UC9xBVVv

**Comment by TheLimePixel** [comment]
The same happens when going to the Nether https://pastebin.com/YkHwTcJA

**Comment by covers1624** [comment]
Ugg, i was sure we tracked this down ages ago..

**Comment by TheSpicePhantom** [comment]
actually, we discovered the error! Just now,  haha. If you place down a PamsHarvestcraft Market in the same chunk as a Machine from Thermal Expansion, its likely to crash! We added a Mod to the Server that enabled us removing it by command and we could join again!

**Comment by drakray** [comment]
That may be it, because in my own crash, there was indeed a market block in the same chunk as Pulverizer/Furnace or Dynamo (I use Lost Cities, so chunk are easy to see, as each building take a whole chunk)
I'll test that more

**Comment by covers1624** [comment]
Can i get a world download with minimal mods please.

**Comment by TheSpicePhantom** [comment]
You can simply download the Modpack on TwitchClient, called "MMD Public Pack", make a new world, place some TE machine together with any Pams Block, Save and Quit to title then try load it back up. It should crash you.

**Comment by covers1624** [comment]
Modpack fails to install and i don't have endless hours to strip down a modpack to the minimal required mods. Please find the minimal mod set for this to happen or i can do nothing to fix it.

**Comment by TheSpicePhantom** [comment]
Okay, you need Code Chicken Lib, thermal foundation, expansion and dynamics, cofh core, redstoneflux api (not sure) and pams harvestcraft

**Comment by covers1624** [comment]
Tracked it down to pams, seems they arent writing the correct nbt data for the client to read, causing the chunk packet to fail, causing cofh's client side tile to be null, causing the game to crash. https://github.com/MatrexsVigil/harvestcraft/issues/29 Not my issue, its pams.

**Comment by TheSpicePhantom** [comment]
I'll link it to them, thanks for taking a look

**Comment by covers1624** [comment]
Well, iv'e already created an issue with an in depth analysis and submitted a pr to fix the issue, don't worry about it.

**Comment by TheSpicePhantom** [comment]
Okay, thank you soo much!
