### ISSUE TITLE
[1.12.1] Rendering issues and crashes with other mods

### ISSUE THREAD

**Issue by TheLimePixel** [TheCBProject/CodeChickenLib#90]
On 1.12.1, the mod causes rendering issues and tesselating block crashes with many mods:
EvilCraft: https://pastebin.com/iXA1vs33
Applied Llamagistics: https://pastebin.com/PR40aVGf
Extra Utilities and Thermal Dynamics: 
![image](https://user-images.githubusercontent.com/25333164/29533676-38ce2696-86b3-11e7-85ce-5dd9b7bff86b.png)

 All of these randomly occur when rejoining a world or going to the dimension in which the blocks are and can be temporarily fixed by replacing the blocks. This didn't happen on 1.12, at least not my knowledge, half of the modders have confirmed that it doesn't have to do with their mods, it has been tested without foamfix and it still happens, so I have come to the conclusion that it has to do with this mod.

**Comment by covers1624** [comment]
Well CCL is a dep for TD.. and all of those stack traces don't end in my code. Report it to the respective mod authors, if i was to guess, its a pams block or something causing client side tiles to not load.
